### ISSUE TITLE
Eliminar uso de xbmc.PLAYER_CORE_AUTO

### ISSUE THREAD

**Issue by alexiri** [tvalacarta/pelisalacarta#114]
El uso de xbmc.PLAYER_CORE_AUTO está deprecado desde el 2013 (http://forum.kodi.tv/showthread.php?tid=173887&pid=1516662#pid1516662) y empieza a fallar en Kodi 17. Hay un par de usos que se pueden eliminar fácilmente.

Este mismo problema también existe en tvalacarta, pero no he encontrado código actualizado para ese plugin.

**Comment by SeiTaN80** [comment]
gracias @alexiri, le hecho un ojo y lo modifico.

**Comment by SeiTaN** [comment]
Esto se podría cerrar ya en el codigo no hay referencia PLAYER_CORE_AUTO, sólo se usa si es "xbox".
