### ISSUE TITLE
Item.py import json

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#119]
Hola,
De momento creo que no habrá ningún problema por que no se usa `def tojson(self, path="")`, pero habría que cambiar la libreria `json`, sólo está incluida a partir de python 2.6.

```python
import json
```
Por 
```python
import from lib simplejson as json
```

**Comment by divadres** [comment]
Si.. python 2.4 solo es compatible con simplejson

**Comment by tvalacarta** [comment]
Bueno, para eso tenemos jsontools.py :)

2016-01-16 0:16 GMT+01:00 David <notifications@github.com>:

**Comment by tvalacarta** [comment]
¿Veis algún problema en cambiar ese "import json" por "import jsontools" y evitar la incompatibilidad?

De todas formas, creo que lo más antiguo es el Python de Boxee y es la 2.6...

**Comment by SeiTaN80** [comment]
Hola @tvalacarta , ¿estás seguro que boxee usa la versión 2.6?

Estuve mirando las versiones de python que usa cada plataforma
http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=7246, y encontré que era la 2.4 al igual que xbox, además para la libreria requests es necesario 2.6+ y creo que por eso se dió este problema https://github.com/tvalacarta/pelisalacarta/issues/92.

Si todas las versiones de pelisalacarta usan 2.6, no haría falta `simplejson` ni el resto de imports que se usan `jsontools`, ya que la librería `json` viene incorporada a partir de la versión 2.6.

Un saludo.

**Comment by SeiTaN** [comment]
cierro ya que está corregido por @divadres :smiley:
