### ISSUE TITLE
tvalacarta enlaces mitele

### ISSUE THREAD

**Issue by cesarDevOp** [tvalacarta/pelisalacarta#124]
Hola,
se que no es el proyecto, pero estoy intentado arreglar la resolución de enlaces del canal de mitele de tvalacarta. El caso es que por algún motivo los enlaces que resultan de interpretar las URL en algunos casos funcionan y otros no. 

Esta serie si funciona:

http://mitele1-vh.akamaihd.net/i/geo/WG/rJ/WGrJzmaK23L34b4ak54k41/hoDhcXLMsWry1HcJrG22H3.1100,,.mp4.csmil/master.m3u8?hdnea=st=1453205495~exp=1453205795~acl=/i/geo/WG/rJ/WGrJzmaK23L34b4ak54k41/hoDhcXLMsWry1HcJrG22H3.1100,,.mp4.csmil/*~hmac=5014493a69dec0a2644f079307b4ff66b2d4f1f2d61a758920589c9c3fb44435

Esta otra no:

http://mitele1-vh.akamaihd.net/i/enc/geo/cd/qG/cdqGyhD6ZBuGF2mCtRl5P4/3c3l6JQY3DCcqt889qQ924.1100,,.mp4.csmil/master.m3u8?hdnea=st=1453203900~exp=1453204200~acl=/i/enc/geo/cd/qG/cdqGyhD6ZBuGF2mCtRl5P4/3c3l6JQY3DCcqt889qQ924.1100,,.mp4.csmil/*~hmac=d83760fee077a70de43c982fdd4d0331c40e5949daf19f350cb6fa624bb041a8

Si no va a esta sección borrarlo, pero estoy atascado y quería ver si alguien podía enfocarme en como solucionarlo.

**Comment by kampanita** [comment]
No sabes lo que te agradezco que te pongas a mirarlo, yo he estado
echandole una ojeada a ver si veía el porque ahora no van los enlaces, a
ver si saco tiempo para intentar echar un cable en lo que pueda..

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

2016-01-19 13:37 GMT+01:00 cesar <notifications@github.com>:

**Comment by cesarDevOp** [comment]
Lortropic en el foro de mimediacenter colgó el script con el cual se pueden ver casi todos los enlaces, pero al parecer los más novedosos no funcionan. 
Kampanita crees que me puedes ayudar a solucionarlo?. Inicialmente no parece un problema de código como tal, más bien a que ahora con los nuevos enlaces o no se usa el mismo sistema de tokenizer o algo a cambiado, si sabes que ha cambiado puedo arreglarlo yo, lo que no sé es como averiguar el cambio en si.
Por otra parte, se va a subir el código de tvalacarta a este repositorio desde google?

**Comment by tvalacarta** [comment]
Respondiendo a la última pregunta...

Sí :)

**Comment by kampanita** [comment]
Acabo de verlo, hacia tiempo que no pasaba por el foro y todavía no he
podido probar el código de Lortropic pero tiene buena pinta y segun los
usuarios, funciona.

Esta tarde le echo una mirada y te comento a ver si veo algo.

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

**Comment by cesarDevOp** [comment]
Funcionan las series que ya estaban antes de cierta fecha, pero las últimas no, parece haber algún tipo de encriptación o cambio en la conexión.

**Comment by cesarDevOp** [comment]
Por mas que busco por Internet el método para sacar el video esta bien en el código. No encuentro documentación de como flash saca este tipo nuevo de vídeos. Tu ves algo?

**Comment by kampanita** [comment]
Que estén usando otro tokenizer para las urls nuevas ¿? quizas es cuestion
de decompilar el flash del reproductor de videos, a ver si hay algo
nuevo... lo miro a ver si saco algo en claro.

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

2016-01-20 11:54 GMT+01:00 cesar <notifications@github.com>:

**Comment by kampanita** [comment]
Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

2016-01-22 17:40 GMT+01:00 cesar <notifications@github.com>:

**Comment by kampanita** [comment]
Pues ahora mismo parece que solo usan el tokenizer 2 .... No veo mucho más.











package com.erades.tele5.player.model.config
{
   import flash.display.Stage;
   import com.erades.tele5.player.view.asset.PlayerTele5;
   import com.erades.tele5.player.view.asset.Preload;

   public class TL5Constants
   {

      public static var IS_DEBUGING:Boolean = false;

      public static const STAGE_WIDTH_UI:uint = 415;

      public static const STAGE_HEIGHT_UI:uint = 290;

      public static var STAGE_WIDTH_RUNTIME:uint;

      public static var STAGE_HEIGHT_RUNTIME:uint;

      public static var STAGE_OBJ:Stage;

      public static const TRACE_MOUSE_EVENTS:Boolean = false;

      public static const TRACE_TIMER_EVENTS:Boolean = false;

      public static var TK_HTTP:String = "
http://servicios.telecinco.es/tokenizer/tk2.php";

      public static var TK_RTMP:String = "
http://servicios.telecinco.es/tokenizer/tk2.php";

      public static var TK_RTMPe:String = "
http://servicios.telecinco.es/tokenizer/tk2.php";

      public static var TK_RTMP_LIVE:String = "
http://servicios.telecinco.es/tokenizer/tk2.php";

      public static var TK_RTMPe_LIVE:String = "
http://servicios.telecinco.es/tokenizer/tk2.php";

      public static var TK_TIME:String = "
http://servicios.telecinco.es/tokenizer/clock.php";

      public static var OV_MAST:String;

      public static var OV_NO_RATIO:Boolean = false;

      public static const VIDEO_HD_STAGE:Number = 600;

      public static const VIDEO_MD_STAGE:Number = 500;

      public static var FLVAR_HOST:String = "xml/tl5config.xml";

      public static var PLAYER_MC:PlayerTele5;

      public static var PLAYER_MC_PRELOAD:Preload;

      public static var PLAYER_SHOW_DESC:Boolean;

      public static var PLAYER_SHOW_SECTIONS:Boolean;

      public static var PLAYER_SHOW_RELATED_VIDEOS:Boolean;

      public static const APP_VERSION:String = "0.1.7.2";

      public static const BUFFER_AD:Number = 3;

      public static const BUFFER_LIVE:Number = 3;

      public static const BUFFER_HTTP:Number = 3;

      public static const BUFFER_RTMP:Number = 3;

      public function TL5Constants()
      {
         super();
      }
   }
}

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

2016-01-22 18:30 GMT+01:00 kampanita <kampanita@gmail.com>:

**Comment by cesarDevOp** [comment]
He decompilado el msplayer.swf y he visto unas librerías akamai, pero no se por donde empezar a mirar, alguna sugerencia?

**Comment by tvalacarta** [comment]
Cierro el issue, si queréis lo reabrimos en el repositorio de tvalacarta que ya está operativo y lo comentamos allí.
