### ISSUE TITLE
Eleccion de acciones con el fichero

### ISSUE THREAD

**Issue by kampanita** [tvalacarta/pelisalacarta#134]
En la última actualización, con las limpias de código creo que se ha eliminado la selección de otros medios para abrir los torrents, como pulsar ...

**Comment by superberny70** [comment]
Sólo por concretar.... Los torrente sólo funciona en XBMC/modo ¿verdad?
Estoy mirando como mejorar esto y no quisiera dejar a nadie fuera.

**Comment by kampanita** [comment]
No entiendo lo de XBMC/modo...
En torrent.py teníamos la opcion de abrir con pulsar/xbmctorrent/KmediaTorrent ...


```
# Returns an array of possible video url's from the page_url
def get_video_url( page_url , premium = False , user="" , password="" , video_password="" ):
    logger.info("[torrent.py] server=torrent, la url es la buena")

    name = page_url[page_url.rfind("/") + 1:page_url.rfind(".")]

    link = page_url

    media_url_xbmctorrent = "plugin://plugin.video.xbmctorrent/play/%s" % urllib.quote_plus(link)
    media_url_pulsar = "plugin://plugin.video.pulsar/play?uri=%s" % urllib.quote_plus(link)
    media_url_stream = "plugin://plugin.video.stream/play/%s" % urllib.quote_plus(link)

    video_urls = [
         [ "[xbmctorrent] %s" % (name), media_url_xbmctorrent ],
         [ "[pulsar] %s" % (name), media_url_pulsar ],
         [ "[stream] %s" % (name), media_url_stream ]
     ]

    return video_urls
```

Ahora esta así

```
def get_video_url( page_url , premium = False , user="" , password="" , video_password="" ):
    logger.info("[torrent.py] server=torrent, la url es la buena")

    name = page_url[page_url.rfind("/") + 1:page_url.rfind(".")]

    link = urllib.quote_plus(page_url)

    video_data = {
        'xbmctorrent' : {
            'url' : "plugin://plugin.video.xbmctorrent/play/%s" % link
        },
        'pulsar' : {
            'url' : "plugin://plugin.video.pulsar/play?uri=%s" % link
        },
        'quasar' : {
            'url' : "plugin://plugin.video.quasar/play?uri=%s" % link
        },
        'stream' : {
            'url' : "plugin://plugin.video.stream/play/%s" % link
        },
        'torrenter' : {
            'url' : "plugin://plugin.video.torrenter/?action=playSTRM&url=%s" % link
        }
    }

    video_urls = []

    for plugin, data in video_data.items():
        if  xbmc.getCondVisibility('System.HasAddon("plugin.video.' + plugin + '")'):
            video_urls.append([ "[" + plugin + "] %s" % (name), data['url']])

    return video_urls
```

No he tenido mucho tiempo para mirarlo, no suelo usar mucho el tema torrent, pero el otro día de casualidad me fijé que esto no iba bien, creo que lo que no está del todo correcto es el tema de xbmc.getCondVisibility(......) , pero no estoy muy seguro.

**Comment by superberny70** [comment]
Me referia a que los torrents son exclusivos de las versiones xbmc/kodi (maldito corrector!!!)
He estado mirando en la version 4.0.7 y me sale una opocion mas q a ti (torrentin), asi q supongo q no debemos estar en la misma version.
Por otra parte el xbmc.getCondVisibility es correcto. De este modo solo aparecen en el menu los añadidos q tienes instalados en tu sistema. Yo por ejemplo solo tengo el quasar y es la opcion q me sale. ¿cuales tienes tu instalados y q opciones te salen en el menu cuando seleccionas un torrent?

**Comment by r0balo** [comment]
y para los minimalistas sólo usan MCT?

**Comment by neno1978** [comment]
Grande los minimalistas!!! 😜

**Comment by CmosGit** [comment]
Mi voto para que MCT se incluya en pelisalacarta, y quién esté en contra :gun: :laughing:

**Comment by superberny70** [comment]
¿los minimalistas podriais hacer una exepcion y explicarnos a los maximilistas de una forma "como pa' tontos" como integrar MCT en pelisalacarta?
Estoy pensando q la lista de clientes de torrent podria estar en la configuracion del plugin (solo para xbmc/kodi). Podrian ser booleanos para los clientes conocidos e incluso uno de texto para poder introducir uno personalizado (como los canales personales).

**Comment by r0balo** [comment]
Ese manual para "como pa tontos" ya sabes dónde está, el resto dependerá del interés y de lo que queramos entender o nos apetezca entender cuando leemos, en un post soy ingeniero eperimentado y en otro pardillo :)

**Comment by neno1978** [comment]
Tú siempre serás el master y punto pelota ... Y coño, superberny , si sabes dónde está ese manual,  comparte coño, no seas egoísta 😂😜

**Comment by superberny70** [comment]
@r0balo perdona pero no lo entiendo. En tu primer mensaje parece q te quejabas de q MCT no estuviese incluido en el menu y cuando te pido ayuda para integrarlo me envias a no se donde a buscarla.
@neno1978 creo q he demostrado reiteradamente q no soy nada egoista. De hecho mi plataforma es un androidTV con android 5.1 q segun creo no puede funcionar con torrent, por lo q es un tema q no conozco mas q de oidas y la verdad personalmente me importa un pito. Solo intente contestar a @kampanita 7 dias despues de q hiciese su pregunta ya q nadie se habia dignado a contestarle.

Repito no soy yo el q tiene ese manual. Pero no os preocupeis pues doy por zanjado el tema, el q quiera incluir o quitar clientes q se monte por su cuenta.

**Comment by r0balo** [comment]
@superberny70 En primer lugar; no hay nada que perdonar ni nada que enteder, no es una adivinanza, chiste o un algoritmo complejo de criptado. En segundo lugar; hoy he aprendido que una pregunta es una queja en algunos barrios. Y en tercer lugar; es una cuestión de interés y de como estemos de actitud, pardillo o ingenerio experimentado

**Comment by neno1978** [comment]
Yo creo que aquí, más que nada un problema de compresión lectora(y mira que le he puesto las caritas y to :) ) Lo que viene a decir que mis palabras no tenían ninguna connotación seria( casi nunca la tienen ) pero si la intención de dar banalidad a lo que no merece otro grado. Es decir, que el "manual para tontos" me lo quedo yo encantado. Igual, si se levantan estas tensiones, debería uno revisar su parte de implicación en ello, y no levantarlas aun más, ya que las palabras , y más por escrito, tienen un reverso complicado y peligroso. No obstante , cada cual es libre de actuar y realizar según le marque su criterio. Yo, desde la modestia , y el humor, sana combinación creo yo, abogo porque las cosas no se tomen nunca tan en serio y con tanta trascendencia.  Y si se toman, pues se habla, que será mejor que irse al rincón de los mosqueos. 
Un saludo y... Benditiito seaisss todo!!

Pd:Chiiiiiiu!!!chuiuuu!!

**Comment by divadres** [comment]
Yo ya lo tengo preparado para añadirlo pero estoy esperando a q se apliquen los cambios que he introducido en el PR de la version mediaserver ya que lo tengo montado sobre ese codigo y sino tendre que cambiarlo luego...

**Comment by tvalacarta** [comment]
Por partes...

@kampanita, podemos cerrar el issue?

Yo el código lo veo bien, pero si el condvisibility no funciona podemos simplemente cambiarlo por una comprobación de que el directorio del add-on esté presente... Ya nos dices.

En cuanto a MCT, a mí me gustaría integrarlo en el master. Me parece una idea cojonuda de hecho porque veo que es la solución para ver torrents desde otras plataformas que no sean el omnipresente Kodi, aunque yo no estoy muy puesto en el tema de los torrents y lo de las librerías binarias me da escalofrios.

Precisamente por esto, si alguien se anima a hacer un PR con los cambios lo probamos y vamos palante.

**Comment by kampanita** [comment]
Si cerrad, cerrad... ;)


Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

2016-03-11 10:40 GMT+01:00 tvalacarta <notifications@github.com>:
