### ISSUE TITLE
Enlaces desactualizados en canales

### ISSUE THREAD

**Issue by carlosyague** [tvalacarta/pelisalacarta#15]
Buenas, me gustaría indicar una mejora para el plugin que sin duda ofrecería una mayor experiencia de usuario:

Es muy frecuente que cualquiera de los canales incluídos en el plugin tengan enlaces desactualizados que hacen que ya no estén disponibles.

Sin duda alguna, el problema reside en el canal que ofrece la información, pero estaría bien disponer de un sistema de indexación de pelisalacarta que fuese descartando aquellos enlaces rotos y por tanto, no aparecieran en las búsquedas que se realizan desde el plugin.

**Comment by tvalacarta** [comment]
No es mala idea :)

Queda como sugerencia, veo el problema de la enorme cantidad de enlaces.

Se podría alojar en un servidor, y que los fallos se registraran.

**Comment by kampanita** [comment]
Veo muy difícil de mantener esto, si el proceso de presentación de enlaces tiene que andar comprobando si dicho enlace está en una lista negra para no mostrarlo, serían demasiadas comprobaciones a hacer. ( en mi humilde opinión ). Esto podría ralentizar bastante la presentación de los menús, y sobrecargar el plugin de trabajo.

Si además eso lo ponemos en un servidor, añadimos tiempos de espera por las comunicaciones ( quizá de hacerse sería más lógico hacerlo con un fichero en local )

**Comment by carlosyague** [comment]
La idea podría ser que existiese un servidor en el corriese un proceso planificado que fuese de forma periódica (una vez al día por ejemplo) verificando los enlaces de cada uno de los canales registrados en el plugin y verificando si siguen activos o no.

Con respecto al proceso de búsqueda del usuario existen dos opciones:

1) Guardar en local un fichero con dicho índice y cuando un usuario busque un contenido se actualice el fichero de índice local con la última versión existente en el servidor y de este modo la búsqueda se haga localmente a partir de dicho índice.
* PROs:
** Se hace una única conexión con el servidor de índices y no es necesario hacer una búqueda canal por canal como se hace actualmente
** Desaparecen los contenidos con enlaces rotos con lo que tambien se reduce el número de resultados.
** Esta solución no requiere de una capacidad de procesamiento en servidor potente ya que el fichero con la última versión del índice podría publicarse en Dropbox, Box, etc.
* CONTRAs:
** Implica un penalización en almacenamiento local ya que obliga a guardar un fichero de índices.

2) Que el servidor de indexación ofrezca un servicio web que permita realizar las búsquedas en cada uno de los canales con todos los enlaces indexados considerados válidos. De este modo, el servicio web devolvería en una única petición todos los resultados con enlaces válidos.
* PROs:
** Se hace una única conexión con el servidor de índices y no es necesario hacer una búqueda canal por canal como se hace actualmente.
** Desaparecen los contenidos con enlaces rotos con lo que tambien se reduce el número de resultados.
** Esta solución no penaliza el almacenamiento local del usuario
* CONTRAs:
** El servidor de búsquedas requerirá de un mayor rendimiento

De las soluciones, la primera solución es facilmente abordable, la segunda implica mayores costes.

**Comment by kampanita** [comment]
- Lo de exponerlo como un servicio, yo no lo veo ningún problema, se puede usar desde un servidor ftp, hasta un fichero en mega, o servido por algún apache con login ... o ..., es decir, no tiene porque ser un webservice, puede hacerse fácilmente mediante otros métodos.

**Comment by SeiTaN80** [comment]
¿Esta mejora que comentais que seria como un "crawler" (araña), tipo Google o Bing indexando todos los enlaces o sólo los enlaces guardados para comprobarlos?

a) ¿Se encargará de obtener el mismo todos los enlaces y chequearlos?
b) El usuario accede al contenido que quiera y esos enlaces se guardaran en el fichero local o remoto, que posteriormente se comprobarán.

Aparte del sistema de comprobación de enlaces válidos, el usuario también debería poder marcar un enlace como no válido, y actualizar la lista.

Lo más importante de este sistema sería como se llevaría acabo la gestión de enlaces, si es un fichero global para todos, por usuario, o una mezcla de ambos.

Yo abogo por usuario y fichero local, ya que en mi caso (kodi en windows) no voy a tener problemas de máquina y sólo se tendrían en cuenta los enlaces que he buscado, aparte también hay que tener en cuenta otras plataformas y rendimiento.

**Comment by superberny70** [comment]
Nadie ha pensado que un servidor rastreando, recopilando y mostrando informacion sobre enlaces a material protegido vulnera nuestra querida LPI.
¿Quien y donde va a contratar ese servidor?

**Comment by carlosyague** [comment]
En mi opinión, la responsabilidad de este servidor sería analizar la disponibilidad (404 NOT-FOUND ó 200 OK) de los contenidos de los canales registrados en pelisalacarta.
Esta información sería explotada internamente desde la opción de búsqueda de los usuarios, y los resultados mostrados nos redirigirían a cada uno de los canales. Pelisalacarta no ofrecería el contenido, simplemente facilitaría la búsqueda disminuyendo el número de resultados.
La navegación que realizara cada usuario por cada canal eso sí debería mantenerse como hasta ahora para no tener problemas con la LPI.

**Comment by superberny70** [comment]
Vamos a ver si lo he entendido. 
Se trata de crear un script en un servidor q acceda a cada uno de los canales de pelisalacarta (¿cuantos hay? ¿10, 15, 20?) en algunos incluso con login. Acceder a cada una de las secciones (películas, series, películas hd, series hd, etc...) y dentro de cada sección acceder a cada contenido ( ¿todos? ¿Los 20 últimos? O los mas recientes ¿ultimo mes?)
Después para cada contenido acceder a cada servidor (algunos mediante cuentas premiun) para ver q responden (el 404 no te vale, lo normal es un q retorne una pagina q incluye el enlace al vídeo o un mensaje del tipo vídeo eliminado).
Con todo esto hacemos un fichero a modo de índice para q cuando el usuario llegue a la pagina de servidores d pelisalacarta si el enlace esta en el índice lo muestre y si no no lo muestre.
Uff no lo veo viable. 
Si no fuera por la LPI te diría hagamos un canal q busque en otros canales y q solo proporcione contenido que este operativo en pongamos 5 servidores. Pero ya te digo como esta el tema no lo veo.


Offtopic: no seria mejor portar este debate al foro de desarrolladores?

**Comment by r0balo** [comment]
El tema de los enlaces rotos debería ser sencillo, si no lo es no nos vale a no ser que quisieramos lucrarnos con eso, entonces sí, monto un servidor o servidores dedicados que analicen las webs, consigan las urls, comprueben encabezado+respuesta y añadan a una lista, llámese indexada o líneas o tuplas en md5, por ejemplo, para comerciar con esa lista por peticiones remotas seguras de un enlace a los usuarios "premium" :)

Cada individuo de pelisalacarta puede tener de mejor o peor manera una lista de de enlaces rotos con sólo 8 líneas si quiere ofuscar los enlaces, el problema para los pardillos como yo radica a la hora de filtrar en los canales. Dónde ponemos la entrada en los canales? findvideos? Me da que no, y si no se puede filtrar en findvideos no tenemos tema. Muy pero que muy pocos canales muestran el enlace al vídeo en la lista de servidores. Resumiendo, podemos tener una lista muy gorda de enlaces rotos que no podemos usar en dónde se debería usar.

**Comment by jurrKodi** [comment]
Buenos dias,

Os comento lo que yo hice en stormtv por si os sirve de idea. Yo no considero necesario que deban tenerse todos los enlaces de las webs indexados para saber si funcionan o no. Lo importante es que hayan enlaces, en mi caso lo que decidi fue que debia sacar un enlace "verificado" por servidor de stream, para que esto funcione es necesario que test_url_exist por servidor funcione y no devuelva true por defecto. El resultado es que se "verifican" los enlaces de una pelicula o episodio en el momento que el usuario pulsa sobre el item en cuestion, el problema es que resulta lento para el usuario, la solucion pre-verficarlos, es decir si estoy siguiendo una serie, veo cual es el último episodio visto y pre-verifico los 5 siguientes. Yo almaceno esta informacion en ficheros xml en el propio cliente por lo que no hace falta servidor centralizado y no se publica nada en internet.

Por si no usasteis Stormtv lo que hacia era una gestion de series, unificaba con un unico id la serie de distintos canales, y ademas añadia si estaba visto o no.

**Comment by r0balo** [comment]
Hola jurr
Algo parecido es lo que tengo hecho para testear pero recogiendo los datos de ```sys.argv[2]``` en ```xbmctools``` y no es para nada lento. Almaceno los enlances que se intentan visualizar en dos archivos de texto. Uno con los OK y otro con los KO. Además de de la url del servidor también recupera si existe el enlace de ```findvideos``` que es el que nos interesaría para filtrar.

Los datos que se almacenan suelen ser con este formato
```
pordede, Ver en vk (spanish) (Calidad Rip, audio Rip) (9 ok, 4 ko), 1|[visto] 1x1  Rose, , vk, http://www.pordede.com/aporte/yt....jw, http://vk.com/video_ext.php?oid=169...889&id=162...342&hash=157..........ab7, OK
```
El campo 6 es que se debería filtrar ```http://www.pordede.com/aporte/yt....jw```, es la url que le pasa ```findvideos``` a ```play```.

En teoría con algo así se podría filtrar pero como muy bien dices, se debería explotar al máximo ```test_video_exists```. Un ```Se ha producido un error en el conector...``` no lo podemos considerar como un enlace roto

**Comment by tvalacarta** [comment]
Si nadie opina lo contrario, cerramos este issue

**Comment by SeiTaN** [comment]
@tvalacarta por mi se puede cerrar :)
