### ISSUE TITLE
Cabeceras http en el fanart del item

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#177]
A raíz de la protección cloudflare que han puesto en el canal tv-vip, he tenido que modificar las urls de los vídeos, thumbnails y fanarts para que además de la dirección web se le añadan varias cabeceras http, ya que en caso contrario no funcionan. Esta solución es válida para los dos primeros, pero con el parámetro fanart se produce un error. Un ejemplo de una url sería:

`http://www.ejemplo.jpg|User-Agent=ejemplo&Cookie=ejemplo`

Creo que es debido a que la función get_params() del launcher hace un split al llegar al carácter "&" y al final el argumento que se le pasa al launcher cuando se entra en un item es erróneo, algo como `plugin://plugin.video.pelisalacarta/|User-Agent=Mozilla/......&channel=`

No sé cómo se podría solucionar, el problema es que no veo otra forma de cargar las imágenes de esa web... :disappointed:

**Comment by tvalacarta** [comment]
Una solución sería usar las nuevas opciones de serializar que tiene el item ¿no?

**Comment by CmosGit** [comment]
> Una solución sería usar las nuevas opciones de serializar que tiene el item ¿no?

Te refieres a que el item se genere como un dict, no? Pero si entiendo bien para eso habría que modificar el launcher para que no se extraigan los parámetros de un string. Supongo que ese es uno de los muchos cambios que se están haciendo en la rama develop de reorganización.

**Comment by tvalacarta** [comment]
Hay que modificar el launcher, claro :)
