### ISSUE TITLE
Errores por cambios en item.category

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#198]
Me he dado cuenta de que varios de los canales que he modificado últimamente para añadir el soporte a la biblioteca como tv-vip o descargasmix tienen varios apartados que funcionan mal. Esto es debido a que anteriormente el parámetro category del item por defecto era el nombre del canal si no se especificaba otro, tal y como se establecía en el launcher:

`    # Extrae la categoria`
`    if (params.has_key("category")):`
`        category = urllib.unquote_plus( params.get("category") )`
`    else:`
`        if params.has_key("channel"):`
`            category = params.get("channel")`
`        else:`
`            category = ""`

Pero ahora al utilizar el método item.fromurl() el category es una cadena vacía y de ahí los errores, ya que los utilizaba para comprobar si la llamada se producía desde un apartado del canal o desde la librería/actualización de ésta y ahora no lo discrimina. ¿Debo modificar eso en todos los canales o es posible volver a utilizar el category de esa manera?

**Comment by divadres** [comment]
Se puede modificar el ítem.py para que la categoría sea igual que el canal en caso de estar vacía...
Pero a mi personalmente no me parece un trabajo muy "limpio"... yo si no es muy complicado... creo que seria mejor hacer los cambios en el canal
Mas que nada por que el ítem se pase lo mas limpio posible sin alteraciones por el camino

Desconozco como funcionan esos canales y que diferencia tiene que hacer si la llamada se hace desde el canal o la librería... pero me parece mas sencillo modificar la librería para que cuando se haga la llamada desde ella modifique el campo category="library" y de esta manera sabes que la llamada se hace desde ahí...

**Comment by CmosGit** [comment]
La librería en principio tiene dos categorías, Cine y Series, y es el único parámetro por el que se puede diferenciar si se está haciendo la llamada desde un canal o desde un strm de la librería.

Yo no tengo problemas en modificar los canales, aunque son varios y no sé si algún otro utiliza este sistema, pero entiendo que la idea era introducir las modificaciones sin que el funcionamiento tal y como estaba hasta ahora se viese afectado y, al menos en mi opinión, no le veo mucha diferencia a que el category sea una cadena vacía o el nombre del canal si no se especifica un valor.

**Comment by SeiTaN** [comment]
@CmosGit a mi tb me ha pasado, lo que he hecho es añadir un campo nuevo al item `from_channel=XXXX`en el canal y ya en la biblioteca, u otro fichero, haces el `item.from_channel`.

**Comment by CmosGit** [comment]
@SeiTaN Es una buena solución, pero entiendo que eso sirve para las nuevas películas o series que se añadan una vez se modifique eso, lo malo es quienes tengan una añadida anteriormente no le valdrá :disappointed:

**Comment by SeiTaN** [comment]
ahh, vale ya te he entendido.
Pues vas a tener que modificarlo, "lo bueno" es que tu desarrollo de biblioteca no lo está usando mucha gente, vaya consuelo ya :smile:

**Comment by divadres** [comment]
Se puede crear una funcion temporal en la libreria y que actualize los strm para añadir el item.category... y en la siguiente actuslizacion borrarla... asi todos los strm guardados se actuslizarian y ya funcionarian

¿que te parece?

**Comment by divadres** [comment]
he estado releyendo todo esto y... no acabo de entender cual es el problema... corrígeme si me equivoco:

cuando abres un strm de la librería el ítem.category puede ser "Series" o "Cine" no?
y los demás ítems, el ítem.category antes era igual al canal y ahora es "" no?

**Comment by CmosGit** [comment]
Gracias @divadres, pero lo que he hecho es modificar los canales para que funcionen si el category es una cadena vacía, con eso se soluciona y tampoco hay que darle muchas más vueltas :wink: 

Sí, en respuesta a tu último mensaje el único cambio es ese, por eso preguntaba si debía modificar los canales o se podía seguir utilizando el category como hasta ahora, pero como muy pocos canales utilizan un código parecido a los míos, pues los modifico y no se hable más xD

**Comment by divadres** [comment]
Vale... pues entonces ya esta...

**Comment by SeiTaN** [comment]
pues a chapar el issue xD
