### ISSUE TITLE
Problemas en la actualización de canales. Nueva línea con "0x0D0D0A"

### ISSUE THREAD

**Issue by r0balo** [tvalacarta/pelisalacarta#207]
Pues eso mismo :)
No hago un PR por que no me fio mucho de lo que pueda pasar al no tener mi copia del github actualizada y como sólo es una letra lo que hay que añadir, pues eso.

Es añadir en el updater la letra `b` al `outfile = open(local_channel_path,"w")` para que quede `outfile = open(local_channel_path,"wb")`

Normalmente no pasa nada y funciona el canal. Sólo nos damos cuenta cuando lo ojeamos para consultarlo o editarlo.

Hoy he forzado la actualización de seriesdanko para asegurarme que no he tocado nada para compararla con una versión personalizada y me ha dado error.
```
  File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_0_8\channels\seriesdanko.py", line 441
    "<img src='/assets/img/servidores/([^\.]+).+?</td><td.+?href='([^']+)'.+?>.*?</a></td>" \
    ^
IndentationError: unexpected indent
```
Esto lo arregla una letra :)

**Comment by tvalacarta** [comment]
Hecho.

Aunque no entiendo por qué eso resuelve el error, si es un fichero de texto debería dar igual escribirlo como texto que como binario...

**Comment by SeiTaN** [comment]
> Aunque no entiendo por qué eso resuelve el error, si es un fichero de texto debería dar igual escribirlo como texto que como binario...

Cierto, no debería ser **rw**? aunque de permisos no entiendo mucho, se supone que es lectura y escritura, de ahí que tienes el fichero abierto y luego intenta escribirlo, no? si añades **b** es para guardar como binario el fichero.

**Comment by r0balo** [comment]
Hay que pensar en windows :)
Todos los ficheros son binarios, la interpretación del binario es tarea de SO  y de las aplicaciones que están sobre él. Con 'wb' te aseguras de que no elimina ni añade nada, se limita a escribir lo que se le entrga sin interpretar saltos de líneas ni chorradas varias que puede implicar un formato de archivo.

**Comment by divadres** [comment]
Yo siempre uso binario... porque de ls otra manera he tenido problemas muchas veces...
