### ISSUE TITLE
cambios en la vista miniaturas de kodi

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#211]
En la ultima version aparecen dos filas de items en las vistas Miniatura, en lugar de las tres q aparecian antes. ¿Habeis cambiado algo?

v.4.0.7
![captura](https://cloud.githubusercontent.com/assets/7559559/14299879/4a2c1ca2-fb8d-11e5-86ec-09c7a1f7ed8a.PNG)

v4.0.9
![captura2](https://cloud.githubusercontent.com/assets/7559559/14299948/b0635936-fb8d-11e5-8f16-53454f53b4cc.PNG)

**Comment by r0balo** [comment]
El motivo aparante es por dejar de usar la función addfolder en el channelselector y dejarle el marrón a xmbctools [#189](https://github.com/tvalacarta/pelisalacarta/commit/11238369964d7fbca601aab2ed562e769b26bd73#diff-eb266f366b2fa025f41299e6fd8ad74a)
Si queremos los 5x3 podemos dar un paso atrás.
```
            else:
                logger.info("channelselector.mainlist Verificar actualizaciones desactivado")

    itemlist = getmainlist()
	#Se devuelve el itemlist para que xbmctools se encarge de mostrarlo
    #return itemlist
    pasoatras(itemlist)

def getchanneltypes(preferred_thumb=""):
```
```
def channeltypes(params,url,category):
    logger.info("channelselector.mainlist channeltypes")

    lista = getchanneltypes()
	#Se devuelve el itemlist para que xbmctools se encarge de mostrarlo
    #return lista
    pasoatras(lista)

def listchannels(params,url,category):
    logger.info("channelselector.listchannels")

    lista = filterchannels(category)
	#Se devuelve el itemlist para que xbmctools se encarge de mostrarlo
    #return lista
    pasoatras(lista)

```


```
def pasoatras(itemlist):
    import xbmc
    import xbmcgui
    import xbmcplugin
    for elemento in itemlist:
        listitem = xbmcgui.ListItem( elemento.title , iconImage="DefaultFolder.png", thumbnailImage=elemento.thumbnail)
        itemurl = '%s?channel=%s&action=%s&category=%s' % ( sys.argv[ 0 ] , elemento.channel , elemento.action , elemento.category )
        xbmcplugin.addDirectoryItem( handle = int(sys.argv[ 1 ]), url = itemurl , listitem=listitem, isFolder=elemento.folder)
```

**Comment by divadres** [comment]
Pues entonces es culpa mia...
Pero tranquilo hay una manera bastante mas sencilla de arreglarlo... mañana subo un PR con el arreglo...

**Comment by r0balo** [comment]
Muy bien, menos code sin paso atrás, pero también se puede hacer paso adelante con menos código. Eliminar la línea 857 del xbmctools `xbmcplugin.setContent(pluginhandle,"Movies")`
:)

**Comment by tvalacarta** [comment]
Bien visto ja ja ja

**Comment by divadres** [comment]
Bueno... se puede eliminar pero entonces siempre saldran pequeñas... y no se si es lo que se busca... ya digo que yo siempre lo tengo en modo lista asi que s mi me da igual....

**Comment by superberny70** [comment]
La misma pregunta entonces q he hecho en otro sitio: ¿para q sirven realmente xbmcplugin.setContent y xbmcplugin.setPluginCategory?

**Comment by tvalacarta** [comment]
No está hecho con mucha intención tampoco...

Lo lógico es que el contenido sea el apropiado (peliculas, series, episodios) y la vista la que el programador del canal elija. Pero al final todo depende siempre del skin, de lo completos que sean los datos, de cómo sople el viento en el Kodi Team etc.

Yo soy más de la versión Skin, y los canales se ven muy chulos ahí.

Lo único que yo apuntaba es que el fix de @r0balo es muy elegante :)

**Comment by tvalacarta** [comment]
> La misma pregunta entonces q he hecho en otro sitio: ¿para q sirven realmente xbmcplugin.setContent y xbmcplugin.setPluginCategory?

El setContent te permitirá elegir vistas apropiadas al contenido (un skin no tiene las mismas vistas en pelis que en series).

El setPluginCategory ni idea :(

**Comment by divadres** [comment]
Deben ser de dstas cosas que algun dial alguien pusi para algo... y ahi se ha quedado...

**Comment by divadres** [comment]
setPluginCategory(...)setPluginCategory(handle, category)--Sets the plugins name for skins to display.
  
 handle : integer - handle the plugin was started with.
 category : string or unicode - plugins sub category.
  
 example:
     - xbmcplugin.setPluginCategory(int(sys.argv[1]), 'Comedy')

**Comment by tvalacarta** [comment]
La clave ahí es "for skins to display".

Yo creo que ni Confluence lo usa, estaría bien poner ahí aunque fuera el nombre del canal :)

**Comment by superberny70** [comment]
Joder o estoy empanao (q seguro q si) o aqui hay meigas!!!
Resulta q para hacer pruebas he sustituido la linea 857 q comentaba @r0balo por:
`
#xbmcplugin.setContent(pluginhandle,"files") #lista, lista grande, miniatura y ancho
#xbmcplugin.setContent(pluginhandle,"songs") #lista, lista grande y miniatura
#xbmcplugin.setContent(pluginhandle,"artists") #lista, lista grande y miniatura
#xbmcplugin.setContent(pluginhandle,"albums") #lista, lista grande y miniatura
#xbmcplugin.setContent(pluginhandle,"movies") #lista, lista grande, miniatura, envoltura del cartel, fanart, info del medio, info del medio 2 y info del medio 3
#xbmcplugin.setContent(pluginhandle,"tvshows") #ancho, lista, lista grande y miniatura, envoltura del cartel, fanart(recomendado), info del medio, info del medio 2 y info del medio 3
#xbmcplugin.setContent(pluginhandle,"episodes") #lista, lista grande miniatura, envoltura del cartel, info del medio, info del medio 2 y info del medio 3
#xbmcplugin.setContent(pluginhandle,"musicvideos") #lista, lista grande, miniatura e info del medio(recomendada)`

y he ido probando de descomentar una linea cada vez, para ver q tipo de vistas permitia segun el contenido q le pusieras. y despues he ido añadiendo al final de la linea los tipos de vistas detras # para no liarme. 
Hasta aqui todo bien, aunq por ejemplo 'files' y 'movies' tengan un modo de vista llamado 'miniatura' existen pequeñas diferencias entre ellos (el primero permite 3 filas y el segundo solo 2), lo q es del todo correcto.
Ahora bien, si dejamos todas comentadas (o sencillamente eliminamos la 857 y no ponemos nada mas kodi 'milagrosamente' asigna el contenido como 'files' para todo lo q sea channelselector (excepto Novedades) y al resto de canales les asigna 'movies'.

A ver si vosotros encontrais la razon, por q yo estoy EMPANAO

**Comment by divadres** [comment]
Por lo que he podido comprobar... las vistas de kodi parece que tienen memoria... si eliges una del menu lateral izq... parece que la memoriza y cuando vuelves a entrar en ese item... vuelve a salir esa... quiza sea algo de eso lo que te pasa....

**Comment by superberny70** [comment]
> Por lo que he podido comprobar... las vistas de kodi parece que tienen memoria...
Eso pasa por q se guarda en la BBDD. Pero no es eso.

Cada tipo de contenido permite una serie de vistas, no tiene sentido utilizar la vista info del medio o  la vista fanart en un menu de opciones del tipo: Estrenos,  Por orden alfabetico, Busca...

**Comment by superberny70** [comment]
Bueno, no dejo de estar empanao, peroparece q hoy un poquito menos :)
el motivo no eran las meigas, sino la linea 400 del launcher:
```
# Activa el modo biblioteca para todos los canales genéricos, para que se vea el argumento 
... 
xbmcplugin.setContent(int( handle ),"movies")
```

Por cierto la linea 381 del xbmctools tb esta mal: 
```
item.category = item.category
```
deberia ser 
```
item.category = parentitem.category
```
A ver si ahora q lo entiendo le puedo dar una vuelta :)

**Comment by tvalacarta** [comment]
Debates aparte, este issue también se puede cerrar :)
