### ISSUE TITLE
peliculasdk adultos

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#212]
El canal peliculasdk deberia etiquetarse como adulto, ya q en algunas secciones devuelven material pornografico.

**Comment by r0balo** [comment]
Casi mejor a nivel de canal para no vetar el canal completo. Están etiquetadas en la página como `Adultos`. Sólo hay que scrapear el género y filtrarlo. De paso se le podría añadir más opciones y la paginación que parace que no tira

**Comment by neno1978** [comment]
Ok mamones, lo tengo en la lista, ya me di  cuenta comprobando el canal un dia... En familia 😁... Es q estoy liao de tiempo.  Lo de la paginación no me dao cuent... La última vez tiraba ... X cierto master, igual pronto tienes noticias mías...vigila tus espaldas peludas...

**Comment by r0balo** [comment]
Pues a ver como duermo está noche :)

**Comment by neno1978** [comment]
No tan pronto, más bien tarde , Pero duerme tapadito 😜

**Comment by superberny70** [comment]
solucionado
