### ISSUE TITLE
empaquetado pelisalacarta-ui-kodi-isengard-4.0.9.zip

### ISSUE THREAD

**Issue by r0balo** [tvalacarta/pelisalacarta#215]
No se si se ha comentado, en el blog, foro y aquí no lo he visto pero nunca se sabe.

En el contenido del zip para descargar desde el blog, el que he puesto en el título, incluye en sus entrañas `pelisalacarta-ui-kodi-jarvis-4.0.9.zip`
:)
No se si se te habrá colao en algún paquete más

**Comment by tvalacarta** [comment]
En realidad no es un fallo... es una solución provisional.

Como todas las versiones de Kodi son iguales, simplemente a la hora de empaquetar la versión skin genero el mismo fichero con distintos nombres:

`        <zip destfile="${target}/kodi-16-jarvis-ui/pelisalacarta-ui-kodi-jarvis-${version}.zip" basedir="${target}/kodi-16-jarvis-ui"/>
        <zip destfile="${target}/kodi-16-jarvis-ui/pelisalacarta-ui-kodi-isengard-${version}.zip" basedir="${target}/kodi-16-jarvis-ui"/>
        <zip destfile="${target}/kodi-16-jarvis-ui/pelisalacarta-ui-kodi-helix-${version}.zip" basedir="${target}/kodi-16-jarvis-ui"/>
        <zip destfile="${target}/kodi-16-jarvis-ui/pelisalacarta-ui-xbmc-gotham-${version}.zip" basedir="${target}/kodi-16-jarvis-ui"/>
`
Así la gente no duda a la hora de descargar.
