### ISSUE TITLE
imagenes en resources

### ISSUE THREAD

**Issue by divadres** [tvalacarta/pelisalacarta#216]
En el commit 2cb3f53f7d90143db863b7ae6e25094820550cad se eliminaron de GitHub los archivos:

thumb_error.png 
thumb_folder.png 
thumb_nofolder.png 

Siendo estos usados en la versión UI, y to también los usaba en la versión mediaserver, hay alguna razón para su eliminación? es posible acceder a estos archivos mediante la url "http://media.tvalacarta.info/..." ?

**Comment by tvalacarta** [comment]
Creo que puse un comentario en el commit...

Los iconos son parte de una colección que compré para esto.

El problema es que la licencia nos permite usarlos en un unico proyecto o
producto (aplicable a pelisalacarta en todas sus versiones), da igual que
estén en el zip o en la URL, pero si los subo a Github los estamos
redistribuyendo bajo GPL que otros pueden usar y redistribuir.

Y eso no lo permite la licencia...

Un lio, lo se, pero no lo pensé cuando los compré y no encontraba unos
libres que me gustaran. Algún dia puede que los cambie si encuentro otros.

En tvalacarta no los cambié por eso, y uso unos libres.

**Comment by divadres** [comment]
Entiendo... pensaba que los habías echo tu... entonces están disponibles en la url? porque no consigo mostrarlos... si es así cual es la url. lo lógico seria:
http://media.tvalacarta.info/pelisalacarta/bannermenu/thumb_folder.png
http://media.tvalacarta.info/pelisalacarta/bannermenu/thumb_error.png 
http://media.tvalacarta.info/pelisalacarta/bannermenu/thumb_nofolder.png 

Pero en esa url no existen, antes esos tres estaban dentro de la carpeta images, aunque creo que lo lógico es que estuvieran dentro de bannermenu"

**Comment by tvalacarta** [comment]
En un rato lo reviso, igual estan solo en el ZIP.

**Comment by tvalacarta** [comment]
Ya los tienes subidos, pero la URL correcta es:

http://media.tvalacarta.info/pelisalacarta/thumb_folder.png
http://media.tvalacarta.info/pelisalacarta/thumb_error.png
http://media.tvalacarta.info/pelisalacarta/thumb_nofolder.png

Ya que no son "bannermenu", sino iconos normales.

**Comment by kampanita** [comment]
Pues si quieres podemos mirar a hacerlos nosotros... ;)
No es que sea un hacha diseñando pero, bueno....todo lo que sea ahorrar
unos eurillos y evitarte problemas de licencias....

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

**Comment by tvalacarta** [comment]
Si es por hacerlos yo también se hacerlos. Lo que no tengo es ese toque para que además sean bonitos, por eso acabé comprando unos ja ja ja

En tvalacarta no voy a comprarlos, precisamente por el tema de licencia y porque los actuales me parecen bien.
