### ISSUE TITLE
¿Filenium ha dejado de existir? Habría que eliminarlo de pelisalacarta

### ISSUE THREAD

**Issue by spaniard1978** [tvalacarta/pelisalacarta#229]
Al menos su web ya no es accesible, por lo que no tiene sentido mantenerlo como servicio no?

**Comment by tvalacarta** [comment]
No, claro.

No tenía ni idea de que ya no existía...

**Comment by SeiTaN** [comment]
@tvalacarta ¿puedes cerrar este issue? Ya estaría corregido con el PR mergueado de @divadres, gracias.
