### ISSUE TITLE
Fallo en DocumaniaTV

### ISSUE THREAD

**Issue by juanpintom** [tvalacarta/pelisalacarta#235]
Hola ,  me falla documania en kodi, tanto en helix como en jarvis, versión 4.0.9,  las novedades y por canales salen vacíos y en top y viendo ahora salen pero da error al reproducir, paso log del helix.
http://pastebin.com/gmqLV2pi

Gracias de antemano 

Salu2

PD.  He intentado reabrir esta [issue](https://github.com/tvalacarta/pelisalacarta/issues/35) pero creo que no tengo permisos xD

**Comment by kampanita** [comment]
https://raw.githubusercontent.com/CmosGit/pelisalacarta/conectores/python/main-classic/channels/documaniatv.py

**Comment by juanpintom** [comment]
Perfecto! Gracias por lo concisa y efectiva de la respuesta :)

Salu2

**Comment by juanpintom** [comment]
Lamentablemente vuelve a fallar :( reabro

**Comment by tvalacarta** [comment]
Resuelto (espero), con el soporte al add-on de Cnubis
