### ISSUE TITLE
Arreglar Conector de OpenLoad

### ISSUE THREAD

**Issue by daniel0707** [tvalacarta/pelisalacarta#275]
El scrapper dejo de funcionar en Openload porque la etiqueta `<video>` cambio, ahora funciona de esta manera.
En el archivo openload.py

Buscar esta linea
`text_encode = scrapertools.get_match(data, "<video[^<]+<script[^>]+>(.*?)</script>")`

y reemplazar por

`text_encode = scrapertools.get_match(data, "</div[^<]+<script[^>]+>(.*?)</script>")`

Saludos.

**Comment by SeiTaN** [comment]
@daniel0707 esto ya lo cambio @CmosGit hace un par de semanas (está en la rama develop), cuando salga la nueva versión se actualizará con el arreglo.

**Comment by daniel0707** [comment]
Muy bien, gracias!
