### ISSUE TITLE
Gestión de cookies

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#279]
Quería comentar un pequeño contratiempo que me ha surgido a la hora de probar el "nuevo" sistema de almacenamiento de cookies que se ha implementado en el scrapertools de la rama develop.

Resulta que mientras estaba probando el arreglo del canal pelispedia, el cual utiliza cloudflare por lo que necesita del archivo de cookies correcto para funcionar, me encontré con que tal y como estaba configurado el canal las urls se formaban con el dominio "http://pelispedia.tv", con lo cual el archivo de cookies se guardaba con el nombre "pelispedia.tv.dat". Pero a la hora de scrapear la página la url que devolvía al entrar en una película/serie era con el dominio "http://www.pelispedia.tv", por lo que el nombre de la cookie era distinto y el canal fallaba al no poder leer las cookies previas.

Sé que en este caso es muy sencillo solucionarlo, pero en mi opinión creo que se podrían evitar errores al darse casos así de redireccionamiento eliminando las "www." de los nombres de los archivos de cookies, no sé si lo veis igual.

También, al hilo de esto, se podría modificar el método get_cookie_data del archivo config con la nueva ruta de las cookies y que reciba una variable con el nombre del archivo .dat.

**Comment by SeiTaN** [comment]
Estoy de acuerdo, creo que sólo debería tener el dominio de la url por lo que comentas.

**Comment by divadres** [comment]
Pues ahor mismo no recueedo como esta echo... y eso que lo hice yo... pero estoy de acuerdo con el dominio es suficiente

**Comment by r0balo** [comment]
No estoy muy seguro pero creo que la única modificación es la ruta y el nombre del archivo `/get_data_path/cookies/dominio.dat`.
Que problemas había en la forma anterior de almacenar las cookies en un sólo archivo? Existian problemas con algunas urls o canales?

@SeiTaN 
Creo son 6 entradas para el valor de `ficherocookies` para la ruta del .dat en `scrapertools`

**Comment by divadres** [comment]
El cambio se hizo para el multithread del buscador... ya que cuando se descargan varias urls simultaneamemte da error al escribir varios threads en el mismo archivo de cookies al mismo tiempo

**Comment by r0balo** [comment]
ok

**Comment by SeiTaN** [comment]
@r0balo hice dos commits, en el primero que haces referencía sólo lo puse en un sitio, ya luego en el segundo lo puse en todos los sitios que aparecía `domain` :wink:

**Comment by r0balo** [comment]
Pues perfecto, no? Y digo yo, qué pasaría si la url en el servicio o máquina usa algo diferente a `www`? Que como poder puede pasar `series.perico.tv` `peliculas.perico.tv`
Ante estos casos, cómo se debería actuar? Se crearían dos archivos o sólo uno?
Y si pasamos de preguntarnos la última de las preguntas, no sería mejor usar algo parecido a `dominio = ".".join(d for d in urlparse.urlparse(url)[1].split(".")[-2:])`? :wink:

**Comment by SeiTaN** [comment]
Pues por que fuí a lo fácil jajaja, y sólo cubrí el caso que daba problemas.

Una duda, ¿no sobraría el for `dominio = ".".join(d for d in urlparse.urlparse(url)[1].split(".")[-2:])` por `dominio = ".".join(urlparse.urlparse(url)[1].split(".")[-2:]))`?

**Comment by r0balo** [comment]
Puro vicio, por eso lo de "algo parecido a", tendemos a vicianos y casi siempre existen soluciones diferentes para un mismo resultado 😄

**Comment by SeiTaN** [comment]
Pues lo pongo por aquí... tp valdría esta solución, con los dominios de tercer nivel como me comentó @superberny70 , estaríamos jodidos.

He estado investigando y al parecer se puede hacer [consultando un fichero](http://codeblow.com/questions/python-extract-domain-title-from-url/), pero no sé si merece la pena y podamos usar algo más simple para generar el nombre `cookies/xxxxx.dat`

**Comment by superberny70** [comment]
No he podido mirarme el codigo, pero pregunto: si el Problema es nombre del fichero, no se puede usar el nombre del canal?
y por otra parte: si el Origen del.problema es el acceso al archivo unico de cookies desde diferentes hilos, no se podria utilizar un metodo lock para bloquear el acceso a dicho fichero, permitiendo q solo uno de los hilos pueda escribir en el?

**Comment by divadres** [comment]
Usar el nombre del canal... no me parece una solucion muy buena... ya que si intentamos acceder desde otro canal a la misma url no podriamos usar las cookies y a demas tendrismos q pasarle el nombre del canal a scraperools para q sepa desde q canal se descarga la pagina... por otro lado... usar el lock funcionaria pero perderiamos la gracia del multihilo ya que hasta q no termine un hilo y cierre el archivo no empezaria el siguiente.

**Comment by divadres** [comment]
Peronpienso yo... en realidad, si yo no estoy equivocado el navegador de inyernet cuando genera las cookies las gener tambien para cada domino de manera que:
Pelis.dominio.com
Series.dominio.com 
No compartirian cookies...

En el caso particular q nos encontramos no seria mas facil.. si al scrapear te devuelve www.dominio... utilizar tambien www. Para  descargar las paginas al entrar al canal  y de esta  manera ya coincidiria todo el rato, no?

**Comment by CmosGit** [comment]
@divadres  Es lo que dije en el primer mensaje, que particularmente en ese canal tiene fácil solución, pero era para evitar posibles errores que se pueden dar por casos así. Al menos en firefox que es donde lo he comprobado, siempre se guardan las cookies sin el "www.".

**Comment by divadres** [comment]
Pues habria que buscar un sistema para separar el subdominio del dominio principal... algo un poco mad elegante que un .replace("www.","")

**Comment by CmosGit** [comment]
A ver qué os parece esta función:

`def get_subdomain_from_url(url):`

    subdomain = urlparse.urlparse(url).hostname
    if subdomain.count(".") > 1:
        domain = subdomain.split(".")
        subdomain = [".".join(domain[i:]) for i in range(len(domain))][len(domain)-2]

    return subdomain`

Con ella, cualquiera que sea la url, siempre devolvería el dominio principal (dominio.com), y da igual que delante solo esté el http://, las www. o una serie de subdominios.

**Comment by superberny70** [comment]
@CmosGit si no me equivoco esa funcion hace lo mismo q la propuesta por @r0balo y @SeiTaN:
Te quedas con lo q hay a izquierda y derecha del ultimo punto ¿no?
Si es asi tiene el mismo problema con los dominios de tercer nivel. Os pongo tres ejemplos reales y suponer q fueran webs de peliculas :smirk::

http://www.tta.com.es/es/index.php
http://www.nti.com.es/
http://www.garro.com.es/

En los tres casos, sino me equivoco, te quedas con 'com.es' por lo q solo se crearia un fichero para tres webs q nada tiene q ver entre ellas y con el consabido error del buscador multihilos.

Por otra parte, he estado mirando scrapertools y no se si es mi falta de sueño o q pero menudo lio.
¿Todo lo referente a la cache se utiliza? ¿todos esas funciones para limpiar codigos html, xml, etc.. se usan? 
Aunq si he visto q lo de los locks no es viable. Lo q no descarto aun es lo del nombre del canal como nombre del fichero: 

- Por un lado no es necesario pasarle el nombre a la funcion, en otros puntos del desarrollo ya hemos obtenido el nombre del canal mediante la pila de llamadas.

- ¿Accedemos a la misma url desde dos canales diferentes? Y si asi fuera, tendriamos dos cookies para esa url, pero cada una para una sesion ¿no?

**Comment by CmosGit** [comment]
@superberny70  Es que para discriminar en ese tipo de dominios se necesitaría una referencia para contrastar que existen, algo como hace la librería [tldextract](https://pypi.python.org/pypi/tldextract), que comprueba los sufijos utilizando esta [lista](https://www.publicsuffix.org/list/public_suffix_list.dat)

Sobre las funciones de scrapertools, creo haber leído hace tiempo a Jesús decir que todo lo referente al caché fue un intento que al final no ha sido muy útil. Y sobre las de limpieza de códigos a mí me han sido muy útiles varias veces.

**Comment by divadres** [comment]
Me parece que no estamos complicando la vida innecesariamente:
He estado haciendo unas pruebas con una web que tengo alojada con el navegador y te las separa de la siguiente forma:

```
dominio.com             -> dominio.com
www.dominio.com         -> dominio.com
subdominio.dominio.com  -> subdomino.dominio.com
```
Realmente supone un problema que las cookies de subdominio.dominio.com no sean accesibles desde dominio.com y viceversa? porque según tengo entendido, el navegador no envía cookies si no pertenecen al mismo dominio, y tampoco se puede acceder a ellas si no pertenece al dominio, por otro lado seria un agujero de seguridad enorme que una web pudiera leer las cookies de otra solo porque estén dentro del mismo dominio principal, creo que en realidad no necesitamos hacer nada de eso, realmente lo que hace en el caso de pelispedia.tv cuando entras por http://pelispedia.tv es redirigirte a www.pelispedia.tv, pero como habíamos enviado la url sin www. pues el nombre del archivo de cookies ya se ha generado así
Creo que el problema lo tenemos en cuanto a las redirecciones, es decir, si tu solicitas la pagina http://www.prueba.com y esta te redirige a http://www.resultado.com, las cookies que genere www.resultado.com scrapertools las guardara en prueba.com.dat y no en resultado.com.dat

**Conclusión:**
o evitamos las redirecciones, solicitando siempre la página real, o volvemos a juntarlo todos en un solo archivo cookes.dat, y buscamos la formula para que no haya problemas con multithread

**Comment by CmosGit** [comment]
Yo no veo un problema que el nombre de las cookies incluya el subdominio, lo único que veía innecesario eran las "www.", y lo argumentaba diciendo que los navegadores hacen lo mismo, las guardan siempre sin ellas. Sois vosotros que os habéis liado la manta a la cabeza :laughing: 

Sobre las redirecciones, lo mismo me equivoco pero no creo que sea algo que se deba tocar, si se evitan habrá páginas que no carguen porque la redirección es necesaria.

**Comment by divadres** [comment]
Hay que tener en cuenta que con este sistema (un archivo por dominio) siempre que haya una redirección que cambie de dominio (o mejor dicho de archivo de cookies) estas no se guardaran bien, si no las necesitamos no va a pasar nada, pero si las necesitamos no funcionará

**Comment by CmosGit** [comment]
@divadres Y qué te parece usar el método de cookies con diferentes nombres si se usa el buscador global y para todo lo demás tal y como estaba antes, con el cookies.dat?

Se podría agregar a las funciones de scrapertools un parámetro tipo "buscador=False", así por defecto se utilizaría el cookies.dat y cuando se llame desde el buscador se crearían archivos aparte para que funcionase correctamente el multihilo...

**Comment by divadres** [comment]
@CmosGit no sirve... ya que las llamadas a scraperools se hacen desde el canal no desde el buscador, de manera que no se puede discriminar... yo personalmente si añadiendo la excepcion del www. No tenemos ningun problema... no lo tocaria...

**Comment by superberny70** [comment]
**Modo Matias On:** Permitame...que insista :laughing::laughing::laughing:
¿Que problema veis al utilizar el nombre del canal para el archivo de cookies?

**Comment by divadres** [comment]
Yo personalmente ninguno... si sirve ya estaria bien tambien

**Comment by SeiTaN** [comment]
¿Al final como vamos a dejar esto? ¿Dejo lo que dice @divadres de eliminar sólo las www? ¿o se va a utilizar el nombre del canal como nombre del fichero de cookies como dice @superberny70?

**Comment by tvalacarta** [comment]
Yo no me he metido a fondo con el tema pero, ¿no bastaría con poner un semáforo para acceder al cookies.dat y dejarlo como estaba?

En el fondo sólo se lee antes de la petición y se escribe después de la petición, por lo que el tiempo de bloqueo sería mínimo.

Si no lo veis claro, me gusta más el nombre del canal que el dominio. Dominios habrá centenares (node1.blablabla.com, node2.blablabla.com, ...), y el número de canales es el que es.

**Comment by divadres** [comment]
Al principio dije que un Lock() o semaforo (no se q diferencia hay) le quitaria la gracia al multithread ya q habra que esperar a q uno termine para que continue el otro... pero pensandolo bien si el lock se pone solo para acceder al archivo, no creo que le afecte ya que el tiempo q esta para leer/escribir en el archivo es muy poco y securamente, a falta de probarlo, sea la mejor solucion de todas

**Comment by tvalacarta** [comment]
Es lo mismo... depende de si eres de la vieja escuela o no :)

Fíjate en el código del scrapertools, lo que hace es leerlo al empezar, luego hace la llamada con ese objeto en memoria y al terminar lo escribe de nuevo.

Basta un semáforo al escribir y listo.

**Comment by superberny70** [comment]
Pues yo lo estuve mirando y no lo vi tan facil.
Hablamos de un unico fichero de.cookies. supongamos q dos canales leen el
fichero, despues de hacer sus 'cositas' el canal 1 guarda los cambios. Acto
seguido es el canal 2 el q ha de guardar la copia q tenia en memoria. Si lo
hacemos tal cual el.canal 2 machacara los cambios del canal 1.
Para evitarlo se ha de bloquear el fichero cuando el canal 1 lo lee y no
liberarlo hasta q escriba sus cambios. Por lo q la multitarea se va a tomar
por c...

Otra cosa es q en.realidad cada canal solo utiliza una parte de ese
fichero, por lo q se podria crear una funcion.q retorne/modifique solo las
cookies de un canal.

**Comment by divadres** [comment]
Lo que habria q probar... a ver si no da problemas es

Al importar scrapertools

cj = cookielib.MozzilaCookieJar()
cj.load("cookies.dat")
lock = threading.Lock()

def downloadpage(parametros...):
   ...
   aqui utilizamos el cj global y telizamos el request...

   Al finalizar
   with lock:
       cj.save("cookies.dat")


Quedaria ver si hay algun tipo de problema en que varios rquest comoartan el mismo objeto MozzillaCookeJar...

Todos los hilos guardarian el fichero cookies.dat al terminar con todo el contenido creo que podria valer...

**Comment by tvalacarta** [comment]
¿Realmente hay algún problema en que se pierda alguna cookie ocasionalmente?

Esto sólo se usa en el buscador, no en el login ni nada por el estilo ¿no?

A mí el código de @divadres me suena bien...

**Comment by SeiTaN** [comment]
Falta por arreglar esto, ya sea con el último código de @divadres o con el simple replace de "www.", si no habrá canales que no funcionen correctamente por el cloudflare.

**Comment by tvalacarta** [comment]
Mmm, por eso no funcionará seriesflv.... le estuve dando unas cuantas vueltas y no lo entendía.

Yo creo que la ventaja de hacer búsquedas / novedades multi-hilo no compensa todo esto ni los problemas que introduce.

Para resolverlo propongo primero volver a un único fichero cookies.dat para todas las cookies. Esto sólo dará problemas (teóricamente) en las operaciones multi-hilo, y así no rompemos nada más.

Y a continuación hacemos pruebas implementando un nuevo MultithreadCookieJar, que podría extender del MozillaCookieJar, que cada vez que se modifique una cookie actualice el fichero en disco con un lock. Viendo el API de la clase no parece complicado.

Me preocupa que tanto bloqueo y desbloqueo deje threads colgando que acabe por tirar la ejecución, pero es el precio del multihilo.

**Comment by superberny70** [comment]
Lo de las pruebas con MultithreadCookieJar, me parece bien, pero lo de renunciar a los multihilos no creo q sea la solucion. Has visto la diferencia entre una busqueda normal y otra multihilos? 
insisto en utilizar de momento un archivo por canal para las cookies, pero utilizando el nombre del canal en lugar de la web.
Yo no puedo probar nada ahora, pero seguro q alguien se anima y lo hace.

**Comment by CmosGit** [comment]
> insisto en utilizar de momento un archivo por canal para las cookies, pero utilizando el nombre del canal en lugar de la web.

Con esto habría que modificar todos los métodos de scrapertools para que reciba el nombre del canal, no? Está claro que más que complicado, con todos los canales y conectores que hay que cambiar, lo que sería es tedioso xD

**Comment by tvalacarta** [comment]
¿Y cómo pasas el nombre del canal hasta allí?

Yo no lo veo... tampoco pasa nada por ignorar simplemente el problema hasta que esté ese MultithreadCookieJar ¿no?

**Comment by SeiTaN** [comment]
Y digo yo, si de momento no se va a hacer "en condiciones y reprobado" (con los cookiejar y tal), y queriendo la mayoría el tema de los multihilos ¿por que no parchearlo con replace("www.", "")??

**Comment by divadres** [comment]
Opino lo mismo que @Superberny en los canales no hay que cambiar nada y por lo demas los cambios q hay que hacer en scrapertools no sonuy complicados... yo mismo los podria hacer... y hasta que se implemente una mejor solucion esta podria estar bien... el buscador gana muchisimo con multithread pudiendo buscar en todos los canales en pocos segundos

**Comment by SeiTaN** [comment]
Mi idea es de momento parchearlo para que funcione la gestión de cookies que hay algunos sitios que no va bien.
Y luego cambiarlo por la solución eficaz

P.D: me han salido 3 mensajes en un momento :dancers:

**Comment by divadres** [comment]
Detectar el canal es sencillo con el modulo inspect asi lo hacemos para otras cosas...


Si la solucion de parchear las "www." Soluciona el problema... tambien lo podemos dejar asi hasta que se busque algo mejor

**Comment by tvalacarta** [comment]
Vale vale ja ja ja

Voy a ver si reuno el valor suficiente para hacer el merge contra master, pero si el que lo tenga más claro hace ese parche y lo sube lo incorporamos rápidamente.

**Comment by divadres** [comment]
Yo no se donde estan los problema exactamente (que canales) pero si parcheando el "www." Es suficiente yo demomento teriaria por ahi...

**Comment by tvalacarta** [comment]
Yo no lo tengo tan claro, pero para evitar otra avalancha me conformaré :)

Por mi parte volvería al cookies.dat, y como mucho pondría el bloqueo a la hora de leer y escribir el fichero de cookies para evitar joderlo.

No hablamos de transacciones bancarias donde si algo falla se pierde dinero, son unas simples cookies ja ja ja.

**Comment by SeiTaN** [comment]
Con httptools ya no se da este problema, si vamos migrando en los canales ya no se dará el caso, se puede chapar :)
