### ISSUE TITLE
Importar "canales" desde core en el launcher

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#288]
Aquí vuelvo de nuevo con otra duda :joy: 

Esta tiene que ver con el launcher de la rama develop, el cual uno de sus cambios es que solo importa canales que estén en la carpeta channels, a diferencia del presente en master que también tiene la opción de importarlos desde la carpeta core. Lo comento porque he reparado el archivo trailertools para realizar la búsqueda de trailers desde el menú contextual y al encontrarse en core falla.

La única solución es pasar ese archivo a la carpeta channels (no lo veo del todo correcto, ya que no es un canal) o se va a seguir contemplando la posibilidad de cargarlo desde core como antes? :confused:

**Comment by SeiTaN** [comment]
Buena pregunta, a mi me pasa igual con mi desarrollo de `filtertools`(no es un canal, es una utilidad), se que Jesús lo puso asi y metió descargas y favoritos dentro de canales por que se usan como tales al mostrar un listado y tal (aunque yo pensaba que channels son las webs), pero para otros ficheros estoy con @CmosGit, no me parece que sea su sitio.

**Comment by tvalacarta** [comment]
El tema de los filtros no lo tengo claro, pero con los trailers yo sí que veo que tiene que ser un canal... tiene que funcionar en otras plataformas, así que necesita acciones, items, play, etc.

Es cierto que hay cosas de descargas y favoritos que deberían estar en el core, pero creo que tampoco es tan importante y así no tenemos dos ficheros para lo mismo.

En tvalacarta por ejemplo hay canales como el nuevo "canal13co.py" que en un momento dado llaman a otro canal "youtube_channel.py" que en realidad no es un canal normal, sino una especie de canal compartido para acceder a cosas de YouTube. Ambos están en "channels", es algo muy útil y creo que se parece mucho a lo que indicas. En un rato subiré al GIT el código de la última versión, que aún no he tenido los ojos suficientemente abiertos para hacerlo.

Dime dónde puedo echar un vistazo a ese cambio concreto que dices en los filtros, y te digo cómo lo veo.

**Comment by SeiTaN** [comment]
@tvalacarta aquí tienes :wink: https://github.com/tvalacarta/pelisalacarta/pull/255

**Comment by tvalacarta** [comment]
Claramente está en el límite de lo que podríamos considerar un canal :)

¿Para qué necesitas que lo cargue el launcher como si fuera un canal?

Igual es mejor ponerlo en "core", y hacer un caso especial en el launcher...

**Comment by SeiTaN** [comment]
No necesito cargarlo como un canal, es más bien una utilidad.

No, no lo necesito cargar como un canal, de hecho actualmente está en core, yo preferiría que estuviera en platformtools, ya que de momento sólo está hecho para kodi.

La duda que tengo... ¿todo tiene que pasar por narices por launcher? Sino fuera asi no tendríamos este problema.

**Comment by tvalacarta** [comment]
Claro que no...

Me gustar entender un canal es una serie de acciones, que cada una de ellas recibe un item como parámetro y devuelve una lista de items como resultado. De esa forma el canal es relativamente genérico, y podemos implementarlo como un servicio en cualquier plataforma mediante un "launcher".

Pero nada de esto está escrito en fuego :)

Nada te impide importar desde un canal un módulo de lo que sea, un thread o lo que se te ocurra. Y si es algo específico de XBMC, basta con que pongas un "if config.is_xbmc()" delante.

**Comment by SeiTaN** [comment]
No me he explicado bien, sé que los canales por lógica deben usar el launcher, me refiero a cosas como `trailertools`, o `filtertools`.

En mi caso lo unico que hace parecido a un canal, es mostrar un listado de los filtros guardados y si pulsas en él te llama a un método que no pasa por launcher como la mayoría de mis métodos, de ahí mi pregunta. La otra parte que usa launcher es para evitar menús interminables en la navegación al ir hacia atrás, usando menús contextuales en kodi, pero estos según he visto necesitan usar una función que es RunScript, que lo que hace es ejecutar el plugin de cero con el item que le pasemos.

Por lo que veo en mi caso, que mi fichero es una especie de hibrido, es medio canal por la arquitectura usada, y es una utilidad por la funcionalidad para lo que está hecho.

Resumiendo, es saber si se mete en channels (aunque no sea un canal), se deja en core y en launcher se vuelve a habilitar la opción de imports de esa carpeta (como se hacía antes), o se busca una tercera vía.

Si tienes alguna duda, me comentas e intento explicarlo mejor :wink:

**Comment by CmosGit** [comment]
> El tema de los filtros no lo tengo claro, pero con los trailers yo sí que veo que tiene que ser un canal... tiene que funcionar en otras plataformas, así que necesita acciones, items, play, etc.

@tvalacarta  Viéndolo así entiendo que sí encaja para incluirlo en channels, lo que pasa es que hasta ahora el único uso de trailertools era a través del menú contextual y así lo enfoqué al comienzo, es decir, para utilizarlo en kodi/xbmc, y de esa manera no me queda claro que entrase en esa categoría. 

Al comentar tú que debería funcionar en otras plataformas me he encargado ya de adaptarlo, distinguiendo si se ejecuta desde el menú contextual de Kodi, de forma que en lugar de listitems se mostraría en diálogos. Ya que estoy pongo un ejemplo de cómo se vería, la primera desde el menú contextual y la segunda si se entra desde "Buscar Tráiler".

![Image 1] (http://i.imgur.com/PIVVhxn.gif)
![Image 2] (http://i.imgur.com/Ij0Euul.png)

**Comment by tvalacarta** [comment]
Pues si tú lo ves bien, dejamos filtertools en channels.

Lo de abrir como canales cosas que están en "core" me parece más confuso, aunque haya sido así siempre.

**Comment by SeiTaN** [comment]
Donde manda patrón no manda marinero, a moverlo a channels entonces.

Creo que solo hay que cambiar las referencias en seriesblanco y seriesdanko.
