### ISSUE TITLE
Problema con openload

### ISSUE THREAD

**Issue by linuxdakota** [tvalacarta/pelisalacarta#294]
cada ves que quiero abrir una serie en el servidor openload me sale un recuadro con la leyenda,
"Se a producido un error en el conector openload"
ojala y puedan arreglar a ese problema..

**Comment by CmosGit** [comment]
En el foro tienes el enlace al archivo corregido: [http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7635#p31978](url)

**Comment by tvalacarta** [comment]
Es el que está subido en este PR, ¿no?

https://github.com/tvalacarta/pelisalacarta/pull/298

¿Cerramos?

**Comment by SeiTaN** [comment]
@tvalacarta por favor cierra este issue, que ya está solucionado.
