### ISSUE TITLE
Ventana de diálogo multiplataforma

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#295]
Pues a raíz de los cambios en realdebrid que obligan a usar su api, estoy intentando portar el [conector](https://raw.githubusercontent.com/CmosGit/pelisalacarta/realdebrid/python/main-classic/servers/realdebrid.py) que he arreglado de forma temporal para Kodi, al resto de plataformas.

El conector como se ve utiliza un DialogProgress ya que es necesario mostrar en pantalla una url y un código que el usuario tiene que introducir, no vale con usar la cuenta y el password como antes. Por lo que he visto en el platformtools de la rama develop, es un tipo de diálogo que existe para todas (excepto para la versión por línea de comandos), pero he probado en Plex y no muestra nada, ni siquiera da error. Es normal o es que falta algo por implementar? En mediaserver no he podido probarlo así que no sé si funciona o no.

Aparte de eso me queda la duda de si almacenar las credenciales necesarias para usar la api en un archivo dentro del userdata como tengo hecho hasta ahora, o modificar los settings de cada plataforma para guardarlos ahí, aunque esto último lo veo un poco innecesario ya que el usuario no tiene que introducir nada en la configuración, es todo automático...

**Comment by divadres** [comment]
Los dialogos de platformtools estan solo para que no de error, no estan implementados...yo pase un tiempo modificando la version plex para impleme tarlos pero por falta de tiempo lo deje aparcado...

**Comment by CmosGit** [comment]
Gracias @divadres, pues entonces supongo que se quedará limitado a Kodi/XBMC :disappointed:

**Comment by divadres** [comment]
En mediaserver si que esta implementado

**Comment by CmosGit** [comment]
Ah, perfecto, pues haré la distinción entonces en el servertools para que solo use el conector en ellas :+1:
