### ISSUE TITLE
Error al instalar plugin

### ISSUE THREAD

**Issue by FROSADO** [tvalacarta/pelisalacarta#299]
Me he atrevido a bajarme la rama develop y crear el paquete para mi kodi 15.2
A no ser que haya hecho algo mal (solo he hecho un ant en la caroeta python)  al ejecutar el plugin sale este error. 

    01:29:31 T:1758307248  NOTICE: -->Python Interpreter Initialized<--
    01:29:32 T:1758307248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name libsmb
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.pelisalacarta/default.py", line 39, in <module>
                                                from platformcode import launcher
                                              File "/home/pi/.kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 39, in <module>
                                                from platformcode import library
                                              File "/home/pi/.kodi/addons/plugin.video.pelisalacarta/platformcode/library.py", line 50, in <module>
                                                from samba import libsmb as samba
                                            ImportError: cannot import name libsmb
                                            -->End of Python script error report<--
    01:29:32 T:1946047040   ERROR: GetDirectory - Error getting plugin://plugin.video.pelisalacarta/
    01:29:32 T:1946047040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pelisalacarta/) failed

Es un error a la hora de empaquetar que me falta algo instalado o es que el plugin tiene una dependencia mal? 

Si  uelvo a Instalar 4.0.9 todo ok

**Comment by kampanita** [comment]
Pues tiene toda la pinta de que le falta encontrar la libreria libsamba, o
no la tienes en la ruta correcta.

Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

**Comment by SeiTaN** [comment]
@FROSADO mira que tienes todo el contenido de la carpeta `lib`, es como dice @kampanita , se queja que no encuentra la librería.

Saludos.

**Comment by FROSADO** [comment]
Hola, mi pregunta es más orientada a el proceso de build. Bajarse la rama y directamente hacer ant provoca este error, ¿no tendría que ser capaz de construirse bien solo?  ¿Donde encuentro esa lib?

**Comment by SeiTaN** [comment]
No es necesario hacer ningún build, simplemente copia el contenido de la carpeta "main-classic" y luego lo zipeas, con ese zip ya puedes instalarlo en kodi.

**Comment by FROSADO** [comment]
Ok, hare la prueba, aun así me gustaría ayudar con esto. 
Este es el contenido de lib, parece que hay un `libsmb` en lugar de `libsamba`
    pi@raspberrypi:~/peliasalacarta/target/python/kodi-15-isengard/plugin.video.pelisalacarta/lib/samba $ ls - l
    total 28
    -rw-r--r-- 1 pi pi  226 jun 29 01:08 __init__.py
    -rw-r--r-- 1 pi pi 8970 jun 29 01:08 libsmb.py
    drwxr-xr-x 2 pi pi 4096 jun 29 01:08 nmb
    drwxr-xr-x 5 pi pi 4096 jun 29 01:08 pyasn1
    drwxr-xr-x 3 pi pi 4096 jun 29 01:08 smb

**Comment by FROSADO** [comment]
Secuencia de build:
    
    git clone https://github.com/tvalacarta/pelisalacarta.git
    cd pelisalacarta 
    git checkout develop
    cd python
    ant

He intentado seguir si se renombra la librería en algún punto del ant, pero no lo parece

**Comment by kampanita** [comment]
Que no hace falta "compilar" ni empaquetar nada. No te hace falta ant para
nada.

Como te dice @SeiTan solamente necesitas bajarte el zip y comprimir a
partir de la rama "main-classic".   Lo unico que hay que tener cuidado con
el nombre del zip, que depende del contenido ....si no a Kodi no le gusta.
en tu caso  -> plugin.video.pelisalacarta-develop.zip

si no tiene ese nombre, no le va a gustar a Kodi y te dira que la
estructura del zip no es correcta.

PD: y yo desinstalaria antes la version anterior del plugin


Otra manera de hacerlo es manualmente :)   Descomprime el zip de la version
develop, y pasa los contenidos de main-classic a
addons/plugin.video.pelisalacarta/



Agurrak, Kepa
______________________________________________________

iNKuBo - *Punk Rock de la Margen Izkierda del puto Nervión*

http://www.inkubopunk.org
______________________________________________________

*Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no.*

**Comment by tvalacarta** [comment]
La secuencia de build es correcta.

Únicamente, como dicen @SeiTaN y @kampanita, aclarar que simplemente para desarrollar no hace falta que hagas nada de todo esto. El build.xml sirve para empaquetar las diferentes versiones, no para "compilar" ya que aquí es todo interpretado.

Si quieres tener una versión "develop" del plugin basta con que hagas el checkout de la rama "develop" tal como has dicho:

```
git clone https://github.com/tvalacarta/pelisalacarta.git
cd pelisalacarta 
git checkout develop
```

Y luego crear un link simbólico en el directorio addons:

```
cd /xxx/Kodi/addons
ln -s /xxx/pelisalacarta plugin.video.pelisalacarta
```

o directamente haz el checkout en el directorio add-ons:

```
cd /xxx/Kodi/addons
git clone https://github.com/tvalacarta/pelisalacarta.git plugin.video.pelisalacarta
cd plugin.video.pelisalacarta 
git checkout develop
```

**Comment by jimyx17** [comment]
> Este es el contenido de lib, parece que hay un libsmb en lugar de libsamba
~/peliasalacarta/target/python/kodi-15-isengard/plugin.video.pelisalacarta/lib/samba $ ls - l
>
>total 28
-rw-r--r-- 1 pi pi  226 jun 29 01:08 __init__.py
-rw-r--r-- 1 pi pi 8970 jun 29 01:08 libsmb.py
drwxr-xr-x 2 pi pi 4096 jun 29 01:08 nmb
drwxr-xr-x 5 pi pi 4096 jun 29 01:08 pyasn1
drwxr-xr-x 3 pi pi 4096 jun 29 01:08 smb

Por favor, fijate donde estas haciendo el ls. Es en dento de la libreria samba donde estas viendo solo libsmb eny no samba. 

El problema no esta solucionado y a mi también me da error desde que actualice a la ultima version. 

El problema de verdad viene porque en el sistema ya hay una libreria que se llama samba pero que no tiene la libreria "libsmb" dentro:

```
# pacman -Qo /usr/lib/python2.7/site-packages/samba/
 /usr/lib/python2.7/site-packages/samba/ is owned by samba 4.4.4-1
# ls /usr/lib/python2.7/site-packages/samba/
auth.so         dcerpc         dsdb.so        idmap.py     messaging.so              netcmd     posix_eadb.so  samdb.py     smb.so       third_party        xattr.py
common.py       dckeytab.so    gensec.so      __init__.py  ms_display_specifiers.py  net.so     provision      schema.py    subnets.py   upgradehelpers.py  xattr_tdb.so
com.so          descriptor.py  getopt.py      join.py      ms_schema.py              ntacls.py  registry.so    sd_utils.py  subunit      upgrade.py
credentials.so  drs_utils.py   _glue.so       kcc          ndr.py                    param.so   remove_dc.py   security.so  tdb_util.py  web_server
dbchecker.py    dsdb_dns.so    hostconfig.py  _ldb.so      netbios.so                policy.so  samba3         sites.py     tests        xattr_native.s
```

Por favor, o usa un nombre diferente para tu libreria samba o utiliza la del sistema y la pones como dependencia.

Un saludo

**Comment by FROSADO** [comment]
Quiero aclarar que el bug escdel sistema de generación del zip, la última actualización me falla por el mismo error que yo reporté. Es una lástima que haya que hacer estas operaciones a mano para poner el plugin otra vez en marcha

**Comment by tvalacarta** [comment]
El error que reportas no estaba en el ant, entre otras cosas porque el log que pones es de Kodi y no de Ant :)

El fallo consistía en que dentro del directorio "lib" había un directorio "samba", y al intentar usarlo en Linux había un conflicto con una librería de python estándar que se llama igual.

No era un error nada trivial, fíjate en el historial del issue, y desde luego no tiene nada que ver con el ant.

Aunque en vez de cerrar el issue podríamos haber investigado un poco más, eso sí.

**Comment by tvalacarta** [comment]
Que por cierto, creo que nadie ha agradecido a @jimyx17 su buena puntería :)

Esa era para nota je je je

**Comment by jimyx17** [comment]
No hombre, no, el que tiene que dar gracias soy yo por el pedazo de curro que haceis con este plugin. Enhorabuena y seguid así!
