### ISSUE TITLE
Please, add Stream to get_video_url

### ISSUE THREAD

**Issue by ergoithz** [tvalacarta/pelisalacarta#3]
xbmctorrent's is poorly maintained and bugged, and pulsar does not work on android, so Stream is the only option I've found.

Stream is a fork of xbmctorrent with several improvements (better perfomance and ui) and an active community (its main project is a bit stalled but still alive).
torrent2http.py module (used in both xbmctorrent and Stream) does not support android Kodi yet but I've send a pull request with a fix (https://github.com/brysonreece/Stream/pull/47)

So here is the patch:

```python

--- torrent.py.orig	2015-01-02 23:00:41.398939127 +0100
+++ torrent.py	2015-01-02 21:52:40.000000000 +0100
@@ -20,10 +20,12 @@
 
     media_url_xbmctorrent = "plugin://plugin.video.xbmctorrent/play/%s" % urllib.quote_plus(link)
     media_url_pulsar = "plugin://plugin.video.pulsar/play?uri=%s" % urllib.quote_plus(link)
+    media_url_stream = "plugin://plugin.video.stream/play/%s" % urllib.quote_plus(link)
 
     video_urls = [
          [ "[xbmctorrent] %s" % (name), media_url_xbmctorrent ],
-         [ "[pulsar] %s" % (name), media_url_pulsar ]
+         [ "[pulsar] %s" % (name), media_url_pulsar ],
+         [ "[stream] %s" % (name), media_url_stream ],
      ]
 
     return video_urls
```

Note: contributions would be easier with a *real* github proyect, and you could still use whatever restrictive license you like.

**Comment by tvalacarta** [comment]
Thanks for this!

I don't have a restrictive license, it is GPL :)

What i don't have is the source control in Github, i still have to migrate the code from Google Code SVN:

https://code.google.com/p/xbmc-tvalacarta/

I'll do this migration as soon as i can, in the meanwhile i have included your patch in the new version of pelisalacarta and will be available on SVN.

**Comment by ergoithz** [comment]
Thanks

**Comment by tvalacarta** [comment]
Github move completed :)

**Comment by kampanita** [comment]
Hi, where can i find this Stream fork ?
I was unable to watch magnet% files with this patch because always get resolved last of video_urls, in my case was "plugin.video.stream" but i couldn't find it, so pelisalacarta gave me error at script.

I solved that part putting pulsar as last option, so pulsar is choosen when a magnet url is selected.

[code]
    video_urls = [
         [ "[kmediatorrent] %s" % (name), media_url_kmediatorrent ],
         [ "[xbmctorrent] %s" % (name), media_url_xbmctorrent ],
#         [ "[stream] %s" % (name), media_url_stream ],
         [ "[pulsar] %s" % (name), media_url_pulsar ]
     ]
[/code]

Is there any way of letting the user choose what video_url to use ?

**Comment by tvalacarta** [comment]
I this it is this:

https://github.com/brysonreece/Stream

We are going to give an improvement to the torrent integration in future releases, there have been interesting advances in forum.

**Comment by kampanita** [comment]
Thank you very much. 
I'm really very interested in this project, i use your plugin every day. 
I used to mod it accordly to my necesities, also tried to fix some things that happened at my rpi2 setup with openelec... It's first time i use python, but i usually program with other languages so i think i could learn and help in a little time.

I was following the forum posts at your blog and discovered yesterday that you were migrating to git... yeah!! ;) 

Thank you very much for your work, will try to help in all that i can.
