### ISSUE TITLE
Eliminar `isGeneric`

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#301]
Lo pongo por aquí para que no se pierda.
Referente a este comentario https://github.com/tvalacarta/pelisalacarta/commit/83b6a906385280e7c20d8f2f10118f81d61bc5e2#commitcomment-17926519

Con el cambio introducido en `launcher.py` ya no es necesario la función `isGeneric` y se puede eliminar de todos los canales.

**Comment by tvalacarta** [comment]
Eso es :)

**Comment by superberny70** [comment]
Si realmente quieres q no se pierda, mejor en el foro.
Aqui cuando se cierra se pierde por los fondos de github.

**Comment by tvalacarta** [comment]
Cerramos ¿no?
