### ISSUE TITLE
error import libsmb en linux

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#306]
He probado de instalar la rama develop en un linux (kodiubuntu) y me da error de script en la linea 50 de library.py, en concreto falla la importacion de libsmb, sin embargo en windows no hay problema.

**Comment by SeiTaN** [comment]
Cuando haga las modificaciones de la biblioteca para que sea menos **kodi-centric** y con cambios que me ha pasado @divadres, le echamos un ojo si te parece con la ayuda de los "samberos" :wink:

**Comment by superberny70** [comment]
Creo q el problema no es samba, sino el modo de importarlo en linux, ya que como digo en windows no falla.
Algun linuxero podris probarlo?

**Comment by javiernoval** [comment]
El problema es si tienes instalado algún paquete (como `python-samba` en mi caso) que provee un módulo llamado `samba`, ya que en un par de sitios se hace:

`from samba import libsmb as samba`

y el paquete `samba` del sistema toma preferencia, por lo que no se importa lo que realmente se quiere (`lib/samba/libsmb.py`). La solución es simple, basta cambiarlo por:

`from lib.samba import libsmb as samba`

**Comment by SeiTaN** [comment]
Entonces todo viene del dichoso nombre, si se cambiaran no habría problemas.

Gracias por confirmarlo @javiernoval :+1:
