### ISSUE TITLE
Actualización de la biblioteca para ser independiente de la plataforma

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#309]
Buenas,

Voy a empezar a subir a mi rama lo que voy modificando de la biblioteca para acometer las posibles sugerencias/mejoras que se han puesto por el foro, de manera que sean visibles aquí y posteriormente realizar un PR, gracias a @superberny70 por la sugerencia :wink: 

De momento se ha cambiado la manera de actualizar las series eliminando el fichero que se utilizaba como sistema centralizado, sugerencia que han realizado varias personas por diferentes motivos.

A partir del fichero `series.xml` se realiza la conversión y ahora las carpetas de series son independientes.

Un ejemplo del contenido de una carpeta:
![image](https://cloud.githubusercontent.com/assets/11775029/16571014/757ba614-4252-11e6-911c-48e65d812dd7.png)
Los `strm` (pronto contendrán la información de infolabels básica), `tvshow.nfo` que es para plataformas Kodi (te permita scrapear una serie para la biblioteca propia de Kodi) y `tvshow.json`(nuevo) que contendrá (en próximas actualizaciones) la información de la serie junto a sus infolabels.

Datos definidos de momento en `tvshow.json`
```json
{
    "active": true, 
    "channel": {
        "name": "seriesblanco", 
        "path": "C:\\Users\\SeiTaN\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pelisalacarta\\library\\SERIES\\the flash [seriesblanco]", 
        "tvshow": "The Flash", 
        "url": "http://seriesblanco.com/serie/1697/the-flash.html"
    }, 
    "scraper": {
        "id": "60735", 
        "name": "tmdb"
    }, 
    "title": "The Flash"
}
```

- **active**, si es True permite actualizar la serie.
- **channel**, contiene la información relativa al canal donde se ha obtenido la información.
- **scraper**, información relativa al scraper utilizado para obtener la información de la serie, con vistas a poder utilizar distintos en un futuro próximo.
- **title**, nombre scrapeado de la serie.

_**Pendiente**, definir la estructura de infolabels para los datos de la serie, temporada y episodios._

Los ficheros modificados están subidos a mi [repositorio] (https://github.com/SeiTaN/pelisalacarta/commits/biblioteca), cambios desde el día **5 de Julio**

**Comment by superberny70** [comment]
Volvemos a darle vueltas a lo mismo. Todo esto esta muy bien, pero ¿guardaras los enlaces a los videos como queria Jesus? ¿permitiras guardar la misma serie de dos canales?

Para hacerlo menos Kodi dependiente no es necesario crear el tvshow.json con el mismo contenido (basicamente) q pueda tener tvshow.nfo. Yo creo q no es necesario guardar ninguna informacion, creo q es mejor leerla de tmdb cuando sea necesario.

**Comment by divadres** [comment]
Y tener que leer cada vez toda la informacion de todas las series/peliculas cada vez que entres en la biblioteca? Me parece mejor tenerla guardada no tener q bajarla cada vez con el consiguiente uso de datos y tiempo de espera... (al fin y al cabo es lo mismo que hace kodi almacenar la informacion en una base de datos)

**Comment by superberny70** [comment]
En algun momento tendras q actualizarlo, kodi tb lo hace. Imaginate q cuando añades una peli o capitulo no esta aun la imagen o la sinopsis disponible. Si tienes una base de datos (o mini bbdd) tendras q irla actualizando en estos casos.
De todos modos, te decia q si hay q guardar los datos, en lugar de duplicarlos, mejor hacerlo con la misma estructura q los nfo, en lugar de json.

**Comment by divadres** [comment]
Si... se pueden guardar con la estructura del .nfo... el formato es indiferente, pero, actualmente en el nfo solo hay una url... y si queremos adaptar la biblioteca a otras plataformas ahi los .nfo ya no son necesarios... y para ese caso los mas facil es directamente guardar los infoLabels en un .json pero repito lo dicho el formato es indiferente y se deveria usar el mismo para todas las plataformas para asi poder compartir la biblioteca en diversas plataformas y que funcione bien en todas

La biblioteca se actualiza al iniciar yo creo que es ahi donde deveria actualizar los datos o incluso añadir una opcion para actualizarlos manualmente si se quiere pero no cada vez que se muestre el listado... ya que solo con que en un momento dado el servidor no este disponible o la api haya cambiado perderemos toda la info hasta que se arregle, mientras que si lo tenemos guardado podemos seguir tirando con los datos que tenemos

**Comment by SeiTaN** [comment]
> Volvemos a darle vueltas a lo mismo. Todo esto esta muy bien, pero ¿guardaras los enlaces a los videos como queria Jesus? 

De momento lo dejo aparcado porque es lo más tedioso y no creo que sea lo más importante ahora mismo que te salga 2 opciones con 40 enlaces cada 1, que te muestra una opción con 80.

> ¿permitiras guardar la misma serie de dos canales?

Sí, se permitirá. @divadres me dijo cual era su idea y la veo bien, se recorren todos los tvshow.json y se compara los valores del scraper, una vez hecho esto ya se puede montar una estructura en memoria que es la que se muestra en la biblioteca (pendiente de hacer).

¿Por qué se prescinde de un fichero centralizado?
-  se soluciona el problema de las series huerfanas.
- permite que las carpetas de las series sean independientes, esto permite hacer backup simple de copiar y pegar que quería @tvalacarta.

> La biblioteca se actualiza al iniciar yo creo que es ahi donde deveria actualizar los datos o incluso añadir una opcion para actualizarlos manualmente si se quiere pero no cada vez que se muestre el listado... ya que solo con que en un momento dado el servidor no este disponible o la api haya cambiado perderemos toda la info hasta que se arregle, mientras que si lo tenemos guardado podemos seguir tirando con los datos que tenemos.

Yo entiendo que es una opción, si quieres actualizar toda la información de la serie o sólo los episodios descargados.
Estoy de acuerdo que se tiene que guardar, parte en el strm y otra dentro del .json.

Aunque no varía mucho de lo que se dijo en el foro en un principio, estaría bien que @tvalacarta se pronunciara para ver que le parece y saber si se puede avanzar con la siguiente parte.

**Comment by tvalacarta** [comment]
Creo que ya comenté en el foro que por mí no os bloquearais, que me parecía bien lo que se avanzara sin necesidad de mi visto bueno. No obstante intento estar pendiente, si algo se me pasa podéis darme un toque por email, MP o lo que sea. Este verano creo que mis vacaciones van a ser testimoniales :(

Sobre que @superberny70 prefiera los XML a los JSON... supongo que todo el mundo acaba pasándose al lado oscuro como un Anakin Skywalker cualquiera ja ja ja

Es cierto que los XML de Kodi son muy completos y bien pensados, a la larga podemos reusarlos para otras plataformas y no duplicar. 

Pensando un poco en la estructura veo que por una parte tenemos que buscar algo ligero, pero por otra parte minimizar las lecturas de ficheros ya que los dispositivos son lentos y el almacenamiento flash much más.

Digamos que al entrar a la biblioteca y elegir "Juego de tronos" deberíamos acceder únicamente a un fichero (o unos pocos) donde estén los episodios y lo que hayamos añadido desde thetvdb o donde sea. 

En este sentido un XML por cada episodio como hace Kodi es imposible, será lento de cojones.

Mi opinión es que un buen equilibrio podría ser algo así:

```
library
\SERIES
  \master.json
  \Juego de tronos
      \tvshow.nfo
      \sources.nfo
  \Los 100
      \tvshow.nfo
      \sources.nfo
```
Ese tvshow.nfo tendría la info de la serie, y sources.nfo todo lo demás (canales, episodios de cada canal, metadatos de episodio, etc.).

Cuando el usuario elija "biblioteca" se carga la lista de series de "master.json" donde estará la información básica para hacer el listado (titulo, fanart, thumbnail, argumento y poco más). Un único acceso al disco. Cuando elija una serie se va al directorio, se lee "sources.nfo" para sacar los canales y sus episodios. El extendedInfo se saca de "tvshow.nfo".

Para que fuera posible configurar esto como una biblioteca Kodi directamente, añadimos los nfo de episodio y los STRM.

```
library
\SERIES
  \master.json
  \Juego de tronos
      \tvshow.nfo
      \sources.nfo
      \1x01.strm
      \1x01.nfo
      \1x01.tbn
      \1x02.strm
      \1x02.nfo
      \1x02.tbn

  \Los 100
      \tvshow.nfo
      \sources.nfo
      \1x01.strm
      \1x01.nfo
      \1x01.tbn
      \1x02.strm
      \1x02.nfo
      \1x02.tbn
```

Cuando el usuario elija el "1x01" el STRM lo lleva a una función que coge la serie, busca ese episodio en sources.nfo, extrae las fuentes donde esté, hace una llamada a cada canal y muestra lo que sea (lista de canales con episodios en cada uno, todos los episodios juntos, etc.).

Y lo de leer en tiempo real de thetvdb cada vez... creo que es mala idea. Aparte del tiempo de acceso y de que thetvdb falla a menudo, está el hecho de que la información puede no ser válida. Para las series mainstream obviamente sí, pero si alguien tiene niños y trata de mantener una biblioteca con las series infantiles sabrá lo que quiero decir. Suelen estar mal catalogadas, y no es raro que cambien el orden de los episodios.

Es más fiable en muchos casos la info que da el canal que la de thetvdb (aunque el canal a veces también tiene info incorrecta).

Y en cuanto a guardar los enlaces, insisto en que lo hagáis como queráis. Mi opinión era eso, una opinión más, y yo creo que se podrá añadir después si el tiempo acompaña.

**Comment by SeiTaN** [comment]
> Creo que ya comenté en el foro que por mí no os bloquearais, que me parecía bien lo que se avanzara sin necesidad de mi visto bueno. No obstante intento estar pendiente, si algo se me pasa podéis darme un toque por email, MP o lo que sea. Este verano creo que mis vacaciones van a ser testimoniales :(

Se agradece el voto de confianza :+1: aunque siempre viene bien que te vayan validando para así avanzar con develop y alguna vez lanzar otra versión de pelisalacarta que tiene muchas novedades :smiley: Siento lo de las vacas :disappointed: 

Lo que tu llamas `master.json` lo hemos quitado (el fichero centralizado para actualizar las series, series.xml o el que hice yo de series.json), de hecho tú querías poder hacer un zip con la biblioteca y olvidarte de hacer nada más y de esta manera se puede hacer :wink: Te copias la carpeta de la serie que quieras y la llevas a otro kodi/plex o lo que sea.. y se te cargará la información de esa carpeta está en `tvshow.json` (de momento) a través del apartado de _biblioteca_(pendiente de montar).
Esto se ha hecho así por la razón de antes, y tb para el desarrollo de divadr con el tema de favoritos/descargas.

Sobre el tema de la info en xml / json y si usar varios ficheros o no, ya os explico luego mi razonamiento a ver que os parece, que ahora estoy en el curro y necesito acceso a los datos de casa.

**Comment by SeiTaN** [comment]
## Ficheros actuales dentro de una serie (carpeta)

### **tvshow.nfo**
Se crea cuando agregas una serie y sólo contiene la url de la serie para el scraper de tmdb, esto está hecho para la biblioteca de kodi, si tienes el scraper de themoviedb añadido a Kodi, y te obtiene la información, de modo que si no está añadido el scraper y no se actualiza la bilioteca de Kodi (para esto hace falta arreglar el famoso "**library.update()**" que creaba bucles infinitos), no te saldrá la información correspondiente.

### **tvshow.json**
Contiene la información propia de la serie que antes estaba centralizada en el fichero `series.xml/json` y contendría en un futuro los infolabels de la serie.

### Cosas a tener en cuenta si se quieren unificar en **tvshow.nfo**:
- Ver si no hay problemas al añadir la información contenida en tvshow.json, vease tags prohibidos o repetir existentes (esto se refiere a Kodi por su biblioteca si está configurada).
- Estudiar la estructura que hace los scrapers para simularla y generar nosotros mismos el fichero .nfo con todos los infolabels y asi olvidarnos de que tenga que estar añadido el scraper en Kodi, para que en este caso, se agrege la información a su propia biblioteca (si la tenemos configurada).

## strm y sus ficheros asociados

### biblioteca de pelisalacarta
> Cuando el usuario elija el "1x01" el STRM lo lleva a una función que coge la serie, busca ese episodio en sources.nfo, extrae las fuentes donde esté, hace una llamada a cada canal y muestra lo que sea (lista de canales con episodios en cada uno, todos los episodios juntos, etc.).

Esto no hace falta, dentro del strm está todo lo que necesitamos, ya que se guarda toda la información correspondiente cuando se cree, depende de lo que tengamos configurado: 
- sin información extra (datos obtenidos del canal).
- información básica (datos obtenidos del tmdb, fanart, thumbnail y plot).
- información extendida (datos obtenidos de tmdb, básica + otros como director, actores, genero....)

Y cuando se cargue el strm se mostrará la información que haya en su interior, así nos ahorramos el tener varios ficheros (gracias a divadr por la idea).

### biblioteca de kodi
Al tener scrapeada la serie no hace falta hacer nada con los ficheros strm (se ha hecho previamente con el fichero tvshow.nfo y su url dentro), que encuentra la información automaticamente del strm cuando se refresca la biblioteca.

La única razón para tener ficheros .nfo con su strm asociado es que tengan nombres raros o no concuerden con lo que hay en la web del scraper, para las series normales no afecta.


## Mis conclusiones:
Yo de momento y tras una conversación que tuve con @divadres, lo dejaría de momento todo por separado con los siguientes ficheros.

#### tvshow.json 
- **Sólo se usa en la biblioteca de pelisalacarta**, contiene información de la serie necesaria para actualizarse y datos de infolabels.

#### tvshow.nfo
- **Sólo se usa para la biblioteca de Kodi**

#### ficheros strm
- Su contenido sólo se muestra en la biblioteca de pelisalacarta, por lo que no influye lo que guardes para la bibliotca de Kodi.

Ya me comentais que os parece o si teneis alguna duda de lo que he dicho :wink:

**Comment by tvalacarta** [comment]
Yo creo que si tienes 100 series en la biblioteca, y para mostrar el listado tienes que abrir y cerrar 100 ficheros, en muchos dispositivos va a ser lento lento. Nunca subestimes la mala tasa de acceso de algunas memorias flash :(

Deberías reconsiderar el master.json ...

De lo demás interpreto que vas a tener un fichero 1x01.strm por cada episodio de cada serie de cada canal, y además lo vas a usar tanto para Kodis como para no-Kodis ¿no?

Como quieras leer "Anatomía de Grey"  con sus ¿12x24=288 episodios?, ficherito por ficherito, en una tarjeta SD como las de la Raspberry, verás lo que quiero decir.

**Comment by divadres** [comment]
Si tienes 100 series en la biblioteca... que mucho me parece... tendras que leer 100 tvshow.json uno por serie al fin y al cavo es lo mismo que hacemos con los canales leer 100 y pico xml para cargar el listado de canales y al principio pensamos que pudiera afectar al rendimiento pero despues se vio que iba bien.. todo sera cuestion de hacer unas pruebas...

Guardar la info en un archivo crntralizado tiene el problema que hay que mantenerlo actualizado...

**Comment by SeiTaN** [comment]
>  Yo creo que si tienes 100 series en la biblioteca, y para mostrar el listado tienes que abrir y cerrar 100 ficheros, en muchos dispositivos va a ser lento lento. Nunca subestimes la mala tasa de acceso de algunas memorias flash :(
> 
> Deberías reconsiderar el master.json ...

De momento lo veo igual que @divadres

@Jesus en el foro:
> A mí lo que me gustaría es un directorio "Library" que yo pueda meter en un ZIP, y luego en una instalación limpia de pelisalacarta descomprimirlo y que mi biblioteca siguiera ahí :)

No lo entiendo, hace un mes no te gustaba la idea de que estuviera centralizado :confused:

> De lo demás interpreto que vas a tener un fichero 1x01.strm por cada episodio de cada serie de cada canal, y además lo vas a usar tanto para Kodis como para no-Kodis ¿no?
> 
> Como quieras leer "Anatomía de Grey" con sus ¿12x24=288 episodios?, ficherito por ficherito, en una tarjeta SD como las de la Raspberry, verás lo que quiero decir.

Me he perdido, además no pasaría eso, la serie se subdivide en temporadas, por lo que no muestras del tirón los 2xx episodios.
```
BIBLIOTECA
 -- PELICULAS
 -- SERIES
    -- ANATOMIA DE GREY
       -- TEMPORADA 1
          -- 1. Piloto
          -- 2. Meredith
          -- 3. Derek
          -- ...
       -- TEMPORADA 2
       -- TEMPORADA 3
       -- TEMPORADA 4
       ....
```
![image](https://cloud.githubusercontent.com/assets/11775029/16662913/25ae2484-447a-11e6-8bcd-acd4d38c284c.png)

**Comment by tvalacarta** [comment]
Una cosa es que sea "portable", y otra que sea "centralizado". Con la estructura que yo he puesto puedo copiar el directorio "SERIES", pasárselo a un amigo y seguirá funcionando :)

Lo que es un infierno es mover una biblioteca de Kodi... es lo que creo que deberíamos evitar.

Pero vamos, que lo habéis pensado más que yo (ya he dicho que era una pensada rápida), si lo tenéis claro adelante.

**Comment by SeiTaN** [comment]
> Una cosa es que sea "portable", y otra que sea "centralizado". Con la estructura que yo he puesto puedo copiar el directorio "SERIES", pasárselo a un amigo y seguirá funcionando :)

aaaaaamigo, que está dentro del directorio SERIES y no fuera como está el antiguo, me voy a ir a trabajar a la ONCE :sunglasses: :laughing: :laughing: :laughing:

La idea era sin fichero ya que @divadres muestra con su desarrollo de descargas, los ficheros descargas tb en la biblioteca :cry:

**Comment by divadres** [comment]
No hay problema con las descargas porque sea centralizado... lo que no sirve es el antiguo series.xml/json que se utiliza para actualizar la biblioteca... pero da igual crear un tvshow.json para cada serie o añadir una entrada a un archivo existente... solo que el archivo devera incluir todo series y peliculas...

**Comment by SeiTaN** [comment]
Pues si os parece, probamos como queda sin centralizar y si lastra mucho el rendimiento miramos de hacerlo con fichero.

### Actualización:
- `filetools` creado y centralizadas todas las referencias sobre otros ficheros para evitar duplicidades.
- `biblioteca` actualizado con soporte para mostrar las descargas, por ahora se muestra el nombre del strm (pendiente de mostrar infolabels).
- cambiada la estructura del fichero `tvshow.json` para ser más natural al crear un elemento mediante `Item.fromjson()`.
```json
{
    "active": true, 
    "channel": "seriesblanco", 
    "path": "C:\\Users\\SeiTaN\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pelisalacarta\\library\\SERIES\\anatomia de grey [seriesblanco]", 
    "scraper": {
        "id": "1416", 
        "name": "tmdb"
    }, 
    "show": "Anatomia de Grey", 
    "title": "Anatomía de Grey", 
    "url": "http://seriesblanco.com/serie/31/anatomia-de-grey.html"
}
```
Recordar que aunque parezca redundante, `show` es el nombre de la serie en el canal y `title` es el nombre de la serie scrapeada
- `launcher` eliminadas referencias para marcar capitulos como visto, ya que se gestiona desde la propia biblioteca.

#### La mayoría del código es del crack @divadres :clap: :clap:

P.D: @divadres si puedes, echale un ojo al código por si se me ha pasado algo.

**Comment by tvalacarta** [comment]
¿Sabías que este cuadro de diálogo no funciona con teclas, o es que estoy haciendo algo mal?

![captura de pantalla 2016-07-08 a las 14 10 51](https://cloud.githubusercontent.com/assets/5525238/16686949/e9c1efc2-4515-11e6-835b-92555cc1fe4c.png)

**Comment by SeiTaN** [comment]
Luego le hecho un ojo.

**Comment by SeiTaN** [comment]
Bueno ya tengo todo el código actualizado en mi rama de la original develop, al final backup y repositorio al '!@#$ y crearlo de nuevo y luego comparar ficheros uno por uno. 
#### I :heart: WinMerge

@tvalacarta sobre la ventana, ¿puedes moverte sobre la de configuración? La que se usa al filtrar.
![image](https://cloud.githubusercontent.com/assets/11775029/16692104/a2e6f54c-452f-11e6-8f6b-8a3416d64a76.png)

Así comparo código ya que yo no hice esto no se que tocar exactamente :grimacing:

**Comment by tvalacarta** [comment]
Tampoco :(

**Comment by SeiTaN** [comment]
ahora es cuando necesitamos la ayuda de @divadres :wink:

**Comment by SeiTaN** [comment]
Ya he solucionado el problema de la navegación en la ventana de filtro, cuando tenga la de información al agregar la serie, hago el PR con el fix para la versión 4.1.0

**Comment by SeiTaN** [comment]
Bueno, tras sacar tiempo después de la 4.1.x esto va marchando.

De momento me queda pendiente de arreglar en la biblioteca:

- [ ] capitulos no sale el nombre en algunos casos.
- [ ] no se puede ver capitulos desde la biblioteca de Kodi.
- [ ] mostrar el nombre de la serie/pelicula (tmdb) al mostrar el listado de series.
- [ ] pedir nombre de la serie/pelicula si no se encuentra al añadirla.

Y ya luego los añadidos que había pensado, que para esto habrá que mirar menu contextual o un item más en las opciones, como..:
- [ ] permitir reescraper una pelicula / serie.
- [ ] activar/desactivar la busqueda de episodios.
- [ ] des/marcar como visto episodio, temporada, serie o pelicula.

**Comment by SeiTaN** [comment]
Bueno esto ya casi está señores, al añadir una serie o pelicula **también se actualiza la biblioteca de kodi** (el famoso "Actualizar la colección") y no da bucle infinito, tb he hecho un apaño para que solo se actualize el contenido que se añade y no se scanee toda la biblioteca.

Una vez que tenga el ultimo error de reproducir cosas desde la biblioteca procederé a subirlo, me haría falta un tester  para probar en linux y mac.

**Comment by tvalacarta** [comment]
Yo te lo pruebo en Mac si quieres

**Comment by SeiTaN** [comment]
Muchas gracias, si te parece bien, después de publiques la nueva versión que corrige lo del config. Lo subo a la rama develop, y luego voy haciendo PR con las correcciones.
