### ISSUE TITLE
Fallo Updater en mediaserver

### ISSUE THREAD

**Issue by divadres** [tvalacarta/pelisalacarta#312]
@tvalacarta , al restaurar el updater este no funciona en la versión mediaserver, se modifico para hacerlo multiplataforma, cual es el motivo para restaurar el updater antiguo? No funciona correctamente algo del nuevo?

**Comment by tvalacarta** [comment]
Mmm, eso explica una de mis dudas de anoche :)

Lo probé y no funcionaba, vi que por ejemplo faltaba el parámetro "plugin_mode" en "checkforupdates()" que se usa para la versión skin así que imaginé que la había cagado con algún cambio de versión y había puesto la vieja.

Lo reemplacé, hice una prueba completa con XBMC y como funcionaba (tras un par de cambios) lo dejé así.

¿Lo subes de nuevo y lo volvemos a probar?

**Comment by divadres** [comment]
Ok..  luego lo subo... la primcipal diferencia es que el updater.checkforupdates() en vez de mostrar el mensaje o añadir un item al itemlist lo que hace es unicamente devolver false si no hay actualizaciones o el numero de version si si que hay... y cada plataforma tiene que decidir la forma de mostrar el mensaje... en kodi/mediaserver ya esta cambiado pero en la version skin... supongo que se quedaroa sin cambiar...

**Comment by tvalacarta** [comment]
Es buena idea...

Lo del plugin_mode también se usa en el canal "Configuración", ahora tiene opciones separadas y una de ellas es "Comprobar actualizaciones". Ahí también tiene sentido ese comportamiento.
