### ISSUE TITLE
Navegar entre las ventanas con cursores

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#324]
![image](https://cloud.githubusercontent.com/assets/11775029/16708543/f6e751d2-45f7-11e6-92ef-40fc3dbf1ef3.png)

Bueno @tvalacarta estoy arreglandolo, lo digo por si vas a subir la versión corrigiendo bugs si te puedes esperar a que lo termine.

**Comment by tvalacarta** [comment]
Sin problema :)

**Comment by SeiTaN** [comment]
Lo he comiteado a develop por si acaso, ya tu haces el merge a master, ok?

**Comment by tvalacarta** [comment]
Ok, yo estaba trabajando también en develop...
