### ISSUE TITLE
Un par de problemas con 4.1.1 y samba

### ISSUE THREAD

**Issue by r0balo** [tvalacarta/pelisalacarta#330]
No se como tendrá el resto de usuarios su configuración para usar samba pero me da la impresión de que no incluyen en la configuración de las rutas urls samba. En caso de tenerlas les debería dar el mismo error que a mí. Reconozco que soy raro pero en este caso debería ser igual para todos.

El primer error que me salta es al iniciar kodi (éste ye existía en develop antes de la versión 4.1)
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
        Error Type: <type 'exceptions.TypeError'>
        Error Contents: cannot concatenate 'str' and 'tuple' objects
        Traceback (most recent call last):
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\library_service.py", line 35, in <module>
            from platformcode import library
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\platformcode\library.py", line 136, in <module>
            MOVIES_PATH = join_path(LIBRARY_PATH, FOLDER_MOVIES)
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\platformcode\library.py", line 123, in join_path
            path = path + "/" + name
        TypeError: cannot concatenate 'str' and 'tuple' objects
        -->End of Python script error report<--
```
Éste lo soluciono para que pueda seguir con
```
    if not samba.usingsamba(path):
        path = xbmc.translatePath(os.path.join(path, *name))
    else:
        #path = path + "%s" % name
        path =  os.path.join(path, *name)
```
Arreglado me salta, también al inicio de kodi, otro aún mas estraño que no se como cogerlo por ahora (éste no existía en develop antes de la versión 4.1)
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
        Error Type: <type 'exceptions.ImportError'>
        Error Contents: No module named nmb.base
        Traceback (most recent call last):
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\library_service.py", line 35, in <module>
            from platformcode import library
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\platformcode\library.py", line 138, in <module>
            if not path_exists(MOVIES_PATH):
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\platformcode\library.py", line 81, in path_exists
            return samba.folder_exists(folder_samba, path_samba)
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\lib\sambatools\libsmb.py", line 278, in folder_exists
            remote = connect(server_name, user, password)
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\lib\sambatools\libsmb.py", line 73, in connect
            from smb.SMBConnection import SMBConnection
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\lib\sambatools\smb\SMBConnection.py", line 5, in <module>
            from base import SMB, NotConnectedError, SMBTimeout
          File "%AppData%\Kodi\addons\plugin.video.pelisalacarta_4_1_1\lib\sambatools\smb\base.py", line 4, in <module>
            from nmb.base import NMBSession
        ImportError: No module named nmb.base
        -->End of Python script error report<--
```

**Comment by tvalacarta** [comment]
Pufff

¿Qué ruta usas? ¿Algo del tipo "smb://blablabla"?

**Comment by r0balo** [comment]
Exasto :)

**Comment by CmosGit** [comment]
Lo he estado mirando y parece que ha cambiado alguna cosa en library desde que probé el tema de samba, en principio veo dos fallos:
El primero que comentas @r0balo, yo lo solucionaría así, sino la ruta se une con "\" en lugar de con "/" y falla:

`path =  os.path.join(path, "/", *name)`

Y luego el segundo se debe a que en libsmb.py también ha de cambiarse el nombre de la carpeta que ahora es sambatools:

```
try:
    import xbmc
    librerias = xbmc.translatePath(os.path.join(config.get_runtime_path(), 'lib', 'sambatools'))
except ImportError:
    xbmc = None
    librerias = os.path.join(config.get_runtime_path(), 'lib', 'sambatools')
```

Con esos dos arreglos debería funcionar :smile:

**Comment by tvalacarta** [comment]
Bien visto...

¿Por cierto, el "samba.py" que hay en core ya se podría quitar?

**Comment by CmosGit** [comment]
Sí @tvalacarta , ese samba.py ya no se utiliza :wink:

**Comment by SeiTaN** [comment]
> El primero que comentas @r0balo, yo lo solucionaría así, sino la ruta se une con "\" en lugar de con "/" y falla:
> 
> path = os.path.join(path, "/", *name)

para filetools ya lo corrigio @divadres , es algo que no pasará cuando se suba todo lo relacionado con filetools :smiley: 
`if paths[0].lower().startswith("smb://"):
        return paths[0].strip("/") + "/" + "/".join(paths[1:])`

Los otros dos cambios los añado por si acaso, aunque no haría falta cuando merguee con developer.

**Comment by r0balo** [comment]
Ok, prueba superada :)

Ahora otra cosa, si os parece bien nos quedamos aquí para cosas varias sobre el tema.

A modo de recordatorio para que no se quede en tareas pendientes cuando se añada `filetools` ya que no hay referencia a samba y posiblemente se quede en el olvido.

Carpeta descarga no ve un carajo :) sólo opción `Descargas pendientes` y `Descargas con error`
Ahora mismo para que vea lo que tenemos descargado en esa carpeta es necesario
```
    # Añade al listado de XBMC
    try:
        #ficheros = os.listdir(downloadpath)
        if not usingsamba:
            ficheros = os.listdir( downloadpath )
        else:
            ficheros = samba.get_files( downloadpath )
        for fichero in ficheros:
```
Cuando se añada `filetools` hay que acordarse de colocar `ficheros = ft.listdir(downloadpath)`
No he probado las opciones de "pendientes" y de "con error" aún por que tengo la cabeza más en F1 que aquí :) si puedo esta tarde lo miraré

**Comment by SeiTaN** [comment]
@r0balo (te invoco a ti y no al incorrecto eh jajajaja), @divadres tiene un desarrollo completamente nuevo de favoritos y descargas que incluye la parte de samba, cuando lo suba ya vemos esa parte.

**Comment by tvalacarta** [comment]
Vaya, acabo de caer que hay un @r0balo con "o" en vez de con "0" ja ja ja

Ese nuevo desarrollo de @divadres es el de filetools, o hay algo más?

**Comment by SeiTaN** [comment]
Es nuevo, pero depende de filetools

**Comment by SeiTaN** [comment]
@tvalacarta por favor cierra este issue, que ya está solucionado.
