### ISSUE TITLE
4.1.x Problema con ventanas en skin distintos al default

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#333]
> File "/storage/.kodi/addons/plugin.video.pelisalacarta/platformcode/platformtools.py", line 191, in show_video_info
>                                                 return InfoWindow("InfoWindow.xml", config.get_runtime_path()).Start(data, caption=caption, callback=callback)
>                                             RuntimeError: XML File for Window is missing

Hay que buscar una solución para que por defecto coja la ruta de resource del default en vez de la configurada.

**Comment by tvalacarta** [comment]
He visto el error en algún post, pero no lo entiendo realmente...

Si no recuerdo mal, hay un problema en Linux cuando llamas al directorio "default" en vez de "Default"... ¿puede que venga por ahí?

**Comment by SeiTaN** [comment]
el fallo viene que cuando tienes otro skin, la ruta de `config.get_runtime_path()` es relativa al skin que tengas seleccionado, y el fichero xml está dentro del directorio default, por lo que las rutas no coinciden.

De momento se soluciona copiando el xml a la ruta del nuevo skin, pero habría que buscar una solución para que no se necesite hacer eso.

**Comment by tvalacarta** [comment]
Pues el fallo está en config.get_runtime_path() y a su vez en el getAddonInfo('Path') de Kodi ¿no?

Podemos calcularlo como hacemos en el __init__.py, con:

`os.path.abspath( os.path.join( os.path.dirname(__file__) , ".." ) )`

Como "config.py" está en el "core", eso siempre será la ruta del add-on.

**Comment by SeiTaN** [comment]
...plugin.video.pelisalacarta\ **resources\skins\Default\720p**

con skin confluence es esta ruta, habría que concatenar cuando se hace la llamada y obtener la parte variable que es lo que dices tú

**Comment by tvalacarta** [comment]
No sabía que ese "resources/skins/Default/720p" era distinto en cada skin...

**Comment by SeiTaN** [comment]
"resources/skins/**Default**/720p" default es el skin confluence

**Comment by neno1978** [comment]
👍👍👍👍❗️❗️😂

**Comment by divadres** [comment]
indowXML(self, xmlFilename, scriptPath[, defaultSkin, defaultRes])--Create a newWindowXML script.
 
xmlFilename : string - the name of the xml file to look for.
scriptPath : string - path to script. used to fallback to if the xml doesn't exist in the current skin. (eg os.getcwd())
defaultSkin : [opt] string - name of the folder in the skins path to look in for the xml. (default='Default')
defaultRes : [opt] string - default skins resolution. (default='720p')
 
*Note, skin folder structure is eg(resources/skins/Default/720p)
 

Creo q la solucion esta en el parametro defaultSkin aunque  por sefecto ya deveria ser Defalut

**Comment by tvalacarta** [comment]
Hay que joderse :)

**Comment by SeiTaN** [comment]
chapando que esto ya no se da :)
