### ISSUE TITLE
4.1.x fichero config en distintas versiones de xbmc

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#337]
El fichero config que está dentro de frodo no está modificado como el de classic/core/config, habría que revisarlos todos.

```def get_setting(name):
    return __settings__.getSetting( name )```

Este get_setting sólo tiene un argumento (Frodo) y para canales como pordede y demás necesita que sean 2 argumentos.

**Comment by tvalacarta** [comment]
También tuve que arreglarlo en Plex... pero no caí en revisarlos todos.

Deja abierto el issue, a ver si no se me olvida para la próxima versión.
