### ISSUE TITLE
unificar ficheros config en xbmc

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#338]
A raíz de #337 me he dado cuenta que todas las versiones de xbmc tienen un fichero config.py personalizado donde la unifica diferencia es `PLATFORM_NAME`.

Se podría unificar en un sólo fichero y ser Ant el que se encargue de cambiar el nombre.

Así por encima he visto que se puede crear una plantilla y luego crear el fichero, o a través de expresiones regulares.

Mi preferencia sería el segundo caso, ya que si queremos desarrollar bajandonos el repositorio, no nos funcionaría y tendríamos que hacer un apaño. Con el segundo caso podríamos seguir funcionando como hasta ahora.

A falta de probarlo, para cada plataforma sería tan simple como lo siguiente.

**Isengard**
```xml
<filterchain>
  <tokenfilter>
    <replaceregex pattern="^[ \t]*PLATFORM_NAME[ \t]*=.*$"
                  replace="PLATFORM_NAME=kodi-isengard"/>
  </tokenfilter>
</filterchain>
```

**kodi-helix**
```xml
<filterchain>
  <tokenfilter>
    <replaceregex pattern="^[ \t]*PLATFORM_NAME[ \t]*=.*$"
                  replace="PLATFORM_NAME=kodi-helix"/>
  </tokenfilter>
</filterchain>
```

A ver si vale de utilidad y nos evitamos problemas de dejar cosas pendientes entre plataformas.

**Comment by tvalacarta** [comment]
Antes PLATFORM_NAME se declaraba en un fichero aparte "platform_name.py" para evitar eso, pero a la larga era más complicado.

Tampoco tiene mucho sentido hacer una plantilla, basta con coger un fichero como base y cambiarlo. Algo parecido a lo que se hace con las versiones antiguas en el build.xml:

```
<target name="copy-xbmc-10-dharma">
...
        <copy todir="${target}/xbmc-10-dharma/plugin.video.pelisalacarta">
            <fileset dir="main-classic">
...

        <copy overwrite="true" todir="${target}/xbmc-10-dharma/plugin.video.pelisalacarta">
            <fileset dir="version-xbmc-12-frodo">
...

        <copy overwrite="true" todir="${target}/xbmc-10-dharma/plugin.video.pelisalacarta">
            <fileset dir="version-xbmc-10-dharma">
...
```

Podemos simplemente copiar el config.py de por ejemplo XBMC Frodo (que no recuerdo pero viendo esto parece el punto de cambio), y luego reemplazar.

'<replaceregexp file="config.py" match="xbmc-ejemplo" replace="xbmc-ejemplo"/>

**Comment by SeiTaN** [comment]
No se si me he explicado mal, yo de Ant no controlo.

Hay dos opciones que he puesto, crear una plantilla o cambiar el valor de la variable, yo prefiero la segunda y veo que tú tb.

Sobre el fichero a copiar, debería ser es config.py de main-classic y cuando se copie al directorio de Frodo, cambiar el valor por expresión regular.

Con esto podríamos borrar las carpetas del proyecto que solo contienen este fichero para otras versiones en el caso especifico de XBMC como `version-kodi-15-isengard/core`

Por cierto creo que jarvis e isengard comparten el mismo fichero config, por que el PLATFORM_NAME es el mismo.

**Comment by tvalacarta** [comment]
Entiendo, pues hablamos de lo mismo :)

Yo con ANT sí que me he tenido que pelear... es horrible pero para lo que sirve tampoco hay que darle más vueltas.

El PLATFORM_NAME debe ser distinto en cada plataforma, aunque sólo sea para descargar el ZIP correcto. Si esas dos lo tienen igual es un error.

**Comment by SeiTaN** [comment]
Cierro ya que está solucionado.
