### ISSUE TITLE
python_libtorrent no se encuentra en mct

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#341]
Desde un AndroidTV no me carga python_libtorrent desde MCT, pero desde Torrenter funciona perfectamente. Lo raro es que desde MacOS me funciona bien el mismo código.

El error que me da una vez quitada la excepción es este de abajo pero no logro averiguar qué pasa para que no encuentre la librería. En Torrenter no veo que hagan nada especial y ese nombre de librería debería estar en el addon script.module.libtorrent que está correctamente instalado en la carpeta addons.

ImportError: No module named python_libtorrent

A ver si a alguno se os ocurre algo.
Gracias

**Comment by ChopChopKodi** [comment]
Creo que me falta modificar addon.xml. Gracias.
Supongo que en el mac como he hecho tantas pruebas tendré la librería python_libtorrent en alguna carpeta de python y no estará usando el addon de dimartino, porque tampoco tengo modificado el addon.xml y MCT me funciona.

En este enlace http://kodi.wiki/view/addon.xml#.3Cimport.3E en el punto 1.3.3 pone que se le puede añadir al import un parámetro llamado "optional" para que la dependencia no sea obligatoria y así deje instalar el addon aunque falte.

Por lo que he leido en el foro vais a replicar el addon de dimartino, pero si el parámetro optional funciona, seria mejor no duplicar funcionalidades y simplemente poner un mensaje al usuario para que se descargue e instale el módulo l primera vez que use torrent con pelisalacarta

**Comment by r0balo** [comment]
En el mac si tienes un libtorrent.so 0.16.xx te funcionará, la última 1.1.0, no nos funciona.

Realmente lo que se intenta es colocar el módulo en la carpeta lib de pelisalacarta con un \__init__.py personalizado reutilizando código de los script de DiMartino. En la carpeta lib/python_libtorrent tendriamos todos OS+arch de la última versión 1.1.0 pero sin subcarpeta de la versión que se va a usar, sólo contendrá el libtorrent.so de la versión que mejor funcione en cada OS+arch. Por esperiencia te puedo decir que las las versiones 0.16.xx suelen ser las que mejor funcionan en todos.

Si hacemos que se descargue la última versión posiblemente no te funcione en el MAC y a otros en otros dispositivos ya que, por defecto, fuerza el uso de las versiones 1.1.0 de los libtorrents

**Comment by ChopChopKodi** [comment]
El mac que tengo es de 32 bits (de finales de 2006 y reproduce vídeos en 1080p) y la librería la compilé yo ya que dimartino sólo tiene para 64 bits. La última que pude compilar creo que es la 1.0.9. La 1.1.0 no la tragaba el compilador viejo.
En el mac ya tengo asumido que tendré que poner a manopla cualquier librería que se salga de lo normal y por ahora funciona perfectamente, pero me he comprado el androidtv para modernizarme y por ahora va muy fino.

Lo de instalar python_libtorrent dentro de pelisalacarta, como veais mejor. El no depender de scripts de terceros también facilita la instalación y una vez funciona tampoco es que se cambie de librerías cada día.
A la tarde probaré a modificar el addon.xml y esperaré a vuestros cambios.
Gracias

**Comment by neno1978** [comment]
Si no recuerdo mal Robalo, la 0.16 q compilamos era compatible con 32 y 64 no?  O me equivoco...seguramente ;)

**Comment by r0balo** [comment]
En eso estaba pensando neno, voy a ver como tengo el tema de los hosting para que pueda @ChopChopKodi descargarlo y probarlo y de paso añado el \__init__.py

**Comment by neno1978** [comment]
😜🍻

**Comment by r0balo** [comment]
Os dejo un enlace temporal que a saber cuanto aguantará
[Index of /temp](http://robalo.net16.net/temp/)
Encontaréis tres zip

- **\__init__.zip** `__init__.py` personalizado con las correciones de @neno1978 y añadidos las archs de la versión 1.1.0.
- **libtorrent.so-osx_0.16.17.0.zip** libtorrente 0.16.17 para osx compilada por neno y un servidor que creemos se compiló para 32b y 64b.
- **python_libtorrent.zip** carpeta `python_libtorrent` que se pegará en la carpeta `lib` de pelisalacarta con el `__init__.py` anterior más las carpetas de las archs con la versión más baja de libtorrent en cada caso en su interior.

**Comment by neno1978** [comment]
👌🏻👌🏻 VIVA PEPOPTAMO 🍻🍻🍻👏👏
