### ISSUE TITLE
bug en launcher kodi

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#348]
@cmos me dijo el otro dia q los infoLabels de los episodios de su canal seriecanal no salian bien (se repetian valores entre todos los episodios). Despues de darle muchas vueltas y de campiar algunas cosas, que subire cuando termine, he encontrado el problema. Resulta q en este canal los episodios los obtiene en la funcion findvideos (se listan tantos items como enlaces haya, por ejemplo 3 episodios con 2 servidores cada uno: 6 items). Pues bien, la funcion launcher.run, si la action es 'findvideos' copia en todos los items del itemlist los infoLabels del padre (229 # Copy infolabels from parent item), con lo q en este caso machacamos la informacion obtenida anteriormente para cada item.
No se quien puso eso ahi, ni el por q, pero se me ocurren dos soluciones:

- Definir claramente para q sirven cada una de las actions predefinidas, por ejemplo: 'findvideos: busca todos los enlaces a servidores de **una sola** pelicula o episodio'

- (Mi preferida) La copia de los infoLabels del padre al hijo se ha de realizar en el momento de crear los hijos. Asi por ejemplo en el metodo canal.findvideos(item) al añadir items a la lista hariamos: `itemlist.append(item.clone(action="play", title=title, url=scrapedurl))`

**Comment by CmosGit** [comment]
Muy buena @superberny70, no se me ocurrió mirar en ese apartado del launcher cuando estuve buscando el por qué ocurría eso. Yo también veo mejor la segunda opción que propones, la primera me parece que limitaría demasiado la función de findvideos.

Y se me ocurre una tercera vía, ejecutar esa parte del código donde se copia en todos los items el infoLabels del padre únicamente en aquellos canales que no tengan una función findvideos definida, de esta forma si el canal la tiene se respeta el contenido que éste le pase sin cambiar nada, y sino se entiende que todos los vídeos pertenecen al mismo contenido (de lo contrario no tiene sentido ejecutar un findvideos génerico) y por lo tanto no hay problema de que el infoLabels sea en todos igual.

**Comment by superberny70** [comment]
Bueno pues como nadie ha dicho esta boca es mia, en #359 he solucionado esto eliminando esas lineas.
