### ISSUE TITLE
Fallo DocumaniaTV

### ISSUE THREAD

**Issue by juanpintom** [tvalacarta/pelisalacarta#35]
Da error desde hace algún tiempo,  ahora da error "No hay nada que reproducir"

Probado en PI2 con OSMC Actualizado.  Pelisalacarta actualizado. 

Gracias a los que hacéis posible esto,  gran trabajo.

**Comment by neno1978** [comment]
Solo descárgate el servidor cnubis q ha añadido Jesús, y el servertool.py del mismo merge y ya te tirara ;)

**Comment by juanpintom** [comment]
Impresionante la velocidad y efectividad de la respuesta! Muchas gracias!

SOLUCIONADO :P

**Comment by neno1978** [comment]
;)

**Comment by juanpintom** [comment]
Hola ,  me falla documania en kodi, tanto en helix como en jarvis,  las novedades y por canales salen vacíos y en top y viendo ahora salen pero da error al reproducir, paso log del helix.
http://pastebin.com/gmqLV2pi

Gracias de antemano! :)

Salu2
