### ISSUE TITLE
Cambiar ruta de biblioteca de pelisacalarta

### ISSUE THREAD

**Issue by jeniospain** [tvalacarta/pelisalacarta#36]
Tengo toda la base mysql en un nas, pero no puedo añadir series a la biblioteca de pelisalacarta porque la ruta TIENE QUE SER LOCAL.
En el archivo settings.xml viene la ruta de los srt
En windows me funciona perfectamente poniendo la ruta como en todos los windows:
<setting id="librarypath" value="//192.168.1.100/video/media/" />
aqui me crea las dos carpetas CINE y SERIES, me las cataloga y todo perfecto.
Pero en android NO.

La solucion ideal sería que salga el cuadro de dialogo del kodi (de añadir ruta en las fuentes previamente añadidas) en las opciones del plugin donde esta la ruta de los srt.
Ahora está puesto que puedas escribir a mano la direccion, pero ya os digo que esto solo funciona en windows, en android no.
Así sería kodi quien se encargara de dar la ruta y no afectaría el sistema en el que estuviera instalado..

GRACIAS POR VUESTRO EXCELENTE AYUDA

**Comment by SeiTaN** [comment]
Esto ya está arreglado, se puede cerrar.
