### ISSUE TITLE
LG TV Plex

### ISSUE THREAD

**Issue by uNbAs** [tvalacarta/pelisalacarta#362]
Tengo un LG WebOS con un cliente Plex que conecta con el servidor instalado en un NAS, cuando intento reproducir algún video del canal pelisalacarta siempre obtengo "el canal no esta respondiendo"

Servidor Open Media Vault donde esta instalado el servidor plex = 2.2.5 (Stone Burner)
Servidor Plex = Versión 1.0.0.2261
Ultima version Pelisalacarta

---

Versión WebOS LG TV = 3.10.9-32.afro.5
Version Plex TV = 2.6.9

**Comment by uNbAs** [comment]
Servidor Open Media Vault donde esta instalado el servidor plex = 2.2.5 (Stone Burner)
Servidor Plex = Versión 1.0.0.2261
***************************************************************************************************************
Versión WebOS LG TV = 3.10.9-32.afro.5
Version Plex TV = 2.6.9

**Comment by uNbAs** [comment]
¿Solucionado?

Bueno leyendo en el foro de plex sobre un plugin para IPTV he encontrado que había problemas a la hora de ejecutar los videos de stream y recomendaban quitar la reproducción directa.

Me he ido a la URL del servidor de plex, ajustes he desactivado la reproducción directa y ya funciona plex + pelisalacarta + pordede

**Comment by SeiTaN** [comment]
Esto se puede cerrar 😉

**Comment by SeiTaN** [comment]
@tvalacarta cierra esto por favor.
