### ISSUE TITLE
Se pueden guardar datos desde un canal?  por ejemplo en un archivo txt

### ISSUE THREAD

**Issue by spaniard1978** [tvalacarta/pelisalacarta#364]
Hola

Os planteo esta duda desde el desconocimiento de si es o no posible.

La duda es si es posible almacenar "de algúnt tipo"  algún dato desde un canal, por ejempolo en un archivo txt (u otra forma).

Lo he intentado con "open()  en diferentes lugares (sobre todo la carpeta userdata y sus subcarpetas) pero o bien no doy localizado el path concreto para llegar y me devuelve error de "no file found" o si intento hacerlo en la propia carpeta Channels el error de "permision denied".

Gracias

**Comment by SeiTaN** [comment]
Hola,

Si se puede, de hecho ya se hace, si te vas a userdata `...userdata\addon_data\plugin.video.pelisalacarta\settings_channels\` dentro de esta carpeta encontrarás un fichero con los datos especificos para cada canal.

Es un fichero json que luego tu puedes crear un módulo aparte, si quieres ver como se trata yo lo hago para dos de mis cosas, filtros(**filtertools.py**) y renombrando de items(**animeflv.numbered_for_tratk**) o tb lo puedes hacer con **channeltools.set_channel_setting** (este último tiene un bug que corrijo en mi PR).


**_Te lee el fichero de datos para el canal desde el que accedes._**
```python

    name_file = os.path.splitext(os.path.basename(__file__))[0]
    fname = os.path.join(config.get_data_path(), "settings_channels", name_file + "_data.json")

    if os.path.isfile(fname):

        data = ""

        try:
            with open(fname, "r") as f:
                for line in f:
                    data += line
        except EnvironmentError:
            logger.info("ERROR al leer el archivo: {0}".format(fname))

        json_data = jsontools.load_json(data)
```

Recuerda cuando guardes el fichero no machacarlo entero si no actualizar solo el nodo que crees para tus datos.

Saludos.

**Comment by r0balo** [comment]
La teoría es que sí. Si tienes problemas de permisos tendrás que arreglar eso. Busca información para tu SO de como hacerlo.
Para las rutas te recomendaría...

1. Si la carpeta está dentro de `kodi/addons/plugin.video.pelisalacarta`:
  * `path_archivo_txt = config.get_runtime_path() + "/ruta para el archivo"`
  * Si el archivo txt está en la caperta `channels`:
    * `path_archivo_txt = config.get_runtime_path() + "/channels/archivo.txt"`

2. Si la carpeta está dentro de `kodi/userdata/addon_data/plugin.video.pelisalacarta`:
 * `path_archivo_txt = config.get_data_path() + "/ruta para el archivo"`
 * Si el archivo txt está en una carpeta `channels` creada en la ruta anterior:
   * `path_archivo_txt = config.get_runtime_path() + "/channels/archivo.txt"`

Si arreglas el temas de los permisos no tendrás ningún problema con ninguna ruta y ni con ningún método (read, write o append).

**Comment by spaniard1978** [comment]
Muchas gracias a ambos

Estas dos líneas son las que necesitaba para encontrar la ruta absluta :)
     name_file = os.path.splitext(os.path.basename(__file__))[0]
    fname = os.path.join(config.get_data_path(), "settings_channels", name_file + "_data.json")

**Comment by superberny70** [comment]
No te compliques la vida, si quieres guardar un par de datos tipo 'ultima visita' o algo asi utiliza config.set_setting(name, value, channel) o channeltools.set_channel_setting(name, value, channel).
La diferencia entre ambas es q la primera te permite guardar el valor del parametro name en el fichero global o en especifico del canal. Value puede ser: str, int, dict o list.

Y para recuperar el valor guardado tan solo debes hacer config.get_setting(name, channel) o channeltools.get_channel_setting(name, channel) respectivamente.

De este modo te olvidas de rutas y demas.

**Comment by spaniard1978** [comment]
Si, esas las conocía, pero yo necesitaba escribir una lista de url asociadas a una imagen en un archivo para poder luego recuperarlas

**Comment by SeiTaN** [comment]
```json
{
    "settings": {
                       "key_existente": "valor",
                       "nombre_imagen": ["url1", "url2", "url3"]
                     }
}
```

**Comment by superberny70** [comment]
a una sola imagen?
value = [url1, url2, url3]
channeltools.set_channel_setting(name_for_imagen, value, channel)

**Comment by spaniard1978** [comment]
Finalmente lo he resuelto con un archivo de texto sencillo con datos en cada línea dividos por una @ (solución cutre pero eficaz) jeje

**Comment by SeiTaN** [comment]
El fichero favoritos.txt lo creaste a mano, no?
Ten cuidado porque el fichero "favoritos.txt" no se comprueba si existe y te puede dar error, a mi tb me paso eso xD

**Comment by SeiTaN** [comment]
Duda explicada se puede cerrar :)
