### ISSUE TITLE
Incluír datos en la parte derecha de las listas

### ISSUE THREAD

**Issue by spaniard1978** [tvalacarta/pelisalacarta#365]
Mre refiero a si es posible, como he visto en otro addons, incluír en la parte derecha de la lista algún dato, tal como se indica en esta captura:

[http://subefotos.com/ver/?be8c1a77520d1f3ae44fa077e158f089o.png](http://subefotos.com/ver/?be8c1a77520d1f3ae44fa077e158f089o.png)

Por  otro  lado he visto en algún addon que, en esa zona, se  marca el tiempo de vídeo visualizado y si ha sido no visto (esto segundo no tendría más ciencia que almacenar el valor de cada vido al que se ha accedido), desconozco si existe algún sistema propio en pelisalacarta que lo haga y lleve el control del tiempo visualizado.

Gracias a todos.

**Comment by SeiTaN** [comment]
En la imagen no aparece lo que comentas de cuanto tiempo has visualizado el video, te muestra la puntuación, la calidad y si ha sido visto, todo esto se consigue con [infoLabels](http://kodi.wiki/view/InfoLabels).

Si miras en `library.mark_as_watched_on_kodi` verás como se puede hacer con strm, para lo tuyo tendrás que hacer algo parecido.

**Comment by spaniard1978** [comment]
La captura era para indicar a la "parte a la que me refería". Ya había investigado las infoLabels, pero no encuentro el modo de pasarlas en un addon del siguiente modo
`itemlist.append(Item(channel=item.channel,  action="loquesea", title=title, fulltitle= item.title ,url=url, thumbnail=imagen, folder=False) )`

Aunque añada las etiquetas dentro no tienen efecto en la visualización.

**Comment by superberny70** [comment]
Como añadir informacion extra al item: http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=7092 
Esto esta completamente integrado ya en la version master (y por supuesto en develop) y muchos canales ya la utilizan para mostrar informacion.
Sobre los datos q comentas en la captura, dependen de varios factores:

- Q la informacion este añadida a su infoLabel.
- El skin utilizado (aunq en este caso creo q es el q viene por defecto)
- El tipo de contenido fijado (creo q es movie) y la vista (info del medio 2)

Tambien podrias decirno q addon es y asi hecharle un ojo

**Comment by spaniard1978** [comment]
Genial... esto me pasa por no leer la documentación del foro porque estaba ahí claro.
Simplemente estoy "trasteando" con el canal filesmonster_catalogue para ponerlo "más bonito"...
Muchas gracias

**Comment by spaniard1978** [comment]
He estado haciendo diferentes pruebas y de todos los valores que se pueden pasar con infoLabel sólo tres de ellos he sido capaz de que se muestra en las líneas de "itemlist" (si ha sido o no visto con playcout, el peso y la duración).

Mi intención era marcar "de algún modo gráfico" los vídeos que han sido añadidos como favoritos y lo que han sido visualizados.

- En el primer caso, los marcados como favoritos, no he sido capaz (imagino que no es posible) añadir ningún indicador gráfico. Supongo que tendré que añadirlo como texto al título con otro color. Salvo que haya algo que se me escapa. 

- En el segundo caso, los visualizados, si soy capaz de mostrar el indicativo pero no acabo de ver como puedo "saber si se ha abierto o no el vídeo" (como mucho he podido controlar cuando se abre el menú para descargarlo, añadirlo a una lista y todo eso)

Curiosamente si podría marcar sin problemas los favoritos usando el indicativo de "visualizado" jeje, pero quedaría un poco raro ;)

**Comment by SeiTaN** [comment]
En el caso 1,  lo más sencillo sería cambiar el color o añadir "[F]" en el titulo por ejemplo, aunque no quedaría muy molón. No se si se podría intentar cargar una imagen en el texto del titulo, kodi soporta la etiqueta [COLOR], sería mirar si soporta [IMAGE] u algo parecido.
En el caso 2, como no guardes los ficheros reproducidos, evidentemente no vas a saberlo.

**Comment by spaniard1978** [comment]
Ya he comprobado que la etiqueta [IMAGE]  [IMG] y todo lo que se nos pueda ocurrir no lo soporta, parece ser que unicamente soporta [estos](http://kodi.wiki/view/Label_Formatting).
Sobre el segundo caso, así está el problema, como detectar que el vídeo ha empezado a reproducirse y almacenar ese valor de algún modo (soy capaz de detectar hasta que da las opciones de descarga)

**Comment by SeiTaN** [comment]
Duda explicada se puede cerrar :)
