### ISSUE TITLE
Desactivadas las actualizaciones de canales???

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#366]
Me acabo de dar cuenta de q desde https://github.com/tvalacarta/pelisalacarta/commit/83b6a906385280e7c20d8f2f10118f81d61bc5e2#diff-1dac521a4cfd9405a5f816461fc072d6 
Se han desactivado las actualizaciones automaticas de canales ¿esto es intencionado?

**Comment by tvalacarta** [comment]
Si, la idea es cambiarlo por un nuevo sistema basado en un servicio.

**Comment by SeiTaN** [comment]
Ya está activado, esto se puede cerrar.
