### ISSUE TITLE
Úlitmas mejoras en la gestión de la biblioteca

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#370]
Bueno ya falta poco para esté terminada, aprovechando la gestión del menú contextual de @divadres, gracias como siempre por tu gran trabajo :smiley: 

Estoy añadiendo las opciones que salen en Kodi (aún no está terminada la funcionalidad), mi idea como ya dije es primero hacerlo así y luego crear una opción por items para las plataformas que no lo soportan.

No os asusteis de las capturas con krypton :laughing: , voy a enumerar las opciones que he añadido, otras que salen las puso @divadres para su desarrollo de favoritos y descargas :wink: 

## **Dentro de la biblioteca:**
![image](https://cloud.githubusercontent.com/assets/11775029/17439186/1f086694-5b27-11e6-840f-299528da4375.png)

## PELICULAS
![image](https://cloud.githubusercontent.com/assets/11775029/17464241/b97147be-5cda-11e6-874d-6b2f3c1d670e.png)

- [x] Información: es el famoso "I" y muestra la información de la pelicula.
- [ ] Marcar como visto/no visto: marcará el capitulo como visto/no visto(este texto y la acción dependerá del valor existente en playcount).
- [x] ~~Reproducir: llamará al play para que se ejecute, este método lo veo como un atajo si estamos en el menú contextual y no es imprescindible.~~
- [x] Eliminar : se encargara de poder borrar la pelicula fisicamente y los ficheros asociados.
- [ ] Cambiar contenido: permitirá gestionar los infolabels para la pelicula, de manera que si nos hemos equivocado al identificarla o lo hemos dejado para más tarde, lo podamos hacer desde aquí.

### **Seleccionando una serie:**
![image](https://cloud.githubusercontent.com/assets/11775029/17464252/e4013552-5cda-11e6-8baa-901c4fd25ae9.png)

- [x] Información: es el famoso "I" y muestra la información de la serie.
- [ ] Marcar como visto: marcará la serie entera como vista, esto si está configurado con Kodi, tb lo hará en su correspondiente lugar.
- [ ] Marcar como visto: caso inverso del anterior.
- [x] Eliminar: se encargara de poder borrar la serie físicamente, aparece un cuadro de confirmación por si le hemos dado erróneamente.
- [x] No/Buscar automáticamente los episodios: establece si en la serie se buscan o no los episodios.
- [ ] Cambiar contenido: permitirá gestionar los infolabels para la serie, de manera que si nos hemos equivocado al identificarla o lo hemos dejado para más tarde, lo podamos hacer desde aquí.

### **Opciones para una temporada:**
![image](https://cloud.githubusercontent.com/assets/11775029/17439212/3d0410f8-5b27-11e6-9e26-e42b086b4cf8.png)
- [X] Marcar como visto: marcará la temporada entera como vista, esto si está configurado con Kodi, tb lo hará en su correspondiente lugar.
- [X] Marcar como visto: caso inverso del anterior.
- [ ] Hacer que tb marque la carpeta y no solo los episodios.

### **Opciones para episodios:**
![image](https://cloud.githubusercontent.com/assets/11775029/17439221/487a4fd8-5b27-11e6-9bd7-1f7ccd64583d.png)
- [x] Marcar como visto/no visto: marcará el capitulo como visto/no visto(este texto y la acción dependerá del valor existente en playcount).
- [x] ~~Reproducir: llamará al play para que se ejecute, este método lo veo como un atajo si estamos en el menú contextual y no es imprescindible.~~

Cuando suba el PR por favor, en general echadle un ojo, no sea que me haya comido algún commit, o los famosos casos que comentó @tvalacarta sobre los "{0}{1}" en los archivos comúnes que ya estaban solucionados.

TODO aparte:
- [ ] falta que divadr suba la parte de mediaserver.
- [x] evitar que se pierda el marcado como visto al actualizar la serie.
- [ ] arreglar el encode/decode.
- [ ] arreglar que pregunte el nombre de la serie cuando ya existe al actualizar la biblioteca.
- [ ] diferenciar el favoritos de pelisalacarta del normal.
- [ ] arreglar bugs del log.

**Comment by tvalacarta** [comment]
Tiene una pinta excelente :)

Me gusta el menú contextual, nunca me ha gustado demasiado porque está muy escondido y no se ve (es una opción muy friki) pero es cierto que es una solución mucho más genérica para que luego cada plataforma lo presente a su modo.

¿Has visto cómo está resuelto en tvalacarta? A mí me resulta muy cómodo...

Lo de "Gestionar..." suena un poco raro, muy "informático". Yo pondría una opción para "Borrar" y otra para "Modificar" si es como dices. A ver quién es el guapo que le da a una opción así ja ja ja

**Comment by SeiTaN** [comment]
> Tiene una pinta excelente :)

Gracias :blush:

> ¿Has visto cómo está resuelto en tvalacarta? A mí me resulta muy cómodo...

No uso tvalacarta :sweat_smile:, puedes poner una captura?

> Lo de "Gestionar..." suena un poco raro, muy "informático". Yo pondría una opción para "Borrar" y otra para "Modificar" si es como dices. A ver quién es el guapo que le da a una opción así ja ja ja

Los nombres son extraídos de lo que sale en Kodi, se puede cambiar claro está.

Sobre las plataformas con biblioteca, kodi y media-server tienen menú contextual no sería problema, lo que no sé es si con plex (de momento no tiene biblioteca) si habría que currarse una alternativa.

**Comment by tvalacarta** [comment]
> No uso tvalacarta 😅, puedes poner una captura?

![captura de pantalla 2016-08-05 a las 16 59 14](https://cloud.githubusercontent.com/assets/5525238/17440793/6481d74e-5b2e-11e6-91dd-05880e85b7f6.png)

Es más bien a nivel de código, si miras en el canal "api_programas" verás un "get_context_menu_for_item" que es llamado desde el xbmctools.

En el xbmctools tienes un "add_items_to_kodi_directory", que viene a ser el "renderItems", que llama a "get_context_menu_for_item" para obtener el menú contextual de cada item.

**Comment by SeiTaN** [comment]
Le echo un ojo, gracias.

**Comment by superberny70** [comment]
"..¿Has visto cómo está resuelto en tvalacarta?.."
El día q nos pongamos a mirar tvalacarta te lo destrozamos seguro!!! Por suerte para ti nunca acabaremos de modificar pelisalacarta y no tendremos tiempo para otros plugins. He visto incluso quien quiere ponerle control por voz para no tener q mover el raton/mando distancia jejeje.
Por cierto llevo tiempo mirando como conectar el microondas a Kodi y poder añadirle un parámetro más a las películas de la biblioteca: 'palomitas': True/False ;-)

**Comment by SeiTaN** [comment]
> ...las películas de la biblioteca: 'palomitas': True/False ;-)

Eso lo pone openload :laughing::laughing::laughing::laughing:

**Comment by tvalacarta** [comment]
Kodi no tiene un InfoLabel para eso ya?

Patanes...

2016-08-05 20:28 GMT+02:00 SeiTaN <notifications@github.com>:

> ...las películas de la biblioteca: 'palomitas': True/False ;-)
>
> Eso lo pone openload 😆😆😆😆
>
>

**Comment by SeiTaN** [comment]
Chapo el issue ya que está subido :)
