### ISSUE TITLE
Problema con la carga de archivos json en Libreelec

### ISSUE THREAD

**Issue by Gongui** [tvalacarta/pelisalacarta#373]
Estoy usando la versión 8 de libreelec, que viene con krypton y python 2.7.11.
La ultima actualización de pelisalacarta volvió prácticamente inútil el plugin en este sistema. Lo único que funciona es reproducir ficheros strm. Tratar de ingresar a cualquier canal u opción del plugin me devuelve una pagina vacía.

Obtengo el siguiente error cada vez que se intenta leer un fichero json y supongo que es lo que inutiliza el plugin:

> `22:27:47 T:140045225350912   DEBUG: pelisalacarta.core.jsontools.load_json Probando simplejson incluido en el interprete
> 
> 22:27:47 T:140045225350912   DEBUG: pelisalacarta.core.jsontools.load_json -> {'settings': {'include_in_newest_peliculas': True, 'include_in_newest_series': True, 'include_in_global_search': False}}
> 
> 22:27:47 T:140045225350912   DEBUG: Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.pelisalacarta/core/jsontools.py", line 109, in load_json
>                                                 from lib import simplejson
>                                               File "/storage/.kodi/addons/plugin.video.pelisalacarta/lib/simplejson/__init__.py", line 240, in <module>
>                                                 _default_decoder = JSONDecoder(encoding=None, object_hook=None)
>                                               File "/storage/.kodi/addons/plugin.video.pelisalacarta/lib/simplejson/decoder.py", line 328, in __init__
>                                                 self.scan_once = make_scanner(self)
>                                               File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in py_make_scanner
>                                             AttributeError: 'JSONDecoder' object has no attribute 'object_pairs_hook'`
> 

Log: https://paste2.org/xNbxzmzv

Otra cosa que parece estar fallando es obtener las imágenes del servidor. Parece que todas devuelven error 404. Ejemplo: http://media.tvalacarta.info/pelisalacarta/posters/thumb_novedades.png

**Comment by javiernoval** [comment]
Yo también tengo el error de JSON, pero a mí el plugin me funciona bien (por lo menos lo que yo uso: navegar por los canales, reproducir series o películas directamente, agregarlas a la biblioteca para acceder rápidamente con Kodi...), por lo que no debería ser lo que inutiliza el plugin.

Creo que ese error concretamente vuelve a ser una colisión de nombres, como en el problema que hubo con las bibliotecas de Samba: en mi sistema (Kodibuntu actualizado) tengo instalado el paquete python-simplejson (del que depende Kodi), que provee también un módulo llamado simplejson, como el incluido en Pelisalacarta. Creo que al ejecutar este import:

`./lib/simplejson/decoder.py:7:from simplejson.scanner import make_scanner`

el simplejson que se importa es el del sistema, y es lo que causa los problemas.

En mi OpenELEC 6.0.3 también está instalado ese módulo en el sistema, por lo que imagino que el problema en LibreELEC es el mismo.

**Comment by SeiTaN** [comment]
Efectivamente el problema es de las librerias json que vienen en libreelec

**Comment by Gongui** [comment]
Estuve editando algunos archivos que importaban directamente json y simplejson.
Una vez arreglado el problema con json parece que los items se cargan (según el log), pero por alguna razón no se muestran en kodi.
Debe ser cosa de libreelec, espero que lo arreglen para la versión final.
Por ahora voy a seguir usando kodi en ubuntu.
Ya pueden cerrar la issue. Gracias por contestar :)
