### ISSUE TITLE
Solucionar el encode/decode de filetools con caracteres no ASCII

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#377]
Si alguien se anima a solucionar esto, todo pasa por filetools (o debería), asi que solo habría que tocarlo ahí.

Se tendría que mirar que el encode/decode se haga igual para los distintos S.O. y que se creen las carpetas con nombres no ASCII.

Esto solucionaría el problema que hay actualmente cuando se crea una serie con nombre con caracteres extraños (normalmente en Anime) y cuando el nombre de usuario de windows tiene tildes y no se puede crear las carpetas necesarias para que funcione el plugin (config.py).

**Comment by ChopChopKodi** [comment]
¿Cuál es la razón de usar la función encode de filetools? Según esto https://docs.python.org/2/howto/unicode.html#unicode-filenames si les pasas una variable de tipo _unicode_ a las funciones de sistema de ficheros de Python éstas las convierten según el sistema en el que estén. ¿Por qué hacer esa transformación a _str_ nosotros en vez de dejársela a Python?

En Kodi parece que las funciones de ficheros soportan o bien _unicode_, o _str_ en formato utf-8. ¿No sería suficiente con asegurarse de que las cadenas que se pasen a las funciones de ficheros sean _unicode_ y estén en _utf-8_ si se pasan a funciones de Kodi o sys.filesystemencoding() si se pasan a funciones de Python?

La verdad es que estoy un poco hecho un lío

**Comment by tvalacarta** [comment]
El encoding en Python es insufrible... por cierto, habéis leído este documento? 

http://nedbatchelder.com/text/unipain/unipain.html

Yo lo tengo que revisar periódicamente, cuando agoto todos los recursos y me sigue fallando un trozo de código de forma incomprensible. Eso que dices es lo que llaman el "Unicode sandwhich" (página 35) je je je

No pondría la mano en el fuego, pero yo diría que no es tan fácil como dices. A mí en Windows siempre me da escalofríos cuando tengo que hacer cosas con Python en el sistema de ficheros. Cuando crees que lo has resuelto descubres que te falla en un nuevo "caso especial".

**Comment by divadres** [comment]
Bueno... yo lo hice asi poraue entendi que era necesario codificar el nombre del archivo con la codificacion que usara el sistema de archivos que tengamos... tal y como esta me funciono bien en todas las pruebas que hice en windows... y alguna (pocas) que hice en linux... ¿que python se encarga de hacer eso automaticamente? Primera noticia... si es asi desde luego se podria quitar eso y pasar el nombre en unicode directamente... pero tengo mis dudas...

**Comment by ChopChopKodi** [comment]
Yo creo que hablo de 2 cosas diferentes. Una es el tipo de la variable _unicode_ o _str_ y otra la codificación del juego de caracteres de la cadena de caracteres que se pasa y se devuelve.

_unicode_ es un tipo de variable en la que cabe cualquier codificación de caracteres. Es como una codificación intermedia en la que guardar cualquier tipo de texto. El problema viene cuando tienes un _str_ o cadena de caracteres, que es el programador el que tiene que saber en qué juego de caracteres está esa cadena para poder convertirla correctamente a _unicode_ y de ahí poderla convertir a otro juegos de caracteres en otro_str_.
Los ficheros trabajan con _bytes/str_, por eso si trabajas internamente en Unicode, al leer de un fichero hay que convertir de _bytes/str_ a _unicode_, y al escribir a un fichero de  _unicode_ a _bytes/str_.

En la función _encode_ de _filetools_, según su comentario, se pasa una variable _str_, codificada en _utf-8_, que se procesa a _unicode_ para convertir su juego de caracteres, y luego se vuelve a convertir a _str_.
Esto puede ser correcto, pero me parece raro que se vuelva a hacer la conversión de _unicode_ a _str_ cuando las funciones de ficheros de Python y las de Kodi usan _unicode_ perfectamente.

Aunque puede que os esté liando porque pasando _str_ y devolviendo _str_ en teoría también funciona.

Lo que pasa realmente con el código es que la función _encode_ ahora mismo está mal y no concuerda con el comentario. Ahora está como pongo abajo y para colmo a _remove_chars_, en vez de un _str_, se le está pasado una variable _unicode_ (que igual da lo mismo porque tanto _str_ como _unicode_ son subclases de _basestring_ y para determinadas funciones funcionan de forma similar, pero no concuerda con el comentario)

```
    if path.lower().startswith("smb://") or _samba:
        path = unicode(path, "utf-8")
    else:
        path = unicode(path, "utf-8")
        # _ENCODING = sys.getfilesystemecoding() or locale.getdefaultlocale()[1] or 'utf-8'

    return remove_chars(path)
```

Yo creo que debería ser algo como esto para quitar los caracteres que no concuerden con el juego de caracteres al que se convierte, y devolver _str_:


```
    path = remove_chars(path)
    if path.lower().startswith("smb://") or _samba:
        path = unicode(path, "utf-8", "ignore")
        path = path.decode("utf-8")
    else:
        _ENCODING = sys.getfilesystemecoding() or locale.getdefaultlocale()[1] or 'utf-8'
        path = unicode(path, _ENCODING, "ignore")
        path = path.decode(_ENCODING)

    return path
```

De esta forma se convierte de _str_ a _unicode_, se quitan los caracteres que no concuerden con el juego de caracteres del sistema de ficheros y se vuelve a convertir en _str_. Si la función de encode es para ser usada en las llamadas a sistemas de ficheros a Python y Kodi esta última conversión no debería ser necesaria.

En vez de "ignore" también se puede usar "replace" y luego reemplazar el caracter \ufffd por un caracter seguro como "guión bajo".

También en la asignación de _ENCODING eso de usar locale.getdefaultlocale()[1] no me convence mucho, pero como me ha comentado @SeiTaN en otro comentario quizás sea necesario en Android como "fallback" en caso de que _sys.getfilesystemEncoding()_ devuelva _None_.

En la función _decode_ pasa algo parecido. Lo que hace la función no concuerda con el comentario. Si simplemente la cadena que se pasa es (según el código) _str_ o _unicode_, y ésta ya está en el juego de caracteres del sistema de ficheros, no es necesario convertirla otra vez a ese juego de caracteres con _ENCODING

Sería algo así para ser correcto, aunque no sé exactamente si es esa la intención

```
def decode(path):
    """
    Convierte una cadena de texto al juego de caracteres utf-8 eliminando los caracteres que no estén permitidos en utf-8
    @type: str, unicode, list de str o unicode
    @param path: puede ser una ruta o un list() con varias rutas
    @rtype: str
    @return: ruta codificado en UTF-8
    """
    if type(path) == list:
        for x in range(len(path)):
            if not type(path[x]) == unicode:
                path[x] = path[x].decode("utf-8", "ignore")
            path[x] = path[x].encode("utf-8", "ignore")
    else:
        if not type(path) == unicode:
            path = path.decode("utf-8", "ignore")
        path = path.encode("utf-8", "ignore")
    return path
```

No sé si he aclarado algo o la he liado más. Espero no haber metido la zarpa con la explicación de _unicode_ y _str_ :smile:

**Comment by SeiTaN** [comment]
> También en la asignación de ENCODING eso de usar locale.getdefaultlocale()[1] no me convence mucho, pero como me ha comentado @SeiTaN en otro comentario quizás sea necesario en Android como "fallback" en caso de que _sys.getfilesystemEncoding() devuelva None.

Exacto.

Te lo has currado @ChopChopKodi, es algo que siempre he tenido dudas con lo de unicode/str.  Lo que comentas me cuadra bastante con las cosas que he leído, se podría añadir tu sugerencia y probarlo.

Aparte del decode/encode habría que ver lo que comentas, si al crear directorios y tal, se hace correctamente cuando se ponen caracteres no válidos para ese S.O.

**Comment by ChopChopKodi** [comment]
Tras meditar mi texto con la almohada me he dado cuenta de que he metido la pata en mis asunciones sobre el código de la función _encode_.

Cuando conviertes un _str_ a _unicode_, el parámetro del juego de caracteres que le pasas no es el juego de caracteres que te gustaría que tuviese la cadena, que es lo que asumimos al usar la variable _ENCODING o "utf-8" a pelo, sino el juego de caracteres en el que está actualmente la cadena _str_ . La función _encode_ tal como está planteada nunca va a funcionar correctamente ya que cuando tomamos un texto de una web, por ejemplo, puede estar en cualquier juego de caracteres que quiera el autor de la web y ahora mismo no podemos saberlo dentro de la función _encode_

La solución la da las páginas 40 y 41 del enlace que ha puesto @tvalacarta http://nedbatchelder.com/text/unipain/unipain.html#42, aunque no parece bonita.

Nada más capturar una cadena de tipo _str_ de cualquier fuente hay que convertirla a _unicode_ con el juego de caracteres en el que sepamos que está esa cadena. Ese juego de caracteres puede ser cualquier cosa y te lo puede decir el _content-encoding_ en caso de venir de una página web, o la documentación en otros casos (Las cadenas que devuelve Kodi en teoría son siempre utf-8). O si están en un fichero de código Python se usa la cabecera -*- coding: utf-8 -*- para saber qué juego de caracteres espera Python que tenga el fichero de código.
Cada cadena puede ser diferente y aunque utf-8 se usa casi siempre no podemos darlo por asumido. 

Creo que hay 2 formas de abarcar el tema.

La primera que considero más correcta:

La función _encode_ debería aceptar sólamente _unicode_ ya que de esta forma nos aseguramos de que el juego de caracteres ya está inferido (bien o mal pero podemos trabajar sin importarnos en qué juego de caracteres estaba la cadena original).
Así,  para asegurarnos de que el nombre va a ser válido y no saltará ningún error de codificación más tarde sólo hay que quitar los caracteres conflictivos que no estén permitidos en un nombre de  de fichero (separadores de directorio, wildcards, etc.) usando _remove_chars_, y convertir esa cadena al juego de caracteres del sistema de ficheros (la variable _ENCODING), o _utf-8_ en caso de una ruta SMB.
Esto lo podemos hacer con el parámetro "ignore" para eliminar los caracteres conflictivos en el juego de caracteres final, o usar "replace" y cambiar el caracter _\ufffd_ por _guión bajo_, por si quisieramos que la cadena resultante tuviera un largo más parecido al original.
Finalmente la volvermos a convertir a _unicode_ o la dejamos como está en formato_str_

Si, además, en la función _encode_ generamos una excepción en caso de que la variable que pasamos no sea _unicode_ podemos saber cuando no hemos inferido el juego de caracteres de una cadena externa y podemos pifiarla porque la cadena original no esté en un juego de caracteres seguro.

La segunda, que puede ser más rápida de implementar pero menos segura:

El parámetro de entrada puede ser _unicode_ o _str_.
Actualmente casi todas las cadenas que nos encontremos estarán codificadas en utf-8.
En la función _encode_ se tendría que poner un parámetro con el juego de caracteres en el que sepamos que está la cadena que pasamos y usar utf-8 por defecto.
En caso de tener una cadena _str_ que sepamos que no está en utf-8 o provenga de un sitio dinámico (venga de una web o similar) **tenemos que pasar el juego de caracteres correcto como parámetro**.

Si la variable que pasamos está en _str_ la convertimos usando el juego de caracteres como parámetro. Si está en _unicode_ no hay que hacer nada ya que el juego de caracteres ya está inferido en otra parte.

Una vez en _unicode_ es igual que la forma 1; _remove_chars_ y convertir a _str_ con el juego de caracteres final para asegurarnos de que la cadena tendrá los caracteres equivalentes al juego de caracteres original y eliminados los conflictivos.


He pensado que si, como dije en los mensajes anteriores, pasamos directamente la cadena _unicode_ a las funciones de ficheros de Python sin asegurarnos de que el juego de caracteres original es convertible al juego de caracteres final, podemos encontrar algún caso raro en el que la llamada a una función de ficheros fallase por usar algún caracter extraño cuando ese fallo es evitable simplemente quitando el caracter erróneo.
Para el usuario muchas veces tener un fichero sin ese caracter no va a ser problema y como los sistemas de ficheros actuales todos usan o bien utf-8 (o unicode en caso de windows) la posibilidad de que haya que quitar caracteres es muy baja, incluso si se usan nombres en codificaciones en ruso, chino, árabe o japonés.

Espero que ahora esté todo mejor pensado.

**Comment by divadres** [comment]
Cuando escribi filetools.py... la idea no era que le pasaras un nombre sacado de una web (sin saber su codificacion) y creara un archivo con ello... la idea es que pasandole una cadena en Utf8 fuera capaz de crear un fichero sea cual sea el sistema de archivos... y este se creara correctamente... 

Es por eso que todas las funciones de filetools deverian recibir nombres en utf8... luego... cada canal es el que deveria encargarse de comprobar que codificacion yiene la pagina web y hacer la conversion adecuada...

Se tambien que hay paginas web q a pesar de indicar que tienen una codificaion luego ye encuentras partes que en realidad estan en otra... por eso al final habria que hacer un unicode(texto, "utf8", errors="replace") para que si queda algun caracter que no esta correcto... lo elimine

Una vez tenemos una cadena en unicode... ya podemos codificarla segun el sistema de archivos sin problema... 

Pero desde luego... no es necesaria quitar todos los caracteres especiales en todas las cadenas ya que muchas no van a dar ningun problema...

Tambien devemos diferenciar entre caracteres especiales que requieren la codificacion adecuada y caracteres prohibidos (que no pueden estar en un nombre de archivo) estos directamente hay que eliminarlos...

**Comment by ChopChopKodi** [comment]
De acuerdo. Entonces algo como el siguiente código debería ser correcto. Lo único que habría que comprobar es que cuando se lean nombres de ficheros desde las webs éstos se conviertan a utf-8 correctamente si no están ya en utf-8

Los caracteres especiales, que yo sepa, no se quitan. Solamente se quitan si no son mapeables al juego de caracteres de destino elegido al codificar la variable a _str_ desde _unicode_ o desde _str_ a _unicode_ si se ha especificado un juego de caracter de origen erróneo.
Por ejemplo, si tienes en _unicode_ una cadena con acentos y demás caracteres de utf-8 y los quieres convertir a ascii, sin "ignore" o "replace" dará error porque esos acentos no son mapeables a ascii. Con "ignore" o "replace" no dará error pero la cadena resultante no contendrá esos caracteres. En ese caso o se pierden los caracteres o se opta por normalizar la cadena y convertir esos caracteres a otros similares en el nuevo juego de caracteres.
En cualquier sistema moderno no creo que haya problema porque o bien se usa utf-8, o juegos de caracteres similares. En cualquier caso usando "ignore" o "replace" no debería haber errores de codificación, aunque sí se perderían los caracteres no mapeables.

En el código he puesto la comprobación de si la variable es unicode porque de ese modo si se pasa ya una variable unicode ésta se convertiría sin dar error.

```
def encode(path, _samba=False):
    """
    Codifica una ruta según el sistema operativo que estemos utilizando.
    El argumento path tiene que estar codificado en utf-8
    @type path unicode o str con codificación utf-8
    @param path parámetro a codificar
    @type _samba bool
    @para _samba si la ruta es samba o no
    @rtype: str
    @return ruta codificada en juego de caracteres del sistema o utf-8 si samba
    """
    if not type(path) == unicode:
        path = unicode(path, "utf-8", "ignore")

    if path.lower().startswith("smb://") or _samba:
        path = path.encode("utf-8")
    else:
        _ENCODING = sys.getfilesystemencoding() or locale.getdefaultlocale()[1] or 'utf-8'
        path = path.encode(_ENCODING, "ignore")

    return remove_chars(path)

```
