### ISSUE TITLE
config.get_platform()

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#391]
El otro dia me encontre con un problema con esta funcion en kodi. 
Cuando instale pelisalacarta me baje la version correspondiente a mi kodi, pero despues he actualizado tanto kodi como el plugin y de ahi el desfase actual ya q las versiones de pelisalacarta q baja update es la q se instalo inicialmente y no la correspondiente al kodi actual. Por ello propongo sustituir config.get_platform() en todas las versiones de kodi por:

```
def get_platform():
    codename = {"10": "dharma", "11": "eden", "12": "frodo", "13": "gotham",
                "14": "helix", "15": "isengard", "16": "jarvis", "17": "krypton"}
    num_version = xbmc.getInfoLabel('System.BuildVersion').split(' ')[0]

    return "kodi-" + codename.get(num_version.split('.')[0], num_version)
```

y nos olvidamos de la constante PLATFORM_NAME.
No lo hago como PR ya q esa constante se cambia al empaquetar el zip.

**Comment by tvalacarta** [comment]
Al contrario, si es la leche... no conocía esas infolabels :(

Hay cosas cojonudas como "System.InternetState" o "System.FreeSpace" que pueden venir muy bien je je je

**Comment by superberny70** [comment]
Esto se quedo un poco olvidado ¿no?

**Comment by tvalacarta** [comment]
Yo dije que me parecía bien :)

Me lo apunto para la próxima beta y lo pensaré, pero es buena idea para afinar el actualizador todavía más.

**Comment by superberny70** [comment]
@tvalacarta 
beta 3!!! beta 3!!!
:stuck_out_tongue_winking_eye: :clap: :stuck_out_tongue_winking_eye: :clap: :stuck_out_tongue_winking_eye: :clap: :stuck_out_tongue_winking_eye:
