### ISSUE TITLE
[Sugerencia] Opción para reproducir siguiente enlace si el actual está roto o no disponible

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#393]
Ya que últimamente tengo poco tiempo dejo aquí la idea por si interesa y alguien se anima a realizarla.

Cuando queremos ver un video y le damos a reproducir, hay veces que da error, ya sea porque el video ha sido borrado o el conector no está actualizado, problemas con la conexión.... y nos salta un mensaje, sería añadir una opción en este mensaje o configurar uno que saldría si se configura un parametro.

Mi idea es que si cuando te muestra la lista de servidores, si en el que has marcado no se ha podido reproducir, se reproduzca el siguiente de manera automatica o preguntando.

Esto sería una opción configurable.
"¿Reproducir automáticamente siguiente video disponible si el actual no lo está?"
"Opciones (No, Si, Preguntar)"

Así nos quitaríamos el típico mensaje de OK, que sale que tenemos que dar a aceptar y luego buscar en la siguiente opción de video.

**Comment by superberny70** [comment]
Entiendo lo q dices pero...

Supongamos q tenemos una lista con 30 enlaces de servidores. El primero es del servidor A y despues hay 20 del servidor B (q casualmente no funciona). Como me ha gustado tu idea tengo la opcion "Reproducir automaticamente siguiente video" = Si
¿q pasara si el primer enlace ha sido eliminado? Que saltara al siguiente, pero como ese servidor no funciona ni el segundo ni ninguno de los siguientes 19 enlaces va a funcionar. 

Yo sugiero q al fallar un enlace pregunte si se quiere reproducir el siguente de la lista o volver al listado.

**Comment by SeiTaN** [comment]
Tb se puede hacer que si hay 5 enlaces que no funcionen vuelva a preguntar.

**Comment by SeiTaN** [comment]
Chapo ya que el desarrollo de autoplay es muy parecido
