### ISSUE TITLE
Series Newpct1

### ISSUE THREAD

**Issue by dabdemon** [tvalacarta/pelisalacarta#4]
Todas las series de Newpct1 estan un capitulo atrasadas. Desde la web parecen estar correctas, pero desde pelisalacarta lo que te devuelve como episode 1 es realmente el 2, etc. Pasa de manera sistematica con todas las series y hace bastante dificil la integración con la biblioteca de kodi.

Por lo demas, un excelentisimo trabajo.
Gracias!!

**Comment by superberny70** [comment]
Esto ya se puede cerrar

**Comment by tvalacarta** [comment]
Perfecto, gracias :)
