### ISSUE TITLE
Patch: core/filetools.py/remove_chars was removing : password separator from url...

### ISSUE THREAD

**Issue by darkermatter** [tvalacarta/pelisalacarta#406]
smb://user:pass@server/share/path gets changed to smb://userpass@server/share/path

This will fix it:

```
def remove_chars(path):
    """
    Elimina cáracteres no permitidos
    @param path: cadena a validar
    @type path: str
    @rtype: str
    @return: devuelve la cadena sin los caracteres no permitidos
    """
    chars = ":*?<>|"
    if path.lower().startswith("smb://"):

        try:
            prefix, path = path.split('@')
            prefix = prefix + "@"
        except:
            prefix = "smb://"
            path = path[6:]
        return prefix + ''.join([c for c in path if c not in chars])

    else:
        if path.find(":\\") == 1:
            unidad = path[0:3]
            path = path[2:]
        else:
            unidad = ""

        return unidad + ''.join([c for c in path if c not in chars])
```

**Comment by darkermatter** [comment]
I have to look into this some more, it stopped working when I selected a different skin!

**Comment by darkermatter** [comment]
I corrected a bad paste, it should work now.

**Comment by SeiTaN** [comment]
@tvalacarta por favor cierra el issue, ya ha incluido @superberny70 el fix

**Comment by darkermatter** [comment]
El fix, no parece correcto...

```
        if re.search(r'(?i)smb://([^\:]+)\:([^\@]+)@', path):
            user, path = path.split("@", 1)
            return "smb://" + user + "@" + ''.join([c for c in path if c not in chars])
```

A mi me parece que devolvera smb://smb://user@path

**Comment by darkermatter** [comment]
He visto el nuevo fix...
 ```
     if path.lower().startswith("smb://"):
          path = path[6:]
          import re
          if re.search(r'(?i)smb://([^\:]+)\:([^\@]+)@', path):
```

Como crees que va a funcionar la expresión regular?

**Comment by superberny70** [comment]
joder tienes razon!!!

**Comment by darkermatter** [comment]
Lo que he puesto arriba es DRY y KISS!

**Comment by superberny70** [comment]
Si menos es mas...
entonces q pasaria con ... smb://user:pass@IP/folder/movies/conectad@s o con smb://IP/folder/DocumentosTV: Conectad@s ?

A ver q te parece:
```
chars = ":*?<>|"
    if path.lower().startswith("smb://"):
        import re
        if re.search(r'(?i)smb://([^\:]+)\:([^\@]+)@', path):
            path = path[6:]
            user, path = path.split("@", 1)
            return "smb://" + user + "@" + ''.join([c for c in path if c not in chars])
        else:
            path = path[6:]
            return "smb://" + ''.join([c for c in path if c not in chars])

    else:
```

**Comment by darkermatter** [comment]
cambia
```
prefix, path = path.split('@')
```
a
```
prefix, path = path.split('@', 1)
```

**Comment by superberny70** [comment]
Se te escapan los dos puntos de la segunda opcion:
smb://IP/folder/DocumentosTV: Conectad@s

**Comment by darkermatter** [comment]
chars = ":*?<>|"
    if path.lower().startswith("smb://"):
        import re
```
    if path.lower().startswith("smb://"):
        import re
KISS?        if re.search(r'(?i)smb://([^\:]+)\:([^\@]+)@', path):
            path = path[6:]
            user, path = path.split("@", 1)
DRY?            return "smb://" + user + "@" + ''.join([c for c in path if c not in chars])
        else:
            path = path[6:]
 DRY?           return "smb://" + ''.join([c for c in path if c not in chars])
```

**Comment by darkermatter** [comment]
no, por eso tienes ```chars = ":*?<>|"```

**Comment by darkermatter** [comment]
a, ya lo veo

**Comment by superberny70** [comment]
a ti los dos puntos y a mi se me escapa KISS y DRY
Q significa eso: ¿menos es mas? no entiendo cuando lo pones insertado en el codigo

**Comment by superberny70** [comment]
vale ya lo he visto: [KISS y DRY](http://www.ivan-garcia.com/blog/principios-de-diseno-de-software-dry-kiss-y-yagni/)

**Comment by darkermatter** [comment]
KISS = keep it simple, stupid https://es.wikipedia.org/wiki/Principio_KISS
DRY = don't repeat yourself https://es.wikipedia.org/wiki/No_te_repitas

**Comment by superberny70** [comment]
La expresion regular controla q la @ pertenezca a las credenciales, no me parece KISS
y respecto a lo q consideras DRY, creo q mas bien se refiere a procesos no a una sola linea de codigo, q ademas no es exactamente igual.
Pero bueno, son interpretaciones libres.
Entonces q te parece el codigo q te he puesto ¿soluciona el problema?

**Comment by darkermatter** [comment]
Yo creo que si soluciona el problema :-)

**Comment by superberny70** [comment]
Ok actualizo PR #418

**Comment by darkermatter** [comment]
Hola de nuevo @superberny70!

Me han dejado en paz por fin y he tomado un café! :-)

Que te parece esto:

```
def remove_chars(path):
    """
    Elimina cáracteres no permitidos
    @param path: cadena a validar
    @type path: str
    @rtype: str
    @return: devuelve la cadena sin los caracteres no permitidos
    """
    chars = ":*?<>|"
    if path.lower().startswith("smb://"):
        import re
        parts = re.split(r'smb://(.+?)/(.+)', t)[1:3]
        return "smb://" + parts[0] + "/" + ''.join([c for c in parts[1] if c not in chars])

    else:
        if path.find(":\\") == 1:
            unidad = path[0:3]
            path = path[2:]
        else:
            unidad = ""

        return unidad + ''.join([c for c in path if c not in chars])
```
Pruebas:
```
tests = ['smb://username@IP/path2/path3', 'smb://username:password@IP/path2/path3', 'smb://IP/folder/DocumentosTV: Conectad@s', 'smb://IP/path2/path3']
for t in tests:
    print t + ' -> ' + remove_chars(t)
```

**Comment by CmosGit** [comment]
Muy buena solución @darkermatter, he probado con varios tipos de rutas smb y funciona perfecto, la que yo utilizaba tenía más código del necesario xD

**Comment by superberny70** [comment]
Ok subo los cambios propuestos por @darkermatter mucho mas KISS (y a mi q esto me suena muy Heavy!!!)

**Comment by tvalacarta** [comment]
BESOS en SECO, sí... heavy total :)

Los informáticos estamos locos ja ja ja

**Comment by divadres** [comment]
Un poco tarde quiza... pero que pasaria si el nombre de usuario o contraseña samba tiene por ejemplo... una @ no es por nada pero yo suelo incluir caracteres de ese tipo en mis contraseñas... por eso de q sean seguras.. jajaja... no se exactamente como funciona esto de las url smb:// pero quiza tenga que hacerle un urlencode al user y password o algo asi no??

**Comment by darkermatter** [comment]
Mientras no contiene ```:``` no pasa nada:

```
smb://username@IP/path2/path3 -> smb://username@IP/path2/path3
smb://username:password@IP/path2/path3 -> smb://username:password@IP/path2/path3
smb://username:p/ssword@IP/path2/path3 -> smb://username:p/ssword@IP/path2/path3
Cambiado!
smb://username:p/ssw:rd@IP/path2/path3 -> smb://username:p/sswrd@IP/path2/path3
smb://username:p@ssword@IP/path2/path3 -> smb://username:p@ssword@IP/path2/path3
smb://username:p:ssw/rd@IP/path2/path3 -> smb://username:p:ssw/rd@IP/path2/path3
Cambiado!
smb://IP/folder/DocumentosTV: Conectad@s -> smb://IP/folder/DocumentosTV Conectad@s
smb://IP/path2/path3 -> smb://IP/path2/path3
```

**Comment by darkermatter** [comment]
a, solo después de una ```/```

**Comment by divadres** [comment]
No me refiero a si la conversión la haría bien o no, me refiero a si funcionaria bien en libsmb...

**Comment by darkermatter** [comment]
He encontrado este código: https://github.com/notspiff/vfs.smb/blob/master/src/SMB.cpp#L225

Parece que si, hay que hacerles un urlencode a ambos.
