### ISSUE TITLE
Error inesperado en el canal buscador

### ISSUE THREAD

**Issue by danifr** [tvalacarta/pelisalacarta#410]
Muy buenas,

cada vez que intento utilizar el buscador me sale el siguiente mensaje:
 ```
Error inesperado en el canal buscador
Esto suele pasar cuando hay un fallo de conexión, cuando la web del canal ha cambiado su estructura, o simplemente porque hay algo mal en pelisalacarta.
Para saber más detalles, consulta el log.
```

Revisando /var/lib/kodi/.kodi/temp/kodi.log encontré lo siguiente:

```
20:21:22 T:1948483584   ERROR: GetDirectory - Error getting plugin://plugin.video.pelisalacarta/?eyJpc1BsYXlhYmxlIjogImZhbHNlIiwgImluZm9MYWJlbHMiOiB7fSwgImFjdGlvbiI6ICJtYWlubGlzdCIsICJ2aWV3bW9kZSI6ICJsaXN0IiwgImZ1bGx0aXRsZSI6ICJHbG9iYWwgc2VhcmNoIiwgImNhdGVnb3J5IjogIiIsICJ0aXRsZSI6ICJHbG9iYWwgc2VhcmNoIiwgImZhbmFydCI6ICIvdmFyL2xpYi9rb2RpLy5rb2RpL2FkZG9ucy9wbHVnaW4udmlkZW8ucGVsaXNhbGFjYXJ0YS9mYW5hcnQuanBnIiwgImNvbnRleHQiOiAiIiwgInRvdGFsSXRlbXMiOiA4LCAidGh1bWJuYWlsIjogImh0dHA6Ly9tZWRpYS50dmFsYWNhcnRhLmluZm8vcGVsaXNhbGFjYXJ0YS9zcXVhcmVzL3RodW1iX2J1c2Nhci5wbmciLCAiY2hhbm5lbCI6ICJidXNjYWRvciJ9
20:21:22 T:1948483584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pelisalacarta/?eyJpc1BsYXlhYmxlIjogImZhbHNlIiwgImluZm9MYWJlbHMiOiB7fSwgImFjdGlvbiI6ICJtYWlubGlzdCIsICJ2aWV3bW9kZSI6ICJsaXN0IiwgImZ1bGx0aXRsZSI6ICJHbG9iYWwgc2VhcmNoIiwgImNhdGVnb3J5IjogIiIsICJ0aXRsZSI6ICJHbG9iYWwgc2VhcmNoIiwgImZhbmFydCI6ICIvdmFyL2xpYi9rb2RpLy5rb2RpL2FkZG9ucy9wbHVnaW4udmlkZW8ucGVsaXNhbGFjYXJ0YS9mYW5hcnQuanBnIiwgImNvbnRleHQiOiAiIiwgInRvdGFsSXRlbXMiOiA4LCAidGh1bWJuYWlsIjogImh0dHA6Ly9tZWRpYS50dmFsYWNhcnRhLmluZm8vcGVsaXNhbGFjYXJ0YS9zcXVhcmVzL3RodW1iX2J1c2Nhci5wbmciLCAiY2hhbm5lbCI6ICJidXNjYWRvciJ9) failed
```

Sistema Operativo: Archlinux (ARM) sobre RP2
KODI: 16.1 Jarvis
Pelisalacarta: 4.2.1

He probado a reinstalar y también esta solución propuesta por Cmos (http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7707#p32646), pero sin suerte.

Alguna idea?
Gracias.

**Comment by SeiTaN** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7977

**Comment by danifr** [comment]
Gracias funciona perfectamente.

Aún así, puedo reproducir el problema simplemente buscando una película que tenga un acento en el título.
Al darle a enviar, el contenido del fichero se elimina y tengo que recrearlo con el contenido mostrado en el enlace que me pones.

¿Hay algún fix pensado para éste problema? Sin haber mirado el código, parece un sencillo problema de encoding.

**Comment by SeiTaN** [comment]
He buscado "aída" y no me ha dado ningún problema (windows 10 kodi krypton beta 3), yo busco en 18 canales, puede que el problema que te pase a ti sea por eso, que falle algún canal y cuelge el addon.

Eres bienvenido a buscar una solución, para eso está en github 😉 

P.D: en tu log no se ve nada, tienes que marcar la opción "log detallado" dentro del plugin para que se muestre las trazas correctamente.

**Comment by danifr** [comment]
Probando la búsqueda:
1) mmmmmmmmmmmmmmmmmmm... --> **OK**
2) avión --> **ROMPE**

Log:
```
21:56:20 T:1717892000  NOTICE: pelisalacarta.core.jsontools.dump_json Probando simplejson incluido en el interprete
21:56:20 T:1717892000  NOTICE: pelisalacarta.core.jsontools.dump_json -> u'{\n    "settings": {\n        "multithread": true,\n        "result_mode": 0,\n        "saved_searches_limit": 0,\n        "saved_searches_list": [\n            "avi\xf3n",\n            "mmmmmmmmmmmmmmmmmmmmmm"\n        ]\n    }\n}'
21:56:20 T:1717892000  NOTICE: ######## ERROR #########
21:56:20 T:1717892000  NOTICE:     [launcher.run] pelisalacarta.platformcode.launcher Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 268, in run
                                                itemlist = channel.search(item,tecleado)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pelisalacarta/channels/buscador.py", line 152, in search
                                                save_search(tecleado)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pelisalacarta/channels/buscador.py", line 343, in save_search
                                                config.set_setting("saved_searches_list", saved_searches_list[:saved_searches_limit], "buscador")
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pelisalacarta/core/config.py", line 138, in set_setting
                                                return channeltools.set_channel_setting(name, value, channel)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pelisalacarta/core/channeltools.py", line 247, in set_channel_setting
                                                open(file_settings, "w").write(jsontools.dump_json(dict_file))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 159: ordinal not in range(128)
```

Reproducido en dos sistemas distintos (ambos archlinux, con Kodi instalado), aunque los dos en inglés.
Falla al escribir el fichero en disco, estoy preparando un mini parche para solucionarlo.

**Comment by SeiTaN** [comment]
@danifr puedes probar esta versión? http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7958

En la betai se toca el tema del unicode, y lo mismo funciona y no hace falta que saques el parche.

**Comment by danifr** [comment]
No puedo instalar la beta. Parece que kodi no puede descomprimr el ZIP.
Lo único que hice fue cambiarle el nombre para quitarle espacios.

$ tail -f /var/lib/kodi/.kodi/temp/kodi.log:
```23:14:06 T:1948483584   ERROR: GetDirectory - Error getting zip://%2fvar%2flib%2fkodi%2fplugins%2fpelisalacarta-kodi-4.1.4b.zip/```

Los permisos y el propietario parece que están bien (aunque es un poco sospechoso que la beta pese tan poco....):
```
[root@archberry2 plugins]# ll
total 19820
drwxr-xr-x 2 kodi kodi     4096 Oct 17 23:06 .
drwxr-xr-x 7 kodi kodi     4096 Jul 23 00:35 ..
...
-rw-r--r-- 1 kodi kodi    48833 Oct 17 23:04 pelisalacarta-kodi-4.1.4b.zip
-rw-r--r-- 1 kodi kodi  4156203 Jul 10 01:18 pelisalacarta-kodi-jarvis-4.1.1.zip
....
```
Voy a abrir la PR, por si a alguien le está pasando lo mismo que a mí y quiere una solución para YA.
Si la beta efectivamente soluciona los problemas, cerramos la PR y listo, si no podemos intentar incluirlo en master.

**Comment by SeiTaN** [comment]
@tvalacarta esto tb se puede cerrar 😉
