### ISSUE TITLE
No se puede visualizar contenido de Animeflv.ME desde Kodi

### ISSUE THREAD

**Issue by vnr00t** [tvalacarta/pelisalacarta#439]
Hola,

Desde hace un par de días no me es posible visualizar capítulos de Animeflv.ME desde Kodi (v 15.2) Pasa con todas las series que he probado, Naruto, One Piece, etc, puedes buscar por populares y demás incluso salen la lista de episodios pero ya desde ahí no encuentra nada.

Si resulta necesario añadir algún log sin problemas, he estado buscando en /recalbox/share/system/.kodi/addons/plugin.video.pelisalacarta pero no he encontrado nada.

Saludos

**Comment by Gongui** [comment]
El log de kodi se almacena en ~/.kodi/temp/kodi.log
También note que no funciona animeflv.me y la actualización de la biblioteca toma años.
Ahora le pego una mirada.

**Comment by SeiTaN** [comment]
Esto está arreglado, se puede cerrar.
