### ISSUE TITLE
Logos para canales

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#44]
He visto que faltan algunos logos en los canales y he puesto unos cuantos nuevos en la carpeta resources/images/squares pero no se ven.
¿Los logos se leen via web o hay que dejarlos en alguna otra carpeta?
En principio por el código me parece que se leen via web, pero no he encontrado exactamente dónde se leen.
Si no existe ya, se podría leer primero el fichero local y si no existe ir a la web o viceversa

**Comment by superberny70** [comment]
Actualmente el logo puede estar en local o online.
Pero hay q definirlos en el channelselector.py

Yo personalmente recomiendo incluir el enlace como variable dentro del canal o en el XML si se utiliza el nuevo formato.
Mi versión 3.9x en github incluye un channelselector dinámico q lee ese parametro del canal. Si abrís los canales podréis ver el enlace q utilizó para cada canal.

**Comment by ChopChopKodi** [comment]
Por lo que he analizado, si en channelselector.py no existe la clave *thumb* en la estructura del canal se usa el método  *get_thumbnail_path* para sacar la ruta a la web *media.tvalacarta.info*
No me parece cómodo definir los thumbnails en cada canal de la lista de canales cuando se pueden leer en local nombrándolos con el nombre del canal en una estructura de carpetas locales

Lo lógico sería usar *get_thumbnail_path* para detectar si existe un thumnail local con el nombre del canal y luego, o bien tirar de la clave *thumb* o de la web *media.tvalacarta.info* como último recurso.

No sé si preferís que meta mano a *get_thumbnail_path* para probar o vais a poner la estructura dinámica de tu repo pronto.
En mi opinión lo mejor sería la estructura dinámica y definir cada "override" de los thumbnails locales en una propiedad de cada canal.

Si eso cuando pueda hago un pull request con mis iconos y decidís que hacer con ellos, porque algunos los he remaquetado para que queden algo mejor que los que he encontrado en las webs.

**Comment by r0balo** [comment]
Puedes probar lo siguiente en el channelselector.

[Líneas 140-141](https://github.com/tvalacarta/pelisalacarta/blob/master/python/main-classic/channelselector.py#L140-L141)
```
                if thumbnail == "":
                    thumbnail=urlparse.urljoin(get_thumbnail_path(),channel.channel+".png")
```
por
```
                if thumbnail == "":
                    LOCAL_PATH = os.path.join(config.get_runtime_path(), "resources/images/") + \
                                 get_thumbnail_path().split('/')[4] + "/"
                    thumbnail = os.path.join(LOCAL_PATH, channel.channel+".png")
                    if not os.path.isfile(thumbnail):
                        thumbnail = urlparse.urljoin(get_thumbnail_path(),channel.channel+".png")
```
[Líneas 185-186](https://github.com/tvalacarta/pelisalacarta/blob/master/python/main-classic/channelselector.py#L185-L186)
```
            if channel.thumbnail == "":
                channel.thumbnail = urlparse.urljoin(get_thumbnail_path(preferred_thumb),channel.channel+".png")
```
por
```
            if channel.thumbnail == "":
                LOCAL_PATH = os.path.join(config.get_runtime_path(), "resources/images/") + \
                             get_thumbnail_path(preferred_thumb).split('/')[4] + "/"
                channel.thumbnail = os.path.join(LOCAL_PATH, channel.channel+".png")
                if not os.path.isfile(channel.thumbnail):
                    channel.thumbnail = urlparse.urljoin(get_thumbnail_path(preferred_thumb),channel.channel+".png")
```

**Comment by tvalacarta** [comment]
En cuanto pongamos el tema de json a funcionar, la URL irá en todos los json para hacerlo más claro.

Es más trabajo al principio, pero luego queda más claro.

**Comment by SeiTaN80** [comment]
@tvalacarta ¿esto se puede cerrar ya?
