### ISSUE TITLE
Streamplay no funciona KODI

### ISSUE THREAD

**Issue by esfort** [tvalacarta/pelisalacarta#446]
Cada vez que intentas visualizar por streamplay dice que el archivo no existe o ha sido borrado.
Mas concretamente en seriesdanko, probado desde ordenador y el enlace funciona.

**Comment by divadres** [comment]
Si, es ciero, lo tengo arreglado, pronto lo subire junto con otros...

**Comment by esfort** [comment]
Muchas gracias, que rapidez!

**Comment by SeiTaN** [comment]
Esto está arreglado, se puede cerrar.
