### ISSUE TITLE
Mejorar las opciones que se muestran por el menú contextual

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#448]
![image](https://cloud.githubusercontent.com/assets/11775029/19975496/7ef486da-a1ec-11e6-8f5e-3f8ad128d702.png)

No debería aparecer la opción "Descargar película", en opciones del menú o items que no sean películas.

**Comment by superberny70** [comment]
Q tiene esa opcion en ítem.contentType?

**Comment by SeiTaN** [comment]
Que yo sepa no tiene, se hereda.

> 14:55:25 T:14192  NOTICE: pelisalacarta.core.jsontools Probando json incluido en el interprete
> 14:55:25 T:14192  NOTICE: pelisalacarta.platformcode.launcher run
> 14:55:25 T:14192  NOTICE: pelisalacarta.platformcode.launcher action= 'mainlist', category= 'Animeflv.ME', channel= 'animeflv_me', contentType= 'movie', fanart= '', infoLabels= {'mediatype': 'movie'}, language= 'es', thumbnail= 'http://i.imgur.com/x9AdvBx.png', title= 'Animeflv.ME', totalItems= 0, viewmode= 'list'
> 14:55:25 T:14192  NOTICE: pelisalacarta.core.channeltools is_adult channel_name=animeflv_me
> 14:55:25 T:14192  NOTICE: pelisalacarta.core.channeltools get_channel_parameters animeflv_me -> {'bannermenu': 'http://i.imgur.com/dTZwCPq.png', 'language': 'es', 'title': 'Animeflv.ME', 'fanart': '', 'categories': ['anime'], 'adult': 'false', 'active': 'true', 'thumbnail': 'http://i.imgur.com/x9AdvBx.png', 'channel': 'animeflv_me', 'include_in_global_search': ''}
> 14:55:25 T:14192  NOTICE: pelisalacarta.platformcode.launcher channel_file=C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\channels\animeflv_me.py
> 14:55:25 T:14192  NOTICE: pelisalacarta.platformcode.launcher running channel channels.animeflv_me C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\channels\animeflv_me.pyo
> 14:55:25 T:14192  NOTICE: pelisalacarta.platformcode.launcher executing channel 'mainlist' method
> 14:55:25 T:14192  NOTICE: pelisalacarta.channels.animeflv_me mainlist

La opción de descargar pelicula sale desde el principio.

![image](https://cloud.githubusercontent.com/assets/11775029/20007991/07d8eb78-a29f-11e6-82b9-75d802f7d718.png)

Estoy hablando del contenido actualizado de la rama **developer** para que quede claro por si acaso 😉

**Comment by CmosGit** [comment]
Partiendo de que esa opción del menú se añade cuando el item.contentType es igual a "movie", creo que se debe a que por defecto el valor de item.infoLabels["mediatype"] es "movie" como se ve en esta parte del código de la clase Item (linea 65):

```
        elif key == 'mediatype':
            # "movie", "tvshow", "season", "episode"
            if 'tvshowtitle' in super(InfoLabels,self).keys():
                if 'episode' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('episode') !="":
                    return 'episode'

                if 'episodeName' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('episodeName') !="":
                    return 'episode'

                if 'season' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('season') !="":
                    return 'season'
                else:
                    return 'tvshow'

            else:
                    return 'movie'
```

Y el item.contentType  a su vez, si no existe, devuelve el valor de mediatype, línea 221:

```
            elif name == "contentType":
                    return self.__dict__["infoLabels"]["mediatype"]
```

Total, que tal y como está, cualquier item va a tener esa opción del menú xD. Si no me equivoco hasta este commit eso no ocurría porque solo se añadía en los item con action "detail" o "findvideos", pero ahora se añade en todos: https://github.com/tvalacarta/pelisalacarta/commit/3d7bc3d1f949296a37e053810e778194b7bf8e24#diff-290ec91bd7b2f42791ed49d771a81f93

**Comment by divadres** [comment]
He tocado yo esa parte in poco... para el tema de las descargas... y soluciono ese tema... si os parece cuando tenga un rato os lo enseño...


-------- Mensaje original --------
De: CmosGit <notifications@github.com>
Fecha: 4/11/16 19:34 (GMT+01:00)
Para: tvalacarta/pelisalacarta <pelisalacarta@noreply.github.com>
Asunto: Re: [tvalacarta/pelisalacarta] Mejorar las opciones que se muestran por el menú contextual (#448)


Partiendo de que esa opción del menú se añade cuando el item.contentType es igual a "movie", creo que se debe a que por defecto el valor de item.infoLabels["mediatype"] es "movie" como se ve en esta parte del código de la clase Item (linea 65):

        elif key == 'mediatype':
            # "movie", "tvshow", "season", "episode"
            if 'tvshowtitle' in super(InfoLabels,self).keys():
                if 'episode' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('episode') !="":
                    return 'episode'

                if 'episodeName' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('episodeName') !="":
                    return 'episode'

                if 'season' in super(InfoLabels,self).keys() and super(InfoLabels,self).__getitem__('season') !="":
                    return 'season'
                else:
                    return 'tvshow'

            else:
                    return 'movie'


Y el item.contentType a su vez, si no existe, devuelve el valor de mediatype, línea 221:

            elif name == "contentType":
                    return self.__dict__["infoLabels"]["mediatype"]


Total, que tal y como está, cualquier item va a tener esa opción del menú xD. Si no me equivoco hasta este commit eso no ocurría porque solo se añadía en los item con action "detail" o "findvideos", pero ahora se añade en todos: 3d7bc3d#diff-290ec91bd7b2f42791ed49d771a81f93<https://github.com/tvalacarta/pelisalacarta/commit/3d7bc3d1f949296a37e053810e778194b7bf8e24#diff-290ec91bd7b2f42791ed49d771a81f93>

-

**Comment by CmosGit** [comment]
@divadres pues sí tú ya tenías localizado el fallo entonces mi "investigación" y pertinente tochaco no ha valido para mucho xDD

**Comment by SeiTaN** [comment]
@CmosGit si ha válido hombre, yo tenía el palpito que era algo de eso y lo has confirmado 😄
