### ISSUE TITLE
Error al entrar en Canales en Android con Jarvis 16.1

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#456]
He bajado la rama develop para probar los últimos cambios y nada más entrar a Canales me salta un error en https://github.com/tvalacarta/pelisalacarta/blob/59ff2a1ab0de9017cb2d897fabc2e7de415efb3a/python/main-classic/platformcode/launcher.py#L172 diciendo que channel es None.
Si quito esa línea me salta otro error en https://github.com/tvalacarta/pelisalacarta/blob/59ff2a1ab0de9017cb2d897fabc2e7de415efb3a/python/main-classic/platformcode/launcher.py#L251 diciendo _AttributeError: 'module' object has no attribute 'channeltypes'_

Trasteando el código veo que la variable _channel_file_ tiene el valor de la carpeta de canales y busca el fichero _channelselector.py_ que no es un canal y no está en esa carpeta.
La última referencia que veo al nombre channelselector como canal es este cambio de @superberny70 https://github.com/tvalacarta/pelisalacarta/commit/9f186054caf82c4ae1572df31d282f9fa7fac334#diff-1dac521a4cfd9405a5f816461fc072d6L67
pero no entiendo bien el código como para ver si hay algo que esté mal.

El caso es que en xbmc 13.2 Gotham en MacosX me funciona bien y he probado a borrar toda referencia al plugin pelisalacarta por si me estaba cogiendo alguna configuración vieja pero me salta el mismo error.

**Comment by kerenmac** [comment]
A mi me paso eso hace un par de semanas, tanto en Android como iOS, pero con el ultimo PR no me sucede ahora ni desde hace un par de semanas. Prueba con el ultimo PR, no deberías tener problemas.
Cuando esto sucedió investigue un poco y resulta que el "action" de channelselector era "channeltypes" y no "getchanneltypes" (el correcto). No entendía como podía estar sucediendo eso sino existía "channeltypes" en ningún lado del código, así que tras mil intentos se soluciono simplemente borrando todos los archivos del addon y reemplazándolos por los del ultimo PR que existía en la rama de desarrollo.
Un saludo.

**Comment by ChopChopKodi** [comment]
En teoría es lo que estoy haciendo. He hecho  una copia local  de la rama develop con
git checkout --track upstream/develop 
y luego con ant genero un .zip para Jarvis que luego instalo en el Android.

Para el Android

_ant clean copy-kodi -Dtarget_platform_folder=kodi-16-jarvis -Dtarget_platform_name=kodi-jarvis_

y en el Macos

_ant clean copy-kodi -Dtarget_platform_folder=xbmc-13-gotham -Dtarget_platform_name=xbmc-gotham_

En el log me sale el action con nombre "channeltypes" que dices y en el xbmc sale getchanneltypes, así que parece que puede ser algún problema de cómo se genera el .zip.
En principio creo que para Gotham y Jarvis es la misma versión, pero por lo menos tengo algo por donde tirar.
Gracias por confirmar.

**Comment by ChopChopKodi** [comment]
En principio los zips son iguales y lo único que cambia es la variable  PLATFORM_NAME.
En el Macos y el Android la versión de python parece que es la misma, la 2.6

He probado a apagar quitando el cable de corriente, a borrar los archivos .pyo por si se hubieran quedado cacheados, pero nada.

He instalado la versión para xbmc en el Android y funciona ¿QUÉ?. Desinstalo el plugin, borro los zips del Android por si acaso, Subo otro zip para Jarvis, instalo y TAMBIÉN FUNCIONA.

¿Qué cachés usa Kodi, Android o el que sea que sobreviven a una desinstalación del plugin y un apagado quitando el cable de la corriente?

Para que luego digan que no existen los duendes de la informática.
