### ISSUE TITLE
4.2.0 beta 1 error con caracteres no ASCII

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#474]
Bueno ahora que está todo junto he probado a trastear un poco y el fallo del unicode sigue estando.

windows 10, kodi 17 beta 6, canal animeflv.me, serie "the idolm@ster"

> 14:26:37.550 T:7632  NOTICE: pelisalacarta.core.library [save_library_tvshow] Creando tvshow.nfo: C:\Users\SeiTaN\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.pelisalacarta\library\SERIES\アイドルマスター [tt2649756]\tvshow.nfo
> 14:26:37.553 T:7632  NOTICE: ######## ERROR #########
> 14:26:37.553 T:7632  NOTICE:     [pelisalacarta.core.filetools.write] ERROR al guardar el archivo: C:\Users\SeiTaN\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.pelisalacarta\library\SERIES\???????? [tt2649756]\tvshow.nfo
> 14:26:37.556 T:7632  NOTICE: ######## ERROR #########
> 14:26:37.556 T:7632  NOTICE:     [pelisalacarta.core.filetools.write] Traceback (most recent call last):
>                                               File "C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\filetools.py", line 161, in write
>                                                 f = open(path, "wb")
>                                             IOError: [Errno 22] invalid mode ('wb') or filename: 'C:\\Users\\SeiTaN\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pelisalacarta\\library\\SERIES\\???????? [tt2649756]\\tvshow.nfo'
> 14:26:37.558 T:7632  NOTICE: pelisalacarta.core.library.save_library_episodes
> 14:26:37.560 T:7632  NOTICE: ######## ERROR #########
> 14:26:37.560 T:7632  NOTICE:     [pelisalacarta.platformcode.launcher.run] pelisalacarta.platformcode.launcher Traceback (most recent call last):
>                                               File "C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\platformcode\launcher.py", line 228, in run
>                                                 library.add_serie_to_library(item, channel)
>                                               File "C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\library.py", line 627, in add_serie_to_library
>                                                 insertados, sobreescritos, fallidos = save_library_tvshow(item, itemlist)
>                                               File "C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\library.py", line 351, in save_library_tvshow
>                                                 insertados, sobreescritos, fallidos = save_library_episodes(path, episodelist, item)
>                                               File "C:\Users\SeiTaN\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\library.py", line 391, in save_library_episodes
>                                                 raiz, carpetas_series, ficheros = filetools.walk(path).next()
>                                             StopIteration

**Comment by divadres** [comment]
Esto es un poco mas complicado que con las tildes...

En samba funciona bien, y sospecho que en sistemas basados en Linux también (aunque no lo he probado)

La única manera de solucionar eso (en Windows que es donde falla) es trabajar con Unicode en vez de "mbcs", lo he probado y parece funcionar (falta probarlo mas a fondo) pero entonces el problema es que en la biblioteca el nombre no se puede leer (salen caracteres raros)

No seria mas lógico usar el nombre de la serie en ingles infoLabels["title"] en vez del nombre original infoLabels["originaltitle"] de este modo ya se podría leer bien y también la carpeta se crearía bien que (a menos que sepas leer chino) tampoco podrías saber que pone

**Comment by SeiTaN** [comment]
Pues si es cosa de windows con mbcs, para que funcione bien al crear el nombre no se tiene que hacer el encode, cosa totalmente distinta a lo que se hace con utf8, que se tiene que hacer el encode y luego pasar a bytes.

Estoy mirando de que el caso que de fallo al crear el directorio cambia el "ignore" por "replace", a ver si con esto se soluciona el problema

**Comment by divadres** [comment]
Si se pasa la ruta en Unicode SI que funciona bien (lo he probado y funciona)

**Comment by SeiTaN** [comment]
A mi me da igual usar una cosa u otra, era por respetar lo que se está usando actualmente, evidentemente en temas de animes es mejor usar el titulo en español o en su caso en inglés.

Siguiendo tu razonamiento tengo una duda ¿puede existir el caso que la serie no tenga titulo en inglés? Es decir use el titulo original, no es encontraríamos en la misma situación y no digo caracteres chinos como dices, ponle cirilico o lo que sea.

**Comment by divadres** [comment]
No se si todas tienen o no titulo en ingles (imagino que si) pero el problema es que en la biblioteca tampoco se lee el titulo... mira, voy a subir un PR ahora, cambiando el encoding a Unicode con esto ya se crean las carpetas con nombres en chino pero veras como se ve en la biblioteca (y esto no es problema de filetools ni del encoding)

**Comment by SeiTaN** [comment]
cierro esto, que ya está solucionado 😄
