### ISSUE TITLE
¿Se ha liado parda con un commit?

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#486]
Hago un pull y veo que se me llena el main de archivos que no deberían estar ahí.

Concretamente han aparecido en este commit: https://github.com/tvalacarta/pelisalacarta/commit/74352416c1b3378bd279373d7e49ffeb1943a793

En el "home" del main-classic (es decir, en el home del addon) han aparecido archivos de canales (xml, py)

**Comment by SeiTaN** [comment]
jajajaj precisamente estaba mirando porque los canales de neno no estaban, los muevo y hago el commit de nuevo, gracias por avisar.
