### ISSUE TITLE
Mejoras para el buscador global tras fix buscador global

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#512]
Mejoras/bugs:

- [x] qseries, no tenía búsqueda, **se quita del xml, pero sigue apareciendo en la lista de canales para buscador global.**
- [x] seodiv, no tenía búsqueda, **se quita del xml, pero sigue apareciendo en la lista de canales para buscador global.**
- [x] buscador no finaliza cuando se pulsa sobre cancelar.
- [x] cuando se pulsa el botón "por defecto" no se marcan los canales que estaban por defecto.

**Comment by superberny70** [comment]
Para q un canal no aparezca en el cuadro de seleccion del buscador global lo que hay q hacer es incluir en su xml la etiqueta `<include_in_global_search>disabled</include_in_global_search>`
El boton 'por defecto' lo q hace es fijar los canales tal y como estaban cuando abriste el cuadro de dialogo. 
El tema del boton 'cancelar' es mas complejo, he intentado mejorarlo, pero hay casos en q todo kodi se cuelga por culpa de una busqueda en un canal (aunq sea en un hilo independiente) y asi es imposible cancelarlo.
Lo subire todo como una PR en un rato

**Comment by SeiTaN** [comment]
> El boton 'por defecto' lo q hace es fijar los canales tal y como estaban cuando abriste el cuadro de dialogo.

Pues no le veo sentido, yo creo que por defecto debería cargar los valores que hay en el fichero xml de cada canal. Si lo que hace actualmente ese botón es eso ¿Qué diferencia hay con que le des al botón cancelar para no guardar los cambios? ¿Qué no te cierra la ventana y te vuelve a mostrar como estaba?

**Comment by superberny70** [comment]
Bueno, se podria hacer eso que dices, pero habria q modificar channelstools.get_channel_parameters para q devuelva el valor por defecto de "include_in_global_search". Y quien elige si un canal debe tener por defecto la busqueda global activa o no? Lo normal es q todo creador de canales quiera fijar por defecto su canal para q entre en el buscador global si es q esta adaptado, asi q tampoco le veia mucho sentido a eso.
Por eso implemente la funcionalidad q ya he explicado. Si q es posible q sea redundante con respecto a cancelar, asi q si prefieres podemos ocultar el boton 'Por defecto' y todos contentos.

Para ocultarlo solo hay q añadir el atributo custom_button={"visible":False} en la llamada a platformtools.show_channel_settings dentro de buscador.settingCanal.
