### ISSUE TITLE
SOLUCIÓN Yaske.ro

### ISSUE THREAD

**Issue by eniebla** [tvalacarta/pelisalacarta#514]
**Necesita el _anti_cloudflare_**
**En**
`HEADER = [
    ["Host","www.yaske.ro"],
    ["Connection","keep-alive"],
    ["Accept","text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],
    ["User-Agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"],
    ["Referer","http://www.yaske.ro/"],
    ["Accept-Encoding","gzip,deflate"],
    ["Accept-Language","es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3"],
    ["Cache-Control","max-age=0"]
]`
**Cambiar por:**
`CHANNEL_HOST = 'http://www.yaske.ro/'`
`HEADER = [
    ['User-Agent', 'Mozilla/5.0'],
    ['Accept-Encoding', 'gzip, deflate'],
    ['Referer', CHANNEL_HOST],
    ['Connection', 'keep-alive']
]`

**y en todas las instancias de:**
`data = scrapertools.cache_page(item.url,headers=HEADER)`
**cambiar por**
`data = scrapertools.anti_cloudflare(item.url,headers=HEADER, host=CHANNEL_HOST)`

**_Con eso ya funciona_**

**NOTA:**
También propongo en `def menu_buscar_contenido`
**Cambiar**
`url = "http://www.yaske.ro/es/peliculas/custom/?"+item.extra+"="+scrapedurl`
**Por**
`        if item.extra == 'gender':`
`            url = "http://www.yaske.ro/genero/"+scrapedurl`
`        else:`
`            url = "http://www.yaske.ro/custom/?"+item.extra+"="+scrapedurl`
eso funciona mejor con la categoría géneros.

Saludos, y gracias por mantener el plugin, lo uso bastante.

**Comment by r0balo** [comment]
Hola @eniebla 
Lo que has propuesto a mí no me llega a funcionar, he usado el yaske.py del PR y siempre elimino las cookies del .dat antes de probar.

La base que indicas para el headers es correcta pero no indicas el motivo aparente del lado del servidor que nos hace usar un formato diferente al usual.

Por lo que he podido pobrar sólo necesitamos para arrancarle la cookie `refresh`, `cf_clearance` y conseguir el html de datos correcto es.
Primero  `[['Referer', ''], ['User-Agent', radom_string[:length]] ]` para conseguir `refresh` y `cf_clearance`
y después, `[['Referer', ''], ['User-Agent', radom_string[:length]], ['Cookie', cookie ]`.

El anti_cloudflare que me funciona es
```
def anti_cloudflare(url):
    import random, string
    agent = ''.join(random.choice(string.lowercase) for i in range(6))

    headers = [
        ['Referer',''],
        ['User-Agent',agent],
    ]

    try:
        resp_headers = scrapertools.get_headers_from_response(url, headers=headers)
        resp_headers = dict(resp_headers)

    except urllib2.HTTPError, e:
        resp_headers = e.headers

    if 'refresh' in resp_headers:
        time.sleep(int(resp_headers['refresh'][:1]))

        _resp_headers = dict(scrapertools.get_headers_from_response(host + resp_headers['refresh'][7:], headers=headers))

        headers.append(['Cookie',_resp_headers['set-cookie']])

    return scrapertools.cache_page(url, headers=headers)
```
Este `anti_cloudflare` tiene un problema. Al cambiar el `User-Agent` en cada llamada, siempre se ejecuta la función completa uanque funciona pero tienes que esperar los 8 segundo que tienen establecidos.
Para evitar el engorro me invento un `User_Agent` :)
```
    #import random, string
    #agent = ''.join(random.choice(string.lowercase) for i in range(6))
    agent = "robalo"
```
