### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#525]
Me he dado cuenta de q el numero de version no sale en ningun sitio dentro del plugin. 
Ahora si van a coexistir varias versiones betas y estables,  creo q deberia haber algun lugar fácilmente accesible desde el q te diga cual es tu versión actual,  ¿pero donde?

**Comment by sergigonza** [comment]
Hola!
Yo lo he probado tanto en windows y en Linux y aparece la versión si entras en vídeos>addons y seleccionas pelisalacarta, te aparece debajo del logo. 

![image](https://cloud.githubusercontent.com/assets/22079247/21592121/0819b6f4-d10b-11e6-9119-e8c819043ad2.png)

Yo creo que con eso si bastaría no?

**Comment by neno1978** [comment]
Correcto, yo x lo menos, siempre la he visto ahí 👍👍

**Comment by kerenmac** [comment]
Una observacion relacionada con la version: Al bajar los últimos cambios de git el archivo settings.xml de addon_data sigue con la version 4201 aunque el settings.xml del addon indica la 4202 (asi que salta la notificación de la actualización), y mirando un poco por el código he visto que el settings.xml de addon_data solo cambiara a 4202 si actualizamos el addon desde Kodi (o editándolo manualmente).

**Comment by tvalacarta** [comment]
Lo de la versión es como dice @sergigonza, sí.

En la versión Skin también se ve en el lateral :)

En cuanto al tema de las numeraciones me pareción buena idea hacerlo en el settings.xml y quitar el version.xml para incluir versiones de canales y conectores, pero luego me di cuenta de que el problema que apunta @kerenmac es realmente un problema...

Volveré a darle una pensada, pero creo que el número de versión irá simplemente en algún .py ya que no va a cambiar a menos que actualices el plugin. Y la versión de canales y conectores irá en algún version.xml dentro de los propios directorios.

**Comment by divadres** [comment]
creo que, por lo menos para kodi, se puede obtener el número de versión de 
> xbmcaddon.Addon("plugin.video.pelisalacarta").getAddonInfo("version")

sin necesidad de utilizar ningún XML ni nada.

creo que podría ser una opción añadir una función en config: config.get_version() para que en cada plataforma la obtenga del lugar adecuado, kodi de xbmcaddon y las demás puede estar grabado en el mismo config.py

**Comment by divadres** [comment]
Si al final no se mantiene el archivo versión.xml, hay que adaptar el config.py de mediaserver en esta parte:
```
def get_plugin_version():
    data = open(os.path.join(get_runtime_path(),"version.xml"),"r").read()
    return data.split("<tag>")[1].split("</tag>")[0]

def get_plugin_date():
    data = open(os.path.join(get_runtime_path(),"version.xml"),"r").read()
    return data.split("<date>")[1].split("</date>")[0]
```
 ya sea sacando los datos de otro sitio o escribiéndolos a mano en el modulo.

**Comment by tvalacarta** [comment]
Ok, los adaptaré.

Yo creo que el versión.xml desaparece, tiene más sentido ponerlo en el .py, pero lo pensaré.

La versión del addon.xml no me convence, los Kodi-ers tienen sus propias restricciones y yo prefiero distinguir la "versión" (numérica tipo "build number") del "tag".

**Comment by superberny70** [comment]
Joder me he perdido entre tantos version.xml q decis, yo creo q me faltan la mitad!!! 
@sergigonza me referia a ver el numero de version sin salir del plugin. 
Y ampliando un poco la pregunta original y pensando en las diferentes versiones de canales y servers ¿no creeis q seria interesante incluir en configuracion una opcion que muestre un listado de items-tags con el numero de version de cada uno de los canales y servidores instalados (o activos)?

**Comment by tvalacarta** [comment]
Bueno, ahora puedes entrar en el instalador de paquetes de configuración y ver cuál es la actual y cuales son anteriores y posteriores :)

Lo de las versiones individuales yo no lo veo... siempre vas a tener la última instalada a menos que sepas lo que haces.
