### ISSUE TITLE
Default.py

### ISSUE THREAD

**Issue by neno1978** [tvalacarta/pelisalacarta#529]
El nuevo default hace que, si te añades el plugin como acceso directo al home , al entrar tarde una eternidad, bueno bastante. Se planta en la ventana de vídeo , hace el updater durante un tiempo y luego entra. Y al salir no te lleva al home, te deja en la ventana de vídeos . Ya he comentado lo del updater , creo que es eso precisamente lo que lo causa. Si pones el default antiguo, todo rula como debiera 😜

**Comment by tvalacarta** [comment]
¿Puedes poner un log?

Lo único que se me ocurre es que el updater ahora lee la información por https y no por http, así que podría depender del dispositivo o algo así...

**Comment by divadres** [comment]
¿lo has probado en boxee y xbmc versiones antiguas? ya que en Python 2.4 creo que hay problemas con https:// o por lo menos algunas no cargan bien...

**Comment by kerenmac** [comment]
Esto no pasa desde hace dos dias, hace un par de meses se edito para hacerlo compatible con otras plataformas y desde entonces pasa eso que comenta neno1978, yo tambien uso la versión antigua de default.py, accede mucho mas rápido y al salir sale bien, no sale en Videos. De esto se van a ver muchos comentarios, ya que llega a ser molesto.

**Comment by tvalacarta** [comment]
No, no he probado aún todas las versiones ni boxee... pero llegaré.

En cuanto a ese problema, la verdad es que no lo he visto. Entiendo que hablamos de Confluence y Kodi Jarvis cuando añades el add-on en la home, porque en Krypton va bien.

La nueva skin de Krypton mola, en un par de días ya no puedes volver atrás :)

**Comment by divadres** [comment]
El tema del default.py te explico como está porque lo puse yo, y se como va exactamente:

vamos a ver:
En un momento dado se añadió al launcher la función launcher.start() que tenia como objetivo lanzar las funciones que deben ejecutarse solo una vez al entrar al plugin (de momento, solo hay una para comprobar que los directorios existan) 

Sobre el papel suena muy bien, pero el problema estaba para averiguar cuando estas entrando al plugin desde "fuera" y cuando estas cargando el mainlist tirando para atrás, entonces monte este sistema que es un poco reliado, pero funcionaba, el problema es que no sabia que existía la función para entrar al plugin desde el home. y por lo visto entrando desde ahí ese método no funciona muy bien, así que quedan dos opciones:
1. Dejarlo como está
2. Modificarlo para que ejecute launcher.start() si sys.argv[2] = ""  (de modo que lo hará también cuando tiras para atrás hasta el mainlist)

Realmente tampoco hay mucho problema en que vuelva a comprobar los directorios al llegar al mainlist, ya que tampoco es algo que tarde tanto, y con eso volveria a funcionar como antes. y puesto que la función launcher.start() por ahora no se usa para otra cosa, puede ser la mejor solución.

**Comment by neno1978** [comment]
Perdón x la tardanza Jesús, estaba tomando cerve...digo disfrutando x ahí del ambiente navideño con los niños 😐... Como veo que div ya lo ha explicado a la perfección es innecesario ya el log evidentemente. Yo primero opte por volver al default antiguo, no obstante , la solución del gran div , tb furula 🍺🍺🍺

**Comment by tvalacarta** [comment]
El único problema entonces es que comprobará la versión cada vez que se pase por el mainlist ¿no?

De todas formas en mis pruebas con la actualización de versiones el comportamiento era ese (si publicaba una nueva versión estando en una pantalla interior al volver al menú la detectaba), así que puede que en cualquier caso no sea útil.

Si podéis hacer ese cambio lo preparamos para la próxima beta, me lo apunto igualmente para hacerlo yo si no podéis.

**Comment by divadres** [comment]
la comprobación de nueva versión se hace en el launcher.run() cuando action es "getmainlist" de modo que esa parte ya funciona así, no le afecta los cambios en launcher.start()

**Comment by tvalacarta** [comment]
Cierto, tienes toda la razón :)

Mi idea siempre fue que se comprobara únicamente al entrar como ocurre en la versión UI, es lo que tiene sentido, y no cada vez que pasaras por el mainlist. Pero se quedó en el camino...

**Comment by Palatosino** [comment]
Comentan en el foro que el default.py nuevo también jode Yatse, mientras el que el antiguo permite navegar por la interfaz.

Así que tal vez debería retomarse esto antes de pasar a la beta-3 o beta-4.

**Comment by Intel11** [comment]
Hola, disculpen que me meta en la conversación; yo fuí el que reportó lo del default.py, como dije el nuevo default.py no funciona con yatse (control remoto para kodi), y antes me funcionaba normal.

Gracias. :)

**Comment by divadres** [comment]
Puedes indicar cual es el problema que te da? No se abre el plugin? da algun error?

**Comment by Palatosino** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8617

Ver screenshots. Con el default actual no carga el addon dentro de yatse.

**Comment by divadres** [comment]
Bueno, visto lo visto, creo que va a ser mejor modificar el default.py, no poner el antiguo, porque puede dar otros problemas, pero modificare las lineas que dan el error, como he comentodo mas arriba, el unico problema que tiene modificarlo es que se lanza launcher.start() siempre que accedemos al menu principal tanto entrando desde a fuera como tirando para atras... aunque hoy por hoy eso no supone ningun problema asi que sera la mejor opcion...

**Comment by Intel11** [comment]
Gracias por responder.

Cuando lo tengas lo probaré.

Gracias otra vez.

Saludos.

**Comment by superberny70** [comment]
¿solucionado?
