### ISSUE TITLE
Canal seriesblanco.py

### ISSUE THREAD

**Issue by sergigonza** [tvalacarta/pelisalacarta#530]
Hola amigos,
Estoy comprobando que al realizar una busqueda en el canal seriesblanco (Desde dentro del canal, apartado de busqueda), el primer resultado que arroja no carga los enlaces, el resto si ...

En el log he comprobado que es porque se esta capturando una Url no valida, seguramente de publicidad... En este caso submanga.org 

> 17:10:45 T:6952  NOTICE: pelisalacarta.platformcode.launcher search
17:10:47 T:6952  NOTICE: pelisalacarta.channels.seriesblanco [search] mentes
17:10:47 T:6952  NOTICE: pelisalacarta.channels.seriesblanco [series] url = http://seriesblanco.com/search.php?q1=mentes&q2=mentes&pagina=1
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] ----------------------------------------------
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] downloadpage
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] ----------------------------------------------
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Timeout: None
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] URL: http://seriesblanco.com/search.php?q1=mentes&q2=mentes&pagina=1
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Dominio: seriesblanco.com
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Peticion: GET
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Usar Cookies: True
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Descargar Pagina: True
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Fichero de Cookies: C:\Users\sac\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.pelisalacarta\cookies.dat
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Headers:
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - Accept-Charset: UTF-8
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - Accept-Encoding: gzip
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Leyendo fichero cookies
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Realizando Peticion
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Terminado en 0.19 segundos
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Response sucess: True
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Response code: 200
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Response error: None
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Response data length: 5397
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Response headers:
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - magicmarker: 1
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - x-varnish: 1768375686
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - content-encoding: gzip
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - transfer-encoding: chunked
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - age: 0
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - vary: Accept-Encoding
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - x-cacheable: YES
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - server: cloudflare-nginx
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - connection: close
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - via: 1.1 varnish
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - pragma: no-cache
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - date: Mon, 02 Jan 2017 16:10:47 GMT
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - cf-ray: 31af7baea46a2f89-MAD
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] - content-type: text/html; charset=UTF-8
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Guardando cookies...
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Encoding: gzip
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Descomprimiendo...
17:10:47 T:6952  NOTICE: pelisalacarta.core.httptools [downloadpage] Descomprimido
17:10:47 T:6952  NOTICE: ######## DEBUG #########
17:10:47 T:6952  NOTICE:     [pelisalacarta.channels.seriesblanco.extractSeriesFromData] Show found: Mentes criminales -> http://submanga.org (http://2.bp.blogspot.com/-blDBYgHcjpk/UTsekzQg9FI/AAAAAAAAPtk/VO4vGR9uuHM/s320/mentes1-seriesdanko.com-.jpg)
17:10:47 T:6952  NOTICE: ######## DEBUG #########
17:10:47 T:6952  NOTICE:     [pelisalacarta.channels.seriesblanco.extractSeriesFromData] Show found: Mentes Criminales conducta sospechosa -> /serie/369/mentes-criminales-conducta-sospechosa.html (http://2.bp.blogspot.com/-Qs-XBI5yXmM/TV2osc1VRDI/AAAAAAAACSA/AiAvE45uSV8/s400/Mentes_criminales_conducta_sospechosa_seriesdanko.jpg)
17:10:47 T:6952  NOTICE: ######## DEBUG #########
17:10:47 T:6952  NOTICE:     [pelisalacarta.channels.seriesblanco.extractSeriesFromData] Show found: Mentes Criminales: Beyond Borders -> /serie/3562/mentes-criminales-beyond-borders.html (http://seriesblanco.com/files/uploads/3562.jpg)
17:10:47 T:6952  NOTICE: ######## DEBUG #########
17:10:47 T:6952  NOTICE:     [pelisalacarta.channels.seriesblanco.extractSeriesFromData] Show found: Mentes en Shock -> /serie/370/mentes-en-shock.html (http://2.bp.blogspot.com/-rDSPOZEzKuM/TZq_9fcowhI/AAAAAAAAEmY/2KsK9MGgNOA/s1600/mentes_en_shock-seriesdanko.jpg)

No entiendo muy bien porque, porque en el codigo arrojado por el navegador lo coge bien ...

**Comment by superberny70** [comment]
Ya lo he solucionado en la PR #522.
Fijate: el problema es q el primer Show found no tienen la url correcta.

**Comment by sergigonza** [comment]
Perfecto! Gracias Maquina!
