### ISSUE TITLE
Error en el item?

### ISSUE THREAD

**Issue by tvalacarta** [tvalacarta/pelisalacarta#535]
Al intentar ver cualquier vídeo en animeid me sale este error en el log:

`14:23:26 T:123145303990272  NOTICE: ######## ERROR #########
14:23:26 T:123145303990272  NOTICE:     [pelisalacarta.platformcode.launcher.run] pelisalacarta.platformcode.launcher Traceback (most recent call last):
                                              File "/Users/jesus/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 218, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/Users/jesus/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/channels/animeid.py", line 308, in findvideos
                                                url=CHANNEL_HOST + url_anterior, thumbnail=item.thumbnail, plot=item.plot, show=item.show,
                                              File "/Users/jesus/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/core/item.py", line 256, in __getattr__
                                                return self.__dict__["infoLabels"]["plot"]
                                            KeyError: 'infoLabels'
`

No veo el problema, a mí me parece que está todo bien.

Debe ser por la gripe, o que el nivel de sofisticación del Item.py ya me supera ja ja ja

**Comment by CmosGit** [comment]
Creo que se debe a que unas líneas por encima en animeid se elimina el infoLabels del item:

```
    if 'infoLabels' in item:
	del item.infoLabels
```
Y eso provoca que cuando se intenta actualizar infoLabels salte el error. Se debería cambiar por algo así, aunque no sé exactamente por qué se decide eliminarlo si no se ha hecho uso de él en todo el canal ❓ 

```
    if 'infoLabels' in item:
	item.infoLabels = {}
```

**Comment by tvalacarta** [comment]
No lo había visto, gracias por la rapidez :)

He seguido probando y sólo me pasaba en ese canal, así que era lógico que fuera algo del propio canal, pero he abierto el issue cuando lo he visto al principio para que no se me pasara por alto.

La cierro entonces, y quito esa parte del canal.
