### ISSUE TITLE
Versión mediaserver rota

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#541]
Actualmente no funciona. Se queda en "Estableciendo conexión".

PD: Pillando la carpeta version-mediaserver y copiandola sobre "main-classic". Es como lo he realizado otras veces (y la versión 4.2 beta 1 que tengo corriendo). Todo ello sobre la rama develop.

**Comment by divadres** [comment]
No funcionara porque se ha eliminado el archivo version.xml  con el nuevo sistema de actualizaciones y hay q adaptar la version mediaserver ya que est lo utilizaba...

**Comment by Palatosino** [comment]
He visto el backtrace, pero le he puesto el version.xml de la anterior y simplemente se me ha quedado igual, pero sin backtrace :laughing:

**Comment by gitjose32** [comment]
Hola, soy nuevo por aquí, pero uso pelisalacarta en kodi (RPi2) habitualmente.
Ayer vi que había una versión mediaserver e intenté ponerla en marcha pero me pasa lo que decís, se queda "estableciendo conexión", tanto en un PC con Windows como en uno cou Ubuntu. He probado una solución que he visto por el foro, añadiendo "hayqueactualizar = False" al updater.py, pero no lo arregla. Por lo que  decís hace falta adaptar el archivo version.xml, ¿hay alguna forma de enterarse de que ya está lista esa adaptación? O no hay más solución que conectarse de vez en cuando al GitHub y mirarlo...
Gracias,
Jose

**Comment by divadres** [comment]
he creado un PR solucionando el problema, solo tienes que modificar el archivo config.py

**Comment by gitjose32** [comment]
Hola:
Mil gracias por la rapidez!
Ahora funciona, puedo seleccionar y descargar, pero lo que no puedo es buscar, me dice:

Se ha producido un error en el canal buscador
Esto puede ser debido a varias razones:
- El servidor no está disponible, o no esta respondiendo.
- Cambios en el diseño de la web.
- Etc...
Comprueba el log para ver mas detalles del error.
Y en el log me encuentro:

ERROR 07/01/17-17:17:22 [websocket.py run                        ] Traceback (most recent call last):
File "R:\pelisalacarta\WebSocket.py", line 70, in run controller.run(path)
File "R:\pelisalacarta\platformcode\controllers\html.py", line 44, in run launcher.run(item)
File "R:\pelisalacarta\platformcode\launcher.py", line 98, in run itemlist = channelmodule.search(item,tecleado)
File "R:\pelisalacarta\channels\buscador.py", line 177, in search  return do_search(item, [])
File "R:\pelisalacarta\channels\buscador.py", line 299, in do_search t.start()
File "R:\Python27\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ())  error: can't start new thread
                                                                
Lo que pasa es que he visto que pelisalacarta UI (4.2.0-beta 2) en mi kodi tampoco me deja buscar, me dice "se ha producido un error".
En cambio con el  pelisalacarta "normal sí" que puedo buscar. Si es muy complicado de resolver seguiré usando este último.
Gracias de nuevo

**Comment by divadres** [comment]
Pues me parece extraño porque a mi si que me funciona bien.

Yo probaría de eliminar la carpeta ".pelisalacarta" (creo recordar que en Linux esta en /home) donde se guarda la configuración, reiniciar pelisalacarta y probar de nuevo con la configuración por defecto, si así te sigue fallando, necesitaría saber:
 1. Que versión de Python utilizas
 2. Enviarme el log completo para ver si veo algo.
 3. Que sistema operativo usas

el único error que muestra en el log que has puesto es:
`File "R:\Python27\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread`
Pero no dice por que no se puede iniciar el nuevo thread, es algo bastante raro y pienso que quizá sea algún problema en tu instalación de Python... si tienes posibilidad pruébalo en otro equipo...
