### ISSUE TITLE
[4.2.0] Fallo con OSMC y json

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#542]
Voy a ir poniendo los fallos más comunes que he visto en esta versión para tenerlos localizados.

> 17:02:32 175.162949 T:1562375152  NOTICE: ######## ERROR #########
> 17:02:32 175.163223 T:1562375152  NOTICE:     [pelisalacarta.core.jsontools.load_json] **NO** se ha podido cargar el JSON
> 17:02:32 175.167801 T:1562375152  NOTICE: ######## ERROR #########
> 17:02:32 175.168045 T:1562375152  NOTICE:     [pelisalacarta.core.jsontools.load_json] Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/jsontools.py", line 58, in load_json
>                                                 value = json.loads(*args, **kwargs)
>                                               File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
>                                                 return cls(encoding=encoding, **kw).decode(s)
>                                               File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>                                                 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                                               File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>                                                 raise ValueError("No JSON object could be decoded")
>                                             ValueError: No JSON object could be decoded

**Comment by Palatosino** [comment]
¿Donde has detectado el fallo? Porque yo lo tengo en OSMC sin problemas.

**Comment by divadres** [comment]
Estaria bien saber cual es la cadena que intenta cargar al json...

**Comment by SeiTaN** [comment]
Estoy en ello xDDD no es mío el fallo, no uso OSMC, **es de un usuario del foro.** y le he pedido el fichero json.

> 17:02:29 172.737793 T:1562375152  NOTICE: pelisalacarta.default init...
> 17:02:30 173.619003 T:1562375152  NOTICE: pelisalacarta.core.jsontools Probando json incluido en el interprete
> 17:02:31 174.787796 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher run
> 17:02:32 174.930405 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher action= 'update_biblio', category= 'Configuración', channel= 'biblioteca', contentType= 'list', fanart= '', folder= False, infoLabels= {'mediatype': 'list'}, thumbnail= 'http://media.tvalacarta.info/pelisalacarta/squares/thumb_biblioteca.png', title= '   Buscar nuevos episodios y actualizar biblioteca', totalItems= 0
> 17:02:32 174.931473 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher channel_file=/home/osmc/.kodi/addons/plugin.video.pelisalacarta/channels/biblioteca.py
> 17:02:32 174.935913 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher running channel channels.biblioteca /home/osmc/.kodi/addons/plugin.video.pelisalacarta/channels/biblioteca.pyo
> 17:02:32 174.936691 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher executing channel 'update_biblio' method
> 17:02:32 175.031647 T:1562375152  NOTICE: pelisalacarta.channels.biblioteca.update_biblio
> 17:02:32 175.086838 T:1562375152  NOTICE: pelisalacarta.library_service [check_for_update] Actualizando series...
> 17:02:32 175.162949 T:1562375152  NOTICE: ######## ERROR #########
> 17:02:32 175.163223 T:1562375152  NOTICE:     [pelisalacarta.core.jsontools.load_json] **NO** se ha podido cargar el JSON
> 17:02:32 175.167801 T:1562375152  NOTICE: ######## ERROR #########
> 17:02:32 175.168045 T:1562375152  NOTICE:     [pelisalacarta.core.jsontools.load_json] Traceback (most recent call last):

**Comment by SeiTaN** [comment]
```python
{
    "settings": {
        "ask_channel": false, 
        "library_mode": 0, 
        "mark_as_watched": true, 
        "no_pile_on_seasons": 1, 
        "original_title_folder": 0, 
        "show_all_seasons": true, 
        "updatelibrary": 1, 
        "updatelibrary_last_check": "2017-01-04", 
        "updatelibrary_wait": 0, 
        "updatetvshows_interval": 0, 
        "watched_setting": 3, 
        "xbmc_host": "", 
        "xbmc_puerto": ""
    }
}
```

Está bien el fichero json

**Comment by divadres** [comment]
Pero esto esta extraido leyendo el json manualmente o obteniendo el texto desde la fincion load_json() yo modificaria el log de jsontools para q en caso se error mande al log el texto recibido, asi dabemos si el problema esta al leer el fichero...

**Comment by SeiTaN** [comment]
@divadres es el fichero fisico "biblioteca_data.json", y ya le he pasado un fichero jsontools con trazas para ver que pasa 😉

**Comment by malkavi** [comment]
Buenas, pues para no molestar en el foro más con este error, subo por aquí los logs. Lo único, no se que pruebas hacer, no se en que log de los que subí estaba el fallo, al importar la bibliteca de la versión anterior, al usar el skin osmc o al intentar agregar una serie nueva.
[kodi.txt](https://github.com/tvalacarta/pelisalacarta/files/687321/kodi.txt)

**Comment by SeiTaN** [comment]
@malkavi, entra a la biblioteca de pelisalacarta, con eso debería saltarte el error.

**Comment by superberny70** [comment]
No sera una serie en concreto?

**Comment by malkavi** [comment]
Ese log creo que lo hice con la carpeta SERIES sin importar a la nueva versión (había vuelto a la carpeta anterior para luego hacer la prueba de importar). Así que tal vez sea cosa de tener mezcla de versiones. Luego hice el log de importar y luego el de añadir series con Confluence.

De todas formas aquí está el log.

[kodi.txt](https://github.com/tvalacarta/pelisalacarta/files/687411/kodi.txt)

**Comment by divadres** [comment]
En estos logs, por lo menos yo, no veo que de el error que se puso en el primer mensaje:

> 17:02:32 175.162949 T:1562375152 NOTICE: ######## ERROR #########
>  17:02:32 175.163223 T:1562375152 NOTICE: [pelisalacarta.core.jsontools.load_json] NO se ha podido cargar el JSON
>  17:02:32 175.167801 T:1562375152 NOTICE: ######## ERROR #########
>  17:02:32 175.168045 T:1562375152 NOTICE: [pelisalacarta.core.jsontools.load_json] Traceback (most recent call last):
>  File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/jsontools.py", line 58, in load_json
>  value = json.loads(*args, **kwargs)
>  File "/usr/lib/python2.7/json/init.py", line 351, in loads
>  return cls(encoding=encoding, **kw).decode(s)
>  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>  raise ValueError("No JSON object could be decoded")
>  ValueError: No JSON object could be decoded

**Comment by superberny70** [comment]
>  lo hice con la carpeta SERIES sin importar a la nueva versión 
Evidentemente q falla al intentar pasar a json lo q ya no lo es... 

Hay algun fallo mas de json en  osmc?  Por. Q si no lo hay cerramos esta discusión,  al menos por mi.
