### ISSUE TITLE
[4.2.0] OSMC y skins

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#543]
> 17:02:16 159.618530 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher running channel channels.biblioteca /home/osmc/.kodi/addons/plugin.video.pelisalacarta/channels/biblioteca.py
> 17:02:16 159.619431 T:1562375152  NOTICE: pelisalacarta.platformcode.launcher executing channel 'channel_config' method
> 17:02:16 159.715179 T:1562375152 WARNING: CSkinInfo: failed to load skin settings
> 17:02:16 159.720352 T:1562375152   ERROR: EXCEPTION: XML File for Window is missing
> 17:02:16 159.734650 T:1562375152  NOTICE: ######## ERROR #########
> 17:02:16 159.735016 T:1562375152  NOTICE:     [pelisalacarta.platformcode.launcher.run] pelisalacarta.platformcode.launcher Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 279, in run
>                                                 itemlist = getattr(channel, item.action)(item)
>                                               File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/channels/biblioteca.py", line 37, in channel_config
>                                                 return platformtools.show_channel_settings(channelpath=os.path.join(config.get_runtime_path(),"channels", item.channel))
>                                               File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/platformcode/platformtools.py", line 538, in show_channel_settings
>                                                 return SettingsWindow("ChannelSettings.xml", config.get_runtime_path()) \
>                                             RuntimeError: XML File for Window is missing

**Comment by tvalacarta** [comment]
Eso es algo que me ocurre también en Android, pero en el Mac no. De hecho la versión skin tampoco me funciona en Krypton sobre Android, pero sí en el Mac.

Si te pasa en OSMC también todo apunta a que puede deberse a un tema de mayúsculas / minúsculas a la hora de buscar el directorio con los xml del skin.

**Comment by SeiTaN** [comment]
@tvalacarta esto pasaba en su día con otros skins, y creo que se asoció a un bug al llamar a WindowXML lo solucionó @divadres pero parece que no se ha conseguido que vaya fino al 100%.

P.D: el error no es mío, no uso OSMC, lo he puesto de gente del foro para que esté más centralizado aquí y fácil de acceder 😉

**Comment by SeiTaN** [comment]
> No, lo probé en Android pero si pones el skin 720p en el directorio 1080i funciona pero la pantalla aparece en una esquina.

Será por las posiciones del xml, habrá que cambiar las coordenadas para las distintas resoluciones.

> La cosa es que sin hacer nada en el ordenador funciona bien, de hecho el skin se reescala correctamente. 

A mi tb pero vamos a tener que hacerlo como comenta @divadres, copiar los 3 xml que hay actualmente en todas las resoluciones y cambiar las coordenadas para centrar la ventana.

No entiendo eso que comentas del caseSensitive, la ruta no se escribe a mano, se obtiene del sistema.

**Comment by tvalacarta** [comment]
La cosa es que si Kodi en mi ordenador sabe reescalar el skin, debería hacerlo en todos y es la mejor opción (para no mantener 5 skins distintos).

Copiar los xml arregla el error pero en una tele 4K (por decir algo), se verá un recuadrito pequeño en una esquina :(

Yo tampoco entiendo cual es el problema, pero la diferencia de los sistemas basados en Linux respecto del resto es precisamente el case sensitive. Eso explicaría que funcione en unos sí y en otros no.

**Comment by SeiTaN** [comment]
> La cosa es que si Kodi en mi ordenador sabe reescalar el skin, debería hacerlo en todos y es la mejor opción (para no mantener 5 skins distintos).

@tvalacarta quizás reescala por que kodi en los pcs/macs al acceder a la resolución del monitor lo reescala automáticamente, pero en caso para versiones donde son tamaños fijos, como 720, pal, 1080, etc no lo hará, es lo único que se me ocurre.

No se mantendrá "5 skins distintos", sobre el papel es retocar las dimensiones y solo deberíamos hacerlo una vez. Ya estaba así con uno que había para captchas.

> Yo tampoco entiendo cual es el problema, pero la diferencia de los sistemas basados en Linux respecto del resto es precisamente el case sensitive. Eso explicaría que funcione en unos sí y en otros no.

En mac no es case sensitive? En fin a ver si sacamos más información, yo soy partidario de lo que ha dicho @divadres así nos ahorramos dolores de cabeza.

**Comment by tvalacarta** [comment]
No, los ficheros en Mac no son case sensitive (creo que puedes forzarlo pero desde luego no viene por defecto).

Lo probaré en Ubuntu a ver, será más fácil añadir logs y diagnosticar.

**Comment by divadres** [comment]
Hay una funcion para reescalar el xml desde xbmc pero el problrma es que parece que esta funcion el parametro que hay q pasarle que es un numero indicando la resolucion a la q esta diseñada cambia en algunas versiones de kodi antiguas y no se si en alguna nueva tambien...

**Comment by divadres** [comment]
Q version de kodi es?

**Comment by divadres** [comment]
```
setCoordinateResolution(...)
  setCoordinateResolution(self, int resolution)--
  Sets the resolution that the coordinates of all controls are defined in. Allows XBMC to scale control positions and width/heights to whatever resolution XBMC is currently using.
  
   resolution is one of the following:
     - 0 - 1080i (1920x1080)
     - 1 - 720p (1280x720)
     - 2 - 480p 4:3 (720x480)
     - 3 - 480p 16:9 (720x480)
     - 4 - NTSC 4:3 (720x480)
     - 5 - NTSC 16:9 (720x480)
     - 6 - PAL 4:3 (720x576)
     - 7 - PAL 16:9 (720x576)
     - 8 - PAL60 4:3 (720x480)
     - 9 - PAL60 16:9 (720x480)n
```

actualmente en las ventanas uso el valor 1 excepto para las versiones antiguas que es 5 no se si en krypton debe ser otro valor, pero si es asi podría especificarse sin problema...

**Comment by SeiTaN** [comment]
> Q version de kodi es?

16:59:37  11.504567 T:1956488112  NOTICE: -----------------------------------------------------------------------
16:59:37  11.504679 T:1956488112  NOTICE: Starting Kodi (16.1). Platform: Linux ARM (Thumb) 32-bit

**Comment by tvalacarta** [comment]
Lo he probado en Krypton.

Casualmente buscando ese "setCoordinateResolution" me he encontrado este post de @CmosGit en el foro.

http://www.mimediacenter.info/foro/viewtopic.php?t=7936&p=34859#p34854

Entiendo que la clave es eso, copiar el script en todos los directorios y poner eso en el onInit.

**Comment by divadres** [comment]
el problema es que eso Ya esta en el onInit.... otra cosa es si hay que pasarle otro valor...

**Comment by tvalacarta** [comment]
En el caso de la ventana de la biblioteca, sólo faltaría entonces copiar los xml de los skins como decías en cada directorio.

En el caso de la versión UI, además hay que añadir eso en el onInit porque no está hecho.

El skin de la versión UI está en 720p, así que será "self.setCoordinateResolution(1)".

Lo pruebo y si funciona queda incluido para la beta 3.
