### ISSUE TITLE
[4.2.0] Canal HDFull no muestra nada.

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#544]
No muestra nada, habrá cambiado la web ¿sería un buen momento para aprovechar y mirar a httptools?

**Comment by r0balo** [comment]
Ahora mismo estoy con lo que toca en estas fechas, fiestas, regalos, gripazo, etc...

No lo creo, es sólo DDoS

**Comment by kerenmac** [comment]
Con los cambios de # @CmosGit del PR #545 ya funciona. Tambien noto que SB y otros canales con cloudflare estan mas agiles, especialmente accediendo desde la biblioteca, puede tener algo que ver con ese cambio en httptools?

Off-Topic: A vosotros tambien os salen constantemente errores (en el log) relacionados con la textura "overlayunwatched.png"? Dice que falta, y solo me aparece al navegar por Pelisalacarta. Si a vosotros os falla tambien igual hay que abrir un issue.

**Comment by SeiTaN** [comment]
> Off-Topic: A vosotros tambien os salen constantemente errores (en el log) relacionados con la textura "overlayunwatched.png"? Dice que falta, y solo me aparece al navegar por Pelisalacarta. Si a vosotros os falla tambien igual hay que abrir un issue.

A mi tb me pasa.

**Comment by SeiTaN** [comment]
chapo este issue ya que lo ha arreglado el gran @CmosGit 👍

**Comment by CmosGit** [comment]
> chapo este issue ya que lo ha arreglado el gran @CmosGit 👍

Por favor, "gran" dice... de venerable para arriba! :triumph: :stuck_out_tongue_winking_eye:

Seguramente se podía arreglar utilizando scrapertools como hasta ahora, pero la verdad es que tengo la sensación de que httptools lidia mejor con cloudflare, y además no me convence cómo maneja las cookies, se pierden algunas por el camino y como se guarden en archivos separados date por jodido xD

**Comment by SeiTaN** [comment]
Pues si, httptools vuelve a usar el fichero global de cookies 😄

**Comment by r0balo** [comment]
@CmosGit estoy contigo, de hecho, mi negación realmente es una afirmación.

No me gusta los cambios de nombres para los arreglos o mejoras a rutinas existente por el tema de tener que estar editando a cada arreglo los imports y llamadas en todos los canales y conecteres. Los canales y conectores son módulos que se debería de interpretar como BBDD de la que se alimenta la aplicación. Se tiene que evitar que todo dependa de todo. Las mejoras no tienen que forzar la reconstrucción de las fuentes de datos.

`scrapertools.dowloadpage` debería seguir dónde está con las mejoras + la comprobación DDoS sin tener que modificar la fuente de datos en caso de necesite o no `anti_cloudflare`. Bastante tenemos ya con los patrones y JS :)

**Comment by SeiTaN** [comment]
@r0balo es que lo que comentas no se tuvo en cuenta en su día, y para tocar cosas que funciona, @divadres lo incorporó en httptools, a partir de ahora si un canal necesita o no comprobar el anti_cloudflare "no daría problemas" si tenemos en cuenta cosas extrañas que pueden pasar como headers.

**Comment by r0balo** [comment]
Los webmaster van y vienen y cada maestrillo tiene su librillo :) ahora se lleva ir a la moda pero eso mañana puede cambiar y todo lo hecho se va a tomar por saco. Todo lo que se ejecuta del lado del servidor no es transparente para nosotros por lo que especulando y probando se puede "intuir" que comprueba o que filtros a podido implementar para tumbar a un posible bot. Esto se debe o debería controlar en los conectores y canales. Tiene muy poca lógica que en el navegador acepte los User-Agent del mismo y con urllib o urllib2 no. No lo he probado pero si usáramos curl posiblemente no tendríamos esos problemas y si con curl funciona también debería funcionar con las librerías de python. Al igual que requests existen mod para este que comprueba distintas formas de menejar cloudflare. Una vista rápida al mod es lo que hice una vez para seriesblanco que actuaba "igual" que el navegador.

**Comment by divadres** [comment]
@r0balo 

>  scrapertools.dowloadpage  debería seguir dónde está con las mejoras + la comprobación DDoS sin tener que modificar la fuente de datos en caso de que necesite o no  anti_cloudflare . Bastante tenemos ya con los patrones y los putos JS ofuscados :)

Hasta donde yo se scrapertools.downloadpage sigue donde estaba..., httptools funciona de una "forma distinta" que scrapertools, ya que lo que he buscado es que una función sirva para "todo" y si en un futuro necesitamos "algo mas" se pueda añadir sin tener que crear 40 funciones que hagan prácticamente lo mismo, 
como ya dije en su dia, tengo un scrapertools modificado que mantiene todas las funciones para descargar paginas, pero lo redirige al correspondiente método en httptools, yo lo uso hace tiempo a modo de debug, y por ahora me va bien, pero es difícil garantizar que en TODAS las funciones el resultado es el mismo que antes, y que no falle en algún conector o canal, por eso no lo he querido subir, para que los canales que usan scrapertools no empiezen a fallar si saber por que...

> Tiene muy poca lógica que en el navegador acepte los User-Agent del mismo y con urllib o urllib2 no

Efectivamente si un user-agent funciona en el navegador, tiene que funcionar en urllib, y hasta donde he podido comprobar funcionan bien, lo que pasa es que los headers por defecto de scrapertools son muy antiguos, y en vez de actualizarlos de vez en cuando la gente ha ido añadiendo headers a cada canal cuando actualizando los genéricos servirían para todo o "casi todo" por eso yo en httptools he puesto los últimos que usa (o usaba cuando lo hice) Firefox, y no he tenido ningún problema...

**Comment by r0balo** [comment]
@divadres ya sé que sigue dónde estaba pero ahora tenemos dos y si el que hay en httptools funciona bien y mejor que el antiguo se debería hacer un PR sobre el del scrapertools.

Hoy es httptools.downloadpage, mañana a saber. Ese es el problema. No es la primera vez que pasa y es un follón.

Como he dicho antes, cada webmaster tiene sus antojos y es bastante fácil si se quieren molestar comprobar si el flujo de peticiones es el de un navegador normal. Por eso y por lo probado, el user-agent de firefox actual o no, no cuela en algunas ocasiones. Vale cualquier cosa menos un user-agent con un len normal. Para arrancarles las cookies hay que darle algo diferente como "Mozilla/5.0" o "robalo" como usé hace poco :) pero esto es bastante fácil de tumbar.
