### ISSUE TITLE
Error en los títulos en versión beta de plex

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#549]
He instalado la versión 4.2.0 beta 2 para plex (actualizado a la última versión) y no se muestra ningún item en el que el título tenga caracteres no compatibles con utf-8 o ascii (tildes, eñes, etc...). Esto no afecta al funcionamiento porque se siguen ejecutando correctamente, pero lógicamente es un fastidio xD. Como muestra, un ejemplo del menú películas de hdfull (faltan los títulos de Últimas películas, Últimos estrenos, Películas Actualizadas...):

![](http://i.imgur.com/soFw1VM.png?1)

No es algo exclusivo de ese canal, pasa con cualquiera, incluso en la lista de canales el título del canal "El señor del anillo" no se ve. He probado a reinstalar la versión de pelisalacarta 4.1.1 por si se debiese a un cambio de plex, pero en ésta los títulos se muestran correctamente. En el log el error es siempre el mismo:

```
2017-01-06 16:53:35,829 (10e0) :  CRITICAL (core:574) - Exception setting attribute 'title' of object <Framework.modelling.objects.DirectoryObject object at 0x056891B0> to El señor del anillo (type: <type 'str'>) (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 71, in _set_attribute
    el.set(convert_name(name), value)
  File "lxml.etree.pyx", line 699, in lxml.etree._Element.set (..\src\lxml\lxml.etree.c:34531)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (..\src\lxml\lxml.etree.c:15781)
  File "apihelpers.pxi", line 1366, in lxml.etree._utf8 (..\src\lxml\lxml.etree.c:22211)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

Consultando los últimos commits que se han hecho para plex no veo nada que pueda estar provocando ese error pero como tampoco se especifica en qué archivo del addon se produce...

**Comment by SeiTaN** [comment]
Cmos, puede que sea por item.

**Comment by CmosGit** [comment]
@SeiTaN bingo para el señorito xD Concretamente por esta línea: https://github.com/tvalacarta/pelisalacarta/blob/develop/python/main-classic/core/item.py#L165

Si se elimina los títulos vuelven a aparecer correctamente, pero supongo que habrá alguna cosa que se verá afectada por ello, así que habría que ver exactamente qué parte del método toutf8 lo está provocando. Eso se lo dejo ya a los gurús del Item, que yo en cuento veo un encode/decode me entra urticaria 😭

**Comment by divadres** [comment]
Creo recordar q en plex NO ha de ser utf8 el titulo... pero eso va a ser mejor modificarlo en plex mejor q en el item, ya que para todos los demas ya esta bien en utf8, en cuanto tenga un rato lo miro..

**Comment by divadres** [comment]
he creado un PR para solucionarlo.
