### ISSUE TITLE
Propuesta formato <changes> en xml

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#564]
Aviso de que esta es una propuesta mas estetica q otra cosa y q hace tiempo q algunos ya venimos utilizando.

Hasta ahora en los xml la etiqueta `<changes>` era sencillamente una sola linea explicativa:
```
...
<version>3</version>
<date>01/07/2016</date>
<changes>Eliminado código innecesario.</changes>
...
```

Mi propuesta es q se incluyan los sucesivos cambios, a modo de historial, dentro de estas etiquetas (como ejemplo pongo divxatope.xml):

```
...
<version>8</version>

<changes>
	<change>
		<date>31/12/16</date>
		<autor>super_berny</autor>
		<description>Adaptado, por cambios en la web</description>
	</change>
	<change>
		<date>01/07/16</date>
		<autor>SeiTaN</autor>
		<description>Eliminado código innecesario.</description>
	</change>
	<change> 
		<date>29/04/16</date>
		<autor>super_berny</autor>
		<description>Adaptar a Buscador global y Novedades Peliculas y Series</description>
	</change>
</changes>
...
```
Hoy por hoy esto no afecta en nada al plugin ya q en ningun sitio se leen estas etiquetas, pero me parece un metodo mas informativo.

**Comment by r0balo** [comment]
Estoy contigo. Además de tener más info de los cambios en las webs y la frecuencia también nos ahorraría tener que tirar del historial del github para buscar una modificación concreta por si queremos recuperarla. La búsqueda sería mucho más fácil.
No se si lo has publicado en el foro, si no lo has hecho sería buena idea hacerlo.
Un tag con la fecha del nacimiento de la criatura también estaría bien :)

**Comment by neno1978** [comment]
Me parece perfecto y lo pongo en practica ;)

**Comment by tvalacarta** [comment]
La etiqueta no se usa internamente para nada, así que no afecta al funcionamiento.

Me parece bien también :)
