### ISSUE TITLE
Algo más relacionado con Cloudflare y thumbnail y fanart (apaño @Cmos en hadfull)

### ISSUE THREAD

**Issue by r0balo** [tvalacarta/pelisalacarta#572]
Al comprobar que los arreglos de @divadres en httptools+cloudflare funcionan muy bien y modificar los canales para que los use me encontré que debía modifcar los canales para incluir en kodi los headers para los thumbnails y fanarts. Un coñazo 😄

Como ya sabéis más de uno, me gustan más los recortes que al gobierno  😂 así que os planteo algo que a mí me está funcionando bien pero como mi versión general de pelisalacarta es ligeramente diferente a lo que hay en la actualidad no se como veréis el apaño, espero que al menos la idea sea útil.

Lo que he hecho:
Coger la función `get_headers` que ha colocado @CmosGit en hdfull, la he modificado un poco y la he añadido a `item.py` al final del archivo (Hace lo mismo pero adaptada a la nueva ubicación)
```
def get_headers(channel):

    from core import config
    if not config.is_xbmc(): return ""

    from core import filetools
    from core import scrapertools

    try: exec "from channels." + channel + " import headers"
    except: headers = [["User-Agent","Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"]]

    headers = dict(headers)

    cookie = filetools.join(config.get_data_path(), 'cookies.dat')
    cookiedata = filetools.read(cookie)

    cfduid = scrapertools.find_single_match(cookiedata,"%s.*?__cfduid\s+([A-Za-z0-9\+\=]+)" % channel)
    headers_append = "|User-Agent=%s&Cookie=__cfduid=%s" % (headers['User-Agent'], cfduid)
    cf_clearance = scrapertools.find_single_match(cookiedata, "%s.*?cf_clearance\s+([A-Za-z0-9\+\=\-]+)" % channel)
    if cf_clearance:
        headers_append += "; cf_clearance=" + cf_clearance

    return headers_append
```
Para añadir o no los headers a los thumbnails y fanarts he añadido a `__init__` de la clase `Item` cuatro líneas por debejo de `self.__dict__.update(kwargs)`
```
        if 'thumbnail' in self.__dict__ and self.__dict__['thumbnail'] != None:
            self.__dict__['thumbnail']+= get_headers(self.__dict__['channel'])
        if 'fanart' in self.__dict__ and self.__dict__['fanart'] != None:
            self.__dict__['fanart']+= get_headers(self.__dict__['channel'])
```
En la versión del `item.py` de `develop` lo anterior que daría así (#L152)
```
        self.__dict__.update(kwargs)
        if 'thumbnail' in self.__dict__ and self.__dict__['thumbnail'] != None:
            self.__dict__['thumbnail']+= get_headers(self.__dict__['channel'])
        if 'fanart' in self.__dict__ and self.__dict__['fanart'] != None:
            self.__dict__['fanart']+= get_headers(self.__dict__['channel'])
        self.__dict__ = self.toutf8(self.__dict__)
```
Al estar por encima `infoLabels` no se si dará problemas, creo que no pero como en la actualidad no lo estoy usando pues no lo tengo probado si funciona bien.

Espero que al menos la idea os plantee otras mejores y no os parezca una barbaridad 😊 

EDITADO: Error en copy/paste

**Comment by superberny70** [comment]
No estoy seguro de haber entendido la necesidad de lo q propones. 
Hasta ahora nunca he necesitado añadirle headers a las url de los fanart ni thumbnails  de los canales q he trasteado, aunq es posible q para algunos canales q obtienen estas imagenes de las propias paginas del canal sea necesario. 
Dicho esto:

- ¿q pasara si en lugar de una url se utiliza una ruta local (a la carpeta resources\images\fanart, por ejemplo)?

- ¿q pasara si en las cookies de ese canal no hay __cfduid?

- ¿q pasara si en lugar de fijar el valor de  fanart o thumbnails al instanciar el Item (__init__) se hace despues (item.fanart= url_fanart)?

**Comment by divadres** [comment]
Bueno yo entiendo que las paginas que usan cloudflare, las imagenes que tiene que descargar kodi necesitan la cookie para descargarlas, imagino que kodi por si solo no es capaz de saltar cloudflare, en los canales que se usa httptools automaticamente es capaz de saltar cloudflare, pero si el canal no sñade los headers a la url de las imagenes, imagino que estas no se mostraran...


Para evitar hacer esto en cada canal, se puede hacer a traves del item, para q busque la cookie...

Creo que la idea es esa... puede ser util... para no repetir tanto codigo en los canales....

**Comment by CmosGit** [comment]
@r0balo a mí me parece una gran idea, cada vez hay más canales que tiran por la vía de cloudflare y hay que tirar de código y añadir a cada thumb/fanart los headers, y así se ahorraría tiempo y código 👍 

Pero lo he probado y le veo algunas pegas, que aun así con depurarlo un poco son perfectamente subsanables. Por un lado como apunta @superberny70 si se utiliza una imagen local, Kodi falla al mostrarla, esto se ve claro por ejemplo con el fanart de pelisalacarta por defecto.

Y por otro lado, usándolo así se añaden las headers a todos los thumbs/fanarts lo que veo algo innecesario porque la mayoría no lo necesitan y obliga a Kodi a volver a cachear las imágenes. Yo optaría por añadir las headers solo si un parámetro del item lo especifica, se podría utilizar "cloudflare" o "headers", y sino está presente dejar la url tal y como está. En cuanto al valor de ese parámetro, en principio pensé en un bool, pero creo que estaría mejor que éste indicase el valor de channel en estas líneas:

```
cfduid = scrapertools.find_single_match(cookiedata,"%s.*?__cfduid\s+([A-Za-z0-9\+\=]+)" % channel)
cf_clearance = scrapertools.find_single_match(cookiedata, "%s.*?cf_clearance\s+([A-Za-z0-9\+\=\-]+)" % channel)
```
Lo digo porque no siempre el channel es igual a la url que se guarda en la cookie. Por poner un ejemplo, la web del canal de tvvip es tv-vip.com, por lo que no encontraría nada...

@superberny70, yo sí me he encontrado algunos canales en los que ocurre esto, como dice @divadres pasa si utilizan cloudflare y hospedan las imágenes en su web, si no les pasas las headers no se ven, no sé si es porque Kodi no intenta cargarlas con sus cookies, pero lo que es seguro es que también se necesita el user-agent con el que esas cookies fueron creadas.

> ¿q pasara si en las cookies de ese canal no hay __cfduid?

Sobre esto, si la web usa cloudflare si no me equivoco esa cookie siempre se crea, la otra, cf_clearance sí que no es segura ya que se crea cuando se supera la verificación/captcha.

**Comment by SeiTaN** [comment]
@r0balo bien pensado y @CmosGit  bien rematado, `item.cf_image = True` y que añada directamente el header a fanart y thumbnail

**Comment by superberny70** [comment]
No, sino dudo de q haya paginas en q lo necesites. De hecho vosotros sois seguramente quienes mejor conoceis estos temas.  Mis dudas estan en el codigo. 
@CmosGit: 
- En la pregunta sobre __cfduid hacia referencia a webs q no usen cloudflare. 

- Si hay q añadir un atributo nuevo al item, con el canal de las cookies,  y ademas en la nueva funcion del item debemos hacer un import del canal para coger el header (si existe)  no seria mas efectivo pasar ya la url con su header correspondiente en el atributo fanart (o el q sea)?  

Tal vez esa función seria mas util en channeltools o en el modulo especifico para cloudflare,  ¿no?

**Comment by divadres** [comment]
Creo que esto es mas sencillo de lo que parece
Vamos por partes:

1. No se porque en algunos canales se tiene la tendencia a modificar los headers cuando, en realidad, no es necesario, o no debería serlo mas que en casos muy concretos, si tenemos en cuenta que las paginas se abren con el navegador, en principio los headers por defecto de cualquier navegador que estén actualizado servirían. hay quien pone "user-agent": "Mozilla/5.0" y cosas así, realmente no se para que. Cuando httptols lo puede abrir perfectamante con los headers que trae, yo en httptools, elegí cuidadosamente los headers para:
   1. Intentar que la página se descargue en UTF-8
   2. Intentar que la pagina se descargue en español
   3. Usar la compresión GZIP para ahorrar trafico

2. Si partimos de que dejamos los headers en paz, los que van por defecto en httptools (actualizándolos de tanto en tanto para que sean los últimos) no tenemos que preocuparnos de que user-agent habrá puesto el canal, y solo con comprobar si el dominio de la imagen tiene un valor "cf_clearance" en cookies.dat  ya podríamos pasarle los headers dando por echo que el user-agent que se ha usado es el user-agent por defecto.
3. En el raro caso de que un canal necesite otro user-agent, (cosa bastante rara) pues siempre se podría optar por añadir los headers a la imagen en ese caso desde dentro del mismo canal.

**Comment by CmosGit** [comment]
> No se porque en algunos canales se tiene la tendencia a modificar los headers cuando, en realidad, no es necesario, o no debería serlo mas que en casos muy concretos, si tenemos en cuenta que las paginas se abren con el navegador, en principio los headers por defecto de cualquier navegador que estén actualizado servirían. hay quien pone "user-agent": "Mozilla/5.0" y cosas así, realmente no se para que. Cuando httptols lo puede abrir perfectamante con los headers que trae, yo en httptools, elegí cuidadosamente los headers para:

Yo me he encontrado algunas webs y servidores que deniegan el acceso según el user-agent que utilices. No me ha pasado creo con el que trae httptools, pero es que tampoco llevo usándolo mucho tiempo, es algo reciente.

> Tal vez esa función seria mas util en channeltools o en el modulo especifico para cloudflare, ¿no?

A mí lo que me echa más para atrás es que si se implementa en el item esto habría que hacerlo con cada item que se cree, si una lista trae 200 items, tendrá que importar 200 o 400 veces (si usa fanart) el canal y leer las cookies (poniéndonos en un caso extremo, la mayoría son 20/40 items y no se nota). Tal vez sería mejor colocarlo en el render_items de platformtools, de esta manera se podría detectar con el parámetro cf_image como propone @SeiTaN y agregarlo al thumb/fanart, importando una sola vez el canal y la lectura de las cookies.

**Comment by SeiTaN** [comment]
> Yo me he encontrado algunas webs y servidores que deniegan el acceso según el user-agent que utilices. No me ha pasado creo con el que trae httptools, pero es que tampoco llevo usándolo mucho tiempo, es algo reciente.

+1

> Si partimos de que dejamos los headers en paz, los que van por defecto en httptools (actualizándolos de tanto en tanto para que sean los últimos) no tenemos que preocuparnos de que user-agent habrá puesto el canal, y solo con comprobar si el dominio de la imagen tiene un valor "cf_clearance" en cookies.dat ya podríamos pasarle los headers dando por echo que el user-agent que se ha usado es el user-agent por defecto.

Totalmente de acuerdo, ahora que existe httptools y vemos que funciona para todo y contempla cosas que el pobre abuelete scrapertools no tenía en cuenta por que no hacía falta en su tiempo, nos quitaremos un posible cacao y si hiciera falta se puede añadir.

> A mí lo que me echa más para atrás es que si se implementa en el item esto habría que hacerlo con cada item que se cree, si una lista trae 200 items, tendrá que importar 200 o 400 veces (si usa fanart) el canal y leer las cookies (poniéndonos en un caso extremo, la mayoría son 20/40 items y no se nota). Tal vez sería mejor colocarlo en el render_items de platformtools, de esta manera se podría detectar con el parámetro cf_image como propone @SeiTaN y agregarlo al thumb/fanart, importando una sola vez el canal y la lectura de las cookies.

Exacto, render_items, que me supongo y ya añadiendo otro tema que es del caché, ¿@divadres tu sistema supongo que se cargará ahí no?

**Comment by divadres** [comment]
En scrapertools fallava en algunas webs porque el user-agrnt q usa es de la pre-historia por eso hay q ir actualizandolos... importar 200 el canal? En relidad no porque el valor seris para todos el mismo ya q el dominio seria el mismo tambien...

Yo tambien soy mas partidario de hacerlo en render_items ya que asi puede ser mas especifico para cada plataforma....

**Comment by r0balo** [comment]
Reconozco que soy muy bruto 😃 pero a mi favor diré que la prueba la he hecho en windows y con el tfm que tengo de seriesblanco que me muetra una lista de 4140 items que extrae solicitando 52 páginas 😃
Me suele tardar unos 10 segundos y me muestra todas las caratulas.

Me ha gustado ver que no ha sido tanta la barbarie, ver tantas alternativas y muy buenas preguntas.

Pensé en clase Item por que todos pasan en primer lugar por ahí y como sólo es sumar texto y python se lo curra bastante rápido, pues eso, a saco. No había pensado en las urls locales pero creo que tiene remedio. Tampoco había pensado en lo no usar el nombre del canal, puto tv-vip :) Buen apunte.

Pero bueno, lo importate es que se ha castado la idea y por lo que he visto se puede llegar a una buena solución.

Personalmente pienso implentar en todos los canales y conectores httptools+cloudflare sí o sí y lo mismo con el tema de los fanarts y thumbnails para todos los canales, también sí o sí. Cloudflare de está poniendo de moda y un problema más que me quito, casi que me daría igual que lo pongan, no me voy a enterar 😃 Eso sí, posiblemente cambie el método para los fanarts y thumbnails con las conclusiones que salga de todo esto si es que lo véis como algo que se pueda usar para no estar pendiente de si implementa cloudflare o no.

**Comment by divadres** [comment]
Estoy dandole vueltas a una idea... cuando se carga httptools automaticamente carga todas las cookies en memoria... puedo añadir una funcion get_headers_from_url(url) que devuelva la url con los headers en caso de existir la cookie... eso si... para q funcione el canal tiene que usar las cookies por defecto...

**Comment by r0balo** [comment]
Estaría bien. Yo pienso igual que tu, con htmltools ya no es necesario añadir headers a los canales. Los que hay está muy bien puestos. También es cierto que cuando intentamos atajar para extraer urls tenemos que lidiar con headers un pelin diferente para sacarles los datos a ciertar páginas por la vía rápida.

**Comment by divadres** [comment]
Añadido PR con una prueba de como quedaría, parece funcionar correctamente.

**Comment by r0balo** [comment]
Ya lo he puesto en el PR pero lo repito por aquí también, perfecto por lo que he podido probar.

Muchas gracias

**Comment by SeiTaN** [comment]
@tvalacarta o @r0balo esto ya se puede cerrar que el PR al que hace referencia está mergeado 😉
