### ISSUE TITLE
Fallo al añadir serie que existe en imdb

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#577]
Por el foro reportan un caso de una serie que no se agrega a la biblioteca cuando si debería hacerlo.

La seríe es `Occultic;Nine` se puede hacer la prueba desde `animeflv_me`

Según he visto no se obtiene el valor infoLabels['code']

### Llamada a tmdb con la serie que si existe

> 21:58:54.377 T:14704  NOTICE: pelisalacarta.core.tmdb [__by_id] [Tmdb.py] Buscando id_Tmdb: 68185:
>                                             http://api.themoviedb.org/3/tv/68185?api_key=f7f51775877e0bb6703520952b3c7840&language=es&append_to_response=images,videos,external_ids,credits&include_image_language=es,null

### Trazas de respuesta de scraper y valor de item
> 21:58:54.684 T:14704  NOTICE: ######## DEBUG #########
> 21:58:54.684 T:14704  NOTICE:     [pelisalacarta.core.library.save_library_tvshow] scraper return True
> 21:58:54.685 T:14704  NOTICE: ######## DEBUG #########
> 21:58:54.685 T:14704  NOTICE:     [pelisalacarta.core.library.save_library_tvshow] item 
> 	action= 'episodios'
> 	category= ''
> 	channel= 'animeflv_me'
> 	contentSerieName= 'Occultic;Nine'
> 	contentThumbnail= 'http://image.tmdb.org/t/p/original/4pJgFnDOA3yd6GrF7Xi34CZab0I.jpg'
> 	contentTitle= 'オカルティック・ナイン－'
> 	contentType= 'tvshow'
> 	extra= 'episodios'
> 	fanart= ''
> 	hasContentDetails= 'true'
> 	infoLabels= {'IMDBNumber': None,
> 		'aired': '08/10/2016',
> 		'castandrole': [('Ayane Sakura', 'Ryouka Narusawa (voice)'), ('Kishou Taniyama', 'Kiryuu Kusakabe (voice)'), ('Miyuki Sawashiro', 'Aria Kureinaino (voice)'), ('Yuuki Kaji', 'Yuuta Gamon (voice)')],
> 		'country': 'JP',
> 		'director': 'Kyohei Ishiguro',
> 		'genre': 'Animaci\xc3\xb3n, Sci-Fi & Fantasy, Misterio',
> 		'homepage': 'http://occultic-nine.com/',
> 		'imdb_id': None,
> 		'last_air_date': '2016-12-24',
> 		'mediatype': 'tvshow',
> 		'number_of_episodes': 11,
> 		'number_of_seasons': 1,
> 		'original_language': 'ja',
> 		'originaltitle': '\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x86\xe3\x82\xa3\xe3\x83\x83\xe3\x82\xaf\xe3\x83\xbb\xe3\x83\x8a\xe3\x82\xa4\xe3\x83\xb3\xef\xbc\x8d',
> 		'popularity': 0.245312,
> 		'premiered': '08/10/2016',
> 		'rating': 8.0,
> 		'status': 'Ended',
> 		'thumbnail': 'http://image.tmdb.org/t/p/original/4pJgFnDOA3yd6GrF7Xi34CZab0I.jpg',
> 		'title': '\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x86\xe3\x82\xa3\xe3\x83\x83\xe3\x82\xaf\xe3\x83\xbb\xe3\x83\x8a\xe3\x82\xa4\xe3\x83\xb3\xef\xbc\x8d',
> 		'tmdb_id': 68185,
> 		'tvdb_id': 316332,
> 		'tvshowtitle': 'Occultic;Nine',
> 		'type': 'Scripted',
> 		'url_scraper': 'https://www.themoviedb.org/tv/68185',
> 		'votes': 1,
> 		'year': 2016}
> 	thumbnail= 'http://image.tmdb.org/t/p/original/4pJgFnDOA3yd6GrF7Xi34CZab0I.jpg'
> 	title= 'Añadir serie a la biblioteca'
> 	totalItems= 0
> 	url= 'http://animeflv.me/Anime/11637/occultic-nine-2016/'
> 21:58:54.685 T:14704  NOTICE: ######## DEBUG #########
> 21:58:54.685 T:14704  NOTICE:     [pelisalacarta.core.library.save_library_tvshow] NO ENCONTRADO EN SCRAPER O NO TIENE IMDB_ID

@superberny70 ¿puedes echarle un ojo que tu controlas más de esto?

Gracias.

**Comment by CmosGit** [comment]
@SeiTaN, creo que es porque en tmdb no se ha asociado una id de imdb a esa serie. Aunque la serie exista en imdb, si tmdb no la asocia es como si no existiese. Intenta cargar la url de la llamada y verás que es null:

`"external_ids":{"imdb_id":null,"freebase_mid":null,"freebase_id":null,"tvdb_id":316332,"tvrage_id":null}`

**Comment by SeiTaN** [comment]
cagon ros 😞 y ¿ahora que hacemos? Ahí no podemos hacer nada, a menos que se cambie `library.py` para que tb permita el tmdb_id o tvdb_id y mi scraper aún está en pañales 😆 

Gracias @CmosGit

**Comment by neno1978** [comment]
Totalmente correcto , hay bastantes series sin id de IMDb asociado en tmdb , relativamente hablando en lo de "bastantes". Y si se depende ello, en estos casos fallara ...

**Comment by neno1978** [comment]
Es lo que os iba. A preguntar desde el desconocimiento. Xq es imprescindible el id de IMDb ? 😜

**Comment by SeiTaN** [comment]
Si no me falla la memoría lo puso así "tu primo", ya que themoviedb y otros sitios web enlazan con imdb y así se evitaba añadir series repetidas.

**Comment by CmosGit** [comment]
> cagon ros 😞 y ¿ahora que hacemos? Ahí no podemos hacer nada, a menos que se cambie library.py para que tb permita el tmdb_id o tvdb_id y mi scraper aún está en pañales 😆

No he mirado punto por punto todos los pasos que sigue la biblioteca al añadir una serie, pero entiendo que comprueba si en ésta ya existe esa serie mirando si en el nombre de la carpeta se encuentra la id de imdb, por lo que imagino que se podría hacer lo mismo con la de tmdb_id, como una comienza por tt y otra es completamente numérica se pueden distinguir fácilmente.

**Comment by superberny70** [comment]
> Xq es imprescindible el id de IMDb ?

Bueno, al idear la biblioteca multicanal vimos q podiamos encontrarnos una serie con diferentes nombres dependiendo del canal. Alguno solo cambiaba por una tilde, o se ponia titulo y subtitulo (me lo invento "Roma. Caida de un imperio" vs "Roma"), o se utilizaba el nombre original vs al traducido, etc,..
Por eso necesitabamos algun tipo de codigo q identificara un contenido (serie o pelicula) independientemente de su titulo. Podriamos haber obtado por el id de tmdb o el de tvdb (hubo mucho debate sobre esto), pero finalmente creo q la base mas popular es imdb (ademas desde cualquier otra bd se obtiene el id de imdb facilmente.
Esta claro q nos podemos encontrar con casos en los q la serie no este en tmdb o incluso (como en este ejemplo) q aun estando en tmdb y tvdb no tenga codigo imdb. La idea inicial era crear un metodo para añadir estos casos especiales, lo q pasa es q esto se quedo un poco en el aire (Seitan comenzo su scraper tvdb y yo paralice el tema) y preferimos publicar lo q teniamos q cubre la inmensa mayoria de los casos.

**Comment by SeiTaN** [comment]
De momento para evitar esto se me ha ocurrido que si pasa esto, el addon te permita buscar la misma serie con otro scraper o cambiar el nombre, parecido a lo que actualmente hace, pero que si no se obtiene el id de imdb desde el scraper que tiene (en este caso tmdb) a otros futuros que existan.

**Comment by neno1978** [comment]
Buaf , menuda parrafada que se da el primo para escusarse... ostia! Que esto no está en privado 😂😂😂😂
No , en serio, es normal. Es imposible trincar la infinitud de casos que pueden llegar a darse con la inmensa variabilidad que podemos encontrarnos . Entiendo lo de IMDb y es lógico y lo más razonable. Que también se puede poner "redes" para este tipo de "excepciones" pos también, pero ; que no es memorable amen de una buena Cruz Campo Glacial ❓😜
Eso sí , lo de añadir sin is generando un código me parece una idea bestial, trabajosa y mucho, pero bestial

**Comment by neno1978** [comment]
Lo de cambiar el nombre , sin querer ser duro, creo que acabaría con más dolores de cabeza para la gente , me parece muy bien lo de otro scraper ;)

**Comment by superberny70** [comment]
Para este caso concreto, el contenido existe en tmdb e imdb, pero no estan asociado se puede hacer: https://www.google.es/search?q=Occultic%3BNine%20site%3Aimdb.com y mediante regex obtener el id.

**Comment by neno1978** [comment]
Cuidadin con google primo. Se puede hacer , pero no abusar , porque el captcha te salta muy pronto , pero mucho

**Comment by superberny70** [comment]
Vaya primo!!! coji la idea de algo tuyo y de @r0balo q me he acordado q lo vi hace tiempo.
Pues nada si es asi olvidaros de google

**Comment by neno1978** [comment]
Por eso te lo digo primo, yo lo uso en mi "autista" manera de obtener los ids en mis canales pero deseche Google por eso mismo. Opté por bing que hay que bombardearlo cada 5segundos para que pete, tendríamos que hacer más de 20busquedas en menos de 10 segundos, que parece que es el tiempo que tiene como resorte, para q petase , y aún así no salta captcha , pero da resultados erróneos y tarda 24h en volver a la normalidad. Yo lo conseguí controlar xq localize una diferencia en el código entre si está fallando y no , y , cuando pasa , le meto un proxy. Pero ya te digo , un relio 😜
Aunque también te digo : cuántos casos se van a dar como este para que salte Google o bing? 😜

**Comment by malkavi** [comment]
Por curiosidad, para casos especiales como este, no se puede hacer nada "a mano"? Que en la versión anterior me dio por crear el tvshow a mano con la url del canal y listo. Incluso no se si sería mucha molestia meter a mano los id de imdb o tmdb si faltan cuando agregas una serie con estas pegas.

**Comment by SeiTaN** [comment]
@malkavi si es para esta serie se podría hacer un apaño, pon antes del "if not scraper_return or not item.infoLabels['code']:"
`item.infoLabels['code'] = "tt6135350"`

Añades la serie y luego quitas la línea, creo que con eso se arreglaría el problema.
