### ISSUE TITLE
formato incorrecto de cadena de texto para format en python 2.6

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#58]
Tengo un mac de 32bits con xbmc gotham y el Kodi Helix de 32 bits no arranca. La versión de Gotham viene con Python 2.6 y los cambios en el archivo xbmctools.py para usar format dan error porque hasta la versión 2.7 se necesitaba que las llaves tuvieran un número de posición.
Para que funcione habría que cambiar los {} en las cadenas de texto por {0}, {1}, {2}, {3}.

Es un poco coñazo pero si no se hace así no funciona con python 2.6 y, en principio, esa sintaxis es compatible con versiones más altas de Python.

**Comment by SeiTaN80** [comment]
He hecho un pull request, falta la aprobación de Jesús y que todo esté correcto.

Saludos.

**Comment by ChopChopKodi** [comment]
En la documentación pone que la posición de los parámetros empieza desde cero y tú has empezado desde 1. Probablemente los parámetros estén corridos 1 lugar, aunque no lo he probado e igual funciona si el número de parámetros corresponde con los parámetros de la cadena

https://docs.python.org/2.6/library/string.html#format-examples

**Comment by SeiTaN80** [comment]
mierda, no me di cuenta sorry, lo arreglo xD

**Comment by SeiTaN80** [comment]
@tvalacarta o @ChopChopKodi por favor cerrar el "issue", que ya está subido.

Gracias.
