### ISSUE TITLE
Eliminar librerias que no se usan

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#583]
Buenas, estoy mirando maneras de aligerar el addon de cosas que no son necesarias y lo principal son las librerias, versiones antiguas que en su día tenían razón de ser y ya no. He recuperado parte de un post que publique en el foro con lo que hay.

Paso el listado de lo que tenemos actualmente y donde se encuentra y debatir si se quita o no.

Como ya se dijo en su día que para que funcione el addon en todas las plataformas se debe usar python 2.4 dejo marcadas las librerías que recuerdo que son necesarias.

## Lib
- [x] Crypto, 128 KB. **Necesaria para conector Mega**
- [x] _**atom, 188 KB. relacionado con gdata y elementree. no se usa. ELIMINADO**_
- [x] _**bencode, 4 KB. ELIMINADO**_
- [x] btserver ,132 KB. **Necesaria para torrent**
- [x] _**cerealizer, 24 KB. no se usa. ELIMINADO**_
- [x] _**elementtree, 104 KB. relacionado con gdata y atom. no se usa. ELIMINADO**_
- [x] _**gdata 980 KB,  relacionado con elementtree y atom. no se usa. ELIMINADO**_
- [x] mechanize, 1,10 MB. usado en varios canales.
- [x] megaserver,  36 KB. **Necesaria para conector Mega**
- [ ] pafy, 56 KB. ***PENDIENTE @tvalacarta 
- [x] requests, 1,58 MB. usado en varios canales.
- [x] sambatools, 1,14 MB. **necesario**
- [x] simplejson, 104 KB **necesario**
- [x] aadecode, 4 KB. **usado en openload y videowood.**
- [x] jjdecode, 12 KB. **se deja por posible uso en un futuro**
- [x] jsinterpreter, 8,44 KB. **Se usa en el conector de youtube, necesaria para vídeos encriptados.**
- [x] libtorrent, 2,31 MB. **Necesaria para torrent**
- [x] _**png, 124 KB. ELIMINADO**_
- [x] unshortenit, 12 KB. **librería muy útil para acortadores de enlaces**

## Core

- [x] _**aes, no veo referencia y hay otro dentro de Crypto. ELIMINADO**_
- [x] _**unwise, no se usa. ELIMINADO**_

Si veis alguna cosa mal o quereís agregar algo, por favor comentadlo.

Gracias.

**Comment by divadres** [comment]
Mi aporte:

- [x] megaserver, 36 KB. **Necesaria para conector Mega**
- [x] Crypto, 128 KB. **Necesaria para conector Mega**
- [x] btserver ,132 KB. **Necesaria para torrent**
- [x] libtorrent, 2,31 MB. **Necesaria para torrent**
- [ ] bencode, 4 KB. **No se usa ya incluida dentro de libtorrent**

**Comment by SeiTaN** [comment]
Gracias, ya está actualizado 👍

**Comment by CmosGit** [comment]
De las que conozco o he usado además de las que dice @divadres:
 

- [X] Crypto: También se usa en el conector de crunchyroll.
- [X] requests: No es indispensable teniendo ahora httptools, pero en mi opinión se debería conservar por su multitud de opciones.
- [X] aadecode: Se sigue usando en openload y videowood.
- [X] jjdecode: Ha dejado de usarse en openload que fue para lo que se añadió, pero es un tipo de ofuscación que otros servidores también utilizan y pienso que no está de más tenerla.
- [X] jsinterpreter: Se usa en el conector de youtube, necesaria para vídeos encriptados.
- [ ] png: La añadí por una modificación de openload para manejar imágenes de ese formato, se puede eliminar.
- [X] unshortenit: Se usa poco pero creo que es una librería muy útil para acortadores de enlaces.

**Comment by r0balo** [comment]
os olvidáis del Señor packe[r/d], creo que es uno de los tipos de ofuscación más utilizados :)

**Comment by SeiTaN** [comment]
> os olvidáis del Señor packe[r|d], creo que es uno de los tipos de ofuscación más utilizados :)

vale, "jsunpack" pero ese está en core, creo que lo moveré a lib para evitar jaleos, y mirando tb en **core** he visto algunos que no se para que se usan.

- [ ] aes, no veo referencia y hay otro dentro de Crypto.
- [ ] unwise, no se usa

**Comment by superberny70** [comment]
Ya q estasis moviendo librerias  recordad q habia problemas en algunos sistemas al importar estas libreria por q cojian las del sistema (o algo asi recuerdo haber leído en el foro)

**Comment by SeiTaN** [comment]
> Ya q estasis moviendo librerias recordad q habia problemas en algunos sistemas al importar estas libreria por q cojian las del sistema (o algo asi recuerdo haber leído en el foro)

Creo recordar que lo arregló @divadres, aparte estoy poniendo `from lib import xxxx`, de momento solo he movido una librería, el resto no ha hecho falta aún hasta que se confirme.

**Comment by SeiTaN** [comment]
Voy a subir el PR, lo que falta es por saber si se va a seguir usando mechanize y requests, que me parece que fue @neno1978 el que lo puso, si no lo dejo tal cual sabiendo que los canales que lo usan no irán en plataformas antiguas.

Además faltaría pafy que se usa para youtube.

**Comment by neno1978** [comment]
Realmente request solo lo usaba bricocine y lleva caído desde "cheketito" , si resurge se puede adaptar a lo nuevo ;) , aunque mi opinión es que request tiene muchas funciones. Eso sí, no me toques mechanize o lloraré como una magdalena 😂😂

**Comment by SeiTaN** [comment]
> Eso sí, no me toques mechanize o lloraré como una magdalena 😂😂

a borrar!!! 😈 

Lo marco entonces.

**Comment by neno1978** [comment]
😂😂😜
