### ISSUE TITLE
[Sugerencia] Que los logs error salgan siempre

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#589]
Actualmente nos encontramos con que sale un error, Pelisalacarta te dice "Mira los logs" y... oh wait:

    if loggeractive:
Resulta que los logs hay que activarlos previamente... cualquier log.
Lo habitual, incluso en Python, es tener diferentes niveles de logs, hasta aquí lo replicláis... más o menos:
info()
error()
debug()

Que actualmente su única diferencia es que INFO escribe el texto y los otros 2 ponen encima una linea extra (ver mi PD para ver que opino de esta linea).

Lo que vería más normal sería que se usara el mecanismo de prioridades de python y Kodi, o en su defecto, que se usara uno propio, pero que no sea un "activo todos los log" o "no activo nada".

Pero con lo que hay ahora creo que los logs errors deberían estar siempre visibles, ya que si no se queda todo oculto si no se han activado previamente, y si los activas está en modo debug y sale mucha cosa. Por eso ¿porque ocultar los logs errors?

PD: Y aprovecho para indicar lo mal que me parece que está el tema del formateado del log. Pones 3 lineas en debug y sale:
***** DEBUG*****
l1
***** DEBUG ****
l2
**** DEBUG *****
l3

Cuando vería mucho más natural un
[priority] texto

[DEBUG] l1
[DEBUG] l2
[DEBUG] l3

**Comment by SeiTaN** [comment]
Al tema del log hay que darle una pensada, estaba en proyecto hacer un sistema automático.

**Comment by superberny70** [comment]
Yo tb creo q deberia mejorarse este aspecto. Hace algun tiempo hice algunas propuestas (en petit comite). 

- La primera era dejar activo siempre el log (loggeractive=True siempre), pero me explicaron q en algunos sistemas esto volvia muy lento al plugin. 

- Mi segunda propuesta se basaba en un sistema de niveles: Debes pensar q hasta hace relativamente poco solo se usaba logger.info para todo (las otras dos funciones existian pero hacian exactamente lo mismo q info), esto unido a q hay canales muy 'parlanchines'  (por ejemplo copiando toda la web descargada al log) hacia q al introducir variables de control para debugear o mensajes de error durante la ejecucion, quedasen 'escondidos' dentro del log. Por eso obte por modificar las funciones debug() y error() para anteceder una linea q sea bien visible al ojear el log (posteriormente se incluyo la trazabilidad en los errores y la identificacion de la funcion desde donde se llama en las tres funciones).
Esta segunda opcion mas o menos es la q tenemos actualmente, aunq depende mucho de como q los creadores de canales la utilicen. Esto mismo sucede con la tercera de mis propuesta (q no llego a implementarse)

- La tercera propuesta es el sistema de prioridades q tu indicas: En las preferencias en lugar de un booleano para activar o desactivar tendriamos 3 niveles:

    - Nivel 1: Solo se escribirian en el log los errores (logger.error())
    - Nivel 2: Se escribirian en el log los errores y los mensajes informativos (logger.error() y logger.info())
    - Nivel 3: Estaria reservado a la depuracion de errores y las 3 funciones escribirian en el log

Como he dicho para q esto funcione realmente es necesario q los creadores filtremos un poco q tipo de contenido es lo q queremos añadir al log, y q informacion puede ser util añadir, cual no deberia incluirse nunca (por ejemplo user/pass) y cual es redundante o solo es util en determinados caso.

Por otra parte, hay otra propuesta q complementaria a esta y q hace tiempo comenzo a gestarse, pero no se por q parece q se ha quedado un poco en el fondo del saco #310 y #350. Creo q deberiamos continuar desarrollando esa idea.

PD: Siento q no te guste el formateo de DEBUG :weary:, pero a q las encuentras a la primera cuando te desplazas rapidamente por el log con AV.Pag?? :yum::yum::yum:

**Comment by Palatosino** [comment]
Si, se ven, hasta que ves:
******* DEBUG *********
Item 1
******** DEBUG ********
Item 2
******** DEBUG ********
Item 3
******** DEBUG ********
Item 4
******** DEBUG ********
Item 5

Solo por usar log.debug en cosas que son realmente debug. Al final dan ganas de ponerlo log.info y volvemos al caso de "los canales no usan bien los niveles de log".

Por otro lado, lo veo aun mejor con un "/DEBUG.*" :laughing: 

Aun así una cosa es poner un sistema de envio de logs, cosa que tampoco creo que sea muy necesaria, y otra que los logs reales (lo que se escribe al archivo de log) o salga todo (log activado) o no salga nada, ni errores (log desactivado).

Obviamente lo ideal es el 3º punto, es como está en todos lados. El propio logging de python o cualquier cosa tiene niveles de log.
Lo que no es aceptable es el primer punto. El log menos verboso (no desactivado) debería mostrar errores (errores reales) y tal vez pondría como extra un "info" de que cosas se añaden a la biblioteca. El resto, todo log.debug()

Pero bueno, abrí esto más que nada porque ayer me salió de golpe en la raspberry "Error en pelis a la carta, revisa el log", fui a mirarlo... y no había nada. Normal, allí lo tengo desactivado. Por eso pensé que, al menos (sin tener que cambiar todo el sistema) los log.error podrían escribirse siempre.
