### ISSUE TITLE
Seriesblanco no muestra los enlaces

### ISSUE THREAD

**Issue by ivanguasch** [tvalacarta/pelisalacarta#59]
Desde el 8 de noviembre Seriesblanco presenta un error. Actualiza correctamente las series pero falla cuando se selecciona un determinado capítulo y debe mostrar los enlaces disponibles.

Parece que falla cuando va a hacer el get_match de los enlaces online.

Adjunto fichero de registro con el error.
[kodi.log.txt](https://github.com/tvalacarta/pelisalacarta/files/32191/kodi.log.txt)

**Comment by ChopChopKodi** [comment]
Parece que han cambiado la forma en la que muestran los archivos en la web.
Ahora se hace una llamada ajax que por el código del plugin antes no debía estar.
He conseguido hacer la nueva llamada y, si no se resiste, espero capturar los elementos para hoy.

**Comment by SeiTaN80** [comment]
@tvalacarta por favor cierralo, @ChopChopKodi ya lo arregló.

Gracias.

**Comment by tvalacarta** [comment]
Visto, gracias :)
