### ISSUE TITLE
Versiones XBMC/KODI

### ISSUE THREAD

**Issue by divadres** [tvalacarta/pelisalacarta#599]
Actualmente pelisalacarta está para las versiones de xbmc/kodi de la 9 a la 17. Yo de tanto en tanto voy instalándolas todas y comprobando que funcione correctamente en cada una de ellas, todas menos XBMC 9 ya que no está disponible para la descarga en la web de kodi.

Después de rebuscar un poco por internet la he encontrado y me ha dado por probar, como era de esperar no funciona, directamente ni se abre, he estado revisando el código y no es muy difícil de arreglar, ya que el problema esta en:
 - logger.py (simpliemente con elminarlo el logger de kodi 17 funciona perfectamente)
 - config.py (hay que hacer algunos cambios nada complicado)
 - xbmc_config_menu.py (cuatro cambios en algún que otro control)
 - settings.xml (no admite las categorías, simplemente eliminarlas y juntar todo los controles)

Con estos cambios parece funcionar, incluso la ventana de configuración pero (todo tiene un pero) me surge un problema que no acabo de ver claro de tanto en tanto (creo que cuando cargo listados grandes) me da un error "XBMC Media Center dejó de funcionar" y se cierra y lo único que muestra el log es: `18:21:53 T:2888 M:1575227392   ERROR: Stat: fd == -1`

**Lo cual me lleva a preguntarme:** 
¿Merece la pena perder el tiempo en intentar arreglarlo?
¿Hay alguien que use esta versión, si nadie se ha dado cuento de que no funciona?

Si alguien sabe algo, quizá @tvalacarta, respecto a que versiones de XBMC siguen usándose en algún aparat , por que no permita actualizar, y cuales no, quizá no tiene mucho sentido mantener una compatibilidad con versiones que nadie usa...

**Comment by kerenmac** [comment]
Este problema es el típico, incluso con Kodi (mirad sino la que han montado por que Kodi 17 no da soporte a Android KitKat), el problema es que normalmente tener que dar soporte para muchas plataformas es lo que impide avanzar sin limites, pero entiendo la necesidad del sistema multi-plataforma.
Ya que se ha abierto el tema voy a preguntar algo relacionado: Cuando empece a conocer el addon y me atreví a "meterle mano" al código recuerdo tener que andar poniendo en todos lados "if config.is_xbmc()" ya que debía ser compatible con todas las plataformas y los módulos específicos de kodi-xbmc no existen en todas. Ahora mismo puedo ver canales y otros archivos que hacen imports de platformcode o directamente hacen "import xbmc" sin comprobar que la plataforma sea "xbmc".  Mi pregunta es: Hay que seguir haciendo las comprobaciones oportunas? Hasta que punto "main-classic" comparte "cosas" con otras plataformas no-xbmc? Que limitaciones impone mantener la compatibilidad (las mas importantes al menos)?
Gracias.

PD: Si fuera por mi iría quitando la compatibilidad con plataformas muy antiguas que nadie usa (alguien sigue usando XBMC <13?). Por otro lado, si las versiones de plataformas que no se han actualizado desde hace mucho no van a tener soporte yo avisaría de que puede que no funcione nada, para que el foro no se llene de la misma pregunta y los usuarios sean conscientes de ello a la hora de descargarla.

**Comment by divadres** [comment]
config.is_xbmc solo es necesario para utilizar librerías propias de kodi, (yo personalmente soy de la opinión que en canales no hay ninguna necesidad de ponerlas usarlas) pero que un canal no funcione en una determinada plataforma o versión es "asumible" ahora bien, si no funciona nada eso ya es algo que hay q mirarlo.

El objetivo de este hilo es averiguar que versiones de xbmc se siguen usando en la actualidad puedo entender que se de soporte para una versión si hay determinada plataforma/equipo que no permite actualizar a una versión superior ya sea por limitaciones de hardware o de otro tipo, pero mantener compatibilidad con versiones obsoletas si NADIE las usa me parece una tontería. y quien mejor puede saber eso es @tvalacarta mirando cuantas descargas han habido en, por ejemplo, el ultimo año de cada una de las versiones, o bien conociendo los aparatos que pueden instalar kodi y viendo que limitaciones de versión tiene, yo principalmente desconozco que versiones se pueden instalar en las antiguas Xbox por ejemplo...

**Comment by tvalacarta** [comment]
Los unicos que podrían usar XBMC 9 a estas alturas son los usuarios de XBOX que se han resistido a pasar a xbmc4xbox, que integra ya cosas de versiones anteriores.

De todas formas si los cambios son sencillos yo no eliminaría ese soporte, tampoco cuesta tanto. Si falla en listados grandes los que lo usen ya sabrán donde no entrar (si todavía usan la XBOX son gente dura ja ja ja).

En cuanto al soporte de otras plataformas y versiones anteriores que comenta @Palatosino , por supuesto que voto por mantenerlo. Mi madre aún tiene XBMC 10 en su Apple TV, sin ir más lejos, y conozco varios casos así :)

**Comment by divadres** [comment]
Lo pregunto justmente por eso, he llegado a la conclusion que el fallo que da es un bug de python que solo afecta a wibdows... asi q en las xbox es muy probable que funcione bien... pero yo no puedo probarlo...

**Comment by superberny70** [comment]
cerramos?
