### ISSUE TITLE
Error en servertools.py 

### ISSUE THREAD

**Issue by kerenmac** [tvalacarta/pelisalacarta#603]
Hola, a cuenta de los últimos cambios en powvideo.py se ha modificado el xml y aparece un error al intentar usar powvideo. El error tiene origen en servertools.py, en la función XML2Dict. En la linea 358 pone `return_dict[tag] = [dct[tags[x]]]` y da error por que no existen ni "dct" ni "tags" ni "x". Parece que al cambiarlo por `return_dict[tag] = [return_dict[tag]]` funciona correctamente.

Dado que se va a liberar la beta 3 creo que seria conveniente arreglarlo antes.
Un saludo.

**Comment by CmosGit** [comment]
Gracias por ver el fallo @kerenmac 😉 La verdad es que no me había parado a probar el cambio en los xml en mi pelisalacarta, supongo que se debe a los tags change para enumerar los cambios que se propuso usar porque los otros cambios son los habituales. Pensaba que esos tags funcionarían bien tanto en los canales como en los conectores, no contaba con esa función xD

**Comment by SeiTaN** [comment]
Yo sigo pensando que se podría dejar  json por xml ahora que todo va por diccionario vendría muy bien y no tendríamos que hacer conversiones durante la ejecución del código 😉

**Comment by kerenmac** [comment]
Cierro. En el PR #613 queda solucionado.
