### ISSUE TITLE
Fallo en tmdb.py cuando no encuentra resultados

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#61]
Al buscar, por ejemplo, el documental Fulboy con el nuevo código de TMDb me da este error 

*TypeError: cannot concatenate 'str' and 'NoneType' objects*

en la línea 358 de core/tmdb.py.

**Comment by SeiTaN80** [comment]
Un pequeño truco, si pinchas sobre la línea y das botón derecho "copiar dirección" (el nombre dependerá del navegador), obtienes la ruta para enlazar la línea directamente.

https://github.com/tvalacarta/pelisalacarta/blob/master/python/main-classic/core/tmdb.py#L358

**Comment by ChopChopKodi** [comment]
github está lleno de sorpresas. Gracias

**Comment by superberny70** [comment]
En cuanto pueda subo la correccion

**Comment by superberny70** [comment]
mira #74

**Comment by superberny70** [comment]
Esto ya se puede cerrar.

**Comment by SeiTaN80** [comment]
Si pones en el titulo de lo que subes "Fix #numero_issue blablabla...", cuando se mergea el codigo, se autocierra el issue, o al menos eso pone en los tutoriales de GitHub :wink:
