### ISSUE TITLE
Añadir atajo a canales configurables por menu contextual

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#617]
Bueno, como me ha pasado que tener que tocar opciones de un canal y están bastante lejos de cuando se tiene probar (dentro del apartado configuración).

He pensado que estaría bien de poder añadir una opción en el menú contextual.
![image](https://cloud.githubusercontent.com/assets/11775029/22622052/84d8e38c-eb31-11e6-95af-c740389f234e.png)

Si mola la idea lo monto, que más o menos lo tengo todo buscado.

**Comment by Palatosino** [comment]
A mi me gusta la idea. Sería más natural que tener que ir a configuración -> seleccionar el canal.

**Comment by SeiTaN** [comment]
@Palatosino ¿Podrías probar mi rama https://github.com/SeiTaN/pelisalacarta/tree/listado_datos_xml?
Es una primera parte del desarrollo #652 que he hecho para implementar esto, he hecho pruebas de rendimiento y no noto la diferencia, se que en tu caso no recuerda si ubuntu o raspberry pi te va más lento, a ver que te sale.

## Versión actual (develop)
### Acceder por primera vez al addon

inicio 21:04:45.415
fin 21:04:45.740

**300 mseg**

### Ya dentro
inicio 21:05:36.765
fin 21:05:37.093

**300 mseg**



## Usando fichero común json

### Acceder por primera vez al addon

inicio 21:07:14.070
fin    21:07:14.384

**300 mseg**

### Ya dentro

inicio 21:01:55.157
fin 21:01:55.471

**300 mseg**

**Comment by SeiTaN** [comment]
Bueno estoy mirando esto y he visto que la manera de mostrar la opción en la lista del canal es con esta condición
```python
if parent_item.channel == "channelselector" and parent_item.action == "filterchannels":
```

Tengo una idea de como ponerlo en todo el canal y no sólo al inicio como era mi deseo inicial, pero me gustaría saber si se os ocurre otra idea de manera que quede más simple.

**Comment by superberny70** [comment]
Esa condicion supongo q habras pensado ponerla dentro de platformtools.set_context_commands ¿no?
Tambien podrias ir al origen... ¿por q no añadirlo directamente al crea el item dentro de channelselector.filterchannels? 

Otra cosa es q no todos los canales tiene configuracion, asi q ademas de saber donde añadirlo o poner la condicion q dices, deberas saber si el canal en cuestion tiene o no configuracion. Puedes ver como esta hecho en mainlist del canal configuracion.py Aunq si yo lo tuviese q hacer reescribiria las lineas L98-113 de esa funcion y las incluiria dentro de channelstools dentro de una nueva funcion que retorne True si el canal pasado como argumento esta activo y tiene settings q no sean los 'include_in_xxx'

**Comment by SeiTaN** [comment]
@superberny70 si, va en set_context_commands.

Referente al incluirla en el origen lo he pensado, pero habría que modificar el elemento item en todos esos canales y meterle el item.clone(), aunque quizás sea eso lo menos complicado.

De paso he reescrito channelselector por que hay código que no hace falta en otras cosas, miraré de adaptar la función en channeltools, gracias.
