### ISSUE TITLE
Revisar navegación del addon, que hay veces que se resetea.

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#618]
Esto lleva pasando desde hace relativamente poco.

Hay veces que entras en alguna opción o das hacia atrás y se sale del addon.

**Comment by divadres** [comment]
eso pasa con kodi 17, creo que es cuando le das muy rápido y aun no ha terminado de cargar del todo, no creo que sea cosa de pelisalacarta...
