### ISSUE TITLE
Sugerencia para TMDb

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#62]
Igual se podría hacer que si no hay sinopsis, o algún otro dato interesante, en español buscara en inglés directamente, porque hay pelis que no tienen traducción y me parece un poco guarro tener que comprobar siempre si no devuelve datos para volver a hacer la petición.

**Comment by superberny70** [comment]
Si, ya lo había pensado. A ver si saco algo de tiempo y me pongo

**Comment by superberny70** [comment]
mira #74

**Comment by superberny70** [comment]
Esto ya se puede cerrar.
