### ISSUE TITLE
cineblog (IT) en rama develop

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#621]
Actualmente aparece un cineblog (IT) en la rama develop (por lo tanto la que dentro de 2 o 3 meses será la beta 3 :rofl: ) que tampoco parece estar funcionando muy bien (es posible que la web no funcione, ni lo he mirado).

Tenía entendido que se habían sacado los canales extranjeros (y en especial italianos, que ya tienen un fork).

Me he dado cuenta de su existencia al hacer una búsqueda y ser el último canal que se se muestra, y se queda un buen rato (supongo que hasta que retorna algún timeout, error o algo así).

**Comment by SeiTaN** [comment]
crea un PR y borra los dos ficheros 😛
