### ISSUE TITLE
Poner como valor por defecto de "novedades" el uso de threads

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#622]
Por defecto la sección novedades desactiva los threads. ¿Tiene algún sentido? ¿Tiene sentido ni siquiera que esto sea configurable?

Activar el uso de threads da un speed up importante gracias a la cantidad de IO que hay (las peticiones web).

Y relacionado con esto ¿se le podría poner algún mensajito como el de la búsqueda? algo que muestre el estado y no parezca que se queda colgado.

PD: Como podéis adivinar con los 2 puntos, probé la sección novedades (sin configurar threads) en la Raspberry y parecía que se había colgado. Entre que tarda mucho y solo sale el circulito de "cargando"... Al final salieron los resultados, y configuré lo de los threads para que vaya más rápido, aun así, al ser algo un pelín lento, que usara lo mismo que la búsqueda (al fin y al cabo debe ser lo mismo: iterar por todos los canales y llamar a un método para recopilar sus resultados) y fuera mostrando que canales está procesando.

**Comment by superberny70** [comment]
La, configuración multihilos se puso por q cuando comenzamos a utilizar los hilo se nos dijo q en algunos dispositivos  podríamos  tener problemas.  Aunq la verdad es q nadie se ha quejado.  Personalmente votaria por dejarlo siempre activado. 

Respecto a los mensajes,  lo puedo mirar,  pero no te digo cuando,  se me acumula el trabajo jejejeje

**Comment by superberny70** [comment]
Ya podemos cerrar esto
