### ISSUE TITLE
Update_url

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#623]
Normalmente en los canales q he visto la rama desde la q se actualizan es la rama master.  Aunque esta rama suele actualizarse con menor frecuencia que la rama develop. 
Propongo que si los cambios solo afectan al archivo py,  se modifique el parámetro update_url señalando la rama develop para q la actualización llegue antes al usuario.

**Comment by CmosGit** [comment]
Pero si modificamos el parámetro update_url en un commit, al usuario le llegará como siempre porque en su xml tendrá puesta la url de la rama master, solo empezaría a funcionar a partir de la siguiente actualización. Y al mismo tiempo, no podemos saber si la siguiente actualización que se haga del canal en develop modificará solo el .py o necesitará de otros archivos para funcionar.

**Comment by superberny70** [comment]
:flushed::flushed::flushed:
Pues tienes razon. Voy corriendo a cambiar mis PR
