### ISSUE TITLE
Permitir varias versiones de un canal

### ISSUE THREAD

**Issue by divadres** [tvalacarta/pelisalacarta#627]
Hola, me surge una duda, hay canales que usan el modulo xbmc y dada su complejidad es difícil ponerlo todo con un try-except, y a pesar de que es una práctica que para nada yo comparto, pero no soy yo quien para decirle al que hace un canal como tiene que hacerlo, me pregunto:

Si quiero hacer que ese canal funcione en otras plataformas tengo dos opciones:
 1. Creo una versión genérica sin tanta "pijada" y machaco la original (y que su creador se cabree)
 2. Creo una versión genérica sin tanta "pijada" y tengo que ponerla manualmente en mi instalación de manera que nadie mas puede usarla.
3. Creo una versión genérica sin tanta "pijada" y buscamos alguna manera de que coexistan las 2 en el sistema pudiendo elegir según plataforma que use una u otra

Por supuesto yo me decantaría por la primera opción , pero por respeto a los demás, creo que podríamos intentar hacer algo para hacer funcionar la tercera, 

no se como lo veis vosotros en especial @tvalacarta, se aceptan sugerencias...

**Comment by SeiTaN** [comment]
Dificil tesitura, yo sería partidario de separar esa parte xbmc intentando contactar con el autor y explicandolo, y que sea llamada como un módulo independiente y que sea configurable, de manera que el canal quedaría de forma sencilla y si alguien quiere algo más y está en kodi puede activar la opción de "pijada" como dices..

Así podría usarse en las dos plataformas y seguiria teniendo la misma funcionalidad que tiene hasta ahora.

Si algún canal que haya hecho yo o tocado te da problemas, dimelo y vemos como arreglarlo 😉

**Comment by superberny70** [comment]
> ...a pesar de que es una práctica que para nada yo comparto...

No me ha quedado muy claro si lo q no compartes es el uso de try...except. Pero en cualquier caso:

- La opcion 3 la descartaria: ahora mismo cuando alguien tiene un problema le tenemos q pedir SO, version kodi, version pelisalacarta y si ha modificado a mano algun canal o fichero. Imaginaros q ademas existan varias versiones de un mismo canal!! Una puta locura!!!

- La opcion 2 es muy de andar por casa y por q no, un poco egoista, me encantan tus propuestas y no quiero q te las reserves solo para ti ;-)

- Por descartes, me quedo con la opcion 1. Todos los canales deberian ser genericos, es decir independiente de la plataforma y si se incluye algo q se sabe q solo va a funcionar en un sistema o, que al contrario, va a fallar en otro. El programador deberia tenerlo en cuenta y poner condicionales o controlar las excepciones. 
Asi pues, yo lo q suelo hacer, es: si se quien es el creador y los cambios son muy radicales comentarselos, sino me lio la manta a la cabeza, tiro "p'alante"  y a esperar a ver quien grita.

Ahora, una cosa te digo, como el canal sea mio, ni se te ocurra tocarlo q me cabreo y me pongo muy agresivo... :triumph: :laughing: :triumph: :laughing: :triumph: :laughing:

PD: La curiosidad mato al :smirk_cat: ¿d q canal estamos hablando?

**Comment by divadres** [comment]
Hay varios pero por ejemplo: bityouth, aquitorrent, bricocine, miltorrents, pasateatorrent, peliculasgratis, torrentlocura, y unos cuantos mas

No son ni uno ni dos, son bastantes, yo como @superberny70 soy de la opinión que los canales deberían ser genéricos, reciben un ítem, y devuelven un itemlist, nada de inventos raros, y si queremos hacer algo especial tipo la famosa "clase textbox" para mostrar una pantalla con información, ¿no es mas lógico, crearla a nivel de platformtools y utilizarla en tus canales si tanto le gusta a alguien eso, en vez de repetir el mismo código en todos los canales?  Veo en todos estos canales infinidad de código repetido que no tiene sentido que este en el canal, mejor dicho en todos los canales, cuando si esta función deja de funcionar, hay que modificar todos los canales para adaptarla de nuevo...

Por ejemplo:
Un canal (ahora no recuerdo cual) que reproduce música de fondo cuando entras en las diferentes pelicualas, en vez de hacerlo mediante usar librerías de xbmc en el canal, añadir un parámetro en el ítem, por ejemplo, "background_sound" y la ruta al archivo de sonido y a nivel de render_items se añade la opción para que si el ítem contiene esa info se reproduzca, así eso sirve para otros canales también, y al mismo tiempo el canal sirve para otras plataformas, y lo mejor de todo, los que no nos gustan esas cosas, podemos desactivarlas sin tener que modificar el canal.

O los "perfiles de color" que tienen algunos canales, no podría hacerse genérico y que, por ejemplo si a alguien le gustan los perfiles de color pues que mediante, yo que se, el contentType? o el action u otro parámetro que se pasara, pues pudieras elegir el perfil de color de los ítems, pero que pudiera servir para todos los canales, así en plataformas donde según que colores no se ven bien, quedaría mejor.


No se, yo pienso que  si nos tomamos en serio lo de las diferentes plataformas, en concreto la versión mediaserver, o se programa pensando de una forma mas genérica o sino es un lio, yo ya no digo que si se cambia algo en cosas comunes como platformtools, ventana de configuración, etc... el que lo cambia tenga que adaptar también las otras plataformas, que seria lo suyo, pero a malas, otro puede hacerlo, pero con los canales es un tema mas delicado porque si le cambias un canal a alguien que lo ha echo de una cierta forma puede molestarse... y resulta que la gente que use la versión mediaserver empezara a decir que si este canal no funciona que si el otro tampoco, cuando podrían funcionar perfectamente...

**Comment by superberny70** [comment]
Voy con lo mio...

> O los "perfiles de color" que tienen algunos canales, no podría hacerse genérico y que, por ejemplo si a alguien le gustan los perfiles de color pues que mediante, yo que se, el contentType? o el action u otro parámetro que se pasara, pues pudieras elegir el perfil de color de los ítems, pero que pudiera servir para todos los canales, así en plataformas donde según que colores no se ven bien, quedaría mejor.

Los perfiles de colores los introduje yo. Busque un sistema para evitar q los titulos llevaran embeido etiquetas tipo [COLOR red] por ejemplo, ya que esto si que no era generico (en plex por ejemplo depende del cliente, no del servidor). En su lugar puse un atributo item.text_color para que el creador del canal defina de q color quiere q se muestre el item y en platformtools.render_item cada plataforma lo gestione segun interese. Esto tiene pero un inconveniente y es q no se permiten items multicolor...q le vamos a hacer :wink:
La gestion de los diferentes perfiles se hace en la configuracion de cada canal, y los diferentes colores q componen cada perfil se definen en el codigo del propio canal. Me parece q este es el mejor sistema. Las diferentes combinaciones de color quedan a la eleccion y gusto 'artistico' del diseñador/creador. Imponer un determinado numero de perfiles haria por una parte mas complicado la creacion de canales al que no quiera usar los colores (o q todos los items de un determinado contentType sean del mismo color) y por otra parte todos los canales se verian igual (en funcion del perfil q cada usario tenga puesto).

Si algun color de los seleccionados en mis perfiles no funciona bien en una determinada plataforma o skin, decirmelo y mirarmos cual queda mejor.

**Comment by SeiTaN** [comment]
> La gestion de los diferentes perfiles se hace en la configuracion de cada canal, y los diferentes colores q componen cada perfil se definen en el codigo del propio canal. Me parece q este es el mejor sistema. Las diferentes combinaciones de color quedan a la eleccion y gusto 'artistico' del diseñador/creador. Imponer un determinado numero de perfiles haria por una parte mas complicado la creacion de canales al que no quiera usar los colores (o q todos los items de un determinado contentType sean del mismo color) y por otra parte todos los canales se verian igual (en funcion del perfil q cada usario tenga puesto).

Ahora que lo dices no me había dado cuenta, los colores no se pueden desactivar :cold_sweat:

**Comment by superberny70** [comment]
> Ahora que lo dices no me había dado cuenta, los colores no se pueden desactivar :cold_sweat:

No, se podria poner un setting en preferencias... pero q pasaria en la biblioteca con las series activas y no activas?

**Comment by SeiTaN** [comment]
Me refiero al canal, y referente a la biblioteca, creo que se debería permitir cambiar tb los colores, ahora mismo están a capón, creo que fue @Palatosino quien dijo algo porque no se le veia bien con un skin que tenía.

**Comment by divadres** [comment]
si el tema de los colores es un ejemplo, y la verdad, el menos problemático pero yo creo que quedaría mejor que el tema de los colores se eligiera de una manera "centralizada", o por lo menos se pudieran desactivar de una forma generalizada. ya que en una plataforma u otra puede que se vea mal o incluso según el skin, pero como digo, este es el menor de los problemas, lo que si que es un problema es lo que no permite que el canal funcione.

A mi me preocupa mas que hay canales que: 
 - Una ventana mediante xbmcgui para mostrar la info (en mi opinión con un diseño bastante mejorable) cuando podría usarse la ventana que ya existe para ello, o incluso la de infoplus, o crear una nueva en platformtools, y así evitaríamos el problema
- xbmc.log() :scream: :scream: :scream: :scream: ¿Quién usa aun eso?
- Otras llamadas a xbmcgui y xbmc

**Comment by r0balo** [comment]
> - xbmc.log() 😱 😱 😱 😱 ¿Quién usa aun eso?

Yo por ejemplo, es el print de los últimos kodi.
El logger, tal está no nos vale para debugear un módulo, método, algoritmos, variables, estc. Mete demasiada info que no necesitamos en ese momento.

Ahora mismo y sin modificar nada, tanto yo como cualquier hijo de vecino que queramos ver cosas concretas sin tener que escarbar en la maraña del log sólo tenemos una opcion, usar xbmc.log().

Si, por lo que sea, se nos queda alguno sin borrar o comentar al subir el .py y queremos que cuando pase esto no rompa la ejecución del módulo, se puede hacer lo mismo que has hecho en el logger del mediaserver en logger.error; usar otra opción para estos casos sin comprobar si está activado el log detallado en el config.

En kodi algo como estoi:
```
def _print(texto=""):
    xbmc.log(get_caller(encode_log(texto)), xbmc.LOGNOTICE)
```

**Comment by superberny70** [comment]
Pues no lo entiendo @r0balo. 
Entonces q haces? desactivas el log detallado y utilizas xbmc.log()? Por q si no lo desactivas estas en las mismas ¿no?
Es cierto q hay demasiada informacion en el log, por eso introduje logger.debug q añade una cabecera ######## DEBUG ######### que, aunque a algunos no les guste, si facilita el localizar algo dentro de todo el log.

**Comment by divadres** [comment]
Si por usarlo mientras estas trabajando en el canal no pasa nada pero cuando se publica el canal habria que cambiarlo... para que no falle en otras plataformas...

**Comment by r0balo** [comment]
@divadres a eso me refería por eso me resultó extraño el comentario

**Comment by r0balo** [comment]
@superberny70 lo que hago es sencillo. Cuando creo/modifico un conector o canal empiezo con la solicitud y carga la página, en la siguiente línea coloco un "print" y en la siguiente a esta última escribo cualquier cosa como punto de ruptura para detener la ejecución, por ejemplo 'aaaa' que dará error y se para. Compruebo el resultado y si es el esperado elimino el 'print' y el 'aaaa' y continuo con lo toque, que no lo es pues toca comprobar que ha cambiado.

'print', en el caso de las nuevas versiones de kodi, es xbmc.log() o looger._print() si la versión que estoy usando le he implementado el método que he puesto antes al logger.

**Comment by superberny70** [comment]
> El logger, tal está no nos vale para debugear un módulo, método, algoritmos, variables, estc. Mete demasiada info que no necesitamos en ese momento.

@r0balo pues creo q haces lo q hacemos todos. Por eso mismo no veo la diferencia entre usar xbmc.log(), logger._print() o cualquier otra funcion de logger.py

**Comment by r0balo** [comment]
>@r0balo pues creo q haces lo q hacemos todos. Por eso mismo no veo la diferencia entre usar xbmc.log(), logger._print() o cualquier otra funcion de logger.py

También creo que lo hacemos todos.
logger._print() si hace lo mismo que xbmc.log() y no rompería la ejeucución en otras plataforfomas si está implementado, las otras no, compueban si está activado el log detallado en la config.

En la versión mediaserver @divadres puso, y pienso que con mucho acierto, logger.error() sin la comprobación de loggeractive

**Comment by SeiTaN** [comment]
Creo que estais hablando de cosas que no tienen que ver, @divadres dice que no se debería dejar xbmc.log en la versión **final** del canal, en el proceso como si se quiere usar un fichero de texto y meter ahí las trazas.

**Comment by r0balo** [comment]
No hay que darles muchas vuelta, es una respuesta a una pregunta y sería repetir una y otra vez lo mismo, pero bueno, una vez más :) Quién lo usa? Yo, por ejemplo. Porqué? Porque las últimas versiones de kodi no nos vale print y no quiero el log detallado para ver el resultado de un algoritmo concreto. Que se me olvida quitarlo o comentarlo, pues lo siento, cosas que pasan. Si existiera una herramienta del tipo _print (dos líneas) daría igual si se me olvida quitarlo o comentarlo, no petaría en otras plataformas.

**Comment by superberny70** [comment]
> ...las otras no, compueban si está activado el log detallado en la config.

@r0balo no te habia contestado antes por q al fin habia entendido tu propuesta (si, lo reconozco soy un poco lento a veces :laughing:)

> ... @divadres puso, y pienso que con mucho acierto, logger.error() sin la comprobación de loggeractive

Entonces si, logger.error() se escribiese siempre en el log, sin comprobacion y sin tener q tenerlo activado, ¿te valdria? Por q eso es lo de lo q hablabamos en #589

**Comment by r0balo** [comment]
Pues claro que me valdría, a mi y creo que a todos, los conectores se resisten con los errores y es dífil sacarselos sin activar el log detallado y escribiendo muy poco. Y un logger.info() sin comprobación (al que me ha dao por llamarlo logger._print) sería la leche. Tengo mucho lio de versiones de los canales y conectores , sobre todo de canales, para mantener viva la rasp1. Es desesperante algunas veces :(

**Comment by superberny70** [comment]
Lo tratado aqui esta ya desglosado en: #376 , #637 y #589 
¿q os parece si cerramos esta y continuamos cada tema en su correspondiente hilo?

**Comment by divadres** [comment]
cierro
