### ISSUE TITLE
[Mejoras para 4.3.x] color_text para todo el addon

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#637]
Hola,

Creo que esto ya lo dijo @divadres, pero he visto que hay muchos canales que incluyen la mejora visual de colores y texto que planteó @superberny70, y he pensado si se podría poner de modo general, es decir que sea **independiente de los canales y que se configure el color para todo el addon**.

También habría que permitir configurar el color para la biblioteca ya que los colores están hardcodeados o algún otro sitio para revisarlos.

**Comment by superberny70** [comment]
Ya comente que no me parece correcto generalizar el tema de los colores. Creo q eso junto al fanart, thumbnail, etc... forma la parte 'artistica' del canal y deberia respetarse la eleccion del creador.
Por otra parte, si lo generalizamos van a parecerse mucho todos los canales ¿no creeis?
Como mucho lo q haria seria poner un setting nuevo q ignorase las etiquetas text_color, text_blod y text_italic por si a alguien no le gustan los colores poder ver los items en el formato original (segun su skin).

Sobre la Biblioteca lo q podrias hacer es añadirle 2 o 3 perfiles y q fuese seleccionable en la configuiracion.

**Comment by divadres** [comment]
@superberny70 en mi opinión, creo que no es correcto tu punto de vista, yo creo que si que se debería generalizar el tema de los colores, por lo menos que exista la opción y que cada uno la active o no, pero creo que tendría poderse desde el plugin desactivar los colores de los canales o personalizarlos ya que para cada plataforma/skin pueden ser mejores unos u otros, y a mi sinceramente, la elección del creador del canal me importa poco, es mi TV y soy yo el que tengo que decidir como quiero verlo.

Yo creo que tendría que añadirse la opción para poder eliminar las etiquetas de color que traigan los ítems en la función render_items, y luego mediante los contentType poder hacer como un perfil de color personalizado para cada tipo de manera que pudieras: dejar que el canal decida, dejarlo todo sin colores, o personalizar los que tu quieras.

de igual manera también pienso, que seria mejor que las etiquetas de idioma, calidad, duración, etc... en vez de que los canales las añadieran en el titulo, se añadieran como atributos del ítem, y que fuera también cada plataforma mediante la configuración de cada usuario la que decidiera como se muestra, colores, etc...

y respecto a que todos los canales se pareciesen mucho (en mi opinión) eso seria fantástico (como puedes ver para gustos colores, y nunca mejor dicho) 

pero para que todo esto funcionara, tendría que haber unas "normas" para hacer los canales, y que no cada uno los haga según su inspiración artística... el que hace un canal de una manera es por que le gusta así ¿no saldríamos ganando todos si en vez de hacer el canal como le gusta, todos pudiéramos poner todos los canales como nos gusta a cada uno mediante la configuración de pelisalacarta?

**Comment by SeiTaN** [comment]
A ver si buscando una cosa intermedia, mi idea sería lo siguiente:

- Configurar todo con o sin colores (cosa que ahora no se permite).
- Configurar el canal con colores a elegir (se hace) o sin (no se hace).

Todo esto creando un modulo aparte y quieres crear más perfiles de colores no habría problemas, seleccionas el que quieras.

**Comment by superberny70** [comment]
@divadres poco a poco creo q se van 'normalizando' los canales, y en gran medida gracias a ti y a la implementacion de tu clase Item. Pero creo q es algo que se tiene q hacer poco a poco. Hay q ir convenciendo a los creadores q usar metodos y atributos normalizados (contentTitle, duration, contetQuality, etc..) facilita la creacion y mantenimiento  de los canales y ayuda a incorporar nuevas funcionalidades. Pero poco a poco, con informacion (y tutoriales) pero sin imposiciones.

Esta claro q tenemos puntos de vista distintos sobre la parte 'artistica', jejeje, pero mientras los cambios sean opciones y haya una q respete los formatos decididos por el creador a mi ya me esta bien.

Lo q no veo es como quieres fijar el color segun en contentType. Cuando propuse por primera vez el atributo text_color algunos criticaban q todo el item tuviese le mismo color. Preferian items multicolor para identificar mejor la calidad, el año, el servidor, etc... Si ahora fijas el color dependiendo del contetType todos los items de la ventana tendran el mismo color (como mucho podras diferenciar los q tiene acction y los q no)

@SeiTaN no creo q haga falta añadir ningun nuevo modulo. Lo correcto seria incluirlo en platformtools, ya q cada plataforma lo va a gestionar de manera distinta y los diferentes perfiles disponibles pueden variar de una plataforma a otra, si no he entendido mal la idea.

**Comment by SeiTaN** [comment]
> @SeiTaN no creo q haga falta añadir ningun nuevo modulo. Lo correcto seria incluirlo en platformtools, ya q cada plataforma lo va a gestionar de manera distinta y los diferentes perfiles disponibles pueden variar de una plataforma a otra, si no he entendido mal la idea.

Lo de crear un módulo era una idea para que todos los canales que tienen color específico tenga ese mismo código en otro sitio centralizado, si no molesta en platformtools no creo que haya ningún problema como dices.

¿Sobre la configuración individual y/o colectiva del color de los canales que te parece la idea?

Lo suyo sería que la configuración individual sea prioritaria sobre la colectiva, asi los canales con configuración específica seguiran siendo distintos al resto. Es decir si yo he configurado que todos mis canales salgan de color azul y en allpelis he puesto que el canal sea verde, que salga así.

## Posible opción en configuración
```xml
- Personalización de colores en los listados:
    - para todos los canales (bool) <-- activado habilita la siguiente opción, deshabilitado no usa ningún color.
          - seleccione el color [listado con opciones de colores]
    - personalizado por canal (bool) (si | no, si es "no" se muestra el color general que esté configurado)
```

**Comment by superberny70** [comment]
Perdon se me habia pasado esto. 

Continuo sin verlo claro.  El tema de las preferencias entiendo lo q pretendes,  aunq no creo q sean correctas las opciones q has puesto. Pero ya te digo q eso es lo de menos, lo importante es diferenciar dentro de un listado q items van de un color y cuales de otro. Hazme una demostracion añadiendo los colores desde fuera del canal.

**Comment by SeiTaN** [comment]
> Continuo sin verlo claro. El tema de las preferencias entiendo lo q pretendes, aunq no creo q sean correctas las opciones q has puesto. 

¿Cuales sugieres tú?

> Pero ya te digo q eso es lo de menos, lo importante es diferenciar dentro de un listado q items van de un color y cuales de otro. 

A ver eso lo decide el creador del canal, yo lo único que digo es que haya un flag para poder desactivarlo.

Te pongo los ejemplos:

## Global:
### Caso 1: Addon sin color personalizado global
![image](https://cloud.githubusercontent.com/assets/11775029/23307910/8b840bee-faa9-11e6-9f4d-15f4b8ffcb6e.png)

### Caso 2: Addon configurado con el color _azul_
![image](https://cloud.githubusercontent.com/assets/11775029/23307727/dac4163c-faa8-11e6-8fa8-c1df6dac6e76.png)


## Canal:
### Caso 1: El canal personalizado tiene puesto que sobreescribe el color global del addon, como tiene configurado que sale las cosas en verde (configuración hecha por el creador del canal, se muestra así)
![image](https://cloud.githubusercontent.com/assets/11775029/23307758/f85973fe-faa8-11e6-9dc9-4bf705f56cb5.png)

###  Caso 2: El canal personalizado **NO** tiene puesto que sobreescribe el color global del addon, y por tanto sale el color configurado (azul)
![image](https://cloud.githubusercontent.com/assets/11775029/23307800/280b4208-faa9-11e6-8d95-ba4dc9f9e628.png)

### Caso 3: El canal personalizado **NO** tiene puesto que sobreescribe el color global del addon, y no hay color global establecido.
![image](https://cloud.githubusercontent.com/assets/11775029/23307972/d274d13c-faa9-11e6-915f-9fe970f19686.png)

**Comment by superberny70** [comment]
Vale. 
Ves las diferencias entre esos ejemplos y cualquiera de los canales q incluyen colores mediante item.text_color?
![image](https://cloud.githubusercontent.com/assets/7559559/23310011/33361a2e-fab1-11e6-9bf6-b6c70d824f78.png)
![image](https://cloud.githubusercontent.com/assets/7559559/23310277/5029fc1c-fab2-11e6-88e4-444258fa2ee6.png)

Todos los items de tus listados tienen el mismo color. Si es eso  lo que buscais (y es optativo) adelante, yo pensaba q queriais automatizarlo de manera q los canales no tengan q implementar los perfiles y sea el addon el q decida de q color pinta cada item dentro del perfil q hallamos seleccionado.
Por ejemplo en le caso de Yaske solo hay un unico perfil con tres colores, pero en el caso de tvmoviedb hay 3 perfiles seleccionables, con 6 colores cada uno e incluso se pueden desactivar los colores desde la configuracion del canal.

Sobre las opciones de configuracion, creo q deberiam ser:

- Colores en los listados (lista): 

    - Sin color.
    - Permitir que los canales gestionen el color.
    - Color rojo.
    - Color verde.
    - Color azul.
    - Color etc...

**Comment by SeiTaN** [comment]
> Todos los items de tus listados tienen el mismo color. Si es eso lo que buscais (y es optativo) adelante, yo pensaba q queriais automatizarlo de manera q los canales no tengan q implementar los perfiles y sea el addon el q decida de q color pinta cada item dentro del perfil q hallamos seleccionado.

Todos los items tienen el mismo color a modo de ejemplo, en el addon global yo pienso que todos deberían tener el mismo color si se quiere separar eso habría que pensarlo más ya sea por algun valor específico como puede ser el nombre del item, su categoria, action, etc....

> en el caso de tvmoviedb hay 3 perfiles seleccionables, con 6 colores cada uno e **incluso se pueden desactivar los colores** desde la configuracion del canal.

Esa es la idea que todos los canales permitan poder desactivarlo.

> Sobre las opciones de configuracion, creo q deberiam ser:
> 
> Colores en los listados (lista):
> 
> Sin color. **<-- "color por defecto"**
> Permitir que los canales gestionen el color.
> Color rojo.
> Color verde.
> Color azul.
> Color etc...
>  **[    ]<--- "cuadro para introducir el codigo hexadecimal del color"**



Cuando me refiero a los colores centralizados me refiero a todos los perfiles de colores estén declarados en el mismo sitio, por eso dije "modulo"

**Comment by divadres** [comment]
creo que no costaría mucho añadir un campo al ítem donde se le asignara una categoría dentro de un perfil de color: listados, grupo, contenido grupo, server, película, serie, episodio, temporada, etiqueta, etc... podríamos añadir bastantes para que hubiera bastante margen para personalizar colores, y luego desde render_items, asignar el color según el perfil de color seleccionado y el tipo de ítem

Esto se podría añadir a modo de que los creadores que quieran añadir perfiles de color, usasen el método "genérico" de este modo el usuario podría elegir el perfil de color para todos los canales (que lo soporten) y simplificaría la creación del canal ya que solo habría que asignarle la categoría a cada ítem y la plataforma haría el trabajo, y asi los perfiles de color podrían ser distintos para cada plataforma (hay colores q en kodi se ven bien y en mediaserver cuesta mucho de ver) y las plataformas que no soportan colores (plex, etc...) pues directamente ignorarían esas categorías...

para ítems multicolor solo habría que añadir las propiedades (calidad, idioma, rating, etc) en las propiedades del ítem y no incorpararlas en el titulo, y que  render_items, montara el titulo, añadiendo los colores según el perfil de color para cada atributo, de modo que incluso podríamos elegir que atributos se ven en el ítem y cuales no y los colores para cada uno...

Pienso yo, puestos ha hacer mejor montar un sistema genérico que sea personalizable para el usuario, y luego ya buscaremos la manera de convencer a los creadores que usen el sistema genérico...

En vez de que cada creador haga su propio sistema de colores, y que luego nosotros lo "machaquemos" desde la configuración... me parece que es trabajar el doble para nada, ¿no os parece?

**Comment by superberny70** [comment]
> creo que no costaría mucho añadir un campo al ítem donde se le asignara una categoría ...
Ya es complicado que los creadores utilicen los atributos reservados actuales correctamente como para añadirles mas. 
Me gustaria oir mas opiniones.

**Comment by divadres** [comment]
Creadores de canales no hay tantos, y menos que usen colores creo que habrá un par o tres y no costaría mucho hablar con ellos y explicárselo, y si quieren aportar alguna idea para el sistema que implementaríamos pues bienvenida sea.

Así por lo menos tenemos una función genérica para hacer eso, lo cual nos ahorra repetir codigo inecesario en cada canal, para que veáis un poco cual es la idea, he añadido la función a platformtools y he creado un canal de pruebas donde se pone un ítem de cada tipo para que veáis cual seria su funcionamiento, he creado una serie de tipos de ítem, pero se pueden añadir los que se quieran en el perfil e incluso se pueden dejar unos adicionales sin uso especifico para si algún creador tiene alguna "necesidad especial"
podéis probarlo aquí: https://github.com/divadres/pelisalacarta-oficial/tree/feature/prueba_colores

De momento la función tiene un solo perfil de color fijo, pero mi idea es que los perfiles de color fueran archivos (.json) que se pudieran añadir dentro de addon_data, y así cada uno pudiera crear perfiles personales si así lo deseara:

Este sistema ofrece muchas posibilidades, permitiendo dar rienda suelta a la creatividad del creador, y además permitiendo al usuario elegir los colores para todos los canales (que lo soporten) y solucionaría definitivamente el problema de los colores en cada plataforma/skin que actualmente (en mediaserver por lo menos) algunos canales cuesta bastante de leer.

**Comment by SeiTaN** [comment]
Para los vagos, la verdad que queda bastante resultón xDD

![image](https://cloud.githubusercontent.com/assets/11775029/23330379/b4400aa8-fb4c-11e6-9a16-a95f828f9ad2.png)

P.D: lo del idioma yo lo pasaría como lista (me es necesario para mi modulo de filtertools, aunque yo uso "language" en vez de "lang"), y ya dentro de platformtools coja el list y lo muestre con "/" o con varias etiquetas.
P.D1: si esto interesa tb habría que ver el tema de poner negrito en los titulos que me supongo que será bastante simple.

**Comment by divadres** [comment]
si miras como funcionan los perfiles, versas que a cada elemento puede añadir lo que quieras negrita, cursiva incluso en las etiquetas, puedes ponerlo entre "()" "[]" o poner lo que quieras como "Idioma: español" ya que el formato es : `"movie": "[COLOR seagreen]%s[/COLOR]" ` y solo se modifica el %s por el titulo o el valor de la etiqueta...

No se trata de vagos, se trata de usar un sistema genérico, y si también, para que repetir la faena cuando con hacerla una vez tenemos suficiente....

**Comment by SeiTaN** [comment]
con lo de "vagos" me refería a copiar tu código y probar, por eso he puesto la imagen para que se viera 😉

**Comment by divadres** [comment]
jajaj, vale lo he entendido al revés...

**Comment by CmosGit** [comment]
Me meto en el tema ya que al fin y al cabo yo soy de los más que se relían con los colorines xD

Al principio era un poco reticente a la idea de generalizar el tema de los colores en el addon, primero porque creo que el creador del canal, ya que se pone y le echa horas al tema, es justo que tenga cierta manga ancha en lo que se refiere al aspecto y disposición del canal. Y también porque me gusta que haya diferencias entre canales y no estén todos cortados por el mismo patrón, pero bueno, esto es algo muy subjetivo y cada uno tendrá sus preferencias.

Pero después de ver la idea y sobre todo la ejecución que ha planteado @divadres, por mi parte soy más receptivo a ello. Se ve que es muy personalizable y que cubre casi todas, si no todas las posibilidades. Lo único es que como sigamos así vamos a tener que crear los canales con un manual al lado 😆  (@superberny70 cuento contigo 👍 )

**Comment by SeiTaN** [comment]
> Me meto en el tema ya que al fin y al cabo yo soy de los más que se relían con los colorines xD

Y más canales hacen 😆 

Pues según se ve es bastante fácil e intuitivo, no haría falta manual para implementarlo, si tiene servidores se usa la propiedad, si tiene idioma y lo quieres agregar, etc, etc.

Otra cosa es que quieras superpersonalizar los colores y demás con los perfiles, eso si va a tener un poco más de jaleo sobre el papel 😉

**Comment by neno1978** [comment]
Buenas , yo personalmente no entiendo esto de "globalizar" el coloreo, más cuando hace un tiempo ni dios coloreaba los canales . No obstante , siempre y cuando se respete lo estipulado por el creador del canal me parece "bien" que se de la opción de quitar o poner .Si, ya se que es "la tele de cada uno" y esas cosas metafísicas, pero en fin , pa gustos los colores nunca mejor dicho ;)  pero , no sé, no acabo de entenderlo, supongo que a todos nos puede importar poco algo diferente en determinada circunstancia , pero hombre, si nos ponemos así al final acabo llamando a T5 pa que me quite el logo de ahí joder , que no me mola ;)

**Comment by divadres** [comment]
No se trata solo de gustos, hay colores que no se leen bien en determinadas plataformas/skin... por mi quitaba todos los colores y listo... pero entoiendo que hay a quien le gusta asi... solo estoy buscando una manera de gestionarlo de una manera global permitiendo que se respeten los gustos de todos...

**Comment by SeiTaN** [comment]
Yo al menos no he entendido que te quiten la posibilidad de poner colores, si no de buscar una manera global para que se pueda personlizar a gustos de todos y de poder quitarlo para evitar el problema con skins/plataformas que ha comentado divadres.

Para eso que mejor que hablarlo entre todos y aunar puntos de vista.

neno a T5 ni agua 😝

**Comment by kerenmac** [comment]
Me parece espectacular el resultado, y la idea de generalizar los colores y estilos creo que es un completo acierto. 👏 👏 👏 

PD: Y el tema de las vistas de las ventanas y tal... que os parece como tema de conversación? Me refiero a que se de la opción de establecer las distintas vistas y/o establecer las vistas sin necesidad de especificarlas en cada ventana (evitando mezclas, como pasa en channelselector, y tener que poner mil veces `viewmode="..."`)

**Comment by superberny70** [comment]
> PD: Y el tema de las vistas de las ventanas y tal... que os parece como tema de conversación? Me refiero a que se de la opción de establecer las distintas vistas y/o establecer las vistas sin necesidad de especificarlas en cada ventana (evitando mezclas, como pasa en channelselector, y tener que poner mil veces viewmode="...")
Para no desviar el tema, mejor usar el[ hilo del foro](http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=8340&p=37240#p37240) que ya existe o si preferis abrir otra issues de estas.

**Comment by divadres** [comment]
Pienso que también cada canal, si quiere tener un perfil propio, puede pasar el perfil mediante el ítem y si en configuración esta activa un ajuste "Respetar perfil de canales" en vez de usar el perfil configurado usase el del canal para ese canal, así la gente que quiere que los canales sean diferentes, podría seguir teniéndolo...

**Comment by divadres** [comment]
Podría ser algo así:
**Configuración:**
   - Seleccionar perfil:           (listado de perfiles)
   - Ignorar perfiles de canales:           [X]


**Canales:**
 - Sin gestión de perfiles (todo se muestra del color por defecto)
- Gestión de perfiles sin perfil propio (Ítems con parámetro para indicar el tipo)
- Gestión de perfiles con perfil propio (Ítems con parámetro para indicar el tipo y parámetro para pasar el perfil del canal)


**Platformtools:**
- Si el canal pasa perfil propio e "ignorar perfiles de canales" es False:
  - Se asigna el formato para el tipo de ítem según el perfil del canal
- Si el canal no pasa perfil propio o ignorar perfiles de canales" es True 
  - Se asigna el formato para el tipo de ítem según el perfil global seleccionado

**Perfiles:**
- Los perfiles serian unos .json que irían guardados en algún lugar del plugin, al iniciar carga el perfil seleccionado.
- Seria un archivo por perfil, así un usuario podría crear su propio perfil con el formato que mas le convenza si es que no le gusta ninguno de los que vinieran por defecto.
- Los perfiles son un dict que contienen:
  - name: Nombre del perfil
  - types: dict con pares "tipo de ítem" :  "formato"
  - labels: dict con pares "atributo ítem a incluir": "formato"
- Los formatos tienen que contener todas las etiquetas color, negrita, cursiva, y un %s donde se pondrá el valor, ya sea el titulo o cualquiera de los atributos del ítem
- En caso de listados desplazados a la derecha (ítems dentro de un grupo) los espacios se añadirán al perfil, así en cada plataforma se adapta (en HTML hay que poner "&nbsp;" en vez de espacios)

_Como podéis ver, este sistema es algo mas que selección de colores, es mas bien el formato, especifica, colores, negrita, cursiva, alineación ítems, formateo de etiquetas en el titulo y se puede mantener si se desea los perfiles independientes de cada canal, siempre y cuando los canales que tienen colores se adapten a este formato, y también permite una gestión centralizada si así se desea (también para los canales que estén adaptados a este formato) el resto de canales se mostraran según el tipo "list" del perfil seleccionado, es decir, todos del mismo color, pero pudiendo seleccionar cual será ese color._

**Comment by superberny70** [comment]
Gracias @divadres, la cosa va cogiendo forma.
Si te fijas lo q hemos dicho algunos es q estaba bien, pero necesitamos q se respete nuestra seleccion de colores/perfil. Esta ultima propuesta va por ahi :clap:
Unas preguntas:

- Si el canal tiene varios perfiles seleccionables desde su configuracion. Entiendo q esto se mantiene, y se pasa mediante el item el perfil q el user haya configurado ahi ¿no? Por supuesto deberemos ampliarlos perfiles existentes y darles el formato del dict q tu indicas.
- En los canales q usaban formatos (color/cursiva, negritas) pero no los atributos item.text_xxxx (estaban embeidos en el titulo) seran limpiados automaticamente por el platformtools ¿no?
- Si los perfiles estan en archivos, en cada llamada a render_items se han de leer el .json, al menos en kodi ¿no? ¿Esto no va a ser muy costoso?

**Comment by divadres** [comment]
> Si el canal tiene varios perfiles seleccionables desde su configuracion. Entiendo q esto se mantiene, y se pasa mediante el item el perfil q el user haya configurado ahi ¿no? Por supuesto deberemos ampliarlos perfiles existentes y darles el formato del dict q tu indicas.

Si, obviamente es el canal que tendrá que pasar el prefil que el usuario haya seleccionado en su configuración

> En los canales q usaban formatos (color/cursiva, negritas) pero no los atributos item.text_xxxx (estaban embeidos en el titulo) seran limpiados automaticamente por el platformtools ¿no?

Los canales que usen eso (y quieran seguir usándolo) tendrán que crear su propio perfil
Lo suyo seria eliminarlo de los canales, pero para no tener que hacer tanto trabajo, podría eliminarse todas las etiquetas desde platformtools hasta que los canales se adapten.

> Si los perfiles estan en archivos, en cada llamada a render_items se han de leer el .json, al menos en kodi ¿no? ¿Esto no va a ser muy costoso?

Yo creo que no, a mi me parece que es un "mito" eso de que leer archivos del disco penaliza mucho el rendimiento una cosa es leer mas de 100 archivos en un bucle (como para mostrar el listado de canales, que tampoco tarda tanto) y otra cosa es leer un archivo de pocos kbs yo nunca he visto que eso se note en el rendimiento. piensa que cada import que hacemos es un fichero que se ha de leer y procesar, y no veo que nadie vaya contando los imports que hace... de igual manera cada vez que hacemos un config.get_setting() tiene que acceder al archivo de configuracion

**Comment by Hernanarce** [comment]
Buenas, fui invitado a dar mi opinión sobre este tema, desde mi poca experiencia creando canales. Por lo que veo la idea es mas o menos lo que yo utilizo normalmente un diccionario que colorea según lo que se le pase, me parece una buena idea, igualmente como no manejo el tema de archivos json hago la siguiente pregunta desde el desconocimiento obviamente al momento de crear un canal además de .py y el .XML se debería crear un .json en caso de ser un perfil dedicado?
Por otro lado con respecto al uso de colores en si, se entiende que es una decisión creativa por parte del creador, pero creo que, sin ofender, hay casos en los que utilizan colores para la lista de películas por ejemplo un azul, y terminamos encontrando que por ejemplo en kodi 17 con el skin por defecto no se ve casi nada. Creo que en ese sentido los colores deberían utilizarse mas como una ayuda visual, en mi caso mis canales lo hacen al mejor modo semáforo, verde es lo ideal, amarillo casi ideal, rojo poco recomendable, aplicándose mas que nada a lo que serian calidades o idiomas, dejando lo que son títulos en blanco que no creo que de problemas en ningún sistema. De ese modo cualquiera que ve los colores sabe a que se refieren, de otro modo creo que mas que una ayuda visual es todo mas confuso.
obviamente es mi opinión y cada uno hace lo que le parece mejor.
Bueno me pase un poco con el texto, espero se pueda aplicar la mejora y no parece demasiado compleja, que por mi parte se agradece.
Saludos

**Comment by divadres** [comment]
el tema del pefil incluido en el canal no es necesario un .json ya que este puede ser un diccionario escrito directamente en el canal, no necesitamos mas archivos para nada!!!

**Comment by neno1978** [comment]
@SeiTaN a T5 ni agua , y si por mí fuera los eliminaba a todos y punto ;) 😂😂😂

**Comment by r0balo** [comment]
Mucho post para un tema que debería ser sencillo. Independientemente de la persona que cree el, de los colores que quiera poner y la forma de hacerlo para evitar colores que dañen la vista dependiendo del fondo sobre el que se imprime (normalmente en mediaserver y plex), las plataformas, sólo se deben de permitir la lista de colores que sean adecuadas a sus colores de fondo, todo color que no esté en la lista de permitidos pasara a ser `style="color: auto"`. Así lo hacía yo antes cuando usamos plex y mediaserver a excepción de algunos colores con mucho brillo de algunos canales que los modifica a mano por otros del mismo color con menos brillo. La lista se puede componer de unos pocos colores básicos con más o menos brillo para cada plataforma. Es una soloción sencilla y fácil de implementar.

Resumiendo, por mi parte @superberny70 puedes hacer lo que te salga de los caramelos o como dice @neno1978 , de los pendientes reales. A más opciones para personalizar los items mejor, menos mermará la creatividad del que cree el canal.

El tema de los perfiles, para una casa (el dueño del balón decide si es gol o no), no le veo mucho sentido. Pero no seré yo el que os quite ese gusto.

**Comment by divadres** [comment]
El tema es que es difícil decidir que colores molestan y cuales no, en kodi depende del skin, en mediaserver, por ahora solo hay una vista disponible, pero nada impide que se pudieran crear varias plantillas con varias visualizaciones, es por eso que yo creo que un sistema de perfiles, donde se definan una serie de "tipos de ítem" lo bastante amplia con un color para cada uno donde un usuario pudiera añadir incluso sus perfiles personalizados seria una solución muy completa.
y si a eso le añadimos que el creador del canal pudiera incluir un perfil para ese canal mediante un diccionario dentro de las propiedades del ítem para que en caso de que el usuario no elija forzar todos los canales al mismo perfil pudiera permitir que el creador del canal pudiera ver su canal como a el le gusta y los demás pudiéramos verlo como nos va bien a cada uno.

Una solución que permite los gustos de cada uno, pero para que funcione los creadores de canales tienen que comprometerse a usar ese sistema, sino va a ser un desastre...

**Comment by r0balo** [comment]
Sobre perfiles y perdidas de tiempo por el usuario por ver un color concreto en el item en el tiempo limitado que tenemos en decidir que ver en compañia, me importa bastante poco.

Sobre implementar colores por plataformas para la que no pensó el creador del canal en que colores usar para que se vea bien en todos, no lo veo para nada difícil. Eso sí, nos lo podemos poner difícill nosotros mismos todo lo que queramos. Tanto si nos llega los colores como "red", como #FF0000 o como rgb(255,0,0) podemos modificar estos a un color semejante con ayuda de diccionario, lista o json con todos los nombres de color y sus valores rgb. Piénsalo si se te apetece. limitar los rangos para los colores básicos suele funcionar y ante la duda "auto".
