### ISSUE TITLE
Error en plex con la ventana de configuración de algunos canales

### ISSUE THREAD

**Issue by CmosGit** [tvalacarta/pelisalacarta#642]
En el [foro](http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8735) un usuario ha reportado un error por el que no puede abrir la configuración de ciertos canales (playmax) lo que produce que no pueda usar el canal ya que se necesita introducir el usuario y el pass. He hecho la prueba y es así, me pasa con playmax y con otros como verseriesynovelas, allpeliculas, pelisdanko...casualmente todos toqueteados por mí (me declaro inocente hasta que se demuestre lo contrario 😆 )

El error en todos ellos es siempre el mismo:

```
  File "C:\Users\Cmos\AppData\Local\Plex Media Server\Plug-ins\pelisalacarta.bundle\Contents\Code\__init__.py", line 150, in canal
    for item in itemlist:
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 107, in <lambda>
    _getiter_           = lambda x: x.__iter__(),
AttributeError: 'NoneType' object has no attribute '__iter__'
```

Como mi comprensión del funcionamiento de plex raya la ignorancia xD, a ver si alguien puede comprobar qué está pasando ahí 👍

**Comment by superberny70** [comment]
De ignorante a ignorante... como instalo la rama develop de plex en mi Plex Media server? :relaxed: :relaxed:
Es cojonudo... la config por canales la introduje yo y ahora no se como abrirlas!!! :laughing:
Puedes ziperar una version plex-develop para descomprimir en la carpeta Plug-ins?

PD: Que triste es hacerse viejo!!! :weary: :weary:

**Comment by superberny70** [comment]
vale creo q ya lo tengo...
En plex (no se si en otras plataformas no kodi tb sera asi o no) la funcion configuracion(item) tiene q devolver la lista devuelta por platformtools.show_channel_settings(), pruebalo:
```
def configuracion(item):
    from platformcode import platformtools
    ret = platformtools.show_channel_settings()
    if config.is_xbmc():
        import xbmc
        xbmc.executebuiltin("Container.Refresh")
    else: #No se si entrara en conflicto con otras plataformas q no sean kodi ni plex
        return ret 
```

**Comment by divadres** [comment]
efectivamente, ya se hablo en su momento, para que funcione en plex tiene que ser:

```
def configuración(ítem):
     return platformtools.show_channel_settings()
```
y esto no interfiere con nada, obviamente, si quieres poner antes del return el refresh hay que guardar el valor en una variable, pero en vez de hacer la comprobación de si es xbmc y luego usar el xbmc.executebuiltin() mejor podemos hacer platformtools.itemlist_refresh() que hace lo mismo y es multiplataforma...

y quedaría asi:

```
def configuracion(item):
    from platformcode import platformtools
    ret = platformtools.show_channel_settings()
    platformtools.itemlist_refresh()
    return ret
```
asi deveria funcionar en todas las plataformas, el plex el "refresh" sobraría, pero como tampoco hace nada en esa plataforma, funcionaria sin problema

**Comment by superberny70** [comment]
Gracias @divadres por confirmar y ampliar.
@CmosGit tampoco se por q es necesario el refresco, ¿kodi ya lo hace por si solo no? Es decir, con el primer fragmento de codigo q te ha puesto @divadres ¿no te funciona bien en todas las plataformas?

**Comment by divadres** [comment]
Esto hace falta si quieres que cuando guardes la configuracion actualice el listado sin tener que salir y entrar otra vez al canal...

**Comment by superberny70** [comment]
y en kodi no lo hace ya por si solo?

**Comment by divadres** [comment]
Creo q no

**Comment by CmosGit** [comment]
Muchas gracias chicos, @divadres y @superberny70, no sabía que para plex debía hacerse con el return, me perdí la clase ese día xD

Sobre el refresh, Kodi no lo hace automáticamente, lo uso sobre todo para que se apliquen cosas como los perfiles de colores al instante o si es un canal con login para que lo haga. Voy a coger todos los canales donde lo uso y corregirlos 😉
