### ISSUE TITLE
Crear un fichero con el listado de todos los datos de los canales (xml)

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#652]
Hola,

Debido a mi sugerencia #617 y para evitar procesos innecesarios dentro de platformtools que lastren el rendimiento del addon. Había pensado lo siguiente que en parte lo sugirió un forero en el punto 2 http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=8639#p38866.

Generar un fichero con todo el contenido de la información de los canales.

## Consideraciones:  
Será mucho más rápido que lo actual que abre todos los canales y recorrerlos cada vez que se accede a las categorías del addon, en la parte de configuración o mi futura mejora #617.

## Funcionamiento:
- Se crea el fichero al iniciar el plugin por primera vez (launcher.start()), añadiendo los datos xml del nuevo canal, revisando que existan los nodos, si no existen el xml asociado se borra el nodo.
- Si hay una versión nueva del canal, se actualizará el nodo del canal con su xml correspondiente.

Si alguien tiene alguna sugerencia o consideración al respecto, por favor no os corteis en comentar 😉

**Comment by divadres** [comment]
Esto es como todo, hacer la prueba y ver el rendimiento, si realmente se gana algo no...

**Comment by SeiTaN** [comment]
Las pruebas las puse en otro issue relacionado, yo no he notado diferencia por que lo uso en un PC.

Lo pongo aquí tb.

## Versión actual (develop)
### Acceder por primera vez al addon

inicio 21:04:45.415
fin 21:04:45.740

**300 mseg**

### Ya dentro
inicio 21:05:36.765
fin 21:05:37.093

**300 mseg**



## Usando fichero común json

### Acceder por primera vez al addon

inicio 21:07:14.070
fin    21:07:14.384

**300 mseg**

### Ya dentro

inicio 21:01:55.157
fin 21:01:55.471

**300 mseg**
