### ISSUE TITLE
Cambios propuestos en library_service y otros

### ISSUE THREAD

**Issue by superberny70** [tvalacarta/pelisalacarta#661]
Abro este hilo a colacion de lo dicho por @kerenmac en #653 para no desviar el tema alli tratado.

@kerenmac dijo:

> Por cierto, la linea 251 de library_service.py habría que pasarla de
if config.get_setting("updatelibrary", "biblioteca") == 1 and not overwrite:
a
if config.get_setting("updatelibrary", "biblioteca") != 0 and not overwrite:
Por que para las opciones 2 y 3 tambien se ofrece la espera al inicio, y sin ese cambio no funciona.
Y en la 302 (creo que es esa) de library.py habría que pasar de
path = filetools.join(TVSHOWS_PATH, ("%s [%s]" % (base_name, _id)).strip())
a
if config.get_setting("original_title_folder", "biblioteca") == 1:
    path = filetools.join(TVSHOWS_PATH, ("%s" % base_name).strip())
else:
    path = filetools.join(TVSHOWS_PATH, ("%s [%s]" % (base_name, _id)).strip())
Para que la carpeta creada no tenga el [_id] si no se quiere

En el primer caso (library_service) no confundas "updatetvshows_interval" con "everyday_delay" no es lo mismo, la primera solo esta disponible cuando actualizamos al inicio (para q no coincida con otros procesos de kodi) y la otra solo cuando actualizamos a intervalos programados (para q lo haga a partir de una hora determinada).

Respecto al tema de library: La configuracion "original_title_folder" es para q el nombre de la serie/pelicula con la q se renombra la carpeta este en castellano o en la version original. Pero el [_id] no lo puedes eliminar!!! en eso se basa la biblioteca multicanal. Es la manera q tenemos de identificar inequivocamente a una serie o pelicula. Al contrario q los scrapers, nosotros si q lo usamos.

**Resumen:** Si alguien ha cambiado esto q lo deje como estaba. Gracias

**Comment by kerenmac** [comment]
Caso 1: La opción "updatelibrary_wait" esta disponible para todos los modos salvo cuando no se actualiza la biblioteca (opción 0). Tal y como esta ahora, si en "updatelibrary" esta fijado "Una sola vez al día" (opción 2) o "Al iniciar Kodi y almenos una vez al día" (opción 3) no hay espera, se inicia Kodi y salta el actualizador de la biblioteca de pelisalacarta, aunque la opción es visible para esas opciones (y me parece lógico que exista). De ahi mi propuesta. Al pasar un intervalo determinado que cumpla las condiciones tendrá el retraso? Si se usa lo que he propuesto si, pero creo que beneficia mas de lo que perjudica el esperar unos pocos segundos cuando lleva Kodi abierto horas y horas. Si no se va a usar mi propuesta habría que cambiar la linea 61 de biblioteca.xml a `<visible>!eq(-2,Una sola vez al día)|!eq(-2,Al iniciar Kodi y almenos una vez al día)</visible>` (y si es posible cambiar "almenos" por "al menos" en esa linea, en la 49 y 41... mejor! 😄)

Caso 2: En la ventana de configuración de la biblioteca se la la oportunidad se usar nombres de carpeta con el titulo original. Puede que lo haya interpretado mal 😔 ; creía que se refería a no usar el id. Por curiosidad, que diferencia hay entre `item.infoLabels['title']` y `item.infoLabels['originaltitle']`?

**Comment by superberny70** [comment]
Bueno pues he creado una PR con los cambios, miratelos cuando puedas. 

Caso 1:
En primer lugar no me gustaba q las opciones aparezcan y desaparezca, prefiero q este siempre visibles y se activen o no segun convenga, me parece q da una vision mas amplia de las opciones disponibles.
Voy a tratar de explicar algunas de las opciones disponibles:

- **Actualizar la biblioteca**: Indica cuando se ha de actualizar (**Nunca, Al inicio de Kodi, Una sola vez al dia o Al inicio de kodi y al menos una sola vez al dia**). Las dos primeras opciones no hace falta explicarlas ¿no?. Las otras dos opciones estan pensadas para los q no desconectan nunca (o casi nunca) kodi (si, los hay :smile:).  Si hace 24 horas desde la ultima actualizacion (forzada desde el menu de configuracion o automatica, bien sea programada o por un reinicio) se arranca el proceso de actualizacion automatico.

- **Esperar antes de actualizar al inicio de kodi**: Cuando kodi arranca comienzan multitud de procesos, desde aqui podemos añadir un pequeño retraso de algunos segundos para no colapsar el arranque.

- **Iniciar actualizacion programada a partir de las (00:00, 04:00, 08:00, 12:00)**: Cuando las actualizaciones son programadas (Una sola vez al dia o Al inicio de kodi y al menos una sola vez al dia) podemos inidcar q comience la actualizacion a partir de estas horas. Los minutos exactos cuando comenzara dependeran de la ultima actualizacion realizada, de tal modo q si la ultima se hizo en el minuto 30 y tenemos fijada aqui la opcion 04:00, la actualizacion comenzara a las 4:30h

Caso 2:
Pues la diferencia es como su nombre indica el titulo traducido al castellano o su version original. 
No recuerdo quien introdujo esto aqui, pero solo lo implemento para las series (un fallo sin duda). 
Por ejemplo si añades (en pelispedia por ejemplo) la serie "a series of unfortunate events" y tienes configurado "Título localizado" te creara la carpeta como "una serie de catastróficas desdichas [tt4834206]", mientras q si lo tienes como "Título original" la carpeta se llamara "a series of unfortunate events [tt4834206]" (si lo vas a probar tienes q borrar la primera antes de crear la segunda, sino como comparten [_id] la segunda vez no se te añadira)

**Comment by kerenmac** [comment]
@superberny70 A mi me gusta la tercera opción (Una sola vez al día), por que solo quiero que se actualice la biblioteca una vez al día, aunque acceda a Kodi mas de una vez (en Android Kodi se cierra cada dos por tres), y en ese caso preferiría tener una espera antes de actualizar la biblioteca, como le has puesto a las opciones 1 y 3 en tu PR. Puede que inicies Kodi antes de la hora que has fijado, en cuyo caso no actualizará la biblioteca, pero si inicias Kodi después de la hora fijada la actualización de la biblioteca sera inmediata, no se si me explico bien. Ademas, para el caso de "Una sola vez al día" creo oportuno acabar con el loop de library_service.py una vez se actualice la biblioteca.

**Comment by superberny70** [comment]
Ok ya lo entiendo. 
Lo q voy a hacer es añadir el retraso "updatelibrary_wait" tb al inicio del monitor justo despues de la L389 en library_service, eso hara q no se compruebe si han pasado ya las 24 horas o mas hasta justo despues de transcurrido el retraso tras el inicio de kodi.

Tb modificare la visibilidad de los ajustes q me has comentado en la #663
