### ISSUE TITLE
Problema biblioteca XBMC 12

### ISSUE THREAD

**Issue by divadres** [tvalacarta/pelisalacarta#674]
He estado revisando la biblioteca en XBMC 12 según el comentario de http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8527&start=250#p40465

He solucionado el problema que comenta el usuario, al parecer xbmcgui.DialogProgressBG() no esta disponible en esa versión de xbmc, lo he solucionado poniendo un try:except de modo que si no existe muestra un progreso "normal" luego he modificado xbmc_info_window.py cambiando los xbmcgui.ACTION_MOVE_LEFT, etc... por su correspondiente id ya que tampoco esta disponible en esas versiondes de XBMC, ya me disponía ha hacer el PR cuando me he dado cuenta de un problema:

En esta versión de XBMC **no se pueden abrir los .strm**, por lo que he podido comprobar si el strm ocupa mas de 1kb este no se abre, mirando por encima la biblioteca, me ha dado la sensación que el strm no se usa para nada mas que para que xbmc ejecute la función de pelisalacarta donde luego la información se recoge del .nfo de modo que ¿si quitamos toda la info innecesaria del strm?
He probado modificando la línea 217 de library.py
de:
```
        item_strm = item.clone(channel='biblioteca', action='play_from_library',
                               strm_path=strm_path.replace(MOVIES_PATH, ""), contentType='movie',
                               infoLabels={'title': item.contentTitle})
```
a:
```
        item_strm = Item(channel='biblioteca', action='play_from_library',
                               strm_path=strm_path.replace(MOVIES_PATH, ""), contentType='movie',
                               infoLabels={'title': item.contentTitle})
```

y en las pruebas que he echo todo parece funcionar correctamente, si algún experto en la biblioteca me puede confirmar que esa información del .strm no se usa para nada, habría que cambiarlo también para las series, y estaría solucionado.

**Comment by SeiTaN** [comment]
Hola @divadres, lo cambié en las series y funciona, se me pasaría hacerlo para pelis.

mira la línea 445
```python
            # Si no existe season_episode.strm añadirlo
            item_strm = Item(action='play_from_library', channel='biblioteca',
                             strm_path=strm_path.replace(TVSHOWS_PATH, ""), infoLabels={})
            item_strm.contentSeason = e.contentSeason
            item_strm.contentEpisodeNumber = e.contentEpisodeNumber
            item_strm.contentType = e.contentType
            item_strm.contentTitle = season_episode
```
Yo borraría tb el contenido de infoLabels y le agregaría contentTitle como propiedad de item y no dentro de infoLabels (no sé si se borrará todo su contenido al añadir solo una propiedad).

**Comment by divadres** [comment]
> Esto es cagada mía 😞 ¿el id es el mismo para todas las versiones aunque no exista como constante?

Creo que si porque la ventana de configuración no da ese problema y ahí se usan números absolutos.

**Comment by SeiTaN** [comment]
@divadres este issue ya lo puedes cerrar, gracias.
