### ISSUE TITLE
Problemas con SSL en pelisalacarta

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#676]
@divadres a ver si puedes darle solución a esto.

En el foro reportan que un canal que yo cree no le funciona (este canal usa https).

**Las trazas son estas:**
```xml
13:49:40 T:7692   ERROR:     [pelisalacarta.core.httptools.downloadpage] Traceback (most recent call last):
                                              File "C:\Users\_VICTOR_\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\httptools.py", line 186, in downloadpage
                                                handle = opener.open(req, timeout=timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1222, in https_open
                                                return self.do_open(httplib.HTTPSConnection, req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
```

@CmosGit ha comentado con acierto que es debido a la versión a la versión de python que se instala con Kodi.

¿Se podría hacer un apaño desde httptools para evitar este problema?

Gracias.

**Comment by divadres** [comment]
Imagino quw si... pero necesiito daber version de kodi y sitema operativo... y canal donde falla

**Comment by Hernanarce** [comment]
Buenas, aporto al tema, el canal al que hace referencia SeTan es animeFLV.ru, lo subio en estos dias al foro y otro que tambien parece tener ese problema es doomtTV un canal que subi yo hace poco tambien.
Al parecer las fallas se dan en kodi 16.1, yo lo comprobe en windows, pero hay reportes de que en androidtv tambien falla.

**Comment by divadres** [comment]
ok, pues lo miro y lo corrijo...

**Comment by divadres** [comment]
Vamos a ver, después de mirármelo bastante, se confirma lo que ya se había dicho por el foro, es un problema de Python versiones anteriores a 2.7.9 no soportan SNI y por lo tanto no funcionan con servidores que lo requieran, como alternativa y dado que esto es mas bien un problema de algún canal en concreto y puesto que afecta a versiones antiguas (aunque no tanto ya que kodi 17 para Android solo se soporta en Android 5+) se puede usar un proxy intermedio que salte este problema como puede ser
`https://ssl-proxy.my-addr.org/myaddrproxy.php/` (algo que ya se usa en algunos canales de @neno1978) modificando la url a `url = "https://ssl-proxy.my-addr.org/myaddrproxy.php/"+url` dado que posiblemente esto modifique algo el contenido de la pagina (no estoy seguro) es algo que habrá que controlarlo desde el canal (patrones, etc) si es que el creador del canal quiere que funcione en kodi 16

**Comment by SeiTaN** [comment]
Muchas gracias @divadres por tu tiempo, pensaba que lo mismo tenía solución.

Le echaré un ojo a lo del proxy a ver si no es muy complicado de implementar y no afecta mucho.

Gracias de nuevo.

**Comment by SeiTaN** [comment]
Edito el título, este problema tb afecta a la actualización de datos llamando a la api de @tvalacarta que va por https.

Reportado en el foro
```xml
09:18:53.258 T:3992 NOTICE: pelisalacarta.platformcode.launcher [run] Traceback (most recent call last):
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\platformcode\launcher.py", line 83, in run
version = updater.checkforupdates()
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\updater.py", line 64, in checkforupdates
latest_packages = api.plugins_get_latest_packages()
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\api.py", line 82, in plugins_get_latest_packages
return remote_call( "plugins/get_latest_packages.php" , parameters )
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\api.py", line 64, in remote_call
response_body = scrapertools.downloadpage(url,post,headers)
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\scrapertools.py", line 333, in downloadpage
data, _ = downloadpageWithResult(url=url, post=post, headers=headers, follow_redirects=follow_redirects, timeout=timeout, header_to_get=header_to_get)
File "C:\Users\josen\AppData\Roaming\Kodi\addons\plugin.video.pelisalacarta\core\scrapertools.py", line 472, in downloadpageWithResult
handle=urlopen(req)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 431, in open
response = self._open(req, data)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 449, in _open
'_open', req)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1240, in https_open
context=self._context)
File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1197, in do_open
raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by tvalacarta** [comment]
Acabo de probar con Kodi 15.2 y el checkforupdates me funciona bien:

`18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.updater checkforupdates
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.api.plugins.get_latest_packages
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.api.remote_call url=plugins/get_latest_packages.php, parameters={'platform': 'kodi-isengard', 'plugin': 'pelisalacarta'}
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools downloadpage
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools url=https://api.tvalacarta.info/v2/plugins/get_latest_packages.php
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools downloadpageWithResult
18:07:42 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools url=https://api.tvalacarta.info/v2/plugins/get_latest_packages.php
...
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools ---------------------------
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools content-length=839
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools x-powered-by=PHP/5.5.9-1ubuntu4.13
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools server=Apache/2.4.7 (Ubuntu)
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools connection=close
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools date=Wed, 08 Mar 2017 17:07:42 GMT
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools content-type=application/json
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools ---------------------------
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.scrapertools Descargado en 1 segundos
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.updater checkforupdates version remota=4202
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.updater checkforupdates version local=4202
18:07:43 T:123145306673152  NOTICE: pelisalacarta.core.updater checkforupdates -> hayqueactualizar=False
`

Dime donde está el reporte para entender el problema, pero ahí tenemos más opciones como ir por http en ciertas plataformas.

En el otro caso lo veo más difícil, y ojo porque ese "ssl-proxy.myaddr.org" indica que está prohibido para bots. Parecen buena gente, propongo buscar otra solución.

**Comment by SeiTaN** [comment]
@tvalacarta aquí tienes el hilo del foro

http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8814

**Comment by divadres** [comment]
@SeiTaN Creo que son problemas distintos, ssl en general da muchos problemas en Python (si no usas la ultima versión) pero por norma general he podido ir solucionándolos todos, menos el del primer post porque realmente es que Python no soporta esa función en versiones anteriores de 2.7.9 el tema de la API de actualizaciones, no creo que sea problema, ya que a mi me ha funcionado incluso con Python 2.4 (mediante httptools) es muy raro eso que le pasa al usuario y mas siendo kodi krypton, se podría probar algunas de las soluciones que tengo, por ejemplo en mediaserver en blusens que usa una versión de Python antigua, 2.7 pero no la ultima, tampoco me iba la api de actualizaciones y lo solucione indicándole que no comprobara los certificados, lo que pasa es que esas funciones no están incluidas porque depende de la versión de Python hay que hacer una u otra cosa, entonces es mas complicado hacer algo que no falle a nadie, pero se puede mirar.

@tvalacarta 

> En el otro caso lo veo más difícil, y ojo porque ese "ssl-proxy.myaddr.org" indica que está prohibido para bots. Parecen buena gente, propongo buscar otra solución.

Me temo que en servidores que utilicen SNI (https://es.wikipedia.org/wiki/Server_Name_Indication) no van a funcionar en versiones de Python anteriores a 2.7.9 la única solución que se me ocurre es usar un proxy podemos usar este, o crear uno propio y que lo cuelgues en tu servidor (si no tienes limitaciones con el trafico), no costaría mucho hacer uno en php que la petición que reciba la redirija y luego retorne los datos, utilizando los headers que le enviemos e incluso las cookies que le enviemos, de este modo nos aseguramos que los datos recibidos son exactos y que el proxy no modifica nada, seria para usarlo solo en los servidores que sabemos que fallan.

**Comment by SeiTaN** [comment]
Vale, 
¿Entonces el problema que reporta el usuario con la conexión de la api como se solucionaria? 
¿Si cambiamos scrapertools.downloadpage por la de httptools funcionaría?

**Comment by divadres** [comment]
Me he dado cuenta que urls con ssl que en scrapertools no van (o van algunas veces si otras no) en httptools si que van, no se el motivo, ya que en principio httptools no tiene nada especial para eso, pero desde el PR que cree para reparar la versión xbmc 9 todas las conexiones van por httptools ya que se redirigen todas las funciones de scrapertools a httptools (precisamente porque la API fallaba con scrapertools), así que si usa lo que esta en develop no tendría que tocar nada, aunque no garantizo que le funcione, porque como te he dicho es muy raro ese fallo, yo también usa Kodi krypton en Windows 10 (como la mayoría supongo) y no he tenido ese problema.
 
**Cómo idea: ¿No tendrá la fecha mal puesta?** 
por lo menos en los navegadores si la fecha del sistema no es correcta da problema con los certificados...

**Comment by SeiTaN** [comment]
@divadres, usa la beta 2 sino me falla la memoria y tu arreglo creo que es posterior. 
Además yo no tengo puesto la opción de buscar actualizaciones por eso no me he dado cuenta de eso.

**Comment by tvalacarta** [comment]
En develop está ya subido el cambio para que funcione por http, lo cambié en la configuración del servidor para permitirlo.

**Comment by SeiTaN** [comment]
Gracias @tvalacarta, cierro el issue 👍
