### ISSUE TITLE
Paginas con carga dinamica via java script

### ISSUE THREAD

**Issue by Hernanarce** [tvalacarta/pelisalacarta#678]
Hola, abro este tema para ver si hay alguna manera de scrapear paginas de este tipo, ya que me encontre con paginas como por ejemplo www.floow.tv, que cargan las paginas mediante un script y al momento de descargar el codigo fuente no se obtienen los datos de las peliculas.
Por mi parte logre obtener los datos pero utilizando selenium y phantomJS, en python, no se si habra alguna manera de hacerlo con las herramientas que ya tenemos en el addon y si no hay, seria muy util tener algo para este tipo de paginas.
Saludos

**Comment by SeiTaN** [comment]
@Hernanarce pues depende de la página yo he empezado a trastear con páginas que se cargan los enlaces después que el HTML, es mirando con la barra de desarrollador en el navegador (F12), y ver las llamadas que se hacen e intentar simular lo que hace sin tener que montar todo el proceso, el cual casi nunca es necesario hacer entero.

**Comment by Hernanarce** [comment]
Tenes algun ejemplo SeiTaN como para ir probando, como te digo utilizando esas herramientas es sencillo pero no se si habra posibilidad de añadirlas a pelisalacarta.
Adjunto algo de lo que estuve probando por si lo quieren ver, esta apenas empezado pero ya reproduce los enlaces.
[floow.zip](https://github.com/tvalacarta/pelisalacarta/files/828633/floow.zip)

Es necesario 
Selenium: http://selenium-python.readthedocs.io/installation.html
PhantomJS: http://phantomjs.org/download.html

**Comment by SeiTaN** [comment]
Según veo con la url de passengers, luego se llama a otra url

![image](https://cloud.githubusercontent.com/assets/11775029/23718679/bd4e21a8-0438-11e7-933a-42cd1ebd319c.png)

Como ves en la indicación, lo que se manda en esa nueva url es el ID de la película.

Y si ves lo que devuelve esa petición...
![image](https://cloud.githubusercontent.com/assets/11775029/23718743/0ae98948-0439-11e7-9f04-cb789dac4f91.png)

Ya sería seguir con la siguiente URL hacemos la llamada
![image](https://cloud.githubusercontent.com/assets/11775029/23718876/7bd703d8-0439-11e7-9b82-066df14aea22.png)

Y si ves el codigo que devuelve ya tienes los enlaces...
![image](https://cloud.githubusercontent.com/assets/11775029/23718901/98ec0cd4-0439-11e7-8d85-86781a44a2b1.png)

**Comment by Hernanarce** [comment]
@SeiTaN, la pagina de inico carga los enlaces bien pero al entrar por ejemplo en peliculas, la carga es via java script, es decir desde la pagina de inicio se pueden ver los enlaces a las peliculas en el codigo pero una vez entramos a la seccion peliculas ya no. O eso es lo que a mi me pasa, a lo mejor lo estoy mirando mal.

**Comment by SeiTaN** [comment]
@Hernanarce lo que te he puesto en por partes.

La carga javascript es lo que te he puesto en la llamada 2 y 3

**Comment by Hernanarce** [comment]
A lo mejor no me hice entender bien @SeiTaN o yo no veo claro lo que me explicas, el problema es en http://floow.tv/peliculas/#!/estrenos, especificamente donde con httptools, me es imposible ubicar las peliculas, (titulos, thumbnails, plots, urls) porque mediante httptools obtengo la pagina pero lo que se carga con el javascript no sale. por lo tanto utilice las herramientas que te comente antes, una vez sorteado ese problema, conseguir los enlaces a los videos es como dices de una pagina a otra y obtener el enlace de video.

**Comment by SeiTaN** [comment]
Lo había entendido mal yo, pensaba que te referias a los enlaces.

Hago el código y te lo pongo.

**Comment by SeiTaN** [comment]
```python
# -*- coding: utf-8 -*-
# ------------------------------------------------------------
# pelisalacarta - XBMC Plugin
# http://blog.tvalacarta.info/plugin-xbmc/pelisalacarta/
# ------------------------------------------------------------

from core import httptools
from core import logger
from core.item import Item

def mainlist(item):
    logger.info()


    itemlist = []
    itemlist.append(Item(channel="floow", title="Peliculas", action="listado"))
    return itemlist


def listado(item):
    itemlist = []

    url = "http://floow.tv/apimovies/moviepremiere/300"
    post = {"key": "73894672jdjhjdddddfhd", "token": "f5f1c20dd0d261ca6d9ea72e0e5aa537decedf69w7Asi825MTQ4OTAwNjExMQ=="}

    import urllib
    from core import jsontools

    post = urllib.urlencode(post)
    data = httptools.downloadpage(url, post=post).data

    dict_data = jsontools.load_json(data)

    if dict_data.get("status", "") == "success":
        for i in dict_data["results"]:
            itemlist.append(item.clone(title=i['title'], url=i['link'], thumbnail=i['poster'], plot=i['synopsis']))

    return itemlist
```

![image](https://cloud.githubusercontent.com/assets/11775029/23723994/8108ee5e-044b-11e7-8b43-d9280f67cb69.png)

**Comment by Hernanarce** [comment]
Muy bueno SeiTaN, la verdad no tenia idea de como hacerlo, el tema es que como dije alguna vez no tengo idea del tema jsontool.

Muchas gracias, veo como lo adapto.

**Comment by SeiTaN** [comment]
@Hernanarce uso jsontools, porque la página que devuelve la información de las peliculas, lo hace en formato json.

Luego se convierte en un diccionario y ya lo usas como necesites.

**Comment by Hernanarce** [comment]
Voy a tener que ponerme a entender el tema de los json.

Gracias @SeiTaN
