### ISSUE TITLE
conectores servidores

### ISSUE THREAD

**Issue by superdoctor1** [tvalacarta/pelisalacarta#717]
funcionan todos los canales y  los conectores  y servidores tengo un plex y una aplicacion kodi 
con la version beta 3 pelisalacarta

**Comment by SeiTaN** [comment]
@superdoctor1 ¿eso es una pregunta o una afirmación?
No entiendo la razón de tu issue 😕

**Comment by superdoctor1** [comment]
es  algunos canales no funcionan bien sale  error por eso pregunte porque   funcionan algunos por eso  pregunta si los conectores y servidores de los canales estan funcionando esa era mi pregunta me entiende amigo  disculpame pero solo preguntaba  esque  escribo muy rapido por eso no me entiende  muy bien

**Comment by neno1978** [comment]
🍺🍺🍺🍺🍺🍺🍺🥃🥃🥃🍷🍷🍷🥂🥂🍾🍻🍺🍸

**Comment by SeiTaN** [comment]
@neno1978 eso es lo que llevas desde las 3 de la tarde?

**Comment by neno1978** [comment]
No, eso es lo que me tomao después de leer al doctor 🤣🤣🤣

**Comment by Intel11** [comment]
Esa es la receta de tu doctor? :smile:
