### ISSUE TITLE
Problemas de concurrencia actualizando biblioteca

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#745]
Por un motivo ajeno a esto estaba importando todas mis series a una instalación limpia (.kodi limpio). He añdido los .strm y he encendido Kodi, eso ha empezado a actualizar... pero ha aparecido un viejo conocido: los problema de concurrencia!

Es curioso porque es algo que se solucionó hace tiempo, pero me he encontrado con que:
https://github.com/tvalacarta/pelisalacarta/blob/develop/python/main-classic/platformcode/xbmc_library.py#L271

Tiene un "update_multi_threads" que no comprueba si se está actualizando la biblioteca, por lo que lanza un video scan y machaca el anterior.

Por otro lado, veo que ahí usa unos Locks() pero, desde mi poco conocimiento de Python, creo que son inútiles. ¿No se está creando un Lock() para cada thread?
args=[update_path, threading.Lock()]

Cada thread que se cree tendrá el output de threading.Lock(), que, según la doc, "A factory function that returns a **new** primitive lock object", por lo que no será compartido, todos podrán pillarlo (ya que es para ellos solos)

Los cambios se metieron en esta revision: https://github.com/tvalacarta/pelisalacarta/commit/95ccdd73c9e5ab106ed9f2078b92e122274d23fb#diff-60971a82cedaed36c8716631cde500ef

**Comment by superberny70** [comment]
Entiendo a lo q te refieres, pero no consigo reproducir el fallo. ¿Se te ocurre como reproducirlo sin tener q reinstalar kodi?

**Comment by Palatosino** [comment]
Guardándote la carpeta de usuario en otro lado, para tener una config limpia y, una vez terminado, restaurarla :laughing: 

Sin esto no se muy bien como lo podrías reproducir. La cosa es  que el primer video scan no haya terminado antes de que se produzca el segundo.

Esto se reproduce muy fácilmente en cualquier  instalación desde 0. Yo he puesto los .nfo por lo que pelisalacarta ha empezado a actualizar (realmente añadir) las series: scrapea la primera, genera los .strm, lanza el library_update y continua con la segunda serie, mientras Kodi va a realizar el escaneo del directorio de la primera añadida. Ahora la segunda serie llega al library_update y la primera no ha acabado, por lo que lanza otro library_update y Kodi para el primero.

Supongo que añadir 2 series consecutivas (y no que no haya acabado de añadir la primera) produce el mismo problema (no es necesario que vaya por el actualizador)

Así que si una serie añade capítulos y la siguiente es muy rápida de scrapear y también añade alguno podría machacar el anterior (aunque obviamente es mucho más complicado de que pase añadiendo episodios que poniendo una serie entera, pero he visto escaneos bastante rápidos en los logs de mi Raspberry estos meses que podrían provocar este problema)
