### ISSUE TITLE
El canal "Novedades" se ha roto

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#761]
En casa utilizan mucho el canal Novedades, le ha salido que se ha actualizado y se ha roto (no encuentra canales el canal).

He restaurado una versión previa (que tengo de una copia de beta3) y funciona OK.

**Comment by SeiTaN** [comment]
@Palatosino ya lo detecto @CmosGit, si quieres que te funciona con la última versión tan sólo tienes que cogerlo de la rama master 😉

**Comment by Palatosino** [comment]
Perfect 👍 
Entonces cierro esto.
