### ISSUE TITLE
Animeflv no funciona

### ISSUE THREAD

**Issue by MakuSensei** [tvalacarta/pelisalacarta#765]
al agregar una serie en favoritos o buscar directamente un anime con toda la lista de capítulos no aparece nada. apenas funciona en el menú de resientes donde solo se ven el capitulo recién subido. 
Esto pasa porque han hecho cambios en la web de animeflv
Tambien quiero recomendar si pueden agregar a animeYT que tiene mejor calidad y no joden haciendo cambios en su web

**Comment by SeiTaN** [comment]
A menos que haya cambiado hace poco, ya está arreglado el canal, está pendiente de aprobar en el pr #759, sobre animeYT le eché un ojo y lo tengo pendiente de hacerlo.

**Comment by MakuSensei** [comment]
Gracias.

**Comment by SeiTaN** [comment]
De nada, si está contestada y solucionada la incidencia, puedes cerrar el "issue" 😉

**Comment by MakuSensei** [comment]
aun no esta corregido

**Comment by SeiTaN** [comment]
Está corregido, otra cosa es que no esté aceptado el PR.

**Comment by MakuSensei** [comment]
que es eso del PR?

**Comment by SeiTaN** [comment]
PR es pull request, y ayer Jesús lo aceptó, con lo que ya se puede cerrar esto ;)
