### ISSUE TITLE
Mejoras en actualización por paquetes

### ISSUE THREAD

**Issue by SeiTaN** [tvalacarta/pelisalacarta#767]
# Paquetes canales/servidores

### Problemática

1. Si hay canales/servers cambiados a mano, estos se machacan al bajar un paquete.
2. Si hay canales que dependen de nuevas versiones de componentes internos, dejan de funcionar ya que no se bajan estas dependencias.

### Posible solución

1. No sobreescribir los ficheros directamente, comprobar el fichero xml local y el descomprimido para ver que si la versión es superior no se machaquen fichero xml y py.
2. Incluir en los zip los componentes internos modificados.

**Comment by CmosGit** [comment]
Creo que la solución 1 estaría bien, pero no soluciona el problema de por sí (el xml puede tener una versión superior pero no funcionar en la actual del addon), y la solución 2 sería complicada, porque a veces los componentes internos modificados son una cadena y afectan a bastantes archivos.

Por qué no añadir un nuevo campo en los xml de los canales/servidores para que compruebe si la nueva versión subida es compatible con el addon instalado? Se puede poner algo así:

`<addon_version>4.2.0</addon_version>`

De esta forma, al actualizar un canal de forma individual o mediante paquetes, se comprueba este campo en el xml y tanto si la versión del addon como la del canal/conector es superior se actualiza. De igual modo, para no tener que modificar todos los xml y solo hacerlo con aquellos no compatibles, si ese campo no existe o está vacío se entiende que es compatible y es apto para actualizarse. Eso sí, en este caso habría que usar siempre en las versiones del addon una nomenclatura numérica y evitar palabras como beta o final (o eliminarlas al hacer la comprobación)

**Comment by Hernanarce** [comment]
Creo que seria bueno utilizar numeraciones "redondas" tipo 4.2.0, para referirse a la version estable, y se podria utilizar el ultimo numero para indicar la version de beta que se lleva, por ejemplo 4.2.1, seria la siguente beta, y asi sucesivamente.
Con respecto a las actualizaciones, ya hay bastante lio con lo que se sube al foro, creo que habria que encontrar una forma mas centralizada de hacer esas subidas "de emergencia", o unificarlas como para que sea mas ordenado, poner la direccion del git del creador del canal en la actualizacion de cada canal no se si seria lo ideal, pero evitaria que se pongan zips sueltos en el foro...

**Comment by tvalacarta** [comment]
> Eso sí, en este caso habría que usar siempre en las versiones del addon una nomenclatura numérica y evitar palabras como beta o final (o eliminarlas al hacer la comprobación)

Ya tenemos versiones numéricas para la versión, lo de las etiquetas tipo "beta1" es solo para que salga en pantalla. 

`def get_current_plugin_version():
    return 4204

def get_current_plugin_version_tag():
    return "4.2.0-final"
`

> Creo que seria bueno utilizar numeraciones "redondas" tipo 4.2.0, para referirse a la version estable, y se podria utilizar el ultimo numero para indicar la version de beta que se lleva, por ejemplo 4.2.1, seria la siguente beta, y asi sucesivamente.

Me gusta la idea, tiene mucho sentido porque creo que la gente se lía mucho con tanta versión. La próxima versión será la 4.3, creo que seguiré tu sugerencia.

> Con respecto a las actualizaciones, ya hay bastante lio con lo que se sube al foro, creo que habria que encontrar una forma mas centralizada de hacer esas subidas "de emergencia", o unificarlas como para que sea mas ordenado, poner la direccion del git del creador del canal en la actualizacion de cada canal no se si seria lo ideal, pero evitaria que se pongan zips sueltos en el foro...

Eso ya funciona así ¿no?

El canal se auto-actualiza con la URL que pone en el xml.

A mí no me parece mal que la gente suba sus propias versiones de los canales en el foro en ZIPs o lo que quiera, nunca he pretendido que sea un sistema cerrado sino más bien al contrario. Eso tiene algún que otro problema desde el punto de vista de la seguridad, ya que yo sólo puedo hacerme responsable de lo que distribuyo personalmente.

Contestando ahora a @SeiTaN, por supuesto en un paquete se pueden meter más componentes pero creo que en ese caso estaríamos hablando de una actualización del plugin. Yo descartaría la solución 2.

Y hablando de la 1, como el tema de los paquetes está pensado más bien para la gente que no anda modificando los canales o descargándolos manualmente no lo había pensado.

Me parece que va a introducir más confusión el hecho de que uno de tus canales no se actualice con el paquete, pero como el que cambie manualmente el canal ya sabe lo que ha hecho tampoco lo veo mal.

Y me parece especialmente interesante lo de etiquetar cada canal con la versión mínima del add-on que necesita, ya lo habíamos discutido anteriormente para identificar si es un canal "kodi-only" y cosas así.

**Comment by superberny70** [comment]
> Problemática
> 
> 1. Si hay canales/servers cambiados a mano, estos se machacan al bajar un paquete.
> 2. Si hay canales que dependen de nuevas versiones de componentes internos, dejan de funcionar ya que no se bajan estas dependencias.

Yo no veo q esos sean los problemas de las actualizaciones de canales/servidores. 
El problema 1, si yo modifico a mano mis canales he de ser consciente q si actualizo se pueden sobreescribir. He de decidir q tipo d actualizaciones voy a hacer: manual o automatica.

A nivel de usuario el caso 2 tampoco deberia preocuparme. Si quiero (y tengo los suficientes conocimiento) ire actualizando desde develop para contar con la ultima version no oficial (version desarrollo) , si no esperare a q se publiquen versiones oficiales.
Donde si hay un problema es a nivel de creadores de canales. Normalmente todos los creadores tenemos lo ultimo de develop (version desarrollo) y modificamos nuestros canales con respecto a esto. 

Para el caso de canales compatibles con las versiones oficial y desarrollo se puede mergear en ambas ramas ( @tvalacarta : sin usar el boton verde!!!).
En el caso de canales incompatibles o bien se sube solo a la rama con la q es compatible o bien tendremos q hacer dos versiones si es posible y subir una a cada rama.

Respecto a lo de las etiquetas de compatibilidad en el XML ya hay algo parecido (tag compatible), aunq no se si se utiliza o no.

Por ultimo donde si veo un problema es en depender de q @tvalacarta merge una PR para q esta pase a estar disponible. Ojo no me entendais mal, esto no es una critica a nadie, y menos para el Boss. Pero si deberiamos buscar alguna manera de hacerlo mas fluido.

**Comment by divadres** [comment]
Coincido con @superberny70 en que los canales y servidores deberian estar disponibles lo antes posible una vez reparados y el sistema actual no es muy fluido, pero no se si github dispone de otra forma....

**Comment by Intel11** [comment]
> Por ultimo donde si veo un problema es en depender de q @tvalacarta merge una PR para q esta pase a estar disponible. Ojo no me entendais mal, esto no es una critica a nadie, y menos para el Boss. Pero si deberiamos buscar alguna manera de hacerlo mas fluido.

Hola a todos, yo también diría buscar una manera que las actualizaciones, al menos de canales y servidores sea mas fluida como dice @superberny70.

Por ejemplo les cuento mi caso, yo tengo recomendado pelisalacarta a unas 10 personas, y estas a su vez a otras y toda una cadena; entonces cuando un canal/servidor no funciona me llaman para contarme su problema. Y para mi es tedioso estar actualizando a cada uno si se puede hacer automático cuando se actualiza el canal/servidor. Después van "desacreditando" a pelisalacarta que dicen: para que me recomiendas algo que no funciona :(

Y también en el foro se arma a veces problemas por que crean hilos e hilos de lo mismo y uno ya no sabe cual es el ultimo *.py actualizado :(

Yo solo propondría por lo menos actualizar (oficialmente) mínimo una vez por semana al menos los canales/servidores.

Pero en verdad no se me ocurre alguna idea como acelerar esto :(

He pensado que suban por ftp a una carpeta de tvalacarta.info o que Jesús le de acceso a alguien mas a mergear los PR, pero no me convencen mucho esas soluciones :(

Ojala puedan llegar a un acuerdo para este tema puntual.

Gracias a todos ustedes por todo :)

**Comment by Palatosino** [comment]
No necesitáis FTP's.

Montad otro repositorio en github y poned como colaboradores a más gente (se puede dar acceso de push a múltiples cuentas, github no se limita a 1 repositorio 1 cuenta y para colaborar tener PR)

Y si digo lo del repositorio independiente es para mantener lo origina lo más protegido posible (como ahora, solo vía PR)

**Comment by tvalacarta** [comment]
Yo creo que el sistema de actualizaciones que tenemos es más que apropiado.

1) Para el uso normal el tema de los paquetes es cómodo y fácil de entender, y será más ágil en el momento que estabilicemos el tema de las versiones en la línea que propone @CmosGit ya que ahora mismo con el cambio de los settings es un poco difícil y no me atrevo a publicar nada. Estoy deseando que demos por cerrado este cambio para publicar una nueva versión.

Luego la idea es que cuando un día se haga al menos un merge se genere al final del día una nueva actualización, que subirá automáticamente al repositorio de paquetes. Es un proceso que está prácticamente automatizado ya, y la idea es que pronto haya más personas que puedan hacer merges además de mí (puto Github y sus permisos) por lo que esto será todo lo ágil que queramos.

2) Para el que quiera más agilidad está la actualización automática por canales individuales, para eso está la URL del canal donde se puede poner la que cada uno considere, y no solo la del github de pelisalacarta. No entro en el dilema de quién es el autor de cada canal y quién tiene la autoridad para poner su URL, ya que nunca hemos tenido ese problema a pesar de haber varios autores, pero entiendo que es el motivo por el que la URL de la mayoría de canales sigue siendo el github de pelisalacarta.

3) Y finalmente para el que quiera enredar todavía más el plugin le permite instalarse canales del foro, ya sea manualmente copiando el fichero o mediante una URL del foro o de donde sea.

Algún día tendremos que entrar en el problema de la seguridad, porque si pelisalacarta instala una actualización de un canal desde una URL que no es la oficial hay que avisar al usuario para que luego no nos venga nadie con responsabilidades.

**Comment by willowzxy** [comment]
Como dice intel11 hoy en día al que recomiendas pelisalacarta te dice "no va" y es que vosotros desarrolladores no sois conscientes de algo...
Seguramente ninguno de vosotros tiene la versión oficial sin retocar canales etc pero es que al que instala la última no le va a funcionar casi nada.

Lo de que los canales modificados se mantengan incluso tras instalar un paquete es la mejor forma de matar el plugin del todo añadiendo más complicación al usuario.

Faltan actualizaciones oficiales más constantes cn conectores corregidos que ya casi los cambian cada pocos días. El creador parece dispuesto a ceder permisos para ello.

Insisto, si instaláis lq versión oficial sin modificar nada a día de hoy no van muchos conectores ni canales ni novedades y esto es lo que ven la mayoría de usuarios.

**Comment by tvalacarta** [comment]
Gracias por tu comentario, tiene algunas cosas interesantes que me han hecho pensar :)

Este hilo busca precisamente mejorar ese proceso de nuevas versiones, para hacer las "actualizaciones oficiales más constantes" como tú dices. Hicimos el sistema de paquetes precisamente para eso, aunque ahora está atascado por el cambio interno que hemos hecho.

Para complicarlo, la semana pasada estaba prevista una actualización de la versión oficial para dar por finalizado el tema, pero la hemos restrasado un poco para discutir el asunto de los cierres de otros add-ons y como nos afectaba. Para nosotros es importante como te imaginarás.

Y por último añadiré que no es verdad que no seamos conscientes de la situación de los usuarios, si miras el foro o los comentarios del blog verás que el 99% son del tipo "No me funciona XXX, por favor arréglalo lo antes posible.".

Simplemente cuando sacamos una versión y no funciona los comentarios son todavía más amargos, y como todos tenemos otra vida además de actualizar los canales y conectores las cosas requieren el tiempo que requieren.
