### ISSUE TITLE
Estado actual de Kodi afecta también a pelisalacarta?

### ISSUE THREAD

**Issue by MakuSensei** [tvalacarta/pelisalacarta#796]
últimamente ando viendo muchas de estas noticias referentes a los addons de kodi https://www.genbeta.com/web/sigue-el-culebron-kodi-tvaddons-desaparece-de-la-faz-de-internet
Ademas que hace rato que Pelisalacarta no se actualiza ni corrige los fallos que hay. pregunto que esta pasando?

**Comment by tvalacarta** [comment]
Yo creo que es fácil de entender.

Mucha gente ha estado haciendo add-ons de Kodi colgando pelis/series/canales piratas, lo que hace que no diferencie de nada el hacer un add-on de tener una web.

Todo el mundo sabe que tener una web de pelis piratas tiene un riesgo, que están dispuestos a asumir a cambio del dinero que ganan, pero parecía que los add-ons de Kodi estaban libres de riesgo.

Ahora que hay denuncias en firme contra los add-ons la gente se echa para atrás.

Yo no he pensado en retirar pelisalacarta a raíz de esto, ya que en realidad no pongo los enlaces sino que están en cada sitio web y pelisalacarta sólo hace más fácil verlos. Creo que no hago nada ilegal, no más ilegal de lo que puede hacer Firefox (que sirve para lo mismo).

Por otro lado, es cierto que es una línea muy delgada y no puedo negar que me quita el sueño algunas veces :(

En cuanto a las actualizaciones, no hay nada desde hace un mes (tampoco es tanto) simplemente porque estamos en medio de un cambio interno importante, de hecho esta semana está previsto hacer una.

**Comment by MakuSensei** [comment]
Gracias, solo queria saber su opinion respecto a este tema. ya que pelisalacarta es el unico add on que uso en mi nexus player
