### ISSUE TITLE
Error en actualizar un PR desde mi rama?

### ISSUE THREAD

**Issue by Intel11** [tvalacarta/pelisalacarta#812]
Hola a todos he actualizado mi rama:

https://github.com/Intel11/pelisalacarta/tree/patch-1/python/main-classic/servers

Servidor vidtome que ya está actualizado en mi rama: patch-1

Pero no se actualizó mi PR:

https://github.com/tvalacarta/pelisalacarta/pull/809

Algo hice mal o algo tiene mal github? :(

Gracias :)

**Comment by divadres** [comment]
parece que ya se ha actualizado...

**Comment by Intel11** [comment]
Si ya se actualizó gracias

Seguro están scrapeando mucho a github por eso está lento 😈
