### ISSUE TITLE
gamovideo resolver funciona-

### ISSUE THREAD

**Issue by bugatsinho** [tvalacarta/pelisalacarta#816]
los urls de gamovideo no reproducen.en un addon que yo hago pruebas porque soy nuevo en python para reproducir los links uso el referer de la pagina busco por el rtmp link.

**Comment by 000cuenta0001** [comment]
Yo no tengo ningún problema con los enlaces gamovideo en descargasmix.

**Comment by bugatsinho** [comment]
tienes razon!mi falta

**Comment by Intel11** [comment]
Hola, si está resuelto tu problema, deberías cerrar este issue.

Saludos :)

**Comment by bugatsinho** [comment]
Seguro.Gracias
