### ISSUE TITLE
La librería Request no funciona en Boxee

### ISSUE THREAD

**Issue by tvalacarta** [tvalacarta/pelisalacarta#92]
Parece que tendremos que pensar esto de usar requests de otra forma, ya que la sintaxis no es compatible con Boxee.

	12:43:58.259 T:4644749312 M:6040772608  NOTICE: Traceback (most recent call last):
	12:43:58.259 T:4644749312 M:6040772608  NOTICE:   File "/Users/jesus/Library/Application Support/BOXEE/UserData/apps/info.mimediacenter.pelisalacarta/default.py", line 27, in ?
	12:43:58.259 T:4644749312 M:6040772608  NOTICE: launcher.run()
	12:43:58.259 T:4644749312 M:6040772608  NOTICE:   File "/Users/jesus/Library/Application Support/BOXEE/UserData/apps/info.mimediacenter.pelisalacarta/platformcode/launcher.py", line 121, in run
	12:43:58.266 T:4644749312 M:6040797184  NOTICE: exec "import channels."+channel_name+" as channel"
	12:43:58.266 T:4644749312 M:6040797184  NOTICE:   File "<string>", line 1, in ?
	12:43:58.266 T:4644749312 M:6040797184  NOTICE:   File "/Users/jesus/Library/Application Support/BOXEE/UserData/apps/info.mimediacenter.pelisalacarta/channels/animeflv.py", line 17, in ?
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: from lib import requests
	12:43:58.268 T:4644749312 M:6040772608  NOTICE:   File "
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: /Users/jesus/Library/Application Support/BOXEE/UserData/apps/info.mimediacenter.pelisalacarta/lib/requests/__init__.py
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: ", line
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: 53
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: from .packages.urllib3.contrib import pyopenssl
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: ^
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: SyntaxError
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: :
	12:43:58.268 T:4644749312 M:6040772608  NOTICE: invalid syntax
	12:43:58.268 T:4644749312 M:6040772608   ERROR: Scriptresult: Error
	12:43:58.784 T:4644749312 M:6040555520    INFO: Python script stopped

**Comment by tvalacarta** [comment]
Parece que tampoco funciona en la XBOX original :(

http://www.elotrolado.net/viewtopic.php?p=1740569149

**Comment by SeiTaN80** [comment]
Habrá que modificar las referencias y crear un scrapertools**v2** como hablamos.
