### ISSUE TITLE
Problemas de la version con json

### ISSUE THREAD

**Issue by SeiTaN80** [tvalacarta/pelisalacarta#97]
Si te parece bien para ir ordenando creo issue y subo fix para no pisarnos con lo que veamos.

~~Está dando un fallo con la librería jsontools.py~~
~~Falla con los jsons de newpct, estoy mirando.~~
Era el launcher, he subido una versión que comenta la referencia a updater, cuando esté lista y añade el fix de #91

**Comment by tvalacarta** [comment]
No te preocupes, voy a cambiar algunas cosillas así que ya iré avanzando yo. Si subimos cosas los dos creo que será más complicado.

En cuanto lo tenga funcionando y estable hago el commit y te aviso.

Gracias igualmente :)

**Comment by SeiTaN80** [comment]
Ok me espero entonces, si ves algo raro y te puedo echar un cable, no dudes en decirlo.

Y gracias a ti :smiley:

**Comment by tvalacarta** [comment]
Empiezo a arrepentirme del json para el channelselector:

- Si te dejas una coma no carga...
- No puedes usar caracteres internacionales porque da fallo de encoding, y me parece un incordio cada vez que quieres editarlo para publicar una actualización.
- La configuración del canal va a ir en el "userdata", así que no le veo tanta utilidad ya que en realidad sólo lo editará a mano el autor del canal.

Voy a comentarlo en el foro, pero creo volveremos a los xml.

**Comment by SeiTaN80** [comment]
>Si te dejas una coma no carga...>
Para eso tiene que ser un json válido y si no es válida da fallo jsontools, se tendría que mirar o validar el json antes de subirlo al github.
>No puedes usar caracteres internacionales porque da fallo de encoding, y me parece un incordio cada vez que quieres editarlo para publicar una actualización.>
¿Cual caracter dices? A mi las `ñ` si me las carga por ejemplo.
>La configuración del canal va a ir en el "userdata", así que no le veo tanta utilidad ya que en realidad sólo lo editará a mano el autor del canal.>
Me he perdido con esto, lo hablamos todo en el foro y a ver que soluciones vemos entre todos :wink:

**Comment by tvalacarta** [comment]
Ya lo he puesto en el foro:

http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=7148&p=28286

De momento voy a dejar el tema de los canales con xml como estaba, y veo como abrir esa rama en github para probar esto.

**Comment by neno1978** [comment]
Yo no quería decir nada por no molestar a nadie, pero el tema json nunca lo vi muy claro. Parece ideal para muchas cosas pero después te acaba pegando patas por otro lao ;)

**Comment by SeiTaN80** [comment]
A mi me matan las expresiones regulares xDD, es como todo, el ponerse, lo bueno del json, es que lo cargas y ya está, en el xml tienes que cargarlo y luego buscar cada elemento que te haga falta.

**Comment by tvalacarta** [comment]
Hay un channeltools para no tener que preocuparnos por esas cosas... además las expresiones regulares son más divertidas :)

De momento es una cuestión de listar ventajas e inconvenientes, y el json pierde por puntos. Ya lo iremos viendo.
